### ISSUE TITLE
oh-knob-card

### ISSUE THREAD

**Issue by BiloxiGeek** [openhab/openhab-webui#1003]
## The problem
Knob card sends multiple commands when trying to set a new thermostat setpoint.

I configured an oh-knob-card to control Thermostat_Setpointcooling item on a CT100 thermostat.  When changing the setpoint in the UI I see multiple commands being sent in the events.log and the setpoint ends up only changing by one degree.  

## Expected behavior

I expected to see a single command sent after the knob was released and the command would be wherever the knob was set at when released.

I was able to run a send command in the console to change the setpoint by multiple degrees and  it worked as expected, setpoint immediately changed to the new value.

## Your environment
Some discussion on the community:  https://community.openhab.org/t/knob-only-incrementing-by-1/120924

OS:  CentOS 8

```yaml
runtimeInfo:
  version: 3.1.0.M3
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 4.18.0-301.1.el8.x86_64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 50923512
  totalMemory: 197132288
bindings:
  - astro
  - hue
  - icloud
  - zoneminder
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 0.8955223880597015
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2144
    height: 1206
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
timestamp: 2021-04-17T18:55:25.480Z

```
