### ISSUE TITLE
Slider nob displayed outside the scale

### ISSUE THREAD

**Issue by soenkekueper** [openhab/openhab-webui#1005]
## The problem

When moving an slider to 100% it jumps to more than 100%.

![Slider](https://user-images.githubusercontent.com/24605357/115141360-1c682000-a03c-11eb-9105-5996049ec41f.gif)

## Expected behavior

The slider should display as 100%.

## Steps to reproduce

Configure an openhab 3 layout containing an slider. Than move the slider to 100% and release. When openhab has set the value to 100% it will display the knob out of the range of the slider.

Here is the snippet of my configuration (leaving out the non relevant list cards for other rooms):
```yaml
config:
  label: Übersicht
blocks: []
masonry:
  - component: oh-masonry
    slots:
      default:
        - component: oh-list-card
          config:
            title: Flur
          slots:
            default:
              - component: oh-slider-item
                config:
                  scale: true
                  label: true
                  scaleSubSteps: 5
                  item: Garderobe_Helligkeit
                  title: Garderobe
                  icon: f7:lightbulb
                  iconUseState: true
```

## Your environment

```yaml
runtimeInfo:
  version: 3.0.1
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.17-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 94167168
  totalMemory: 195035136
bindings:
  - ahawastecollection
  - astro
  - avmfritz
  - denonmarantz
  - exec
  - heos
  - linky
  - mqtt
  - netatmo
  - network
  - ntp
  - tankerkoenig
  - tradfri
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/89.0.4389.128 Safari/537.36
timestamp: 2021-04-18T09:52:22.987Z

```

## Browser console

```txt
Sending command to Garderobe_Helligkeit: 100
```

## Browser network traffic

![image](https://user-images.githubusercontent.com/24605357/115141482-df505d80-a03c-11eb-9199-17a297653425.png)

## Additional information

I've tested and produced this issue on

Chrome Version 89.0.4389.128 (Offizieller Build) (64-Bit) on Windows 10
Firefox 87.0 (64-Bit) on Windows 10
Chrome 89.0.4389.105 on Android 11
