### ISSUE TITLE
Allow to disable Service Worker

### ISSUE THREAD

**Issue by Legion2** [openhab/openhab-webui#1018]
## The problem

There is a bug in chrome and other browsers, related to a problem in the Web Fetch API in combination with Service Workers and Basic Authentication, see https://github.com/whatwg/fetch/issues/1132.
As a result it is not possible to use openHAB main ui behind a HTTPS reverse proxy with Basic Auth. On first page load it works. However one day later, the page is blank, because the Basic Auth prompt is not triggered by the Service Worker and therefore the access to the rest api is denied.

As you can see in the screenshot, the service worker caches the ui components, but the non-cached requests fail, because they don't trigger the Basic Auth prompt. 
![image](https://user-images.githubusercontent.com/12752323/115990285-a6773200-a5c2-11eb-83ed-e8bac89eb36a.png)

## Your suggestion
This is a bug in Browser, not openHAB ui. However, while this bug is present as a workaround, openHAB should allow to disable the service worker.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.10.17-v8+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 59561608
  totalMemory: 144703488
bindings:
  - mqtt
  - openweathermap
  - tr064
  - upnpcontrol
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/90.0.4430.85 Safari/537.36
timestamp: 2021-04-25T10:38:46.293Z

```

## Additional information

I use Apache Web Server as Reverse Proxy with TLS termination and Basic Auth.
