### ISSUE TITLE
Copy UIDs buttons lead to misalignments in MD theme

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-webui#1024]
## The problem

The "copy UIDs" buttons introduced in #980 either introduce rather ugly line misalignments in lists or are themselves misaligned vertically. 

![Screenshot_20210426_214240_com.android.chrome.jpg](https://user-images.githubusercontent.com/2004147/116141655-40310300-a6d9-11eb-8c02-3941e6b3e16c.jpg)

![Screenshot_20210426_214326_com.android.chrome.jpg](https://user-images.githubusercontent.com/2004147/116141668-458e4d80-a6d9-11eb-8c7e-cbdbbd79c7ec.jpg)

Compared to before (on the demo server):

![Screenshot_20210426_220212_com.android.chrome.jpg](https://user-images.githubusercontent.com/2004147/116143297-43c58980-a6db-11eb-9e3e-81a202bbf6de.jpg)

## Expected behavior

The functionality should be improved so the buttons render seemlessly in all themes. 

## Steps to reproduce

1. On Android (actually MD theme): Go to Things channels or a page where the general Thing UID with the button is displayed

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M3
  buildString: Milestone Build
locale: fr-FR
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.10.17-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 92441560
  totalMemory: 201326592
bindings:
  - astro
  - hue
  - icloud
  - mqtt
  - telegram
  - teleinfo
clientInfo:
  device:
    ios: false
    android: true
    androidChrome: true
    desktop: false
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: android
    osVersion: "10"
    webView: true
    webview: true
    standalone: true
    pixelRatio: 3
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: en-GB
    languages:
      - en-GB
    onLine: true
    platform: Linux aarch64
  screen:
    width: 360
    height: 780
    colorDepth: 24
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/90.0.4430.66 Mobile Safari/537.36
timestamp: 2021-04-26T19:50:58.582Z
```

## Additional information

 Related to #980.
