### ISSUE TITLE
[Main UI] Provide access to widget properties from widget expressions

### ISSUE THREAD

**Issue by matthijskooijman** [openhab/openhab-webui#1025]
## The problem

I have a oh-label-card, which has its `item` property set to some value. In the label property, I want to create an expression that references the configured item, but it seems I cannot access the current widget's properties (only the global list of `items` and the `props` for the page).

## Your suggestion
I would suggest making this possible, e.g. by adding a `widget` predefined variable that resolves to the current widget's properties. This would allow using e.g. `widget.item` for my case, but also opens up room for a lot of customization by accessing the other properties.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: en-NL
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 49622120
  totalMemory: 194838528
bindings:
  - chromecast
  - dsmr
  - ipp
  - mqtt
  - spotify
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1280
    height: 1024
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
timestamp: 2021-04-28T09:17:06.871Z
```
