### ISSUE TITLE
[Main UI] Widget expression tester shows `undefined` as empty string

### ISSUE THREAD

**Issue by matthijskooijman** [openhab/openhab-webui#1026]
## The problem

When you use the widget expression tester and enter an expression that results in an undefined value, an empty result is shown.

## Expected behavior

It would be more useful if the tester would show `undefined`, making it more clear to the user that their expression is valid, but returns undefined (just showing nothing at all is vague, I initially suspect I had a syntax error or some other hidden problem).

## Steps to reproduce

![image](https://user-images.githubusercontent.com/194491/116379939-cbaeaf00-a813-11eb-990d-8e1130b9eb10.png)

You can confirm that the value is undefined by forcing it to string:

![image](https://user-images.githubusercontent.com/194491/116380022-dff2ac00-a813-11eb-8eaf-81fcfc17d114.png)

## Your environment

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: en-NL
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 49622120
  totalMemory: 194838528
bindings:
  - chromecast
  - dsmr
  - ipp
  - mqtt
  - spotify
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1280
    height: 1024
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
timestamp: 2021-04-28T09:21:32.026Z

```
