### ISSUE TITLE
To remove an invalid channel Link from an Item should not trigger a "go back" to the List of Items

### ISSUE THREAD

**Issue by vletroye** [openhab/openhab-webui#1032]
## The problem

When I click on an "(unknow) Invalid Link" in the Channel Links of an Item (in the "Settings" of OpenHab 3), I get a popup suggesting to remote it. If I click on "OK" to remove it, the UI "goes back" automatically to the list of Items, which is really annoying when one has several such Invalid Links to remove. One has indeed to search again for the Item, etc...

![image](https://user-images.githubusercontent.com/9768028/116787625-578b3a00-aaa5-11eb-8f64-3ea7080b6319.png)

## Expected behavior

It would be more convenient to refresh the page displaying the current Item instead of going back to the list of Items.

## Steps to reproduce

I have just upgraded from openHab2 to openHab3. The link with my Somfy Tahoma box was lost. So I did restore the binding but all Items previously linked have not invalid Links.

Via the Items menu of OpenHab3's Settings, find an Item with such an Invalid Link, click on that invalid link and answer "Ok" when suggested to remove this invalid link...

## Your environment

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: en-BE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 49750040
  totalMemory: 324403200
bindings:
  - allplay
  - chromecast
  - daikin
  - deconz
  - hue
  - ipcamera
  - network
  - openweathermap
  - samsungtv
  - somfytahoma
  - yamahareceiver
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - fr-FR
      - en
      - fr-BE
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/90.0.4430.93 Safari/537.36
timestamp: 2021-05-01T15:48:24.862Z

```

## Browser console

```txt

```
