### ISSUE TITLE
When going back from an Item to the List of Items, the current filter should be reapplied

### ISSUE THREAD

**Issue by vletroye** [openhab/openhab-webui#1033]
## The problem

To edit an Item in openHab3, we have to search for it first, via the Settings > Items of the Main UI.
To search for it, we enter its name in the Search box.
Once we have searched and found the item, we click on it to see the details (open the Item).
Once done, we click on "Back" to go back to the list of Items.

But once back in the list of Items, although the name used to search for the item is still there, the page immediately displays the full list of items. One has to modify the name in the search box to reapply the filter.

It would be convenient that, when coming back to the list of Items, it is automatically filtered with the name still available in the Search box (Especially when one intends to edit all Items with the same name). In other cases (when one intends to edit other items), one has anyway to type another name (changing or removing de facto the filter).

![dsMfubr](https://user-images.githubusercontent.com/9768028/116788257-ea79a380-aaa8-11eb-8efe-94c20a7212ce.gif)

## Expected behavior

When going back to the list of Items, the name typed in the Search Box should be reapplied as a filter instead of showing the complete list of Items.

## Steps to reproduce

1. Go to the Settings > Items menu of openHab3
2. Search for an Item 
3. Open that item
4. Click on Back

You can see that the name of the item, typed as step 2, is still in the search box. But the list is not filtered anymore.
(Actually, it's filtered when you just come back to the list but within 1 second, it's unfiltered) 

## Your environment

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: en-BE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 109776824
  totalMemory: 324403200
bindings:
  - allplay
  - chromecast
  - daikin
  - deconz
  - hue
  - ipcamera
  - network
  - openweathermap
  - samsungtv
  - somfytahoma
  - yamahareceiver
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - fr-FR
      - en
      - fr-BE
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/90.0.4430.93 Safari/537.36
timestamp: 2021-05-01T16:16:40.360Z

```

## Browser console

```txt

```
