### ISSUE TITLE
[Main UI] Error in Z-Wave Network Map when zwave_neighbours is undefined

### ISSUE THREAD

**Issue by TheNetStriker** [openhab/openhab-webui#1037]
## The problem

I've got some ZWave devices in my network that have no zwave_neighbours thing property. Those are mainly ghost devices where the device discovery did not work, but I also cannot delete them anymore from the controller so I just leave them as a thing in my config so that they don't appear in the inbox. Those devices are causing an error in the browsers console when opening the Z-Wave Network Map and nothing is displayed. I was able to temporarily fix this by adding the zwave_neighbours property with an empty string to those devices using the rest api. But it would be nice if the javascript would check if the property is missing.

## Expected behavior

My suggestion to solve this problem would be to just assume that the zwave_neighbours property is empty when it does not exist.

## Steps to reproduce

This could be reproduced e.g. by adding a battery operated Z-Wave device without finishing the discovery process. Then the thing does not have the zwave_neighbours property. Or the property could just be deleted on one Z-Wave thing by using the rest api.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: de-CH
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.10.17-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 99498400
  totalMemory: 324403200
bindings:
  - doorbird
  - exec
  - harmonyhub
  - http
  - kodi
  - mail
  - mqtt
  - network
  - networkupstools
  - onewire
  - onkyo
  - openweathermap
  - samsungtv
  - systeminfo
  - telegram
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
timestamp: 2021-05-04T08:51:06.595Z
```

## Browser console

```txt
app.js:32 Error evaluating async computed property: TypeError: Cannot read property 'split' of undefined
    at http://172.17.2.21:8080/js/39.app.js:1:1168
    at Array.forEach (<anonymous>)
    at http://172.17.2.21:8080/js/39.app.js:1:865
```

## Browser network traffic

There are no failed requests in the network tab. It is simply an error in the javascript because of the undefined property.

## Additional information

Here is a possible solution that could solve the problem:

In the file **bundles/org.openhab.ui/web/src/components/thing/zwave/zwave-network.vue** add the following on line 103:
`let neighbours = t.properties.zwave_neighbours ? t.properties.zwave_neighbours : ''`
And then on line 103 change the line to:
`neighbours.split(',').forEach((n) => {`

I was not able to test this solution because I was not able to build the web ui for OpenHab 3.0.2 and maybe there is a cleaner solution. This is just a suggestion.
