### ISSUE TITLE
[main UI] on-expression in oh-colorpicker-cell not working

### ISSUE THREAD

**Issue by d-sko** [openhab/openhab-webui#1039]
## The problem

The on-expression is not working in `oh-colorpicker-cell`, the cell is always colored. The following screenshot shows an `oh-colorpicker-cell` and an `oh-slider-cell` with the same on-expression (`on: =(items.eHueGo_Zustand.state==='ON')`). The slider cell is correctly colored, the colorpicker cell not.

![image](https://user-images.githubusercontent.com/5774313/117039285-e3e96700-ad08-11eb-9aa6-76463cfef5e0.png)

## Expected behavior

`oh-colorpicker-cell` should be colored depending on the on-expression (if set)

## Steps to reproduce

1. add a `oh-colorpicker-cell`
2. set item etc so you have a basic example
3. add an on-expression which correctly resolves the on/off state of the item/equipment
4. add a color
5. save
6. turn item on/off

here is the code for the cells in my screenshot above:

```yaml
- component: oh-colorpicker-cell
  config:
    title: Hue Go
    item: eHueGo_Farbe
    icon: "=(items.eHueGo_Zustand.state === 'ON') ? 'f7:lightbulb_fill' : 'f7:lightbulb'"
    footer: "=(items.eHueGo_Zustand.state === 'ON') ? \"Helligkeit \" + items.eHueGo_Helligkeit.state + \"%\" : \"ausgeschaltet\""
    on: =(items.eHueGo_Zustand.state==='ON')
    color: yellow
    action: toggle
    actionItem: eHueGo_Zustand
    actionCommand: ON
    actionCommandAlt: OFF
    modules:
    - wheel
    - brightness-slider
  slots: null
- component: oh-slider-cell
  config:
    item: eHueGo_Helligkeit
    min: 0
    max: 100
    action: toggle
    actionItem: eHueGo_Zustand
    title: Hue Go
    icon: "=(items.eHueGo_Zustand.state === 'ON') ? 'f7:lightbulb_fill' : 'f7:lightbulb'"
    on: =(items.eHueGo_Zustand.state==='ON')
    actionCommand: ON
    actionCommandAlt: OFF
    color: yellow
    footer: "=(items.eHueGo_Zustand.state === 'ON') ? \"Helligkeit \" + items.eHueGo_Helligkeit.state + \"%\" : \"ausgeschaltet\""
```

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M4
  buildString: Milestone Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.17-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 16096656
  totalMemory: 154472448
bindings:
  - astro
  - homematic
  - miio
  - mqtt
  - network
  - shelly
  - unifi
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/90.0.4430.93 Safari/537.36
timestamp: 2021-05-04T16:51:20.327Z

```

## Browser console

```txt
Sending command to eHueGo_Zustand: ON app.js:38 
Sending command to eHueGo_Zustand: OFF app.js:38
```

## Browser network traffic

![image](https://user-images.githubusercontent.com/5774313/117040652-6161a700-ad0a-11eb-83d0-2b645729bea8.png)

## Additional information

 I've tried this in openHAB 3.0.2 and 3.1.0.M4, both running in docker on an Raspberry Pi 4.
