### ISSUE TITLE
Main UI Widgets - Set props not saved

### ISSUE THREAD

**Issue by 2relativ** [openhab/openhab-webui#1058]
## The problem

While setting props in an Widget (i.e. the thing it is showing or values in the widget) those aren't being saved

## Expected behavior

Values being saved after clicking save or crtl+s
## Steps to reproduce

1. Create a new widget (i.e. https://raw.githubusercontent.com/Hypfer/Valetudo-Openhab/master/widgets/valetudo-standalone.yml)
2. Click set props
3. click done
4. click save
5. exit widget
6. open widget again finding the props not being saved

## Your environment

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.4.0-73-generic
  osArchitecture: amd64
  availableProcessors: 1
  freeMemory: 34067840
  totalMemory: 141557760
bindings:
  - astro
  - avmfritz
  - denonmarantz
  - exec
  - logreader
  - miio
  - mqtt
  - network
  - ntp
  - openweathermap
  - zigbee
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1366
    height: 768
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
timestamp: 2021-05-19T14:02:27.453Z
```

## Browser console

```txt

```
