### ISSUE TITLE
Area chart to support shading CLOSED instead of OPEN

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-webui#1072]
## The problem

I use `Contact` items to measure relay status. `CLOSED` status is used to denote situation when relay is closed, i.e. relay is passing power, `OPEN` is used to denote situation when there is no power.

Area chart seems to highlight time periods when item status is `OPEN` -- this is inverse to what I would like to have.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/315866/120093797-4aee1600-c125-11eb-8f9e-8d43ed6bb531.png">

```yaml
    - component: oh-time-series
      config:
        name: OH patterit
        gridIndex: 0
        xAxisIndex: 0
        yAxisIndex: 0
        type: line
        areaStyle: {}
      slots:
        markArea:
          - component: oh-mark-area
            config:
              name: LivingRoomRadiatorPower
              item: LivingRoomRadiatorPower
```

## Your suggestion

Allow 'inverting' area chart colors, i.e. highlighting CLOSED instead of OPEN.

Can I use `areaStyle` configuration property to override colors?

## Your environment

openHAB 3.0.2

```yaml

```

**Comment by crnjan** [comment]
A new property was introduced `states`:

```
markArea:
          - component: oh-mark-area
            config:
              name: LivingRoomRadiatorPower
              item: LivingRoomRadiatorPower
              states: CLOSED
```

that should do the trick. Also more can be specified

```
markArea:
          - component: oh-mark-area
            config:
              name: LivingRoomRadiatorPower
              item: LivingRoomRadiatorPower
              states: 
                 - CLOSED
                 - OFF
```
