### ISSUE TITLE
[Main UI] Layout and Search Issues in Regional Settings

### ISSUE THREAD

**Issue by hypetsch** [openhab/openhab-webui#1083]
## The problem
The following issues where found in the "Regional Settings" section but may also apply to other elements.

1) Regional Settings > Land/Region: Searching for some characters does not yield an expected result (Browser language set to "German"). e.g. searching for "Öster" is missing "Österreich".
![p4ai6AFh4c](https://user-images.githubusercontent.com/16302578/120384726-d1257a80-c326-11eb-953f-94338d479d11.gif)
A similar issue happens when searching for "Ä" which yields results without any "Ä".
![image](https://user-images.githubusercontent.com/16302578/120380931-1bf0c380-c322-11eb-8863-0f3a1af5f803.png)
See also 3)

2) The scrollbar is hidden by the popup header:
![xpgEH0wFlW](https://user-images.githubusercontent.com/16302578/120384328-4e042480-c326-11eb-8e61-c2df83597d66.gif)

3) The configured language is not consistently used. Although "English" is configured, some UI elements are still shown in German (even after page reload - probably by design?).
When switching the browser to "English", the behavior of issue 1) is different; just a guess, but it looks a bit like the search is not using the translated entries?
![image](https://user-images.githubusercontent.com/16302578/120381771-295a7d80-c323-11eb-91f5-fd11bdeb5289.png)

## Expected behavior
- Search results should contain only entries matching the criteria / should contain all matching entries.
- Scrollbar should be entirely visible.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M4
  buildString: Milestone Build
locale: en-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 79250024
  totalMemory: 194772992
bindings:
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en
    languages:
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/91.0.4472.77 Safari/537.36
timestamp: 2021-06-01T20:08:22.164Z
```
