### ISSUE TITLE
Customizable page-icons - Especially for Sidebar

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-webui#1087]
## The problem
At the moment, there is no possibility to configure individual icons for pages.
Especially for the Sidebar this could be a useful thing to cluster pages or give a better overview through page-related icons.
For sure f7-icons with customizable colors (as for widges) would give a good flexibility

![sdf](https://user-images.githubusercontent.com/68030498/120637304-04732100-c46f-11eb-8603-1ce380f53c05.jpg)

## Your suggestion
Add for pages the options
- set icon (oh, f7 and individual, placed in the same folder) --> Same as for widgets
- set icon colors for f7-widgets --> Same as for widgets
- give the option, to choose if icon-color is also used for the page-name shown in the sidebar

## Your environment
openHAB 3 UI
Microsoft Edge Browser

```yaml
runtimeInfo:
  version: 3.1.0.M5
  buildString: Milestone Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 59329008
  totalMemory: 194772992
bindings:
  - astro
  - chromecast
  - http
  - mqtt
  - network
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/92.0.4514.0 Safari/537.36 Edg/92.0.902.2
timestamp: 2021-06-03T11:28:09.495Z

```
