### ISSUE TITLE
Rule re-configuration does not overtake old attributes

### ISSUE THREAD

**Issue by Nears** [openhab/openhab-webui#1091]
## The problem
When I define a rule and reconfigure it by changing the WHEN condition e.g. from "an item receives a command" to "an item state changes" the value of the preconfigured item is no longer valid and I need to re-set it even if I choose exactly the same item.

## Expected behavior
No regonfiguration of the item should be required.

## Steps to reproduce

1. Define a rule 
2.  save it
3. Then modify it again as described above

## Your environment
OH3 running on an raspberry pi 3 with rasbian os

```
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.17-v8+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 11039328
  totalMemory: 243269632
bindings:
  - astro
  - exec
  - http
  - hyperion
  - ipcamera
  - kodi
  - mqtt
  - network
  - ntp
  - playstation
  - sonos
  - telegram
  - tr064
  - tradfri
  - zigbee
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 0.8955223880597015
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 4288
    height: 1787
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101
    Firefox/88.0
timestamp: 2021-06-05T11:58:41.337Z
```

## Browser console

```txt

```
