### ISSUE TITLE
[Main UI] Advanced and linked channels not shown

### ISSUE THREAD

**Issue by hypetsch** [openhab/openhab-webui#1094]
## The problem
Thing configuration: Channel category "Linked" does not show all linked channels.

![image](https://user-images.githubusercontent.com/16302578/120972282-e0188c80-c76d-11eb-9402-57b597ed60f0.png)

![image](https://user-images.githubusercontent.com/16302578/120972310-e60e6d80-c76d-11eb-9d4f-6cba02c3171d.png)

## Your suggestion
This behavior might be intended (and is correct in regards to the "Show advanced" option) but I think the UI could be improved and it would be less confusing to show all linked channels, regardless of the "Show advanced" flag (...I just wondered why my linked channel disappeared).
At least some visual indication that there are linked channels could make sense (like a badge on the "Linked" category) or auto-enabling the flag when switching to the "Linked" category if there are linked "advanced channels" or make the "Show advanced" only available on the "All" category, ...

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M4
  buildString: Milestone Build
locale: de-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 101027576
  totalMemory: 251006976
bindings:
  - amazonechocontrol
  - astro
  - bsblan
  - fronius
  - gpio
  - hue
  - onewiregpio
  - openweathermap
  - somfytahoma
  - telegram
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - en
      - de
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/91.0.4472.77 Safari/537.36
timestamp: 2021-06-07T06:54:53.015Z
```
