### ISSUE TITLE
[Main UI] Opening Links in new Tab/Window is not possible

### ISSUE THREAD

**Issue by hypetsch** [openhab/openhab-webui#1097]
## The problem

Using the browser functionality "Open in new tab/window" is not working.

![jhyOCbCKIq](https://user-images.githubusercontent.com/16302578/121225268-a472e500-c889-11eb-8131-405106efbd34.gif)

## Expected behavior

Opening should be possible.

## Steps to reproduce

See screen capture.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M4
  buildString: Milestone Build
locale: de-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 70427960
  totalMemory: 251006976
bindings:
  - amazonechocontrol
  - astro
  - bsblan
  - fronius
  - gpio
  - hue
  - onewiregpio
  - openweathermap
  - somfytahoma
  - telegram
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en
    languages:
      - en
      - en-US
      - de-DE
      - de
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/91.0.4472.77 Safari/537.36
timestamp: 2021-06-08T16:47:54.163Z

```

## Additional information

The opened URL is `http://192.168.1.2:8080/developer/` but should be `http://192.168.1.2:8080/#!/developer/`?

![image](https://user-images.githubusercontent.com/16302578/121226163-8954a500-c88a-11eb-876f-25400adb0b8b.png)
