### ISSUE TITLE
Analyzer always includes zero Y value if min and max are set to 'auto'

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab-webui#1101]
## The problem

When using the Analyzer to visualise item state evolution over time, MainUI always includes the zero Y value, even when min and max are set to auto (default setting).

The side-effect is that you can't render atmospheric pressure readings in a meaningful way, unless you manually define a minimum value (the differences are too small to render as they oscillate only minimally). Same is true for temperature readings.

<img width="1069" alt="Screenshot 2021-06-12 at 11 06 27" src="https://user-images.githubusercontent.com/48714736/121771255-9c0ef880-cb6e-11eb-9543-67d06a4521f3.png">

<img width="1070" alt="Screenshot 2021-06-12 at 11 06 50" src="https://user-images.githubusercontent.com/48714736/121771256-9dd8bc00-cb6e-11eb-99ad-db1f09068b4c.png">

## Expected behavior

The Y range should obey the default settings: min and max set to auto. Don't automatically include the zero reading to the Y axis range.

## Steps to reproduce

Any Analyzer reading from a persisted item or from the Properties entries (MainUI semantic model browser)

## Your environment

openHAB3 on Raspberry Pi 3B+ (openhabian on buster) - previously upgraded from openHAB2.5 through `openhabian-config`

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: en-BE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 64526296
  totalMemory: 247332864
bindings:
  - astro
  - buienradar
  - exec
  - gpstracker
  - openweathermap
  - sonos
  - telegram
  - tradfri
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: en-gb
    languages:
      - en-gb
    onLine: true
    platform: MacIntel
  screen:
    width: 3360
    height: 1890
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
timestamp: 2021-06-12T09:04:12.360Z

```

## Browser console

```txt

```
