### ISSUE TITLE
Chart widget don't support expressions

### ISSUE THREAD

**Issue by Belgadon** [openhab/openhab-webui#1102]
Inside an oh-mark-area object the items doesn't get called from props. It only works when its hardcoded by its name.

I made a minimal example. See the last line - the item is not selected.
If I hardcode the item by its name its working, but thats not very flexible.
I tried _=props.window_item_ and _=items[props.window_item]_.

```
uid: test
tags: []
props:
  parameters:
    - context: item
      description: Window Sensor Item shown in chart
      label: Window Item
      name: window_item
      required: false
      type: TEXT 
component: f7-card
config:
  title: test
slots:
  default:
    - component: oh-chart
      config:
        label: test
        periodVisible: false
      slots:
        grid:
          - component: oh-chart-grid
            config:
              show: true
              left: 50
              right: 50
        xAxis:
          - component: oh-time-axis
            config:
              gridIndex: 0
        yAxis:
          - component: oh-value-axis
            config:
              gridIndex: 0
        series:
          - component: oh-time-series
            config:
              name: Fenster
              gridIndex: 0
              xAxisIndex: 0
              yAxisIndex: 0
              type: bar
              color: red
            slots:
              markArea:
                - component: oh-mark-area
                  config:
                    name: Fenster
                    item: =props.window_item #=items[props.window_item]
```

**Comment by arjan-io** [comment]
This is also true for the ```label``` item in
```
- component: oh-chart
      config:
        label: test
```
It does not support expressions.
It does work however in a ```oh-time-series``` like this:
```
- component: oh-time-series
      config:
        areaStyle:
          opacity: 0.2
        gridIndex: 0
        item: =props.hum
        name: Luchtovchtigheid
        service: rrd4j
        smooth: true
        type: line
        xAxisIndex: 0
        yAxisIndex: 1
```
(Different chart example)

**Comment by canufarm** [comment]
> Inside an oh-mark-area object the items doesn't get called from props. It only works when its hardcoded by its name.

+1 from me.

Expressions also do not work with "period:". Most of the echart-settings are not supported by the chart widget. Would be great if all echart-settings could be used with expressions, because otherwise one has to build separate widget for each item, although the widgets are exact copies.

Thanks.

**Comment by crnjan** [comment]
Which version are you using? This should work with latest snapshots (and 3.4.0 Milestone 4), i.e. a slightly modified widget:

```
uid: test
tags: []
props:
  parameters:
    - context: item
      description: Window Sensor Item shown in chart
      label: Window Item
      name: window_item
      required: false
      type: TEXT
timestamp: Nov 9, 2022, 12:43:42 AM
component: f7-card
config:
  title: ="Value = " + @(props.window_item)
slots:
  default:
    - component: oh-chart
      config:
        periodVisible: false
      slots:
        legend:
          - component: oh-chart-legend
            config:
              bottom: "8"
              orient: horizontal
              show: true
        grid:
          - component: oh-chart-grid
            config:
              show: true
              left: 50
              right: 50
        xAxis:
          - component: oh-time-axis
            config:
              gridIndex: 0
        yAxis:
          - component: oh-value-axis
            config:
              gridIndex: 0
        series:
          - component: oh-time-series
            config:
              gridIndex: 0
              item: =props.window_item
              name: =props.window_item
              type: line
              xAxisIndex: 0
              yAxisIndex: 0
```

after picking temperature item it renders:

<img width="695" alt="Screenshot 2022-11-09 at 00 47 45" src="https://user-images.githubusercontent.com/3818211/200700638-2fe277c2-fa9a-4d83-a43c-59a2c5629ca9.png">

**Comment by crnjan** [comment]
> This is also true for the `label` item in
> 
> ```
> - component: oh-chart
>       config:
>         label: test
> ```


syntax is a bit different

```
    - component: oh-chart
      config:
        ...
      slots:
        title:
          - component: oh-chart-title
            config:
              text: =props.title
```

and i also evaluated (with https://github.com/openhab/openhab-webui/pull/1638), FYI
