### ISSUE TITLE
Scaling in sliders (in HSV widget) is completely off

### ISSUE THREAD

**Issue by dK0y** [openhab/openhab-webui#1103]
## The problem

The scaling of sliders in HSV widgets in 3.1.0M5 is off.

(Edit: it only seems to happen in edit mode. In 'run mode' everything seems ok.)

For instance, the knob of the H value with a range of 0..360 is at the extreme right of the scale at at value of ~50. You can still increase it further though by dragging it beyond the widget. The value shown next to the widget and the color of the knob do show the correct values.

In the image for instance at '1', the value is 139 but the knob is not shown as it is placed outside the widget.
In the same image at '2' you can see the knob at roughly 66% of the scale, but it's value is only 29 (out of 360). The color of the knob itself is correct for '29' though. At '3' it's similar for the brightness.

![image](https://user-images.githubusercontent.com/85194074/122006968-c1db0e00-cdb7-11eb-9cab-27c077c7624f.png)

## Expected behavior

1) With the knob of a slider placed at the extreme left, the value should be the minimum value (ok)
2) If the value is the minimum value the knob should be placed at the left of the slider (ok)
3) With the knob of a slider placed at the extreme right, the value should be the maximum value (not ok)
4) If the value is the maximum value the knob should be placed at the right of the slider (not ok)

## Steps to reproduce

1. Use openHab 3.1.0M5 (other versions not tested)
2. Create a layout page using the fixed grid
3. Add a widget
4. Create the widget from your model, using a color item

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M5
  buildString: Milestone Build
locale: en-NL
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.8.0-53-generic
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 317382272
  totalMemory: 504365056
bindings:
  - astro
  - homewizard
  - hpprinter
  - hue
  - knmi
  - mqtt
  - neato
  - nest
  - netatmo
  - network
  - onkyo
  - somfytahoma
  - spotify
  - stecagrid
  - systeminfo
  - unifi
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en
    languages:
      - en
      - nl-NL
      - nl
      - en-US
      - de
      - da
      - mt
      - fr
      - pl
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/91.0.4472.101 Safari/537.36
timestamp: 2021-06-15T06:54:40.274Z

```

## Browser console

```txt
I see no console tab
```
