### ISSUE TITLE
[Main UI] OH3 Overview Page Spacing and alignment depends on how accessed

### ISSUE THREAD

**Issue by Mark-VG** [openhab/openhab-webui#1104]
## The problem

The Overview Page on openHAB 3 behave differently depending on which method is used to access:

- openHAB Logo on Main Page
- Overview Page from Left Panel

When accessed via the openHAB logo, there is additonal spacing above the actual content which affects the way the page is displayed - especially on smaller screen devices with limited space

When accessed via the Left Panel Menu the page is displayed correctly.

![Overview1](https://user-images.githubusercontent.com/84638697/122109315-8410d080-ce1d-11eb-9976-87ee64693b46.gif)

As you can see from the above GIF, there is a difference in the way the page is displayed between the two access methods.

## Expected behavior

The two access methods to produce the same results for the same page.

## Steps to reproduce

1. Create a Cell as follows on the Overview Page:

```
component: oh-cell
config:
  on: true
  title: Test Space
slots:
  default:
    - component: f7-page
      config:
        style:
          z-index: 0
          --f7-navbar-height: 0px
          --f7-navbar-font-size: 0px
          --f7-navbar-bg-color: white
          --f7-navbar-border-color: white
          --f7-navbar-link-color: black
          --f7-navbar-text-color: black
      slots:
        default:
          - component: f7-list
            config:
              class:
                - padding-bottom
            slots:
              default:
                - component: Label
                  config:
                    text: First Line
                    style:
                      padding-left: 20px
                      font-weight: 500
                      line-height: 20px

```
2. Access the Page via the openHAB logo on the main page and observe the spacing before the **First Line**
3. Access the Page via the Overview Link on the Laft Menu and observe the spacing before the **First Line**

## Your environment

Configuration folder C:\openHAB\conf
User data folder C:\openHAB\userdata
Logs folder C:\openHAB\userdata\logs
Operating system Windows 10/10.0 (amd64)
Java Runtime Azul Systems, Inc. 11.0.9.1 (Zulu11.43+55-CA)

openHAB 3.1.0.M5
