### ISSUE TITLE
[Main UI] Group blocks a analyze graph from being seen.

### ISSUE THREAD

**Issue by Skinah** [openhab/openhab-webui#1105]
## The problem

Group does not disappear when clicking on a item that draws a graph and it blocks the graph from being seen. Only happens from the overview page. Has been working great up until a week ago aprox so I'm very certain it is a recent change in the daily snapshots.

![image](https://user-images.githubusercontent.com/32607303/122230099-ac233100-cefc-11eb-875b-db5fed6fd450.png)

## Steps to reproduce

Setup a label cell on the overview page that will display a group popup of X equipment when clicked.
Open up this group popup of X equipment from the overview page.
Click on any item that will open an analyze graph window.
The group does not disappear like it used to a week ago and the group and all the controls stay on top and block the graph that does display in the back ground.
You can not move the group display to see the graph.

If I do the same thing on the equipment tab instead of the overview page, it works great. Click on the temperature item and the graph displays and the group disappears so the graph can be seen.

Since it is inconsistent behaviour, I am pretty confident this is a bug and not intended behavior. Only started happening the past week in the daily snapshots. Todays build still has the problem.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2425"
locale: en-AU
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.8
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.41+75-CA
  osName: Linux
  osVersion: 5.10.34-meson64
  osArchitecture: arm
  availableProcessors: 6
  freeMemory: 531583696
  totalMemory: 648740864
bindings:
  - chromecast
  - harmonyhub
  - ipcamera
  - ipobserver
  - mqtt
  - opensprinkler
  - telegram
  - wled
  - zigbee
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1707
    height: 960
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.48
timestamp: 2021-06-16T13:45:31.463Z

```
