### ISSUE TITLE
[3.1.0-SNAPSHOT] Slider triggering multiple ItemCommandEvents during sliding

### ISSUE THREAD

**Issue by WaldemarLehner** [openhab/openhab-webui#1114]
## The problem

Instead of sending one ItemCommandEvent when dragging a Slider connected with a Dimmer-Item,
with version `3.1.0-SNAPSHOT`, multiple ItemCommandEvents are generated.

You can see the wrong Behaviour here:
https://youtu.be/ebjau8ZRULI

## Expected behavior
One ItemCommandEvent should be sent out once user has stopped dragging the Slider.

You can see the behaviour as it was back in version `3.0.1-Release` here:
https://youtu.be/eEW9369IZME

## Steps to reproduce

1. Run version `3.1.0-SNAPSHOT`
2. Create a new Item of Type "Dimmer" (I called mine `TestDimmer`)
3. Create a new Layout and place either a Dimmer-Card, or a List-Card with a Dimmer-Item. In either case, link it up to the Item that was created in Step 2.  
    3.a Alternatively, use this Layout Definition:
    ```yaml
    config:
        label: UI Command Bug
        sidebar: true
        layoutType: responsive
    blocks:
        - component: oh-block
        config: {}
        slots:
            default:
            - component: oh-grid-row
                config: {}
                slots:
                default:
                    - component: oh-grid-col
                    config: {}
                    slots:
                        default:
                        - component: oh-list-card
                            config: {}
                            slots:
                            default:
                                - component: oh-slider-item
                                config:
                                    title: Test Dimmer
                                    min: 0
                                    max: 100.02
                                    item: TestDimmer
                    - component: oh-grid-col
                    config: {}
                    slots:
                        default: []
        - component: oh-block
        config: {}
        slots:
            default:
            - component: oh-grid-row
                config: {}
                slots:
                default:
                    - component: oh-grid-col
                    config: {}
                    slots:
                        default:
                        - component: oh-slider-card
                            config:
                            item: TestDimmer
                            min: 0
                            max: 100
                            title: Test Dimmer
    masonry: null
    ```
4. Drag the Sliders. You should see that the other Slider updates aswell.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2404"
locale: de-DE
systemInfo:
  configFolder: _redacted_/openhab/conf
  userdataFolder: _redacted_/openhab/userdata
  logFolder: _redacted_/openhab/userdata/logs
  javaVersion: 11.0.11
  javaVendor: Oracle Corporation
  osName: Linux
  osVersion: 5.11.22-2-MANJARO
  osArchitecture: amd64
  availableProcessors: 12
  freeMemory: 242711784
  totalMemory: 381681664
bindings:
  - stellwerk
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
timestamp: 2021-06-23T10:25:06.322Z

```

## Browser console

![image](https://user-images.githubusercontent.com/27686785/123081936-ca1df380-d41e-11eb-94a7-24d9be186620.png)

## Browser network traffic

Seems regular. POST-Requests with the new state in the POST-Body.
![image](https://user-images.githubusercontent.com/27686785/123082378-3d276a00-d41f-11eb-94c7-e99b0ec987fa.png)
