### ISSUE TITLE
widget development: Unable to correctly create custom list widgets

### ISSUE THREAD

**Issue by wuschi** [openhab/openhab-webui#1129]
## The problem

Coming from OH 1.8, I'm currently trying to get my head around building custom widgets.
I am currently trying to build a custom list widget that renders _exactly_ like the predefined widgets, e.g. the oh-rollershutter-item.
At the current state of the widget editor, this seems to be impossible. For example, for the f7-list-item widget, i cannot define a slot "footer" that renders within `<div class="item-inner"><div class="item-footer">`. Same applies to slot "media". 

## Expected behavior

I would have expected that the widget editor lets me define custom list widgets in yaml using the f7 widget components with the respective slots renderings correctly.

## Steps to reproduce

doesn't really apply here, but here's my current content of the widget editor:

```yaml
uid: custom_list_item
tags:
  - list
  - blinds
props:
  parameters:
    - context: item
      description: Control Item
      label: Control Item
      name: item
      required: false
      type: TEXT
  parameterGroups: []
timestamp: Jul 9, 2021, 2:30:05 PM
component: f7-list-item
config:
  mediaItem: true
  title: Test-Title
slots:
  content:
         - component: f7-row
           config:
             class:
               - align-items-center
             style:
               width: 100%
               flex-wrap: nowrap
           slots:
             default:
               - component: f7-col
                 config:
                   class:
                     - display-flex
                     - flex-direction-row
                     - align-items-center
                     - margin-top
                     - margin-bottom
                   style:
                     height: 100%
                     width: fit-content
                     min-width: 100px
                 slots:
                    default:
                      - component: oh-button
                        config:
                          icon-f7: lightbulb_fill
                          style:
                            --f7-button-bg-color: transparent
                            --f7-button-hover-bg-color: transparent
                            --f7-button-pressed-bg-color: transparent
               - component: f7-col
                 config:
                   class:
                     - display-flex
                     - flex-direction-row
                     - align-items-center
                     - margin-top
                     - margin-bottom
                   style:
                     width: fit-content
                     min-width: 100px
                 slots:
                   default:
                     - component: oh-rollershutter-item
                       config:
                         item: =props.item
  
```

## Your environment

```yaml
runtimeInfo:
  version: 3.0.2
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.25-linuxkit
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 23145520
  totalMemory: 105906176
bindings:
  - hue
  - knx
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
timestamp: 2021-07-09T14:33:23.550Z

```

**Comment by arroyoj** [comment]
I ran into the same problem when I was trying to build a custom list widget using `f7-list-item`. Here is a dummy example to demonstrate the problem:

Widget editor YAML:
```
uid: widget_a354cde555
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Sep 17, 2021, 10:45:39 PM
component: f7-list-item
config:
  title: title in config
  footer: footer in config
  mediaItem: true
slots:
  content:
    - component: oh-button
      config:
        text: content slot button
  footer:
    - component: oh-button
      config:
        text: footer slot button
  header:
    - component: oh-button
      config:
        text: header slot button
  after:
    - component: oh-button
      config:
        text: after slot button
  default:
    - component: oh-button
      config:
        text: default slot button
```

This gets rendered to the following HTML:
```
<li class="media-item">
  <div class="item-content">
    <div class="item-inner">
      <div class="item-title-row">
        <div class="item-title">title in config</div>
      </div>
      <a href="#" class="button"><span>content slot button</span></a>
      <a href="#" class="button"><span>after slot button</span></a>
      <a href="#" class="button"><span>header slot button</span></a>
      <a href="#" class="button"><span>footer slot button</span></a>
      <a href="#" class="button"><span>default slot button</span></a>
      <div class="item-footer">footer in config</div>
    </div>
  </div>
</li>
```

Instead of each button being wrapped in a div for the appropriate slot, all of the buttons are being rendered as if they had been placed in the `inner` slot.

I believe this is due to the way Framework7 v5 handles `list-item` and `list-item-content`. In F7's `list-item`, it looks like the components in all the slots are first collapsed into a list and passed into the default slot of `list-item-content`. See here: https://github.com/framework7io/framework7-vue/blob/9c34714cb7b153655ba33dff3cc9ac44a9be0433/src/components/list-item.vue#L71-L117.

Then, in F7's `list-item-content`, the components are put back into their original slots, but the slot names are found by looking for the `slot` key in each component's data object. See here: https://github.com/framework7io/framework7-vue/blob/9c34714cb7b153655ba33dff3cc9ac44a9be0433/src/components/list-item-content.vue#L63-L84. 

The problem seems to be that in MainUI, the slot components are not being passed in with their slot names. As a result, all the components wind up in the `inner` slot, as shown in the HTML above. I think this can be traced back to the `generic-widget-component` template here: https://github.com/openhab/openhab-webui/blob/0c2b25beb8cf3eebc1af120c82ad62f4d1ce6dea/bundles/org.openhab.ui/web/src/components/widgets/generic-widget-component.vue#L1-L17

On line 4 above, the components within a slot are wrapped in a `<template>` with the correct slot name, which gets them the correct slot names in `list-item`. However, the components themselves do not have the necessary slot name associated with them on line 6 or 8 for them to be assigned properly in `list-item-content`. I tried adding `:slot="slotName"` to the `generic-widget-component` for the subcomponents on line 8:
```
-      <generic-widget-component v-else :context="childContext(slotComponent)" v-for="(slotComponent, idx) in slotComponents" :key="slotName + '-' + idx" @command="onCommand" />
+      <generic-widget-component v-else :context="childContext(slotComponent)" v-for="(slotComponent, idx) in slotComponents" :slot="slotName" :key="slotName + '-' + idx" @command="onCommand" />
```

With that change, when I now render the above widget YAML in the editor, I get this as the HTML:
```
<li class="media-item">
  <div class="item-content">
    <div class="item-inner">
      <div class="item-header">
        <a href="#" class="button"><span>header slot button</span></a>
      </div>
      <div class="item-title-row">
        <div class="item-title">title in config</div>
        <div class="item-after">
          <a href="#" class="button"><span>after slot button</span></a>
        </div>
      </div>
      <div class="item-footer">
        footer in config
        <a href="#" class="button"><span>footer slot button</span></a>
      </div>
    </div>
    <a href="#" class="button"><span>content slot button</span></a>
  </div>
</li>
```

Now all of the buttons are being wrapped in the appropriate divs. The button in the `default` slot is actually missing because `list-item-content` does not directly render the `default` slot. It didn't seem like the change was needed on line 6, but maybe it should be made there too for consistency. The addition of `:slot="slotName"` on line 8 did not seem to cause any obvious problems with my other widgets, and the unit tests passed. However, I'm not really familiar with Vue or MainUI, so I'm not sure if this change could end up causing other problems elsewhere.
