### ISSUE TITLE
Unable to set state to 0 via oh-button

### ISSUE THREAD

**Issue by hypetsch** [openhab/openhab-webui#1134]
I am using `oh-button`s in a `f7-segmented` element inside a widget to set the value of a number item to `0`, `1`, ... `5`. Everything is working fine except that setting to `0` does not work. Trying to set to `0` results in a `415 Unsupported Media Type`.

## Expected behavior

Setting to `0` should also work.

## Steps to reproduce

Excerpt of the widget config:

```yaml
- component: f7-segmented
  config:
    raised: false
    round: false
  slots:
    default:
      - component: oh-button
        config:
          actionItem: =(props.item)
          actionCommand: 0
          action: command
          iconMaterial: power_settings_new
          active: =(items[props.item].state == 0)
      - component: oh-button
        config:
          actionItem: =(props.item)
          actionCommand: 1
          action: command
          iconMaterial: looks_one
          active: =(items[props.item].state == 1)
      - component: oh-button
        config:
          actionItem: =(props.item)
          actionCommand: 2
          action: command
          iconMaterial: looks_two
          active: =(items[props.item].state == 2)
      - component: oh-button
        config:
          actionItem: =(props.item)
          actionCommand: 3
          action: command
          iconMaterial: looks_3
          active: =(items[props.item].state == 3)
      - component: oh-button
        config:
          iconMaterial: schedule
          actionItem: =(props.item)
          actionCommand: 4
          action: command
          active: =(items[props.item].state == 4)
      - component: oh-button
        config:
          iconF7: wind
          actionItem: =(props.item)
          actionCommand: 5
          action: command
          active: =(items[props.item].state == 5)
```

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: de-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 45734688
  totalMemory: 201469952
bindings:
  - amazonechocontrol
  - astro
  - bsblan
  - exec
  - fronius
  - gpio
  - hue
  - onewiregpio
  - openweathermap
  - somfytahoma
  - telegram
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - de-AT
      - de-DE
      - de
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/92.0.4515.107 Safari/537.36
timestamp: 2021-07-24T19:52:35.638Z

```

## Browser console

```txt
Sending command to cwl_mode: 1
app.js:38 Sending command to cwl_mode: 0
app.js:7 POST http://192.168.1.2:8080/rest/items/cwl_mode 415 (Unsupported Media Type)
s @ app.js:7
(anonymous) @ app.js:7
s.promise @ app.js:7
postPlain @ app.js:33
sendCommand @ app.js:38
(anonymous) @ app.js:17
u.dispatch @ app.js:23
dispatch @ app.js:17
performAction @ app.js:7
clicked @ app.js:23
qe @ app.js:7
n @ app.js:7
qe @ app.js:7
e.$emit @ app.js:7
(anonymous) @ app.js:7
t.a @ app.js:7
dispatchEvent @ app.js:23
onClick @ app.js:23
:8080/page/tabletMain:1 Uncaught (in promise) Unsupported Media Type
```

## Browser network traffic

Compared to the working case, no content is added to the REST request:

OK:
![image](https://user-images.githubusercontent.com/16302578/126879853-52d3fee3-f001-4d4d-b3e3-141a7cd9ea76.png)

NOK (Content is missing):
![image](https://user-images.githubusercontent.com/16302578/126879866-ab5c551b-ee13-407a-b6b4-50926a92baa9.png)
