### ISSUE TITLE
Add support for Equipment_Lightbulb for light badge

### ISSUE THREAD

**Issue by vguna** [openhab/openhab-webui#1144]
## The problem

I mainly configure my semantic model with having equipment directly in locations. So If I look at the Locations section with all the rooms, I can see e.g. lightbulbs directly under Devices of a location - not Properties. Now I fell in love with the badges displayed on the cards. As it seems there is currently no support for lights coming from `Equipment_Lightbulb`s. I found this PR https://github.com/openhab/openhab-webui/issues/556 which nicely shows the graceful fallback behavior, if no points etc. are configured, but looking at the equipment directly.

## Your suggestion

It would be awesome if there would also be a fallback to `Equipment_Lightbulb`s to show the light badge.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.12
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.50+19-CA
  osName: Linux
  osVersion: 5.10.52-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 116663208
  totalMemory: 309374976
bindings:
  - amazonechocontrol
  - astro
  - bluetooth
  - goecharger
  - http
  - knx
  - mail
  - miio
  - mqtt
  - network
  - openweathermap
  - smartmeter
  - systeminfo
  - telegram
  - tr064
  - weathercompany
  - weatherunderground
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101
    Firefox/90.0
timestamp: 2021-08-15T12:01:57.164Z

```
