### ISSUE TITLE
Allow the "Show non-semantic" to be permanent

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#1159]
## The problem
The checkmark "Show non-semantic" is reset everytime the page model is opened. It would be nice if there waere the option to show non-semantics on a permanent basis. This

## Your suggestion
There are two option to realize the desired behaviour. Firt: store the last state of the check mark and retrieve it on page reload. Second create a new area in the settings like "Main UI" and create a flag that enables the permanent display of non-semantics

## Your environment
```yaml
runtimeInfo:
  version: 3.2.0
  buildString: "Build #2485"
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.12
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.50+19-CA
  osName: Linux
  osVersion: 5.10.0-8-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 245799304
  totalMemory: 407896064
bindings:
  - astro
  - automower
  - homematic
  - http
  - icalendar
  - mqtt
  - netatmo
  - tankerkoenig
  - unifi
  - wled
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.75
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1564
    height: 1043
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38
timestamp: 2021-09-08T18:53:13.606Z

```

## Additional information

No additiona information
