### ISSUE TITLE
[MainUI] Model Editor: Category icon not changed when selecting another location

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-webui#1164]
## The problem

I have defined a location hierarchy with different category icons for each location. 

1. Now I select the root location:

![image](https://user-images.githubusercontent.com/616792/133898033-85f63c52-5d52-45d4-bb97-cc14943e18ac.png)
The "Wohnung" is of category "attic" and the correct icon is display.

2. I now select another location:
![image](https://user-images.githubusercontent.com/616792/133898059-99ad4593-f7d2-4b1b-a053-f513cdc81886.png)

"Arbeitszimmer" has category "office", but the "attic" icon is shown.

According to the network tab of the developer tools there is no request sent to server to load another icon.

3. Now I perform a refresh (F5) and open the location tree (without selecting the root item). If I now select "Arbeitszimmer" the correct icon is displayed:
![image](https://user-images.githubusercontent.com/616792/133898118-3a710ebe-6c6e-48d6-aa37-3fd8eb5ad1c5.png)

Tested with Edge and Firefox.

## Expected behavior

Show the correct category icon.

## Steps to reproduce

see description above

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0.M2
  buildString: Milestone Build
locale: de-DE
systemInfo:
  configFolder: /opt/oh3/conf
  userdataFolder: /opt/oh3/userdata
  logFolder: /opt/oh3/userdata/logs
  javaVersion: 11.0.12
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.50+19-CA
  osName: Linux
  osVersion: 5.10.52-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 89713560
  totalMemory: 215199744
bindings:
  - astro
  - deconz
  - dwdpollenflug
  - dwdunwetter
  - hpprinter
  - http
  - mqtt
  - ntp
  - shelly
  - systeminfo
  - tankerkoenig
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101
    Firefox/92.0
timestamp: 2021-09-18T18:00:01.085Z

```

## Browser console

no relevant messages

## Browser network traffic

![image](https://user-images.githubusercontent.com/616792/133898210-47e8e5d3-369c-43ab-8bf1-0a479fac2729.png)
The marked line appears in step 1, but there is no GET request for step 2.
