### ISSUE TITLE
Cannot set all possible values of certain configuration parameters

### ISSUE THREAD

**Issue by AdrianLucasCD** [openhab/openhab-webui#1166]
## The problem

(I'm not sure if this is a general UI problem or one specific to a binding and Thing so apologies if it's in the wrong place)

<img width="616" alt="Screenshot 2021-09-24 at 11 25 21" src="https://user-images.githubusercontent.com/91279390/134660650-af32c7a1-ac0f-40ed-8a3a-954f73e000c5.png">

 In the Thing’s Configuration Parameters section, the description says “This is a BIT flag allowing all options to be set” but the 4 options are represented by radio buttons of which only one can be selected at a time. 

## Expected behavior

The options should be check boxes so more than one can be selected.
## Steps to reproduce

1.  Include a Fibaro Smart Implant (FGBS-222) with the Z-Wave binding 
2. Try to set parameters 40 or 41 with more than one selection.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.12
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.50+19-CA
  osName: Linux
  osVersion: 5.10.60-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 72733352
  totalMemory: 194772992
bindings:
  - hue
  - network
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: en-gb
    languages:
      - en-gb
    onLine: true
    platform: MacIntel
  screen:
    width: 2240
    height: 1260
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
timestamp: 2021-09-24T10:42:13.394Z


```

## Browser console

```txt

```

## Additional information

There is a workaround by setting the parameters in the "Code" tab
