### ISSUE TITLE
Allow configuration of marketplace addons

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-webui#1168]
## The problem

Bindings that are installed via the community marketplace and need configuration on binding level cannot be configured, even if the config-description-uri is properly reported by the REST API (`http://localhost:8080/rest/bindings`):

```json
[
  {
    "description": "This is the binding for SNMP Test.",
    "id": "snmp",
    "name": "SNMP Binding",
    "configDescriptionURI": "binding:snmp"
  }
]
```

This has two reasons: 

- It is currently not possible to link from the community-marketplace-addon-id (which is `marketplace:123456`) to the binding-id `binding:snmp`. 
-  It looks like the check if a configuration is available is not implemented for community marketplace addons.

## Your suggestion

A possible solution would be to extend the community marketplace so that the config-description-uri can be set on Discourse (preferred, nor sure what the best way to do is). Another solution would be to move the binding configuration from the addon marketplace to a new section on the `Settings` page where all entries that are reported via `rest/bindings` can be configured.

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: "Build #2505"
locale: de-DE
systemInfo:
  configFolder: /Users/jan/openhab/conf
  userdataFolder: /Users/jan/openhab/userdata
  logFolder: /Users/jan/openhab/userdata/logs
  javaVersion: 11.0.12
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.50+19-CA
  osName: Mac OS X
  osVersion: "11.6"
  osArchitecture: aarch64
  availableProcessors: 8
  freeMemory: 166521248
  totalMemory: 465567744
bindings:
  - snmp
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: de-de
    languages:
      - de-de
    onLine: true
    platform: MacIntel
  screen:
    width: 1440
    height: 900
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
timestamp: 2021-09-26T08:57:40.629Z

```
