### ISSUE TITLE
Amazon Echo Control Binding: Metadata Class "Blind" (which allows discovery of a Group) cannot be added to Item Type "Group"

### ISSUE THREAD

**Issue by Boldfor** [openhab/openhab-webui#1181]
## The problem
When creating a Group-item (in order to group a number of blinds into it) it is not possible in Web UI to add the Amazon Alexa Metadata Class "Blind" to it (which allows discovering the group via Alexa), but only the Alexa Class "Endpoint.InteriorBlind" or "Endpoint.ExteriorBlind" (which do not result in Alexa discovering the group).

To be able to select the Alexa Class "Blind" the creation flow of Web UI has to be "tricked": First, create an item (e.g. type "Switch", then add the Amazon Alexa Metadata Class "Blind" (which is not available for a Group but e.g. for a Switch), and then change the Type of the item back from "Switch" to Group (while keeping the Amazon Alexa Metadata Class "Blind").

## Expected behavior
When creating a Group-item, it should be able to add the Amazon Alexa Metadata Class "Blind" without the need to "trick" the creation flow / switching back from item "Group" back to "Switch" and back to "Group".  

## Steps to reproduce
1. Create a Group-item
![image](https://user-images.githubusercontent.com/37384006/137788076-16263fdc-f709-47cd-9e3c-feb70ccef17d.png)
2.  The Class "Blind" that allows the Group to be discovered in Alexa is not available (but only "Endpoint.InteriorBlind" or "Endpoint.ExteriorBlind" which do not allow Alexa to discover the group)
![image](https://user-images.githubusercontent.com/37384006/137788208-b12d94bd-9e5e-4f9f-a208-7766f56f105d.png)
3. Change the item back to Type "Switch" and add the Amazon Alexa Metadata Class "Blind" 
![image](https://user-images.githubusercontent.com/37384006/137788411-c9dbb9bd-d486-4e71-9849-63800b55192a.png)
4. Change the item back to Type "Group" (while keeping the Amazon Alexa Metadata Class "Blind")
5. Discover the item "Group" via Alexa
6. Done.

## Your environment
```
runtimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.52-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 67363968
  totalMemory: 219230208
bindings:
  - amazonechocontrol
  - gardena
  - homematic
  - mqtt
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1366
    height: 768
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
timestamp: 2021-10-18T18:26:11.621Z
```

## Browser console
n/a

## Browser network traffic
n/a

## Additional information
n/a
