### ISSUE TITLE
Inconsistent behavior of popup action for some widgets

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-webui#1184]
## The problem

I found that using popup action with actionModalConfig is unstable and does not work in certain conditions. If widget or page require extra parameters these are not passed over. Effectively supported popups are only static.
Looking closer at the generated HTML code I found:
```
<a href="#" class="button" action="popup" actionmodal="widget:cell_consumption_summary" actionmodalconfig="[object Object]" style="position: absolute; top: 163px; left: 25px; text-align: right; font-size: 14px; font-weight: 300;"><span class="">Wärmepumpe</span></a>
<img url="/icon/Heizungsanlage.svg" action="popup" actionmodal="page:group-popup" actionmodalconfig="[object Object]" class="oh-image" style="position: absolute; top: 127px; left: 33px; filter: invert(1);" src="/icon/Heizungsanlage.svg">
```
Components are quite basic:
```yaml
                - component: oh-button
                  config:
                    text: Wärmepumpe
                    style:
                      position: absolute
                      top: 163px
                      left: 25px
                      text-align: right
                      font-size: 14px
                      font-weight: 300
                    action: popup
                    actionModal: widget:heat_summary
                    actionModalConfig:
                      title: Heatpump
                      item: TInstallations_HeatPump
                      iconUrl: /icon/Heizungsanlage.svg
                      groupDetails: TInstallations_HeatPump
```

Behavior and melding actionmodelconfig happens for link/buttom/image components.

## Expected behavior

I expected that popups will work.

## Steps to reproduce

1. Create widget A and B, where A refer B
2. Make sure B uses some parameters
3. Create an action on widget A which does call B with required parameters

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0.M3
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: ~/openhab-3.2.0.M3/conf
  userdataFolder: ~/openhab-3.2.0.M3/userdata
  logFolder: ~/openhab-3.2.0.M3/userdata/logs
  javaVersion: 11.0.11
  javaVendor: AdoptOpenJDK
  javaVendorVersion: AdoptOpenJDK-11.0.11+9
  osName: Linux
  osVersion: 5.14.12
  osArchitecture: amd64
  availableProcessors: 2
bindings:
  - zigbee
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.3953488372093024
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 2
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1376
    height: 774
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0
timestamp: 2021-10-20T22:35:40.876Z
```
