### ISSUE TITLE
OH3 3.1 stable - Stepper widget sends commands spontaneously

### ISSUE THREAD

**Issue by xsherlockpl** [openhab/openhab-webui#1186]
## The problem
A wigget is sending  spnatagnus commands to the items, rounding them up to the stepper step

![image](https://user-images.githubusercontent.com/23699880/138481735-d241fb99-469a-4cd9-ac21-82dba7593c42.png)

## Expected behavior

Should not happen.

## Steps to reproduce

Create item modified by some external controler.
On loading the UI layout page. observe the log it will show a number of the commands issued to the items in the steppers on the page 

code for the stepper
```yaml
component: oh-stepper-item
config:
  item: Archive_01_Postriscaldo_valve
  min: 0
  max: 100
  scale: true
  unit: "%"
  releaseOnly: true
  commandInterval: 1000
  step: 5
  title: Archive 01
```

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: en-IT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.4.0-88-generic
  osArchitecture: i386
  availableProcessors: 2
  freeMemory: 26034576
  totalMemory: 166723584
bindings:
  - astro
  - co7io-bacnet
  - mqtt
  - telegram
  - weatherunderground
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 24
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 4096
    height: 1728
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/94.0.4606.81 Safari/537.36
timestamp: 2021-10-22T15:30:23.423Z

```

## Browser console

No erros in console but wisible commands send

```Update iconUseState to true
16.app.js:1 {"item":"Archive_01_Postriscaldo_valve","min":0,"max":100,"scale":true,"unit":"%","releaseOnly":true,"commandInterval":1000,"step":5,"title":"Archive 01","iconUseState":true}
app.js:38 Sending command to postriscaldo_valve_reset_switch: ON
app.js:38 Sending command to Archive_03_Postriscaldo_valve: 50
app.js:38 Sending command to Archive_07_Postriscaldo_valve: 30
app.js:38 Sending command to Archive_04_Postriscaldo_valve: 35
app.js:38 Sending command to Archive_02_Postriscaldo_valve: 35
app.js:38 Sending command to postriscaldo_valve_reset_switch: ON
app.js:38 Sending command to Archive_07_Postriscaldo_valve: 35
app.js:38 Sending command to Archive_06_Postriscaldo_valve: 50
app.js:38 Sending command to Archive_06_Postriscaldo_valve: 45
app.js:38 Sending command to Archive_05_Postriscaldo_valve: 65
app.js:38 Sending command to Archive_04_Postriscaldo_valve: 30
app.js:38 Sending command to Archive_06_Postriscaldo_valve: 50
 
```
