### ISSUE TITLE
[OH3] 3.1.0 Item Name can not start with "0" when importing from textual

### ISSUE THREAD

**Issue by ohkaja** [openhab/openhab-webui#1188]
When i try to import "old" items from the textfiles and they begin with "0" e.g. 00_main_house_floor the parser says:

"Error: Syntax error at line 1 col 65:

  Number haus_meterwater    "Zähler Wasser [%s m³]"    <water>   (0
                                                                  ^
Unexpected number token: "0". Instead, I was expecting to see one of the following:"

To make screenshots:
see attached

The item should be importes as every other item.

## Steps to reproduce

Create a item and name it (Item name!) starting with "0" or put it in a group starting with "0".

```yaml

runtimeInfo:
  version: 3.2.0.M3
  buildString: Milestone Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.11.0-38-generic
  osArchitecture: i386
  availableProcessors: 1
  freeMemory: 85920904
  totalMemory: 189792256
bindings:
  - astro
  - avmfritz
  - hue
  - openweathermap
  - samsungtv
  - tr064
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 2294
    height: 960
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.30
timestamp: 2021-10-26T18:02:15.128Z

```

## Browser console

```txt
none
```

## Additional information
<img width="817" alt="Screenshot 2021-10-26 200524" src="https://user-images.githubusercontent.com/93218188/138936452-687d08ef-a9e8-4034-ba10-da272e5a40c6.png">
