### ISSUE TITLE
Change the title and description for automation add-ons from the marketplace

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1189]
## The problem

The add-ons that can be installed from the marketplace under the Automation category can be either rule templates or automation add-ons (e.g. support for a new rules language). However the header and description only mention rule templates.

![image](https://user-images.githubusercontent.com/6385096/139452012-d3d005cb-eedb-4e36-ad47-296fa9c97824.png)

This is somewhat confusing to users since, as of this posting, there are actually two separate automation add-ons to support Java rules development in the list which are not rule tempaltes.

![image](https://user-images.githubusercontent.com/6385096/139452196-055e0afa-b754-4ca5-b8f3-0ccbfb5cdc92.png)

## Expected behavior

It would be awesome if there could be two separate sections, one for rule templates and another for automation add-ons. But that is probably a pretty big change. I'd be satisfied with just changing the heading and description to something like 

> ### Automation Add-Ons and Rule Templates
> 
> Automation add-ons to support new languages to write rules and rule templates to help bootstrap your automation shared by the community.

## Steps to reproduce

1. Navigate to Settings -> Automation in MainUI

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0.M3
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.12
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.50+19-CA
  osName: Linux
  osVersion: 5.4.0-89-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 85185608
  totalMemory: 460324864
bindings:
  - astro
  - bluetooth
  - chromecast
  - ipcamera
  - mail
  - mqtt
  - network
  - networkupstools
  - openweathermap
  - roku
  - shelly
  - zigbee
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 10
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
timestamp: 2021-10-29T14:30:00.165Z

```

## Browser console

```txt
NA
```

## Browser network traffic

NA

## Additional information

NA
