### ISSUE TITLE
Vanishing Repeater Fragments

### ISSUE THREAD

**Issue by JustinGeorgi** [openhab/openhab-webui#1199]
## The problem
This is a minor but weird one:

When the visibility of children of an oh-repeater is changed, the last item in the array vanishes completely.  This only occurs if the repeater `fragment` property is true.  `listContainer` and standard work as expected.  The following simple widget demonstrates this:

```
uid: err:repeat_visible
tags: []
props:
  parameters: []
  parameterGroups: []
component: f7-card
config:
  title: Error
slots:
  default:
    - component: oh-link
      config:
        iconF7: "=(vars.vis) ? 'eye_fill' : 'eye_slash_fill'"
        action: variable
        actionVariable: vis
        actionVariableValue: =!vars.vis
    - component: f7-row
      config: []
      slots:
        default:
          - component: oh-repeater
            config:
              for: someData
              sourceType: array
              in:
                - data: 5
                  text: five
                - data: 15
                  text: fifteen
                - data: 20
                  text: twenty
              fragment: true
            slots:
              default:
                - component: Label
                  config:
                    visible: =!vars.vis
                    text: =loop.someData.data
                - component: Label
                  config:
                    visible: =!!vars.vis
                    text: =loop.someData.text
```
![repeat_error](https://user-images.githubusercontent.com/77952587/140621261-e5b0b6d2-d8f6-48f9-9907-6d41c8454d79.gif)

## Expected behavior
Components should continue to exist if visibility is turned back on...

## Steps to reproduce
See widget above and use the link to toggle item visibility.

## Your environment
```
runtimeInfo:
  version: 3.2.0.M3
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.12
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.50+19-CA
  osName: Linux
  osVersion: 5.4.0-88-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 462783944
  totalMemory: 866123776
clientInfo:
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
timestamp: 2021-11-06T19:26:05.487Z
```

**Comment by JustinGeorgi** [comment]
Also: Adding a `key` tied to the visibility variable to the repeater's parent :
```
component: f7-card
config:
  title: Error
  key: =Math.random() + vars.vis.toString
```
refreshes and does mask the problem.
