### ISSUE TITLE
Extra 'ghost' option appearing when parameters have only a list of possible values / options

### ISSUE THREAD

**Issue by fpap72** [openhab/openhab-webui#1221]
## The problem

When device parameter values are a list of possible values (i.e. not any value, but only an enumerated list of values or options), there can be a 'ghost' value/option apparing before all the others.
I've seen that, if a device parameter has only few options (max 3 or 4), these values appear inline immediately after the parameter and this works as expected (see image below):

![image](https://user-images.githubusercontent.com/28343122/144827575-3fe5bd1b-4c7c-44fb-b80a-8a0f98b897fd.png)

Instead, when the options are more, a separate window opens with the list of possible options **plus an extra ghost option**:

![image](https://user-images.githubusercontent.com/28343122/144827709-a569bf49-43ae-4b46-bd6b-761cb1edc461.png)

You can see that, before 'Normally closed alarm input', there is a bullet with an empty description, which does not exist in the device.

**This 'ghost' option can be selected, and it is not clear what happens in this case:**

![image](https://user-images.githubusercontent.com/28343122/144830008-fa6cd418-86f1-4380-94d9-9581078dcc7f.png)

Same thing here, before 'Controller':

![image](https://user-images.githubusercontent.com/28343122/144828105-b2f92cdc-83cd-4015-9032-03b9a8407d38.png)

I experienced this problem with ZWave deviceS but I guess it could exist also for other types of devices, this is the reason why I post this bug issue here.

## Expected behavior

No 'ghost' options should appear among the list of possible values of the parameters.

## Steps to reproduce

In order to reproduce this problem, you should have a device with a parameter with a list of options longer than maybe 5 or 6 values. If you have a ZWave device, please look at the Association Groups, here you should find the number of options that trigger this problem.

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0.M5
  buildString: Milestone Build
locale: it-IT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.63-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 109748928
  totalMemory: 258830336
bindings:
  - hpprinter
  - ipcamera
  - mail
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: it-IT
    languages:
      - it-IT
      - it
      - en-US
      - en
      - fr
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/96.0.4664.45 Safari/537.36
timestamp: 2021-12-06T10:16:12.684Z

```

## Browser console

```txt

```
