### ISSUE TITLE
Marketplace addon documentation render issues

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-webui#1251]
## The problem

It seems that marketplace addon documentation rendering is missing some features (compared to openhab.org docs)

At least the following features are not working 
- table of contents 
- list of sub-pages

In markdown 

```

The binding has the following extensions:

<!--list-subs-->

The rest of this page contains details for configuring this binding:

{::options toc_levels="2..4"/}

- TOC
{:toc}
```

Comparison of marketplace vs openhab.org

![image](https://user-images.githubusercontent.com/315866/147223332-69668aa0-6b2e-4633-8e25-d23bc3787cca.jpeg)

![image](https://user-images.githubusercontent.com/315866/147223353-44ccab1c-d352-4863-b977-fa7d1014e301.jpeg)

## Expected behavior

Docs would be rendered the same way as openhab.org docs

## Steps to reproduce

Use modbus binding docs as example.

1. 

## Your environment

```yaml

runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: fi-FI
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: AdoptOpenJDK
  javaVendorVersion: AdoptOpenJDK-11.0.11+9
  osName: Linux
  osVersion: 5.10.63-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 61456376
  totalMemory: 340787200
bindings:
  - fmiweather
  - modbus
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: true
    android: false
    androidChrome: false
    desktop: false
    iphone: true
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: ios
    osVersion: "15.2"
    webView: false
    webview: false
    standalone: false
    pixelRatio: 3
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: en-GB
    languages:
      - en-GB
    onLine: true
    platform: iPhone
  screen:
    width: 375
    height: 812
    colorDepth: 32
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: true
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X)
    AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148
    Safari/604.1
timestamp: 2021-12-23T09:58:48.198Z



```

## Browser console

```txt

```
