### ISSUE TITLE
[MainUI] Focus keeps going to backgroup while adding discovered thing

### ISSUE THREAD

**Issue by stefaanv** [openhab/openhab-webui#1253]
## The problem
When adding a discovered thing, after having clicked on the `Add as Thing` button, a small dialog box titled `Add as Thing` let's the user set a name.  The focus of text box in this dialog box keeps going to the `search` textbox in the background window.

## Expected behavior
The focus should remain in the dialog box

## Your environment
Openhab 3.2 on Raspbian on Raspberry Pi 4

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: nl-BE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.10.63-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 39911192
  totalMemory: 185470976
bindings:
  - astro
  - buienradar
  - deconz
  - hue
  - modbus
  - mqtt
  - rfxcom
  - tado
  - volvooncall
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: nl-NL
    languages:
      - nl-NL
      - nl
      - en-US
      - en
      - fr
    onLine: true
    platform: Win32
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/96.0.4664.110 Safari/537.36
timestamp: 2021-12-24T10:22:11.206Z

```

## Browser console

```txt
...empty...
```
