### ISSUE TITLE
HABPanel not working when implicit user role is disabled

### ISSUE THREAD

**Issue by lorenzo93** [openhab/openhab-webui#1255]
## Which UI are you reporting an issue for?

- [ ] Basic UI
- [x] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

I've disable inside OH3 the "Implicit User Role".
If I open the HABPanel interface, I get in the bottom "Connection lost! Trying to reconnect..." even if I'm actually logged in to OH3 (tried with admin credentials and with user credentials, same behaviour).
If I use Developer tools to see the XHR Requests, the request to `/rest/items` returns with a `401 Unauthorized response` code.

## Expected behavior

I should be able to use HABPanel if properly logged

## Steps to reproduce

1. In your OH3 interface, go to `Settings > API Security > Implicit User Role` and disable it
2. Open the HABPanel interface

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: en-IT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.10.63-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 53370096
  totalMemory: 194772992
bindings:
  - astro
  - mqtt
  - network
  - onewiregpio
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
      - it-IT
      - it
      - es
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/96.0.4664.110 Safari/537.36
timestamp: 2021-12-27T23:46:33.150Z

```

## Browser console

```txt

```

## Browser network traffic

Each failed request is just like this. If you need more details, please ask :)

Request Headers (modified the X-OPENHAB-SESSIONID for privacy):
```txt
GET /rest/items HTTP/1.1
Host: openhabian:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Referer: http://openhabian:8080/habpanel/index.html
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7,es;q=0.6
Cookie: X-OPENHAB-SESSIONID=cc33ffae-b20c-4054-8efd-xxxxxxxxxxxxx
```

Response Headers:
```txt
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Date: Mon, 27 Dec 2021 23:43:51 GMT
Transfer-Encoding: chunked
Server: Jetty(9.4.43.v20210629)
```
