### ISSUE TITLE
Provide slot after "header" in oh-cell template

### ISSUE THREAD

**Issue by Profoktor** [openhab/openhab-webui#1259]
## The problem

When extending the base widget `oh-cell`, the only way to put own content on the primary card (That which you see when opening the hosting page) is by overwriting the `header`-slot completely or by falling back to the `background`-slot.

In result, it is hard (and cumbersome) to match the exact layout of the original `oh-cell` (considering title, icon)
Example: The following snippet gets close, however an icon is yet unaccounted for
```
uid: extend_slot_header
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Jan 3, 2022, 4:31:03 PM
component: oh-cell
config:
  title: Title of oh-cell
  expandable: false
slots:
  header:
    - component: f7-list
      config:
        mediaList: true
      slots:
        default:
          - component: f7-list-item
            config:
              title: Title of f7 list item
```

## Your suggestion

Provide a separate slot right after the header, which can be used to add custom content without altering the overall design/layout of the cell's title (icon/title and so on)

## Your environment

OH 3.2
