### ISSUE TITLE
Requested Content not found after clicking back after item edit

### ISSUE THREAD

**Issue by limdul79** [openhab/openhab-webui#1263]
## The problem
I get consistenly and reproducable a not found error

## Expected behavior

I expect that I do not get a not found error

## Steps to reproduce

* Created a MQTT Thing with multiple Channels
* Link a Channel to new item
* Click on from the channels view on that item and add a State Description Meta Data
* Save the Meta Data
* Click the back link:

Sorry

Requested content not found.

Debug information

Url: /settings/things/mqtt:topic:broker:fensterMarcel/links/lqiFensterMarcel/linkquality
Path: /settings/things/mqtt:topic:broker:fensterMarcel/links/lqiFensterMarcel/linkquality
Hash:
Params:
Query:
Route: (.*)

Once I click back again, I'm correctly at the thing view

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.13.19-2-pve
  osArchitecture: amd64
  availableProcessors: 1
  freeMemory: 397753376
  totalMemory: 612368384
bindings:
  - amazonechocontrol
  - dwdunwetter
  - exec
  - http
  - mqtt
  - tankerkoenig
  - telegram
  - tr064
  - unifi
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - en
      - de-DE
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 2048
    height: 1152
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/96.0.4664.110 Safari/537.36
timestamp: 2022-01-05T19:06:40.227Z

```

## Browser console

```txt

```
