### ISSUE TITLE
Sending the defined `defaultValue` in `oh-input` widget does nothing without "touching" the value

### ISSUE THREAD

**Issue by boehan** [openhab/openhab-webui#1275]
## The problem

If a `defaultValue` is defined for a `oh-input` widget, the value can not directly be sent by clicking the send button (does nothing). The value has to be edited once before the the value is actually sent (can even be set back to defaultValue before sending).

## Expected behavior

Should be possible to directly send the `defaultValue` to the item. Otherwise setting a default doesn't have much purpose.

## Steps to reproduce

1. Create an `oh-input` widget
2. set an item (which should have a `NULL` state) and a `defaultValue` for the widget
3. enable "Send button"
4. Use the widget and directly click the send button to send the default value to the item

Sample widget code:
```yaml
component: oh-input-card
config:
  defaultValue: TestDefault
  item: TestItem
  title: DefaultValue Tester
  outline: true
  sendButton: true
  type: TEXT
```

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: de-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.10.63-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 100402896
  totalMemory: 324403200
bindings:
  - astro
  - bluetooth
  - bosesoundtouch
  - comfoair
  - denonmarantz
  - exec
  - gpio
  - http
  - icalendar
  - kodi
  - mqtt
  - network
  - openweathermap
  - spotify
  - systeminfo
  - unifi
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
timestamp: 2022-01-12T21:39:29.408Z
```

## Browser console

```txt

```
