### ISSUE TITLE
Habot manipulates inappropriate items (tagged as read only or semantically tagged as measurement)

### ISSUE THREAD

**Issue by einalex** [openhab/openhab-webui#1288]
## Which UI are you reporting an issue for?

- [ ] Basic UI
- [ ] HABPanel
- [X] HABot
- [ ] CometVisu

## The problem

Habot sets items tagged as 'measurement' and also items with state metadata set to 'read only'.
when I try to set my radiator temperature, it sets not only the setpoint target temperature but also the measured local temperature and the battery level to the target value.

## Expected behavior
Habot should only try and touch points classified as control points and apply a heuristic to choose which:
switch on, enable -> switch control if present
raise, lower, ... -> slider control
never -> measurements, and items tagged as read only

## Steps to reproduce
create an item with a set of points, measurements, controls, statuses, mark some as read only.
the tell habot to set the item to a number.
in my case the line was "Stelle die Heizung im Büro auf 24"

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.4.0-96-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 1356085208
  totalMemory: 2700083200
bindings:
  - astro
  - bosesoundtouch
  - chromecast
  - dwdunwetter
  - icalendar
  - lgwebos
  - miio
  - mqtt
  - network
  - openweathermap
  - pioneeravr
  - remoteopenhab
  - spotify
  - upnpcontrol
  - zigbee
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.1145833730697632
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - de
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2296
    height: 1291
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/97.0.4692.71 Safari/537.36
timestamp: 2022-01-26T11:37:15.336Z

```

## Browser console

```txt

```
