### ISSUE TITLE
Code view shows white screen in Firefox

### ISSUE THREAD

**Issue by JoveToo** [openhab/openhab-webui#1289]
## The problem

Everywhere in the UI where there is a code view, I get a white screen. It does not seem to matter what the content is or where it appears. If I open the same link in Chrome, I get the actual code view (YAML, JS, ...).  I cannot interact with the white screen.

Firefox 96.0 running on Fedora 35. All browser extensions disabled on the site.

## Expected behavior

I expect to see a Code view.

## Steps to reproduce

Browse to Thing, select a thing, click the "Code" tab.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.1
  buildString: Release Build
locale: en-BE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.14
  javaVendor: Red Hat, Inc.
  javaVendorVersion: "18.9"
  osName: Linux
  osVersion: 4.18.0-348.2.1.el8_5.x86_64
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 91574376
  totalMemory: 254803968
bindings:
  - amazonechocontrol
  - astro
  - avmfritz
  - buienradar
  - knx
  - modbus
  - mqtt
  - ntp
  - samsungtv
  - snmp
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.8181818181818181
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2112
    height: 1188
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
timestamp: 2022-01-27T18:43:00.668Z
```

## Browser console

```txt
new SSE connection: https://xxxx:8443/rest/events?topics=openhab/thin…hab/things/*/updated,openhab/things/*/status,openhab/inbox/*, 1 open app.js:32:454101
Array [ EventSource ]
app.js:32:454184
SSE connection closed: https://xxxx:8443/rest/events?topics=openhab/thin…hab/things/*/updated,openhab/things/*/status,openhab/inbox/*, 0 open app.js:32:454388
Array []
app.js:32:454474
Start tracking states app.js:37:2597
new SSE connection: https://xxxx:8443/rest/events/states, 1 open app.js:32:454101
Array [ EventSource ]
app.js:32:454184
Setting initial tracking list: [] app.js:37:3057
new SSE connection: https://xxxx:8443/rest/events?topics=openhab/things/*/*,openhab/links/*/*, 2 open app.js:32:454101
Array [ EventSource, EventSource ]
app.js:32:454184
Empty string passed to getElementById(). app.js:1:3784
Adding knx:device:e130d123:FF_BedroomFront_TemperatureAQS to code because it is extensible app.js:32:280134
Adding knx:device:e130d123:FF_BedroomFront_Humidity to code because it is extensible app.js:32:280134
Adding knx:device:e130d123:FF_BedroomFront_CO2 to code because it is extensible app.js:32:280134
Empty string passed to getElementById(). 34.app.js:77:4559
```

## Browser network traffic

![Screenshot from 2022-01-27 19-47-18](https://user-images.githubusercontent.com/18113628/151424274-fe8928a0-a43e-425e-b3d7-00b123995a26.png)
