### ISSUE TITLE
Widget: Item from props cannot be resolved for oh-aggregate-series

### ISSUE THREAD

**Issue by eric1905** [openhab/openhab-webui#1295]
I want to create a bar chart which can be used in multiple pages. 
Therefore I use the oh-aggregate-series.
The item can be defined in the props section, but this item is not evaluated in the widget code, so currently it is only possible to create one widget per item and it is not possible to create only one widget and set the item via the props section:

`
props:
  parameters:
    - context: item
      description: Main toggle item (use for single toggle or as main switch for group)
      label: Item
      name: item
      required: false
      type: TEXT

...

                    series:
                      - component: oh-aggregate-series
                        config:
                          name: Stromverbrauch
                          gridIndex: 0
                          xAxisIndex: 0
                          yAxisIndex: 0
                          type: bar
                          item: =props.item
                          dimension1: hour
`

It is described in this thread: https://community.openhab.org/t/custom-widget-item-defined-in-property-not-shown/132707/7?u=eric1905

**Comment by marianorenzi** [comment]
Same for charting switches:

```
    - component: oh-time-series
      config:
        name: Light
        gridIndex: 0
        xAxisIndex: 0
        yAxisIndex: 0
        type: line
        areaStyle: {}
      slots:
        markArea:
          - component: oh-mark-area
            config:
              name: Light
              item: =props.light_item
```
