### ISSUE TITLE
Single tap on floor plan on iOS does not work

### ISSUE THREAD

**Issue by georg138** [openhab/openhab-webui#1296]
When I try to single tap on a marker on a floor plan, it actually issues a double tap. I'm trying to use a floor plan to toggle a light. This works fine on chrome on desktop but not on my mobile running iOS (at least chrome and Safari). I can see the icon is toggled for a very short time and then toggled again. As a result, the light usually stays off (or on).  Rarely it works. The following example demonstrates this issue:
```yaml
config:
  label: Sandbox
  sidebar: true
markers:
  - component: oh-plan-marker
    config:
      name: New Marker
      action: command
      actionItem: test
      actionCommand: '=(items.test.state > 0) ? "0" : "100"'
      actionCommandAlt: "100"
      icon: "=(items.test.state > 0) ? 'f7:circle_fill' : 'f7:circle'"
    slots:
      default: []

```
I found the following issue with leaflet which I think causes this:
https://github.com/Leaflet/Leaflet/issues/7255#issuecomment-849638476
Disabling tap as proposed there fixes the issue for me.
