### ISSUE TITLE
[blockly] Enhance 'round' block to allow setting decimal places

### ISSUE THREAD

**Issue by digitlength** [openhab/openhab-webui#1303]
## The problem
At the moment the 'round' maths block rounds to the nearest integer.

## Your suggestion
Enhance this block to allow setting a user definable number of decimal places. And at least two so that currency values make sense!

## Your environment

```yaml
runtimeInfo:
  version: 3.3.0.M1
  buildString: Milestone Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.14
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.54+23-CA
  osName: Linux
  osVersion: 5.13.19-2-pve
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 170920880
  totalMemory: 314572800
bindings:
  - astro
  - http
  - mqtt
```
