### ISSUE TITLE
Page to select bridge does not honor multi-line descriptions

### ISSUE THREAD

**Issue by FSeidinger** [openhab/openhab-webui#1304]
## Adding a bridge with multi line descriptions

As described in the documentation of labels and descriptions of things:
https://www.openhab.org/docs/developer/bindings/thing-xml.html#formatting-labels-and-descriptions
Multi-line descriptions can have multiple lines with a subset of HTML markup.

The first stage of the bridge selection process in the `choose-thing-type.vue` does not honor these kind of descriptions and renders them as plain text including the HTML markup.

![image](https://user-images.githubusercontent.com/4890418/153079453-c39774eb-3181-446b-b3f2-3b3b931f409c.png)

## Expected behavior

The page should honor the multi-line descriptions and render them accordingly like the `thing-add-vue` does.

## Steps to reproduce

1. Open the page `Settings/Things`
2. Hit the `+` button to add a new Thing
3. Select the binding from the selection by clicking on it
4. See the formatting of the description

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: default
systemInfo:
  configFolder: C:\Users\frank\PROGRA~1\Java\OPENHA~1.0\conf
  userdataFolder: C:\Users\frank\PROGRA~1\Java\OPENHA~1.0\userdata
  logFolder: C:\Users\frank\PROGRA~1\Java\OPENHA~1.0\userdata\logs
  javaVersion: 11.0.13
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-11.0.13+8
  osName: Windows 10
  osVersion: "10.0"
  osArchitecture: amd64
  availableProcessors: 16
  freeMemory: 234811608
  totalMemory: 322961408
bindings:
  - knxng
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 16
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
      - it-IT
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/98.0.4758.82 Safari/537.36
timestamp: 2022-02-08T21:38:23.467Z
```

## Browser console

```txt
Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/rest/ui/tiles:1          Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/:1 Uncaught (in promise) Not Found
app.js:7 TypeError: Cannot read properties of undefined (reading 'val')
    at s.value (app.js:7:419575)
    at i.<anonymous> (16.app.js:1:227174)
    at Array.<anonymous> (app.js:7:12361)
    at Ze (app.js:7:11804)
Ge @ app.js:7
```

## Browser network traffic

No errors here.

## Additional information

I guess a fix is easy, because the handling is already done in `thing-add-vue`.
