### ISSUE TITLE
[blockly] Add historicState option to Persistence blocks

### ISSUE THREAD

**Issue by digitlength** [openhab/openhab-webui#1309]
## The problem
At the moment it is not possible to retrieve a single value from persistence without jumping through a hoop or two (see workarounds below).

In code this would use the `historicState` function.

## Your suggestion
Add a feature which enables retrieval of a single value from persistence (re)using a single block.

### OH3.2+
For numerical values only, use the `delta` function to get the difference between now and the specific point in the past. Then take this value away from the current state of the item.

![image](https://user-images.githubusercontent.com/62958838/153746554-9e6e24df-37ff-4a8a-8898-451567a00196.png)

which generates the following relevant code

```javascript
var current_state, historic_state;
var zdt = Java.type("java.time.ZonedDateTime");
var persistence = Java.type('org.openhab.core.persistence.extensions.PersistenceExtensions');

current_state = itemRegistry.getItem('MyItem').getState();
historic_state = current_state - (persistence.deltaSince(itemRegistry.getItem('MyItem'), zdt.now().minusHours(13)));
```

### OH3.3M1+
The above workaround still works, or use the inline script block to use the `historicState` function directly, which enables getting the state of any type of Item, not just numerical.

![image](https://user-images.githubusercontent.com/62958838/153746646-cddbd01a-a963-4f5a-bf6a-edca557890d1.png)

which contains the following code

```javascript
var zdt = Java.type("java.time.ZonedDateTime");

var persistence = Java.type('org.openhab.core.persistence.extensions.PersistenceExtensions');

historic_state = persistence.historicState(itemRegistry.getItem('MyItem'), zdt.now().minusHours(13)).getState();
```

## Your environment

```yaml
runtimeInfo:
  version: 3.3.0.M1
  buildString: Milestone Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.14
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.54+23-CA
  osName: Linux
  osVersion: 5.13.19-2-pve
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 108793552
  totalMemory: 314572800
bindings:
  - astro
  - http
  - mqtt

```

**Comment by stefan-hoehn** [comment]
@digitlength 
I think this was fixed with https://github.com/openhab/openhab-webui/pull/1549 
Do you mind checking that and then close this issue?

**Comment by digitlength** [comment]
> @digitlength I think this was fixed with #1549 Do you mind checking that and then close this issue?

As far as I can tell, on 3.4.0 Build Release, this issue is not fixed. If it is, please share a screenshot of the block which mimics the behaviour on the _inline script_ example in the OP.

```yaml
runtimeInfo:
  version: 3.4.0
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.17
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.60+19-CA
  osName: Linux
  osVersion: 5.15.64-1-pve
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 205030344
  totalMemory: 429916160
  startLevel: 100
bindings:
  - http
  - mqtt
  - solarforecast
```
