### ISSUE TITLE
oh-input should allow setting the value of f7 input

### ISSUE THREAD

**Issue by chaosjug** [openhab/openhab-webui#1316]
## oh-input should allow setting the value of f7 input
If value is not set, input types such as datetime-local or time show the current date/time instead of the old value

## Add an option to oh-input to supply the string for value
example for time:
```yaml
- component: oh-input
  config:
    inputmode: text
    item: =props.item
    outline: true
    placeholder: =items[props.item].state
    sendButton: true
    type: time
    value: 09:00
```
The "value" option is the new thing.

This should result in something like this:
```
<input placeholder="2022-02-17T09:00:00.000+0100" inputmode="text" class="" type="time" value="09:00">
```
This leads to 9:00 being shown instead of an empty time picker.

## Your environment

```yaml

```
