### ISSUE TITLE
Including "Basic authentication header" forces UI into login promt even if auth aren't explicit enabled

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhab-webui#1323]
## The problem

When sending a request which includes a [_basic authentication header_](https://en.wikipedia.org/wiki/Basic_access_authentication) the UI will be stuck at a login promt even if openHAB doesn't require authentication. It looks like the browser automatically got redirected to "https://openhab.site.com/rest/" when an "basic auth" header was provided in the request.

This invalidates the usecase of using openHAB behind the reverse proxy "haproxy" configured with basic authentication. This is an issue as the "basic auth header" are kept in the request after being used by haproxy.

<img width="686" alt="Screenshot 2022-02-19 at 23 47 54" src="https://user-images.githubusercontent.com/4204655/154821677-1b1d008b-bd2e-4eaf-8358-51eb87c90a73.png">

## Expected behavior

If openHAB are not configured with basic authentication the login promt are not to be shown.

## Steps to reproduce

1. Add "random" basic auth header when requestning access to openHAB.
2. Access openhab

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: sv-SE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.14
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.10.92-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 102179416
  totalMemory: 201326592
bindings:
  - mqtt
  - onewiregpio
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 2
    language: sv-SE
    languages:
      - sv-SE
      - sv
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 3008
    height: 1692
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101
    Firefox/97.0
timestamp: 2022-02-19T22:50:15.478Z
```
