### ISSUE TITLE
Search not working after you remove an item

### ISSUE THREAD

**Issue by Chasbrot** [openhab/openhab-webui#1334]
## The problem
If you remove a item, the search doesn't work anymore. You have to refresh the page with F5 and it works again.
![image](https://user-images.githubusercontent.com/58513998/156750043-6bab272c-e296-4218-ab45-c8aab9844a95.png)

![image](https://user-images.githubusercontent.com/58513998/156750256-e1566471-b456-43c2-8584-3d14073ccb49.png)

## Expected behavior
It should work.

## Steps to reproduce
1. Create new item.
2. Open item and remove it.
3. Enter something in the search bar.

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: de-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.12
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.10.63-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 29763144
  totalMemory: 147279872
bindings:
  - astro
  - exec
  - http
  - miio
  - mqtt
  - network
  - pirf
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en
      - es
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/99.0.4844.51 Safari/537.36
timestamp: 2022-03-04T10:53:00.904Z

```
