### ISSUE TITLE
Overview fails to load when layout type is changed

### ISSUE THREAD

**Issue by ThaDaVos** [openhab/openhab-webui#1338]
## The problem

When one sets the `layoutType` and `fixedType` of the `overview` page so the canvas can be used:
```YAML
config:
  label: Overview
  layoutType: fixed
  fixedType: canvas
```
The MainUI is unable to load the overview page and displays the following error even though it's correctly configured:
![image](https://user-images.githubusercontent.com/5251028/158030758-2062acfb-b7d6-4e72-9495-e7914c205148.png)

The layout I tried to load (it contains multiple custom widgets):
```yaml
config:
  label: Overview
  layoutType: fixed
  fixedType: canvas
blocks: []
masonry: null
grid: []
canvas:
  - component: oh-canvas-layer
    config: {}
    slots:
      default:
        - component: oh-canvas-item
          config:
            x: 0
            y: 0
            h: 260
            w: 165
          slots:
            default:
              - component: widget:universal_toggle_v3
                config:
                  title: Lamp 1
                  icon: lightbulb
                  color: white
                  maintoggle: Lamp1_Lamp1Switch
        - component: oh-canvas-item
          config:
            x: 200
            y: 0
            h: 260
            w: 165
          slots:
            default:
              - component: widget:universal_toggle_v3
                config:
                  title: Lamp 2
                  icon: lightbulb
                  color: white
                  maintoggle: Lamp2_Lamp2Switch
        - component: oh-canvas-item
          config:
            x: 380
            y: 0
            h: 260
            w: 165
          slots:
            default:
              - component: oh-label-card
                config:
                  item: shop_state
                  action: toggle
                  actionItem: shop_state
                  actionCommand: OPEN
                  actionCommandAlt: CLOSED
        - component: oh-canvas-item
          config:
            x: 560
            y: 0
            h: 260
            w: 165
          slots:
            default:
              - component: widget:universal_toggle_v3
                config:
                  title: Lamp 3
                  icon: lightbulb
                  color: white
                  maintoggle: Lamp3_Lamp3Switch
        - component: oh-canvas-item
          config:
            x: 740
            y: 0
            h: 260
            w: 165
          slots:
            default:
              - component: widget:universal_toggle_v3
                config:
                  title: Lamp 4
                  icon: lightbulb
                  color: white
                  maintoggle: Lamp4_Lamp4Switch
        - component: oh-canvas-item
          config:
            x: 920
            y: 0
            h: 260
            w: 165
          slots:
            default:
              - component: widget:universal_toggle_v3
                config:
                  icon: tv
                  title: Televisie
                  color: white
                  maintoggle: WoonkamerTV_Power
        - component: oh-canvas-item
          config:
            x: 0
            y: 340
            h: 260
            w: 165
          slots:
            default:
              - component: oh-list-card
                config:
                  title: Televisie Applicatie
                  simpleList: false
                  mediaList: true
                slots:
                  default:
                    - component: oh-list-item
                      config:
                        title: Televisie
                        icon: iconify:cil:tv
                        action: command
                        actionItem: WoonkamerTV_Application
                        actionCommand: smartstb
                        listButton: true
                    - component: oh-list-item
                      config:
                        title: Emby
                        icon: iconify:mdi:emby
                        action: command
                        actionItem: WoonkamerTV_Application
                        actionCommand: com.emby.app
                        listButton: true
                    - component: oh-list-item
                      config:
                        title: Netflix
                        icon: iconify:mdi:netflix
                        action: command
                        actionItem: WoonkamerTV_Application
                        actionCommand: netflix
                        listButton: true
                    - component: oh-list-item
                      config:
                        title: Amazon Prime
                        icon: iconify:simple-icons:prime
                        action: command
                        actionItem: WoonkamerTV_Application
                        actionCommand: amazon
                        listButton: true
                    - component: oh-list-item
                      config:
                        title: Disney+
                        icon: iconify:arcticons:disney
                        action: command
                        actionItem: WoonkamerTV_Application
                        actionCommand: com.disney.disneyplus-prod
                        listButton: true
                    - component: oh-list-item
                      config:
                        title: Youtube
                        icon: iconify:fa:youtube
                        action: command
                        actionItem: WoonkamerTV_Application
                        actionCommand: youtube.leanback.v4
                        listButton: true
        - component: oh-canvas-item
          config:
            x: 200
            y: 340
            h: 260
            w: 165
          slots:
            default:
              - component: oh-list-card
                config:
                  simpleList: true
                  title: Downloads
                slots:
                  default:
                    - component: oh-label-item
                      config: null
                      item: Notifications_NewMovie
                      title: Film
                    - component: oh-label-item
                      config:
                        item: Notifications_NewSerie
                        title: Serie

```

## Expected behavior

I expect to see the configured layout, using Canvas

## Steps to reproduce

1. Change the type as shown above, for example by creating a new layout, setting it to Canvas, adding widgets and copying the yaml

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: en-NL
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.14
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.26-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 123639024
  totalMemory: 335544320
bindings:
  - astro
  - chromecast
  - lgwebos
  - mqtt
  - network
  - networkupstools
  - rfxcom
  - shelly
  - sonos
  - unifi
  - unifiprotect
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: simple
    homeBackground: standard
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
timestamp: 2022-03-12T18:45:29.502Z

```

## Browser console

```txt

```
