### ISSUE TITLE
Autocomplete incorrect with ECMAScript 2021+

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-webui#1358]
## The problem

MainUI rule editor is suggesting incorrect autocomplete entries with `application/javascript;version=ECMAScript-2021`:

![image](https://user-images.githubusercontent.com/315866/164973396-4ef02a10-4fbd-40dd-b714-3b0eac31aa29.png)

## Expected behavior

MainUI rule editor would not suggest incorrect autocomplete entries.

For example, with ECMAScript 2021+ (aka `application/javascript;version=ECMAScript-2021`), there should be instead `event.oldItemState`, not `event.previousState`.

## Steps to reproduce

Create rule, select item trigger, and use action with type "ECMAScript 262 Edition 11". 

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: fi-FI
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: AdoptOpenJDK
  javaVendorVersion: AdoptOpenJDK-11.0.11+9
  osName: Linux
  osVersion: 5.10.63-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 125179096
  totalMemory: 959447040
bindings:
  - fmiweather
  - modbus
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
      - en
      - en-US
      - fi
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3072
    height: 1728
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/100.0.4896.88 Safari/537.36
timestamp: 2022-04-24T11:07:19.945Z

```

## Browser console

```txt

```
