### ISSUE TITLE
[oh-swiper slider] Add options "slides-per-view" and "centered-slides"

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-webui#1389]
## The problem

I was searching for a more dense visualisation of several swipable cards than the openHAB "Swiper Card" gives by default

At the moment you can only activate
- Pagination
- Navigation
- Scrollbar
from within the Swiper Card Widget Configuraion Dialog

## Your suggestion

Adding the options
- Centered Slides
- Slides Per View (with the ability to insert "auto")

So basically all i want to have is to be able to configure the Swiper Card, that the outcome is exactly the example "Auto Slides Per View + Centered" from the f7-homepage [here](https://framework7.io/docs/swiper)

![Screenshot_20220510_135008](https://user-images.githubusercontent.com/68030498/167621829-e6b4199a-e74a-42d0-b90c-f7f5425e40c8.png)

## Your environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.13
  javaVendor: Alpine
  osName: Linux
  osVersion: 5.10.93+truenas
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 200903128
  totalMemory: 448790528
bindings:
  - astro
  - chromecast
  - http
  - ipcamera
  - miio
  - mqtt
  - network
  - ntp
  - openweathermap
  - pushbullet
  - telegram
  - wifiled
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.147 Safari/537.36
timestamp: 2022-05-10T11:49:16.034Z

```
