### ISSUE TITLE
Support for expression evaluation at chart axis level

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-webui#1418]
## The problem

Currently axis elements such as labels, colors and visibility are static. This is a diverge from series components which accept expressions at config level. In order to provide a unified handling both axis and series slots should permit expressions. This will allow making some axes conditional for wide charts, if ie. mobile screen is detected.

## Your suggestion
Expression evaluation is part of widget mixin, however most of chart elements have indirect access to evaluation through instance of chart widget. With some small changes in axis handling (probably in other chart related components) visibility of these elements can be a bit less constrained.

## Your environment
Example yaml as an idea

```yaml
  yAxis:
    - component: oh-value-axis
      config:
        min: 0
        gridIndex: 0
        name: Enery
    - component: oh-value-axis
      config:
        gridIndex: 0
        name: Coverage
        min: "0"
        max: "100"
        nameGap: 40
        nameRotate: "90"
        nameLocation: center
        show: =device.desktop # currently it doesn't work
```
