### ISSUE TITLE
Navigating to another page is slow because it queries all current item states before

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-webui#1424]
## The problem
When I navigate away from a page (either by clicking on a page name on the sidebar or via a widget action), OH first queries the state of all items of the current page before it loads the new page.
This makes page navigation super slow when the current page has a lot of widgets.

## Expected behavior
When I navigate away from a page, it should just do so immediately.
Instead, it first queries the state of all items on the current page.

## Steps to reproduce
1. Put some widgets on a grid page
2. Run the page
3. Navigate away from the page
4. OH will query all states of all items on the current page before actually loading the other page

## Your environment
```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /home/mythtv/openHAB/conf
  userdataFolder: /home/mythtv/openHAB/userdata
  logFolder: /home/mythtv/openHAB/userdata/logs
  javaVersion: 11.0.15
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-11.0.15+10
  osName: Linux
  osVersion: 5.10.61-gentoo-x86_64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 113013016
  totalMemory: 487587840
bindings:
  - avmfritz
  - chromecast
  - denonmarantz
  - enigma2
  - exec
  - homeconnect
  - homematic
  - http
  - ipcamera
  - lgwebos
  - mail
  - network
  - networkupstools
  - openweathermap
  - pushover
  - tr064
  - unifi
  - unifiprotect
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.125
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2275
    height: 1280
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/102.0.0.0 Safari/537.36
timestamp: 2022-06-22T05:11:24.858Z
```
