### ISSUE TITLE
Tagging via MainUI using an Android device not possible.

### ISSUE THREAD

**Issue by JueBag** [openhab/openhab-webui#1440]
## The problem

Using an Android device ( in my case Samsung devices) for tagging the keyboard does never show the "Enter" symbol on the usual button, however it displays the German word for continue ("Weiter"), hence the entered string is never set as a tag.
## Expected behavior
The keyboard should display the "Entr" symbol in order to correctly submit the string as a Tag.

## Your environment

```yaml
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.10.63-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 134687544
  totalMemory: 258478080
  startLevel: 100
bindings:
  - amazonechocontrol
  - http
  - hue
  - mqtt
  - network
  - sonos
  - systeminfo
  - tankerkoenig
  - viessmann
clientInfo:
  device:
    ios: false
    android: true
    androidChrome: true
    desktop: false
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: android
    osVersion: 8.1.0
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - en-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Linux armv8l
  screen:
    width: 800
    height: 1280
    colorDepth: 24
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Linux; Android 8.1.0; SM-T580) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
timestamp: 2022-07-01T02:27:25.810Z

```

## Browser console

```txt
Sorry, no DevTools on the Android devices.
```
