### ISSUE TITLE
Number channel cannot be linked to Switch Item (with profile)

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-webui#1478]
## The problem

When linking a Number channel, it is impossible to select Switch item to link to

I use profile to transform the numbers to ON/OFF type.

As a workaround, it is possible to change item type temporarily to Number, do the channel link, and revert item type back to Switch.

## Expected behavior

UI would not filter out items of different type when linking channels. Thanks to profiles, otherwise "incompatible" types should be linkable.

## Steps to reproduce

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: fi-FI
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.15
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.32-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 81427080
  totalMemory: 372244480
  startLevel: 100
bindings:
  - fmiweather
  - modbus
  - network
  - shelly
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: true
    android: false
    androidChrome: false
    desktop: false
    iphone: true
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: ios
    osVersion: 15.6.1
    webView: true
    webview: true
    standalone: true
    pixelRatio: 3
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
    onLine: true
    platform: iPhone
  screen:
    width: 390
    height: 844
    colorDepth: 32
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: true
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X)
    AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
timestamp: 2022-08-24T04:24:27.134Z

```

## Browser console

```txt

```
