### ISSUE TITLE
MainUI when linking item to channel

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-webui#1479]
## The problem

1. Go to model view
2. Select item 
3. From bottom "panel" select links
4. Click "add link"
5. Select thing 

The list of channels is empty, linking cannot be done.

Note: as a workaround one can go to thing view, and link the channel from there.

![image](https://user-images.githubusercontent.com/315866/186328171-7299ff18-14df-4f96-a2d2-deab252843c4.jpeg)
![image](https://user-images.githubusercontent.com/315866/186328190-fc98e673-1859-4147-8560-ea77c8871b85.png)

## Expected behavior

1. Go to model view
2. Select item 
3. From bottom "panel" select links
4. Click "add link"
5. Select thing 
6. Expected: channels should be visible 

## Steps to reproduce

1. 

## Your environment

```yaml

runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: fi-FI
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.15
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.32-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 81427080
  totalMemory: 372244480
  startLevel: 100
bindings:
  - fmiweather
  - modbus
  - network
  - shelly
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: true
    android: false
    androidChrome: false
    desktop: false
    iphone: true
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: ios
    osVersion: 15.6.1
    webView: true
    webview: true
    standalone: true
    pixelRatio: 3
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
    onLine: true
    platform: iPhone
  screen:
    width: 390
    height: 844
    colorDepth: 32
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: true
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X)
    AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
timestamp: 2022-08-24T04:24:27.134Z

```

## Browser console

```txt

```
