### ISSUE TITLE
Model tree view is something collapsed again after going "Back"

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-webui#1480]
## The problem

The model view tree gets collapsed when navigating into item details, and then back. This is annoying when you are visiting several items, and you have to constantly "re-expand" the tree in Model view.

1. Go to Model view
2. Open tree view, select item
3. Go Back using browser back button or MainUI Back button
4. Click "Direct Parent Groups"
5. Click Back
6. Click Back
7. (there is a moment when UI has "loading" icon)

Expected: We should be back in tree view, with similarly expanded tree as in step 2.
Actual: we are back in tree view, but  the tree is collapsed again

Note: this works
1. Go to Model view
2. Open tree view, select item
3. Go Back using browser back button or MainUI Back button
5. (Tree view is not collapsed, and is the same state as in step 2)

## Expected behavior

See above

## Steps to reproduce

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: fi-FI
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.15
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.32-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 97366840
  totalMemory: 372244480
  startLevel: 100
bindings:
  - fmiweather
  - modbus
  - network
  - shelly
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
      - en
      - en-US
      - fi
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3072
    height: 1728
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/104.0.0.0 Safari/537.36
timestamp: 2022-08-24T04:42:29.315Z

```

## Browser console

```txt

```
