### ISSUE TITLE
Model View inline Edit view does not show all editable properties

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-webui#1482]
## The problem

In Model view, when selecting an item, there is an option to "Edit" Item in the side-pane (1)

Confusingly, this is not a full edit view and does not have all the settings. For example, "Group Settings" (Members Base Type and Aggregation Function) are not editable. Neither is Non-Semantic Tags.

(1)
![image](https://user-images.githubusercontent.com/315866/186331484-2f8b17c4-800f-4f10-b66d-f2006e493d28.png)

(2)
![image](https://user-images.githubusercontent.com/315866/186331771-f83c2a64-0fc4-4736-b22c-0baa1b502d38.png)

## Your suggestion

I find it would be more logical either to have full Edit view (2) in the side-pane or simply having Edit button to go the full view. I find this partial implementation confusing and I start to doubt myself where to find the property I want to edit.

## Your environment

```yaml
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: fi-FI
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.15
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.32-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 56449984
  totalMemory: 372244480
  startLevel: 100
bindings:
  - fmiweather
  - modbus
  - network
  - shelly
  - systeminfo
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
      - en
      - en-US
      - fi
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3072
    height: 1728
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/104.0.0.0 Safari/537.36
timestamp: 2022-08-24T04:53:23.580Z


```
