### ISSUE TITLE
Sorting things alphabetically does not do a two level sort

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-webui#1511]
Maybe related to #792

## The problem
Sorting things alphabetically only considers the first character. Things are not sorted alphabetically inside the character view.
e.g.
```
Shelly
Squeezebox
Shelly
```

![grafik](https://user-images.githubusercontent.com/10754716/194688171-6670013a-a106-408a-a42b-74fabdf7c611.png)

## Expected behavior

When grouped by first character things should be fully sorted alphabetically, e.g.
```
Shelly
Shelly
Squeezebox
```

## Steps to reproduce

Have different things with the same first character

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: de-DE
```
