### ISSUE TITLE
Analyzer view does not show anything if stateDescription metadata set for Dimmer Item

### ISSUE THREAD

**Issue by NikolayKash** [openhab/openhab-webui#1523]
I have a Dimmer item where I set   state description metadata like

```
value: " "
config:
  options: 16=1,32=2,48=3,64=4,80=5,100=6
  step: "16"
  min: "16"
  max: "100"
```

Values are stored in DynamoDB

When I try to analyze this item, Analyzer view does not show anything

like:
![image](https://user-images.githubusercontent.com/8295880/194938343-037d2839-6617-4a0b-baa1-48d38d528200.png)

When I remove stateDescription metadata, it shows raw values as expected

![image](https://user-images.githubusercontent.com/8295880/194939375-ab7571d3-2c8e-424d-82ce-23526740c2ff.png)

## Expected behavior

Analyzer should show values as defined  in stateDescription or raw values

## Steps to reproduce

1.  Create dimmer item and add storing values to some persistence provider like DynamoDB
2.  Add stateDescription metadata as mentioned above
3. Press Analyze button 

## Your environment

```yaml
runtimeInfo:
  version: 3.4.0.M2
  buildString: Milestone Build
locale: en-RU
systemInfo:
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA

clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
      - en
      - ru
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/105.0.0.0 Safari/537.36
timestamp: 2022-10-10T19:32:53.111Z

```

## Browser console

As I see  it retrives item info as well data from persistence correctly. 

```json
{"link":"xxxx:xxxxxx:xxxx/rest/items/xxxxxx_FanSpeed","state":"16","stateDescription":{"minimum":16,"maximum":100,"step":16,"readOnly":false,"options":[{"value":"16","label":"1"},{"value":"32","label":"2"},{"value":"48","label":"3"},{"value":"64","label":"4"},{"value":"80","label":"5"},{"value":"100","label":"6"}]},"commandDescription":{"commandOptions":[{"command":"16","label":"1"},{"command":"32","label":"2"},{"command":"48","label":"3"},{"command":"64","label":"4"},{"command":"80","label":"5"},{"command":"100","label":"6"}]},"editable":true,"type":"Dimmer","name":"xxxxxx_FanSpeed","label":"xxxxxx_FanSpeed","category":"DimmableLight","tags":["Point"],"groupNames":["xxxxxxx"]}
```

```json
{"name":"xxxxxxx_FanSpeed","datapoints":"34","data":[{"time":1665389576886,"state":"0"},{"time":1665413806289,"state":"16"},{"time":1665413836135,"state":"48"},{"time":1665413836192,"state":"16"},{"time":1665413836259,"state":"48"},{"time":1665414377802,"state":"16"},{"time":1665414377858,"state":"48"},{"time":1665414377937,"state":"16"},{"time":1665423580526,"state":"48"},{"time":1665423580595,"state":"16"},{"time":1665423580659,"state":"48"},{"time":1665424121897,"state":"16"},{"time":1665424121995,"state":"48"},{"time":1665424122072,"state":"16"},{"time":1665424181910,"state":"48"},{"time":1665424181977,"state":"16"},{"time":1665424182058,"state":"48"},{"time":1665424723618,"state":"16"},{"time":1665424723709,"state":"48"},{"time":1665424723785,"state":"16"},{"time":1665427791730,"state":"48"},{"time":1665427791793,"state":"16"},{"time":1665427791863,"state":"48"},{"time":1665427827556,"state":"16"},{"time":1665427841463,"state":"48"},{"time":1665428332777,"state":"16"},{"time":1665428332822,"state":"48"},{"time":1665428332954,"state":"16"},{"time":1665428392719,"state":"48"},{"time":1665428392787,"state":"16"},{"time":1665428392852,"state":"48"},{"time":1665428935799,"state":"16"},{"time":1665428935872,"state":"48"},{"time":1665428935937,"state":"16"}]}
```
