### ISSUE TITLE
Define stylesheets as YAML objects not strings

### ISSUE THREAD

**Issue by litronics** [openhab/openhab-webui#1551]
## The problem

I would like to use custom stylesheets in my widgets which generally work well. 
However when I try to use dynamic styles based on the state of an item the code becomes very unreadable.

```yaml
-component: object
  config:
    stylesheet: ="#MyID {fill: "+(items[props.item].state == ON)?"true":"false"+"}"
```
Just imaging how unreadable this code is when there are more than one css definition is defined.

## Your suggestion

Defining the YAML like this would enhance readability of the code a lot:

```yaml
-component: object
  config:
    stylesheet:
      #MyID: 
         fill: "=(items[props.item].state == ON)?'true':'false'"
```

Currently this code delivers "[Object]" to the stylesheet and I suppose there is no objectparser which converts that YAML object into strings.

## Your environment

Currently I am running openHAB 3.4.0.M4

**Comment by litronics** [comment]
played around little more - turned out that even the single line definition is not working.
Hence this might be a bug and not an enhancement issue.


```yaml
    - component: span
      config:
        content: "=(items[props.item_Kesselpumpe].state == ON)?'path#pump_Kessel {green !important;}':'path#pump_Kessel {yellow !important;}'"
        style:
          font-weight: bold
    - component: object
      config:
        stylesheet: "=(items[props.item_Kesselpumpe].state == ON)?'path#pump_Kessel {green !important;}':'path#pump_Kessel {yellow !important;}'"
        data: "=(props.SVG_file) ? (props.SVG_file) : '/static/images/Heizung.svg'"
```

Running this definition in my widget prints the correct string in the span but delivers this into the stylesheet:

```
<style id="scoped-8c2192fa5f">
     =(items[props.item_Kesselpumpe].state == ON)?'path#pump_Kessel {green !important;}':'path#pump_Kessel {yellow !important;}'
</style>```

Look like that there is no expressions allowed within the stylesheet component.

It would be great to add this functionality as this would allow the creation of dynamic styles based on item states.
