### ISSUE TITLE
`oh-slider-cell` having different width than `oh-cell`

### ISSUE THREAD

**Issue by puresick** [openhab/openhab-webui#1567]
## The problem

On a new layout page, adding `oh-cell` and `oh-slider-cell` side by side their widths differ without any visible reason.

[Screencast from 2022-12-09 11-33-56.webm](https://user-images.githubusercontent.com/2714266/206683398-8a190ce6-cd88-4f95-9d0b-42b073ce6f93.webm)

## Expected behavior

Both cells should have the same width and gap size.

## Steps to reproduce

1. Create new layout page
2. Click on "Add Block"
3. "Click on "Add Cells"
4. Add "Cell" from standard library
5. Add "Slider Cell" from standard library
6. Repeat 4. and 5. in random order to make the issue visually clearer
7. Look at the cell widths and gaps being different between "Cell" and "Slider Cell"

## Your environment

```yaml
runtimeInfo:
  version: 3.4.0.M2
  buildString: Milestone Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.16.1
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-11.0.16.1+1
  osName: Linux
  osVersion: 6.0.5-arch1-1
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 128746144
  totalMemory: 282066944
  startLevel: 100
bindings:
  - avmfritz
  - http
  - lgwebos
  - network
  - shelly
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 2
    language: en-GB
    languages:
      - en-GB
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2560
    height: 1292
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0
timestamp: 2022-12-09T10:40:00.129Z

```

## Browser console

There is nothing relevant.

```txt

```

## Browser network traffic

There is nothing relevant.
