### ISSUE TITLE
[MainUI] Oversized List Item Widgets break overview cards.

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1599]
## The problem

In the MainUI Overview tabs, any Item that has an "oversized" list item widget causes the "Analyze All" and "Close" buttons at the bottom of an opened card no longer respond to clicks.

For example:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/6385096/208981926-6315c395-8cd0-479c-99f2-78505a7a8127.png">

Not sure if it's related but there appears to be extra space at the bottom of the card too.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/6385096/208982094-7b27668a-255d-40b8-92e4-dc5846dd6d3b.png">

Another example:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/6385096/208982585-cc525c30-d938-427f-b59a-7db2dc163aa6.png">

The widgets below the large one still work as expected. It's just the buttons at the bottom of the card that seem to be broken.

## Expected behavior

We can use larger list item widgets so that we can combine multiple Items into one widget for a more compact interaction.

## Steps to reproduce

Here is the YAML for the thermostat widget shown above.

```

```

## Your environment

```yaml
uid: simple_thermostat_list
tags:
  - list
props:
  parameters:
    - default: Thermostat
      description: Set the title for this thermostat
      label: Title
      name: title
      required: false
      type: TEXT
    - context: item
      description: Item representing the setpoint
      label: Setpoint Item
      name: setpoint
      required: true
      type: TEXT
    - context: item
      description: The current temperature
      label: Current Temperature
      name: currentTemp
      required: true
      type: TEXT
    - context: item
      description: HVAC Mode
      label: Current thermostat mode
      name: mode
      required: true
      type: TEXT
    - default: °F
      description: Set the temperature units
      label: Units
      name: units
      required: false
      type: TEXT
      options:
        - label: °C
          value: °C
        - label: °F
          value: °F
  parameterGroups: []
timestamp: Oct 4, 2022, 3:17:30 PM
component: f7-card
config:
  style:
    boarder-radius: var(--f7-card-expandable-board-radius)
    class:
      - padding: 0px
    height: 100px
    margin-left: 5px
    margin-right: 5px
    noShadow: true
    width: calc(100%)
slots:
  content:
    - component: f7-block
      config:
        style:
          display: flex
          flex-direction: row
          left: 15px
          position: absolute
          top: -5px
      slots:
        default:
          - component: f7-icon
            config:
              color: "=(items[props.mode].state == 'HEAT') ? 'orange' : (items[props.mode].state == 'COOL') ? 'blue' : 'gray'"
              f7: "=(items[props.mode].state == 'HEAT') ? 'thermometer_sun' : (items[props.mode].state == 'COOL') ? 'thermometer_snowflake' : 'thermometer'"
              size: 32
              style:
                margin-right: 10px
          - component: Label
            config:
              style:
                color: "=(items[props.mode].state == 'HEAT') ? 'orange' : (items[props.mode].state == 'COOL') ? 'blue' : 'gray'"
                font-size: 14px
                font-weight: 700
                margin-top: 0px
              text: "=(items[props.mode].state == 'OFF') ? 'Thermostat is off' : 'Thermostat is set to ' + items[props.mode].displayState + ' to ' + items[props.setpoint].state"
    - component: f7-block
      config:
        style:
          position: absolute
          width: 100%
      slots:
        default:
          - component: f7-chip
            config:
              style:
                --f7-chip-bg-color: rgba(255, 255, 255, 0)
                color: "=(items[props.mode].state == 'HEAT') ? 'orange' : (items[props.mode].state == 'COOL') ? 'blue' : 'gray'"
                font-size: 14px
                position: absolute
                right: 18px
                top: 8px
              text: =items[props.currentTemp].state
    - component: oh-slider
      config:
        color: "=(items[props.mode].state == 'HEAT') ? 'orange' : (items[props.mode].state == 'COOL') ? 'blue' : 'gray'"
        item: Thermostat_TargetSetpoint
        label: true
        max: "=(props.units == '°F') ? 80 : 27"
        min: "=(props.units == '°F') ? 50 : 10"
        releaseOnly: true
        step: "=(props.units == '°F') ? 1 : 0.5"
        style:
          position: absolute
          top: 35px
          width: 90%
        unit: =props.units
    - component: oh-button
      config:
        action: options
        actionItem: Thermostat_ThermostatMode
        color: "=(items[props.mode].state == 'HEAT') ? 'orange' : (items[props.mode].state == 'COOL') ? 'blue' : 'gray'"
        fill: true
        style:
          position: absolute
          top: 60px
          width: 90%
        text: Mode
```

## Browser console

```txt
runtimeInfo:
  version: 4.0.0
  buildString: "Build #3245"
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.5
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-17.0.5+8
  osName: Linux
  osVersion: 5.15.0-56-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 280765464
  totalMemory: 823132160
  startLevel: 100
bindings:
  - amazonechocontrol
  - astro
  - chromecast
  - http
  - ipcamera
  - mail
  - mqtt
  - network
  - networkupstools
  - openweathermap
  - roku
  - shelly
  - vesync
  - zigbee
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
timestamp: 2022-12-21T18:59:30.158Z
```

Note: I've seen this behavior for quite some time, at least since OH 3.3, possibly longer.

## Browser network traffic

No errors are logged when opening the card or attempting to click on the buttons.
