### ISSUE TITLE
Slider and Setpoint with Number:Temperature broken after upgrading to OpenHAB 3.4.0

### ISSUE THREAD

**Issue by goligo** [openhab/openhab-webui#1605]
## Which UI are you reporting an issue for?

- [X] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

After updating to OpenHAB 3.4.0 the slider widgets for controlling the target temperature do no longer work. Moving the slider has no effect, the temperature is neither updated on the UI, nor is any event for changing the item state shown in the event log. 

The reason is that request triggered by the slider is receiving a "400 Bad Request" response. When checking the request payload, I saw that the slider is sending "19 %unit%" as the update value. This seems to be causing the error, when I change the pattern on the item explicitely to "%.1f °C", the issue does no longer occur.

## Expected behavior

When moving the slider, the item state should be updated and the target temperature should be changed.

## Steps to reproduce

1. Create an item of type "Number:Temperature" and set the pattern to "%.1f %unit%"
2. Create slider in the basic UI for this item
3. Try to move the slider and check the browser network trace 

## Your environment

```yaml
runtimeInfo:
  version: 3.4.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.63-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 37094744
  totalMemory: 194772992
  startLevel: 100
bindings:
  - avmfritz
  - exec
  - goecharger
  - http
  - icalendar
  - ipp
  - mail
  - mqtt
  - network
  - ntp
  - shelly
  - telegram
  - tr064
  - vitotronic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
timestamp: 2022-12-24T02:13:18.376Z
```

## Browser console

```txt
smarthome.js:1          POST http://openhab:8080/rest/items/HaupthausBadLinks_Zieltemperatur 400 (Bad Request)
l @ smarthome.js:1
I @ smarthome.js:1
(anonymous) @ smarthome.js:1
o.call @ smarthome.js:1
a @ smarthome.js:1
```

## Browser network traffic

![Screenshot 2022-12-24 at 03 15 05](https://user-images.githubusercontent.com/1894593/209417857-5e43b6f1-e45a-47d4-a6aa-a29a96e64096.png)
![Screenshot 2022-12-24 at 03 15 23](https://user-images.githubusercontent.com/1894593/209417861-32de2709-9fef-45ef-934c-f3c6dfa5ed17.png)

## Additional information

Slider was working fine with OpenHAB 3.3.0, issue only occured after upgrading to 3.4.0
