### ISSUE TITLE
Adding Equipment/Points via "Expert Mode" throws error "TypeError: Cannot read properties of undefined"

### ISSUE THREAD

**Issue by bohni** [openhab/openhab-webui#1610]
## The problem
Error message while trying to add equipment or points with "Export mode"

     There was an error generating the items definition: TypeError: Cannot read properties of undefined (reading '$oh')

## Expected behavior
The text area input field should open with textual presentation of the Items

## Steps to reproduce

1. Go to a thing
2. Switch to "Channels" tab
3. Follow Link "Add Equipment to Model" or "Add Points to Model"
    ![image](https://user-images.githubusercontent.com/1252254/209570130-66a40c8a-a242-46f2-a7b1-67971f277270.png)

4. Click Link "Expert Mode"
    ![image](https://user-images.githubusercontent.com/1252254/209570168-ab823047-f77a-4e65-af3d-5724998f3b83.png)

5. The error popup is shown (Mozilla Firefox)
    ![image](https://user-images.githubusercontent.com/1252254/209570222-24167364-b269-46d6-be67-53518c3bf12f.png)

7. Microsoft Edge
    ![image](https://user-images.githubusercontent.com/1252254/209570251-643d3fb2-19c3-42c6-8a48-eec16968c862.png)

## Your environment

Mozilla Firefox 108.0.1, 64-bit

```yaml
runtimeInfo:
  version: 3.4.0
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.16
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.76-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 38466824
  totalMemory: 154140672
  startLevel: 100
bindings:
  - deconz
clientInfo:
  device:
    firefox: true
    windows: true
    os: windows
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101
    Firefox/108.0
timestamp: 2022-12-26T17:14:38.126Z

```

Microsoft Edge Version 108.0.1462.54 (Offizielles Build) (64-Bit)

```yaml
runtimeInfo:
  version: 3.4.0
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.16
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.76-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 38887200
  totalMemory: 154140672
  startLevel: 100
bindings:
  - deconz
clientInfo:
  device:
    windows: true
    language: de
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
timestamp: 2022-12-26T17:08:35.549Z
```

## Browser console

Mozilla Firefox

```txt
TypeError: u is undefined
    f http://openhabian:8080/js/16.app.b85df14c3a7ad94c41f1.js:1
    f http://openhabian:8080/js/16.app.b85df14c3a7ad94c41f1.js:1
    switchToExpertMode http://openhabian:8080/js/16.app.b85df14c3a7ad94c41f1.js:1
    qe http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    n http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    qe http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    $emit http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    a http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    a http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    dispatchEvent http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    onClick http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
16.app.b85df14c3a7ad94c41f1.js:1:6961
    switchToExpertMode http://openhabian:8080/js/16.app.b85df14c3a7ad94c41f1.js:1
    qe http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    n http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    qe http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    $emit http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    a http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    a http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    dispatchEvent http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
    onClick http://openhabian:8080/js/app.b85df14c3a7ad94c41f1.js:7
```

Microdoft Edge

```
16.app.b85df14c3a7ad94c41f1.js:1 
        
       TypeError: Cannot read properties of undefined (reading '$oh')
    at f (16.app.b85df14c3a7ad94c41f1.js:1:4332)
    at f (16.app.b85df14c3a7ad94c41f1.js:1:5009)
    at i.switchToExpertMode (16.app.b85df14c3a7ad94c41f1.js:1:6708)
    at qe (app.b85df14c3a7ad94c41f1.js:7:11319)
    at i.n (app.b85df14c3a7ad94c41f1.js:7:13064)
    at qe (app.b85df14c3a7ad94c41f1.js:7:11319)
    at e.$emit (app.b85df14c3a7ad94c41f1.js:7:34215)
    at app.b85df14c3a7ad94c41f1.js:7:94108
    at Array.forEach (<anonymous>)
    at t.a (app.b85df14c3a7ad94c41f1.js:7:94079)
```

## Browser network traffic

No network traffix, because of Javascript-Link

## Additional information

* Fresh install of OpenHABian (32-bit) via Raspberry Pi Imager.
* Install deconz (add key, add sources.list, apt update & apt install deconz)
* Systemd: Stop deconz-gui, disable deconz-gui, enable deconz, start fdeconz
* Add deconz binding
* Add Thing "Phoscon Gateway"
* Add Thing "Daylight (Philips)"
