### ISSUE TITLE
Adding channel links via Item does not work

### ISSUE THREAD

**Issue by TheNinth7** [openhab/openhab-webui#1618]
## The problem

I am trying to add a Channel Link to an Item via the Item page, but when choosing Add Link and there choosing a Thing, no Channels are displayed. The Item is of type Switch and the Channel as well. I can add the link when I go via the Thing page, that shows in principle the linking works, only not via the Item page.

## Expected behavior

The Channel should be displayed on the Item page and linking should work via the Item page as well.

## Steps to reproduce

Here is how my screens look like when I am trying to add the link via the Item page:

![Screenshot - 31_12_2022 , 07_24_23](https://user-images.githubusercontent.com/118298758/210127461-40f1998b-86ac-47b2-993d-ce556998e8ff.png)

![Screenshot - 31_12_2022 , 07_22_57](https://user-images.githubusercontent.com/118298758/210127468-f5a66cd3-e533-4c26-b4d1-8fbacc476fb6.png)

However, adding the link via the Thing page does work. On the Thing page the Channel is displayed correctly:

![Screenshot - 31_12_2022 , 07_28_25](https://user-images.githubusercontent.com/118298758/210127530-27e4b3e5-e752-45da-8b24-579f6c4f6fbc.png)

And I can link it to the Item:

![Screenshot - 31_12_2022 , 07_29_01](https://user-images.githubusercontent.com/118298758/210127566-1016c6d1-ad68-492b-bd57-1a8dce77dae9.png)

Which then has the link stored correctly:

![Screenshot - 31_12_2022 , 07_29_30](https://user-images.githubusercontent.com/118298758/210127573-27c9fe89-70f5-4e6c-ba5b-238001eec43a.png)

So, the linking works in principle, just not via the Item page but only via the Thing page.

## Your environment

```
runtimeInfo:
  version: 3.4.0
  buildString: Release Build
locale: en-AT
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.17
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-11.0.17+8
  osName: Linux
  osVersion: 4.4.180+
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 23543568
  totalMemory: 159383552
  startLevel: 100
bindings:
  - openwebnet
  - shelly
  - sonos
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101
    Firefox/108.0
timestamp: 2022-12-31T06:32:24.808Z
```
