### ISSUE TITLE
Channel ID does not accept dash characters

### ISSUE THREAD

**Issue by Gemikro1** [openhab/openhab-webui#1630]
## The problem
Trying to add a channel to a thing with a channel ID that contains a dash "-" does give an error message `The identifier should only contain alphanumeric characters`

![Zwischenablage-1](https://user-images.githubusercontent.com/79222544/211334873-5de35951-8e52-40c0-b8cd-79fc21870218.png)

## Expected behavior
The entered ID with a dash character is accepted without error message as the dash character should be within the allowed alphanumeric character set

## Steps to reproduce
enter an ID that contains a dash character

1. Open a thing (in my case a roller shutter)
2. Select `Add Channel` 
3. Enter an ID that contains a dash character
4. Select `Create`

## Your environment

```yaml
runtimeInfo:
  version: 3.4.1
  buildString: Release Build
locale: en-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.15.84-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 95189800
  totalMemory: 194772992
  startLevel: 100
bindings:
  - avmfritz
  - boschshc
  - fronius
  - http
  - modbus
  - mqtt
  - ntp
  - shelly
  - weatherunderground
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 0.8955223880597015
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-GB
    languages:
      - en-GB
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2144
    height: 1206
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101
    Firefox/108.0
timestamp: 2023-01-09T14:36:52.934Z

```

## Browser console

```txt

```

## Additional information

Adding the channel manually to the yaml code with a dash does work and the channel is accepted correctly
