### ISSUE TITLE
Users cannot read any values

### ISSUE THREAD

**Issue by FelixSchick** [openhab/openhab-webui#1643]
My problem is that the user with custom Role has rights to a page, but cannot read any values. Some times the users can read values, but only very rarely

![image](https://user-images.githubusercontent.com/79106367/212494351-b796d137-7974-4bcd-9b10-35d39df1c836.png)

## Your environment

```
runtimeInfo:
  version: 3.4.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.16
  javaVendor: Debian
  osName: Linux
  osVersion: 5.15.76-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 22884568
  totalMemory: 136314880
  startLevel: 100
bindings:
  - homematic
  - weathercompany
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/107.0.0.0 Safari/537.36 OPR/93.0.0.0
timestamp: 2023-01-14T20:11:01.243Z
```
## Browser console

![image](https://user-images.githubusercontent.com/79106367/212494554-fb4a11a6-9d4b-43c8-be8b-943f5dc59350.png)
