### ISSUE TITLE
[MainUI] /settings/things/<thing uid> requests entire things JSON from API

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-webui#1650]
## The problem

I have a lot of things. With an even more ridiculous amount of channels. My /rest/things endpoint returns over 2.5MB of JSON. When I'm local, this takes nearly a second just to transfer. If I'm remote, it would take _much_ longer. Right now, when I click on an individual thing to configure it, I notice that it's using /rest/things to load the data. I'm sure this takes a long time for the javascript to parse, as well.

## Your suggestion

Instead, it should use `/rest/things/<thing UID>` to _only_ load the relevant information for the current page.

## Your environment

```yaml
runtimeInfo:
  version: 3.4.1
  buildString: Release Build
locale: en-Latn-US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.5
  javaVendor: Private Build
  osName: Linux
  osVersion: 5.15.0-57-generic
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 169239392
  totalMemory: 2147483648
  startLevel: 100
bindings:
  - amazonechocontrol
  - astro
  - bondhome
  - dscalarm
  - lgwebos
  - mqtt
  - myq
  - onkyo
  - pioneeravr
  - tuya
  - unifi
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 3008
    height: 1692
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/16.2 Safari/605.1.15
timestamp: 2023-01-17T23:36:18.688Z
```
