### ISSUE TITLE
 Custom icon issue with List Item Widget

### ISSUE THREAD

**Issue by francemgit** [openhab/openhab-webui#1663]
## The problem

Configuring a custom icon/category for one item makes the icon work on the semantic model but, when the item uses a list item widget the icon is broken.

## Expected behavior

Custom icon is used everytime and for every widget (List, Card, etc.)

## Steps to reproduce

1. Openhab 3.4
2. Item configured via item file
3. Configure a custom icon/category for one item e.g. <"if:mdi:toggle-switch-off">
4. The item icon is displayed correctly in the semantic model
5. When the item is displayed using a list item widget the icon is broken
6. If you try to add metadata from Openhab interface to “Default List Item Widget” by default the icon field value is inherited but the value is "oh:if:mdi:toggle-switch-off"
7. “oh” prefix is added to the field value and hence, the valeu became invalid.

## Your environment

```
runtimeInfo:
  version: 3.4.0
  buildString: Release Build
locale: en-IT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.10.103-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 105987976
  totalMemory: 194772992
  startLevel: 100
bindings:
  - daikin
  - gpstracker
  - logreader
  - mqtt
  - network
  - openwebnet
  - samsungtv
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: it
    languages:
      - it
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
timestamp: 2023-01-26T20:58:58.102Z

```

## Browser console

```txt

```

## Additional information

[Related source code snippet](https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui/web/src/components/widgets/standard/list/default-list-item.js#L168)

Community forum post: [Post](https://community.openhab.org/t/custom-icon-issue-with-list-item-widget/143692)
