### ISSUE TITLE
Memory Leak in Chart Control

### ISSUE THREAD

**Issue by ThomasBrodkorb** [openhab/openhab-webui#1674]
There is a severe memory leak in the chart control causing the OpenHAB app and also Gpogle Chrome crash.
Details are listed here https://community.openhab.org/t/memory-leak-in-bowser-and-oh-client-app/143394

**Comment by Yetangitu** [comment]
I just came her to report a bug on this. Any page which contains an auto-refreshing chart grows on each refresh until memory is exhausted and the process killed. Using Firefox, you seem to be using Chrom{e|ium} so this is not browser-specific. I saved a few memory snapshots showing the growth in case someone is interested.

**Comment by lolodomo** [comment]
Chart in MainUI or BasicUI?

**Comment by Yetangitu** [comment]
MainUI

**Comment by ThomasBrodkorb** [comment]
Great to hear that there is a solution,
who can integrate this in OH?
Another option to solve the issue is to refresh the complete page at a certain interval, or at least catch the OutOfMemory Exception in the OH Client and reload the page instead of crashing the app.
anyway, why are these elements detached in first place?
To me it looks like they come in when the chart refreshes (which is very slow, aprox. three seconds when redrawing the chart.
This should flash, not draw pixel by pixel.

**Comment by Yetangitu** [comment]
I doubt there is a resolution, the problem seems to lie in ECharts itself if those two reports - and a number of potentially related ones - point at the cause. Nulling the chart does _not_ seem to release the memory so the links I originally posted (and now removed) seem to be irrelevant.

**Comment by Yetangitu** [comment]
Partly in Chinese but the gist is clear, there have been and still seem to be memory leaks in ECharts, possibly related to the use of the GPU. The latter could easily be tested by trying the code in a browser without hardware acceleration.

https://github.com/apache/echarts/issues?q=is%3Aissue+is%3Aopen+memory+leak

**Comment by Yetangitu** [comment]
I just ran some test without hardware acceleration, the memory leak still occurs. Here's some memory values after running some hundred chart refreshes on a page with a single dynamic chart:

```
webIsolated=https://example.org (pid 7174)
Explicit Allocations

3,903.69 MB (100.0%) -- explicit
├──3,586.81 MB (91.88%) -- window-objects/top(https://dash.example.org/page/page_883056a9a9, id=60)
│  ├──3,381.25 MB (86.62%) -- active
│  │  ├──3,361.84 MB (86.12%) -- window(https://dash.example.org/page/page_883056a9a9)
│  │  │  ├──3,332.06 MB (85.36%) -- js-realm(https://dash.example.org/)
│  │  │  │  ├──3,320.99 MB (85.07%) -- classes
│  │  │  │  │  ├──1,619.05 MB (41.47%) -- class(Array)/objects
│  │  │  │  │  │  ├──1,230.66 MB (31.53%) ── gc-heap
│  │  │  │  │  │  └────388.39 MB (09.95%) -- malloc-heap
│  │  │  │  │  │       ├──335.55 MB (08.60%) ── elements/normal
│  │  │  │  │  │       └───52.84 MB (01.35%) ── slots
│  │  │  │  │  ├────736.55 MB (18.87%) -- class(Object)/objects
│  │  │  │  │  │    ├──597.29 MB (15.30%) ── gc-heap
│  │  │  │  │  │    └──139.26 MB (03.57%) -- malloc-heap
│  │  │  │  │  │       ├──138.48 MB (03.55%) ── slots
│  │  │  │  │  │       └────0.78 MB (00.02%) ── elements/normal
│  │  │  │  │  ├────290.29 MB (07.44%) ── class(Date)/objects/gc-heap
│  │  │  │  │  ├────275.70 MB (07.06%) -- class(Set)/objects                                                                                                                                   
│  │  │  │  │  │    ├──256.56 MB (06.57%) ── malloc-heap/misc                                                                                                                                  
│  │  │  │  │  │    └───19.14 MB (00.49%) ── gc-heap                                                                                                                                           
│  │  │  │  │  ├────163.00 MB (04.18%) -- class(Function)/objects                                                                                                                              
│  │  │  │  │  │    ├──160.90 MB (04.12%) ── gc-heap                                                                                                                                           
│  │  │  │  │  │    └────2.10 MB (00.05%) ── malloc-heap/slots                                                                                                                                 
│  │  │  │  │  ├────157.58 MB (04.04%) -- class(Call)/objects                                                                                                                                  
│  │  │  │  │  │    ├──157.50 MB (04.03%) ── gc-heap                                                                                                                                           
│  │  │  │  │  │    └────0.08 MB (00.00%) ── malloc-heap/slots                                                                                                                                 
│  │  │  │  │  ├─────72.18 MB (01.85%) -- class(ArrayBuffer)/objects                                                                                                                           
│  │  │  │  │  │     ├──72.02 MB (01.84%) ── malloc-heap/elements/normal                                                                                                                       
│  │  │  │  │  │     └───0.16 MB (00.00%) ── gc-heap                                                                                                                                           
│  │  │  │  │  └──────6.65 MB (00.17%) ++ (22 tiny)                                                                                                                                            
│  │  │  │  └─────11.07 MB (00.28%) ++ (5 tiny)                                                                                                                                                
│  │  │  └─────29.79 MB (00.76%) ++ (3 tiny)                                                                                                                   
```
The memory is lost in JS classes, forcing a garbage collect does not release it.

**Comment by Yetangitu** [comment]
This looks like a similar scenario:

https://github.com/apache/echarts/issues/15480

_After period of 1:30h browser crashes with the error below. Using Edge Chromium.
Error code: Out of memory

Before the crash browser is reporting 4GB of RAM usage.

Below is code excerpt that is used to chart data.
New data is coming every 3 seconds._

_Issue was resolved by fixing the way vue.js instantiates echart objects.
The original implementation seemed to be instantiating echarts objects on each data bind.
New implementation is working with object references and setOptions.
Memory and CPU are now stable._

The question now is what happens when a chart is refreshed in OpenHAB. From its behaviour it seems something similar is happening here so a similar solution could be used - instead of instantiating a new echart object on each update a reference to the existing one can be retrieved, its data nulled and new data inserted. I had a look at the code but don't know at what level of this bowl of JS/Vue spaghetti to start.

**Comment by 0xAskar** [comment]
@Yetangitu I think I'm having the same problem? When I have been using this in dev mode, randomly after a few hours it would crash. Do you know why it would that and how to prevent this in production?

**Comment by jsjames** [comment]
We have updated echarts versions as part of the big mainui update to vue3/etc. It would be good if someone can retest this with OH 5.2 to determine if the memory leak still occurs.

**Comment by jsjames** [comment]
Given the age of this issue and upgrades since (and no feedback), I will close this issue.  If necessary when folks can test and if the issue still exists, we can re-open.

**Comment by ThomasBrodkorb** [comment]
Well, issue persists in 5.1.3 - having to restart my tablet every hour or so. Living with it.
Was willing to install 5.2 but was not offered.
So could not test,

**Comment by jsjames** [comment]
thanks - i reopened given it still persists!

**Comment by jsjames** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

keep issue open as this is still an issue.

**Comment by ThomasBrodkorb** [comment]
The issue still exists in version 5.2.

There are plenty of detached "oh-chart-container" elements in the page.
Apparently, whenever it refereshes, the old chart is removed from the visibility tree and a new one is created and shown, but the old one is not destroyed and still consumes memory.
This leads to a crash at a later stage in the OH client.

**Comment by jsjames** [comment]
> The issue still exists in version 5.2.
> 
> There are plenty of detached "oh-chart-container" elements in the page. Apparently, whenever it refereshes, the old chart is removed from the visibility tree and a new one is created and shown, but the old one is not destroyed and still consumes memory. This leads to a crash at a later stage in the OH client.

@ThomasBrodkorb - can you provide the snippet of your code which does the refresh? Are you using something like what is mentioned here: https://community.openhab.org/t/auto-refresh-charts-and-widgets-in-mainui/132504?page=2

**Comment by ThomasBrodkorb** [comment]
I am not sure that I understand what you mean. There is no code which does a refresh.
I have this widget:

```
version: 1
widgets:
  CHART_Widget:
    tags: []
    props:
      parameters:
        - description: Header of the cell
          label: Header
          name: header
          required: false
          type: TEXT
        - description: Icon on top of the card (only f7 icons (without f7:))
          label: Icon
          name: icon
          required: false
          type: TEXT
        - context: item
          label: Graph Item 1
          name: graphItem1
          required: false
          type: TEXT
        - label: Graph Item Color 1
          name: itemColor1
          required: false
          type: TEXT
        - label: Area 1 filled
          name: area1filled
          required: false
          type: BOOLEAN
        - label: Name 1
          name: Name1
          required: false
          type: TEXT
        - context: item
          label: Graph Item 2
          name: graphItem2
          required: false
          type: TEXT
        - label: Graph Item Color 2
          name: itemColor2
          required: false
          type: TEXT
        - label: Area 2 filled
          name: area2filled
          required: false
          type: BOOLEAN
        - context: item
          label: Graph Item 3
          name: graphItem3
          required: false
          type: TEXT
        - label: Graph Item Color 3
          name: itemColor3
          required: false
          type: TEXT
        - label: Area 3 filled
          name: area3filled
          required: false
          type: BOOLEAN
        - context: item
          label: Graph Item 4
          name: graphItem4
          required: false
          type: TEXT
        - label: Graph Item Color 4
          name: itemColor4
          required: false
          type: TEXT
        - label: Area 4 filled
          name: area4filled
          required: false
          type: BOOLEAN
        - label: Name 2
          name: Name2
          required: false
          type: TEXT
        - label: Name 3
          name: Name4
          required: false
          type: TEXT
        - label: Name 4
          name: Name4
          required: false
          type: TEXT
      parameterGroups: []
    component: f7-card
    config:
      key: =Math.random() + items[props.graphItem1].state.split(" ")[0] + items[props.graphItem2].state.split(" ")[0] + items[props.graphItem3].state.split(" ")[0]
      style:
        background-color: rgba(0,0,0,0)
        border-radius: var(--f7-card-expandable-border-radius)
        box-shadow: 5px 5px 10px 1px rgba(0,0,0,0.1)
        margin-left: 5px
        margin-right: 5px
        noShadow: false
        padding: 0px
    slots:
      content:
        - component: f7-block
          config:
            style:
              display: flex
              flex-direction: row
              left: 16px
              position: absolute
              top: -5px
          slots:
            default:
              - component: f7-icon
                config:
                  f7: =props.icon
                  size: 18
                  style:
                    margin-right: 10px
                  visible: "=props.icon ? true : false"
              - component: Label
                config:
                  style:
                    font-size: 12px
                    margin-top: 0px
                  text: "=props.header ? props.header : ''"
      default:
        - component: oh-chart
          config:
            options:
              color:
                - rgba(255,0,0,1)
                - rgba(0,255,255,1)
                - rgba(0,255,0,1)
                - rgba(255,255,0,1)
            period: 4h
          slots:
            grid:
              - component: oh-chart-page
                config:
                  containLabel: true
                  height: 85%
                  includeLabels: true
                  left: 20px
                  show: false
                  top: 16px
                  width: 95%
            legend:
              - component: oh-chart-legend
                config:
                  bottom: 0px
                  show: true
                  type: scroll
            series:
              - component: oh-time-series
                config:
                  areaStyle:
                    opacity: "=props.area1filled ? 0.2 : 0.0"
                  color: =props.itemColor1
                  item: =props.graphItem1
                  markPoint:
                    data:
                      - name: Max
                        type: "=props.item1max ? 'max' : ''"
                      - name: Min
                        type: "=props.item1min ? 'min' : ''"
                      - name: Average
                        type: "=props.item1average ? 'average' : ''"
                  name: "=props.Name1 = '' ? props.graphItem1 : props.Name1"
                  smooth: true
                  type: line
                  xAxisIndex: 0
                  yAxisIndex: 0
              - component: oh-time-series
                config:
                  areaStyle:
                    opacity: "=props.area2filled ? 0.2 : 0.0"
                  color: =props.itemColor2
                  gridIndex: 0
                  item: =props.graphItem2
                  markPoint:
                    data:
                      - name: Max
                        type: "=props.item2max ? 'max' : ''"
                      - name: Min
                        type: "=props.item2min ? 'min' : ''"
                      - name: Average
                        type: "=props.item2average ? 'average' : ''"
                  name: "=props.Name2 = '' ? props.graphItem2 : props.Name2"
                  smooth: true
                  type: line
                  xAxisIndex: 0
                  yAxisIndex: 0
              - component: oh-time-series
                config:
                  areaStyle:
                    opacity: "=props.area3filled ? 0.2 : 0.0"
                  color: =props.itemColor3
                  item: =props.graphItem3
                  markPoint:
                    data:
                      - name: Max
                        type: "=props.item3max ? 'max' : ''"
                      - name: Min
                        type: "=props.item3min ? 'min' : ''"
                      - name: Average
                        type: "=props.item3average ? 'average' : ''"
                  name: "=props.Name3 = '' ? props.graphItem3 : props.Name3"
                  smooth: true
                  type: line
                  xAxisIndex: 0
                  yAxisIndex: 0
              - component: oh-time-series
                config:
                  areaStyle:
                    opacity: "=props.area4filled ? 0.2 : 0.0"
                  color: =props.itemColor4
                  item: =props.graphItem4
                  markPoint:
                    data:
                      - name: Max
                        type: "=props.item4max ? 'max' : ''"
                      - name: Min
                        type: "=props.item4min ? 'min' : ''"
                      - name: Average
                        type: "=props.item4average ? 'average' : ''"
                  name: "=props.Name4 = '' ? props.graphItem4 : props.Name4"
                  smooth: true
                  type: line
                  xAxisIndex: 0
                  yAxisIndex: 0
            tooltip:
              - component: oh-chart-tooltip
                config:
                  confine: true
                  orient: vertical
                  show: true
                  smartFormatter: true
            xAxis:
              - component: oh-time-axis
                config:
                  gridIndex: 0
            yAxis:
              - component: oh-value-axis
                config:
                  gridIndex: 0

```
and this is the config in the page:

component: widget:CHART_Widget
config:
  Height: 200
  Name1: Produktion
  Name2: Verbrauch
  Name4: Batterielast
  area1filled: true
  area2filled: false
  area4filled: true
  graphItem1: Persist_PV_Output
  graphItem2: Persist_PV_Consumption
  graphItem4: Persist_PV_BatteryLoad
  itemColor1: green
  itemColor2: red
  itemColor4: yellow
