### ISSUE TITLE
 Blank first Home Page card after closed in MainUI iOS

### ISSUE THREAD

**Issue by jjmeseguerrr** [openhab/openhab-webui#1685]
## The problem

On iPhone and on iPad, both in iOS app and in Safari, the locations, equipment and properties sections cards background images load ok, but when I close the first one, it goes blank:
![iPhone app](https://community-openhab-org.s3.dualstack.eu-central-1.amazonaws.com/original/3X/c/8/c8909d43b54bf11030cc8b3b716857fd841761d1.jpeg)
On iPad it works ok in the properties tab, but on iPhone it happens in all three tabs.
It only happens with the first card, and it shows ok again after opening another card.
I’ve tried to change the image background, even to the same used by another card, and it is always the same.
## Expected behavior

It shoudn't be blank.
## Steps to reproduce

1. Set a background image in the first card of the locations tab. Save.
2. In MainUI, open that first card.
3. Close the first card.
4. If you open another card, when you close it, the background of the first card will be shown ok again.

## Your environment

```yaml
runtimeInfo:
  version: 3.4.1
  buildString: Release Build
locale: es-ES
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.18
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.62+17-CA
  osName: Linux
  osVersion: 5.15.0-58-generic
  osArchitecture: amd64
  availableProcessors: 16
  freeMemory: 557561320
  totalMemory: 2387607552
  startLevel: 70
bindings:
  - astro
  - chromecast
  - kodi
  - lgwebos
  - mihome
  - miio
  - milight
  - mqtt
  - network
  - samsungtv
  - shelly
  - systeminfo
clientInfo:
  device:
    ios: true
    android: false
    androidChrome: false
    desktop: false
    iphone: true
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: ios
    osVersion: "16.2"
    webView: true
    webview: true
    standalone: true
    pixelRatio: 3
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: es-ES
    languages:
      - es-ES
    onLine: true
    platform: iPhone
  screen:
    width: 375
    height: 812
    colorDepth: 32
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: true
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X)
    AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
timestamp: 2023-02-05T19:36:37.394Z

```
iOS app version is the latest to date: 2.4.56 (1580410531).

## Browser console

```txt

```
Is there a browser console on iOS?
