### ISSUE TITLE
Do not allow illegal characters in custom widget name

### ISSUE THREAD

**Issue by jjmeseguerrr** [openhab/openhab-webui#1689]
## The problem
I created a custom widget named "Increase/Decrease". When I saved it there was no warning about "/" being an illegal character and the custom widget was saved.
But immediately I got an error saying that the widget could not be found (I don't remember exactly).
The widget is listed but when I try to edit or delete it I get this error:

![image](https://user-images.githubusercontent.com/35690504/217232317-35ff7c8a-147f-4840-9856-7c3c0cd58728.png)

This is a WebUI bug, but I also believe the backend should have checked for illegal characters before saving. I don't know if I need to open a new issue.

## Expected behavior
WebUI and the backend should have reported an error before saving.

## Steps to reproduce

1. Create a custom widget with the character "/" in its name.
2. Save.

## Your environment

```yaml
runtimeInfo:
  version: 3.4.1
  buildString: Release Build
locale: es-ES
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.18
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.62+17-CA
  osName: Linux
  osVersion: 5.15.0-58-generic
  osArchitecture: amd64
  availableProcessors: 16
  freeMemory: 1104077312
  totalMemory: 3797942272
  startLevel: 70
bindings:
  - astro
  - chromecast
  - kodi
  - lgwebos
  - mihome
  - miio
  - milight
  - mqtt
  - network
  - samsungtv
  - shelly
  - systeminfo
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: es-ES
    languages:
      - es-ES
      - es
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3840
    height: 2160
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/109.0.0.0 Safari/537.36
timestamp: 2023-02-07T11:32:52.969Z

```

## Additional information
I stopped OH, edited /var/lib/openhab/jsondb/uicomponents_ui_widget.json, replaced "/" by "-" where I found the name of the widget and started OH to be able to edit and delete.
