### ISSUE TITLE
MJPEG and Basic UI Video cuases network failure

### ISSUE THREAD

**Issue by woolf100** [openhab/openhab-webui#1693]
## Which UI are you reporting an issue for?

- [ X] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

   
Since I upgraded To OH 3.4.1 (coming from 2.5.12) Streaming MJPEG data causes an interesting Problem.

Inserting even multiple Videos in the sitemap using code like this was never a problem with OH 2.5
Video label="vidstream" icon="video" url="XXX" encoding="mjpeg" visibility=[Object==ON]

they would dynamically appear and disappear based on the item state of "Object"

With OH3.4.1 this still works in general but after a while will crash my network stack on all installations I tested.

Using "tcptrack -i wlan0"  shows that more and more connections are opened using always new ports with only one of them causing network traffic. However the old connections seem to remain open and occupy ports. After a while it appears as if all ports available are occupied and wlan0 becomes unreachable.

## Your suggestion

Let the browser stream the video and don't route it through openhab, or alternatively ensure that unused ports are closed or maybe cleaned up afer a while.

## Your environment

Reproducibility and Enironments tested:
Operating Systems: Debian Buster and Bullseye

Devices
The Issue can be reproduced on the following Systems: 
Raspberry 4 8GB Openhabian Image
Raspberry 4 8GB Manual installation
Raspberry Pi3B+  Openhabian Image
Raspberry Pi3B+ Manual installation
Rock PI 4 2gb manual OH installation (not tried anything else)

The client info below is misleading as it was copied from a PC environment and does not represent the always on display strategy using an I-Pad with Safari to display the basicUI sitemap

one of the setups:
```
runtimeInfo:
  version: 3.4.1
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.16
  javaVendor: Debian
  osName: Linux
  osVersion: 5.15.84-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 542971912
  totalMemory: 1677721600
  startLevel: 100
bindings:
  - astro
  - dwdpollenflug
  - dwdunwetter
  - ekey
  - exec
  - fineoffsetweatherstation
  - hpprinter
  - http
  - hue
  - ipcamera
  - keba
  - knx
  - miio
  - mikrotik
  - mqtt
  - network
  - openweathermap
  - rfxcom
  - shelly
  - sonos
  - systeminfo
  - tcpudp
  - telegram
  - tr064
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32 (Misleading the alwasy on is an IPAD with Safari)
  screen:
    width: XX
    height: XX
    colorDepth: XX
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: 
timestamp: 2023-02-08T20:40:12.744Z


```
