### ISSUE TITLE
Some missing Material Icons

### ISSUE THREAD

**Issue by XmlmXmlmX** [openhab/openhab-webui#1708]
In my openHAB 3.4.2 UI, some material icons are not working.

This is my YAML for a oh-label-card widget:

```yaml
component: oh-label-card
config:
  trendItem: SenecHome_BatteryPower
  title: Solarspeicher
  footer: =items.SenecHome_BatteryCurrent.state
  item: SenecHome_BatteryFuel
  icon: material:solar_power
  taphold_action: navigate
  taphold_actionPage: page:PV_Speicher
  action: navigate
  actionPage: page:PV_Speicher
  actionPageTransition: f7-circle
```

The rendered result looks like this:

<img width="210" alt="image" src="https://user-images.githubusercontent.com/677165/219033395-e17d84ca-cb93-4943-96f4-f6b7212b5f66.png">

And the HTML like this:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/677165/219033596-91ebbaba-b0eb-414e-a82e-cc3dc3f6c4cf.png">

The expected icon for `solar_power` would be:

> ![solar_power_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/677165/219034114-8f432965-3a1e-42c0-93c5-1e5ef71016b6.png)

(See https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Asolar_power%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

Also weird, that the incorrect rendered plug icon is misplaced.

For other oh-label-cards this works fine:
<img width="180" alt="image" src="https://user-images.githubusercontent.com/677165/219035761-b3d9c23f-24d6-4bc4-8da1-cd3c929db56d.png">
