### ISSUE TITLE
`oh-colorpicker` component doesn‘t accept `style` configuration

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-webui#1713]
## The problem

All `oh-` components accept CSS style configuration in the widget editor, but `oh-colorpicker` does apply the `style` configuration.

## Expected behavior

`oh-colorpicker` should apply `style` configuration.

## Steps to reproduce

Create a new widget and add this code to the slots.default section:

```yaml
    - component: oh-colorpicker
      config: 
        item: Florian_RGB
        style:
          position: absolute
          right: 5px
          top: 65px
          height: 60px
          width: 60px
```

## Your environment

```yaml
openHAB 3.4.1
```

## Browser console

Nothing related to this issue.

## Additional information

Wrapping `oh-colorpicker` inside a `div` works:

```yaml
    - component: div
      config: 
        style:
          margin: 0 0 0 0
          position: absolute
          right: 5px
          top: 65px
          height: 60px
          width: 60px
      slots:
        default:
          - component: oh-colorpicker
            config:
              item: Florian_RGB
              modules:
              - current-color
```
