### ISSUE TITLE
 Wrong width of oh-slider component in oh-widget

### ISSUE THREAD

**Issue by sofa1780** [openhab/openhab-webui#1714]
Hi,

I might have the exact same issue like described within [bug-report](https://github.com/openhab/openhab-webui/issues/967#issue-837628582) with the sliders at a different situation:
I am using a widget showing several light parameters includig oh-sliders with a min/max different from 0 to 100.

![grafik](https://user-images.githubusercontent.com/84171677/219467249-b412126d-f31e-4031-a02e-7eee46716eb4.png)

With this widget I am running into the same bahaviour presented by the op.

The used widged is shown bellow:
```
uid: widget_oh-slider_race_condition
tags: []
props:
  parameters:
    - description: Title of the widget
      label: Title
      name: title
      required: false
      type: TEXT
    - description: Item Title
      label: Light temperature title
      name: temperature_title
      required: false
      type: TEXT
    - context: item
      description: Item for holding the temperature value
      label: Light temperature item
      name: temperature_item
      required: false
      type: TEXT
    - description: Min value
      label: Light temperature min
      name: temperature_min
      required: false
      type: TEXT
    - description: Max value
      label: Light temperature max
      name: temperature_max
      required: false
      type: TEXT
    - description: Step
      label: Light temperature step
      name: temperature_step
      required: false
      type: TEXT
timestamp: Feb 16, 2023, 7:19:24 PM
component: oh-list-card
config:
  accordionList: false
  mediaList: true
  simpleList: false
  title: =props.title
slots:
  default:
    - component: oh-slider-item
      config:
        icon: f7:lightbulb
        item: =props.temperature_item
        label: true
        max: =props.temperature_max
        min: =props.temperature_min
        releaseOnly: false
        scale: false
        step: =props.temperature_step
        title: =props.temperature_title
```

My assumption is, that the sollution is quite simmilar as within the mentioned topic above.

Best regards
