### ISSUE TITLE
Web Audio Sink on iOS devices not working

### ISSUE THREAD

**Issue by CodeYuggi** [openhab/openhab-webui#1717]
## The problem
Main UI within Safari on iPad / iPhone does not play the sound using Web Audio Sink.

On my iPad Pro with iOS 16.3 and on my iPhone with iOS 16.3 audio sink is not working. Same on my other iPad (non por model).
I have Main UI running and activated “Enable Web Audio sink support” but no sound is played.
I have tried it with a HABPanel but also here no sound is played.
I upgraded to OH 3.4.1 to use this “Enable Web Audio sink support” feature in the Main UI.

When testing the same (Main UI and enable audio sink) on a Windows 10 machine within Chrome brwoser: the sound is played successfully.

As I have no Mac I cannot test if the issue is related to iOS or to Safari.

I tested it via a virtual switch item that triggers a rule that plays the sound "Barking" and uses sink "Web Audio" and volume = 100

## Expected behavior
I should hear the sound

## Your environment
```yaml
runtimeInfo:
  version: 3.4.1
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.103-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 114643720
  totalMemory: 324403200
  startLevel: 100
```

## Browser console
On my iPad I activated in the Developer Tools in the Debug tab the SSE Streaming. If the audio is pushed I saw in the streaming list the record

```txt
openhab/webaudio/playurl PlayURLEvent
“/audio/…a uuid…”
```

**Comment by florian-h05** [comment]
I guess it’s some problem with browser API implementation in WebKit at https://github.com/openhab/openhab-webui/blob/5b680e3a0811d8d8e6eb05b9e9226bfe02ec7a26/bundles/org.openhab.ui/web/src/components/app.vue#L626-L652

@digitaldan Since you already helped me at the SIP Client with WebKit compatibility, can you have a look at this?

**Comment by wborn** [comment]
I read that not all browsers support decoding all audio codecs.
So it could depend on your browser and the file you are playing.

You check browser/codec support with https://chinmay.audio/decodethis/

**Comment by CodeYuggi** [comment]
@wborn Thanx for the hint. I tested it on my iPad and my iPhone in Safari. On both devices the sounds can be played: mp3, wav, mp4.
The sound files in /openhab-conf/sounds are of type mp3
Hence I feel the issue is related to openhab's UI implementation

**Comment by CodeYuggi** [comment]
@florian-h05 @digitaldan : In addition I tested the following on openhab main UI:
I used the component "oh-video" with the following configuration.
```
    - component: oh-video
      config:
        url: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
        type: video/mp4
```
In openhab's UI on my iPad (safari browser) the video is played, but without any sound. Testing the same on my Windows machine and openhab's main UI in chrome the video is played WITH sound.

If I test the video url http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 **directly** in **safari** on my **iPad**, the video is played **WITH sound**.

It seems that the missing sound is related to openhab's UI implementation.
