### ISSUE TITLE
Add Scenes option to oh-repeater component

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-webui#1721]
## The problem
The newly introduced scenes via scenes editor are only available within actions when creating custom widgets.

## Your suggestion
It would be great to have the scenes available within the oh-repeater component, to create widgets with automatically generated scene lists.

**Comment by stefan-hoehn** [comment]
I looked a bit into the topic because I found it tempting to have a list of scenes that could be switched on and off.
However, from what I understood so far the repeater is all about items and all its components you iterate over are also item-components. The catch is that scenes are specific kind of rules and not items.  

What would be possible of course to a new source named "rules" that loads these rules (and I did a proof of concept on that and that works) but they would be processed as items which, I think, is not a clean approach even if added a new component for example "oh-list-rule", for example.

maybe @ghys could give some hints in what direction this could be developed in a clean way.

**Comment by hmerk** [comment]
Thanks for looking into this @stefan-hoehn 👍
From what I understood from the oh-repeater code, we would need to add a new sorce type „rules“ which should issue a REST call against the rules endpoint. The result should then give the rule/scene UID and name.

**Comment by stefan-hoehn** [comment]
This is exactly what I implemented in my POC but as I mentioned the whole concept is around managing items in widgets or repeaters and not something else like things or rules.

**Comment by hmerk** [comment]
Don't understand your comment.
Actually, you can already run rules within widgets and this is what I want to achieve : 

```
    - component: oh-repeater
      config:
        for: scene
        sourceType: rulesWithTags
        ruleTags: Scene
      slots:
        default:
          - component: oh-button
            config:
              action: rule
              actionRule: =loop.scene.UID
              text: =loop.scene.description
```

**Comment by stefan-hoehn** [comment]
Yes, similar to the above code is what I wanted to achieve: 
```
- component: oh-repeater
            config:
              for: rule
              sourceType: rules
            slots:
              default:
                - component: oh-list-item
                  config:
                    icon: oh:window
                    iconColor: red
                    title: =loop.rule.label
                    item: =loop.rule.name
                    badge: =loop.rule.state
                    badgeColor: red
```

Thanks for insisting on it 😄 

This is now what I did: I extended the repeater code to add a new source

```
else if (this.config.sourceType === 'rules') {
        return this.$oh.api.get('/rest/rules?summary=true').then((d) => d)
      } 
```

And it does create a list which is based on the rules that have been loaded. I debugged and I could see within the repeater that each element is a rule and you have directed my into the _right_ direction. I was looking for a component that would allow me to access the properties and I tried the oh-list-item (obviously incorrectly - see below) which didn't work and I could't find something suitable but the oh-button did then work with the following widget code based on your idea:

```
uid: list_of_rules
component: f7-card
config:
  title: Liste von Regeln
slots:
  default:
    - component: oh-list
      slots:
        default:
          - component: oh-repeater
            config:
              for: scene
              sourceType: rules
            slots:
              default:
                - component: oh-button
                  config:
                    action: rule
                    actionRule: =loop.scene.UID
                    text: =loop.scene.description
```

which in fact produces the following

<img width="346" alt="image" src="https://user-images.githubusercontent.com/5937600/219942839-93e4354e-af1d-4276-8e1e-1aa34c6c6c64.png">

So, I went along, added the ruleTags property 

```
slots:
  default:
    - component: oh-list
      slots:
        default:
          - component: oh-repeater
            config:
              for: scene
              sourceType: rulesWithTags
              ruleTags: Scene
            slots:
              default:
                - component: oh-button
                  config:
                    action: rule
                    actionRule: =loop.scene.uid
                    text: =loop.scene.name
```

and voila, we get

<img width="410" alt="image" src="https://user-images.githubusercontent.com/5937600/219943574-d760de37-a0ca-440e-8d71-84f2d2b5123e.png">

and >drum role< it even works when you click on the entry.

and I tried an oh-list-item and it works as well

```
- component: oh-list-item
                  config:
                    icon: f7:wand_stars
                    title: =loop.scene.name
                    action: rule
                    actionRule: =loop.scene.uid
                    text: =loop.scene.name
```

and produces

<img width="423" alt="image" src="https://user-images.githubusercontent.com/5937600/219944170-a96002fb-9954-4268-b33e-db19bccfb3cd.png">

So, I think we can call this "success". Let's say what the maintainers say when I finally do a PR.
