### ISSUE TITLE
Expert Mode Fails

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1775]
## The problem

When creating Items from a Thing, clicking on "Expert Mode" causes an error.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/6385096/223180864-27f6488f-3f81-493a-8bea-affaf93eb16e.png">

It looks like it might be a regression from PR #1578 according to JustinG (see https://community.openhab.org/t/oh3-expert-mode-cannot-be-accessed/144988)

## Expected behavior

Clicking on "Expert Mode" enters expert mode

## Steps to reproduce

1. Navigate to Settings -> Things -> pick any Thing.
2. Click the Channels Tab
3. Choose "Add Equipment to Model" or "Add Points to Model"
4. Click "Expert Mode"

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0
  buildString: "Build #3352"
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.6
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-17.0.6+10
  osName: Linux
  osVersion: 5.15.0-60-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 126140320
  totalMemory: 713031680
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
timestamp: 2023-03-06T17:11:31.137Z

```

## Browser console

```txt
SSE connection closed: http://10.10.1.112:8080/rest/events?topics=openhab/things/*/added,openhab/things/*/removed,openhab/things/*/updated,openhab/things/*/status,openhab/inbox/*, 0 open
app.501606344f29b6d1136a.js:69 []
app.501606344f29b6d1136a.js:7 Start tracking states
app.501606344f29b6d1136a.js:69 new SSE connection: http://10.10.1.112:8080/rest/events/states, 1 open
app.501606344f29b6d1136a.js:69 [EventSource]
app.501606344f29b6d1136a.js:7 Setting initial tracking list: []
app.501606344f29b6d1136a.js:69 sseConnected true
app.501606344f29b6d1136a.js:69 new SSE connection: http://10.10.1.112:8080/rest/events?topics=openhab/things/*/*,openhab/links/*/*, 2 open
app.501606344f29b6d1136a.js:69 (2) [EventSource, EventSource]
2app.501606344f29b6d1136a.js:69 Setting keepalive interval seconds 10
app.501606344f29b6d1136a.js:7 Stop tracking states
app.501606344f29b6d1136a.js:69 SSE connection closed: http://10.10.1.112:8080/rest/events/states, 1 open
app.501606344f29b6d1136a.js:69 [EventSource]
app.501606344f29b6d1136a.js:69 SSE connection closed: http://10.10.1.112:8080/rest/events?topics=openhab/things/*/*,openhab/links/*/*, 0 open
app.501606344f29b6d1136a.js:69 []
16.app.501606344f29b6d1136a.js:1 TypeError: Cannot read properties of undefined (reading '$oh')
    at f (16.app.501606344f29b6d1136a.js:1:4912)
    at f (16.app.501606344f29b6d1136a.js:1:5589)
    at i.switchToExpertMode (16.app.501606344f29b6d1136a.js:1:7288)
    at qe (app.501606344f29b6d1136a.js:7:11319)
    at i.n (app.501606344f29b6d1136a.js:7:13064)
    at qe (app.501606344f29b6d1136a.js:7:11319)
    at e.$emit (app.501606344f29b6d1136a.js:7:34215)
    at app.501606344f29b6d1136a.js:7:94108
    at Array.forEach (<anonymous>)
```
