### ISSUE TITLE
[BasicUI] Proxy for video and image widgets is not available anymore

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-webui#1782]
## Which UI are you reporting an issue for?
- [X] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

All my `Video` and `Image` widgets are broken and not showing anymore.
They both rely on the proxy-servlet, which does not seem to exist anymore:

<img width="845" alt="Bildschirm­foto 2023-03-07 um 22 38 50" src="https://user-images.githubusercontent.com/3244965/223558917-e3d82a50-f46c-43ff-919d-088c45e28a38.png">

## Expected behavior

Videos and images are shown.

## Steps to reproduce

Use a Video or Image widget in a sitemap.

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0
  buildString: "Build #3356"
locale: default
systemInfo:
  configFolder: /Applications/openhab4/conf
  userdataFolder: /Applications/openhab4/userdata
  logFolder: /Applications/openhab4/userdata/logs
  javaVersion: 17.0.6
  javaVendor: Homebrew
  javaVendorVersion: Homebrew
  osName: Mac OS X
  osVersion: 12.6.3
  osArchitecture: x86_64
  availableProcessors: 4
  freeMemory: 184646824
  totalMemory: 575668224
  startLevel: 70
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2.200000047683716
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - de-DE
      - en-GB
      - de
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1792
    height: 1120
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
timestamp: 2023-03-07T21:42:16.486Z

```
