### ISSUE TITLE
Channel Details is broken

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-webui#1784]
## The problem

When clicking "Channel Details":
![image](https://user-images.githubusercontent.com/19519842/224021506-d5c83085-c483-4bb0-8c95-17e39c845f52.png)

I see this:
![image](https://user-images.githubusercontent.com/19519842/224021535-06c46873-00a9-4f28-9844-c2fa2f5c74a1.png)

## Expected behavior

Channel details should be shown, i.e. Channel UID.

## Steps to reproduce

Navigate to a random thing and a random channel and click "Channel Details".

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0
  buildString: "Build #3358"
locale: da-DK
systemInfo:
  configFolder: C:\PROGRA~1\openHAB\conf
  userdataFolder: C:\PROGRA~1\openHAB\userdata
  logFolder: C:\PROGRA~1\openHAB\userdata\logs
  javaVersion: 17.0.5
  javaVendor: Oracle Corporation
  osName: Windows 10
  osVersion: "10.0"
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 144139736
  totalMemory: 266338304
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: da
    languages:
      - da
      - en-US
      - da-DK
      - en-DK
      - en
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 1600
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/110.0.0.0 Safari/537.36
timestamp: 2023-03-09T16:03:47.964Z
```

## Browser console

![image](https://user-images.githubusercontent.com/19519842/224081396-6b63b49a-aa88-489e-9c26-57e2e58c9087.png)

```txt
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/rest/config-descriptions/channel:unifi:wirelessClient:4921f92893:169dc7c8:rssi
```

When I access this URL directly:

```json
{"error":{"message":"Authentication required","http-code":401}}
```

The same happens in 3.4.2 actually, but here the UI still works.

# Additional information

See https://community.openhab.org/t/openhab-4-0-snapshot-discussion/142322/239

Might be a regression of #1683.
