### ISSUE TITLE
Wrong calulations in JavaScript from Blockly with numeric types in OH4

### ISSUE THREAD

**Issue by EvilPingu** [openhab/openhab-webui#1791]
## The problem
Hi,

if found a Blockly JavaScript Problem with OH4 regarding calulations:

I created a little script

![grafik](https://user-images.githubusercontent.com/10487375/224766832-260d34b4-542d-4ab6-a6d7-6b802bd469c5.png)

We see that the state of an item is saved in a variable named “oldValue”. The Item is a Number (it also works with Number:Length in OH3).
We see also ne variable named “newValue” which is calculeted from old and new value of another item of type number. Finally both variables are added.

With the “old” script engine from OH3 the result looks like this:

2023-03-12 17:28:19.046 [INFO ] [org.openhab.rule.db19777b97                  ] - 518
2023-03-12 17:28:19.069 [INFO ] [org.openhab.rule.db19777b97                  ] - 0.09999999999999964
2023-03-12 17:28:19.074 [INFO ] [org.openhab.rule.db19777b97                  ] - 518.1

With the “new” script engine from OH4 the result looks like this:

2023-03-12 17:23:03.001 [INFO ] [org.openhab.automation.script.ui.db19777b97  ] - 518
2023-03-12 17:23:03.004 [INFO ] [org.openhab.automation.script.ui.db19777b97  ] - 0.10000000000000009
2023-03-12 17:23:03.006 [INFO ] [org.openhab.automation.script.ui.db19777b97  ] - 5180.10000000000000009

You can see that the strings are concated instead of calculating the numbers. Is there a chance to migrate such scripts? I didn’t find a solution.

## Expected behavior

Expected is that the two numbers are calulated instead concating the strings.

This is the OH4 javascript:
```javascript
var oldValue, newValue, result;


oldValue = items.getItem('WeatherStation_RainCounter').state;
newValue = event.itemState - event.oldItemState;
result = newValue + oldValue;
console.info(oldValue);
console.info(newValue);
console.info(result);
```
This is the OH3 javascript:
```javascript
var oldValue, newValue, result;

var logger = Java.type('org.slf4j.LoggerFactory').getLogger('org.openhab.rule.' + ctx.ruleUID);


oldValue = itemRegistry.getItem('WeatherStation_RainCounter').getState();
newValue = event.itemState - event.oldItemState;
result = newValue + oldValue;
logger.info(oldValue);
logger.info(newValue);
logger.info(result);
```

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0.M1
  buildString: Milestone Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.6
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.84-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 19231104
  totalMemory: 235274240
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101
    Firefox/111.0
timestamp: 2023-03-13T16:36:59.597Z

```
