### ISSUE TITLE
[MainUI] Loading instead of authorization error

### ISSUE THREAD

**Issue by felixschndr** [openhab/openhab-webui#1794]
## The problem

When trying to access a page in the MainUI, that is reserved for administrators (e.g. `host:port/settings/rules/`) while not beeing logged in the page looks like it is loading (forever) and does not prompt the user for a login.

![image](https://user-images.githubusercontent.com/45742226/224820496-9b0baa1f-c5de-4e1e-b698-43712e1daa73.png)

Example: This happens when opening a bookmark (maybe on a different device)
## Expected behavior

A redirect to the login page and after login a redirect to the page the user was trying to access in the first place

## Steps to reproduce

Try to access `host:port/settings/rules/` in an incognito tab

## Your environment

```yaml
runtimeInfo:
  version: 3.4.2
  buildString: Release Build
locale: de-DE
  javaVersion: 11.0.18
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-11.0.18+10
  osName: Linux
  osVersion: 5.15.0-67-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 190889904
  totalMemory: 701497344
  startLevel: 100
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.75
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - en-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1715
    height: 1143
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/111.0.0.0 Safari/537.36
timestamp: 2023-03-13T20:14:01.165Z
```
