### ISSUE TITLE
[MainUI] Rephrase login prompt in german

### ISSUE THREAD

**Issue by felixschndr** [openhab/openhab-webui#1795]
## The problem

This issue is specifically about the german login page for administrators. In my opinion the text that is shown is unclear. Since this issue is about a German text I'll switch to German:

> Anmelden, um admin Zugriff auf http://grievous.fs:5000 zu gewähren:

![image](https://user-images.githubusercontent.com/45742226/224824187-521cb86e-752d-47a3-b4d4-cfcb5bf218c9.png)

Was genau heißt dieser Satz?
- Bekomme ich Administratorzugriff, wenn ich mich einlogge? Dann sollte "admin Zugriff" zusammen geschrieben werden --> Adminzugriff / Administratorzugriff oder
- Bekommt der User `admin` Zugriff? Wenn ja, warum muss ich dann den Nutzernamen angeben? 

## Expected behavior

A change of the sentence presented

## Steps to reproduce

Opening the login-page while the server is set to german

## Your environment

```yaml
runtimeInfo:
  version: 3.4.2
  buildString: Release Build
locale: de-DE
systemInfo:
  javaVersion: 11.0.18
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-11.0.18+10
  osName: Linux
  osVersion: 5.15.0-67-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 190889904
  totalMemory: 701497344
  startLevel: 100
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.75
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - en-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1715
    height: 1143
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/111.0.0.0 Safari/537.36
timestamp: 2023-03-13T20:14:01.165Z

```
