### ISSUE TITLE
 [MainUI] Presence badge not shown for points part of equipment

### ISSUE THREAD

**Issue by TheRocken** [openhab/openhab-webui#1797]
## The problem
According to https://github.com/openhab/openhab-webui/issues/556 the presence badge should be shown either for points directly in a location or in an equipment within an location. The second case is not working for me.

## Expected behavior
Unfortunately for me only this is working:
```
Kitchen (class kitchen)
|-> Contact (class Point_Status, relatesTo Property_Presence)
```

But the following does not work:
```
Kitchen (class kitchen)
|-> MotionSensor (class motionDetector)
    |-> Contact (class Point_Status, relatesTo Property_Presence)
```

## Steps to reproduce

1. Create a point with
- class: Point_Status
- relatesTo: Property_Presence
2. Within an equipment like this:
- class: motionDetector / sensor
3. Within an location like this:
- class: kitchen

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0.M1
  buildString: Milestone Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.6
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-17.0.6+10
  osName: Linux
  osVersion: 4.4.180+
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 89696304
  totalMemory: 401604608
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101
    Firefox/110.0
timestamp: 2023-03-14T20:49:36.424Z
```

## Browser console

```txt

```

## Additional information

The issue seems to be independent of the item type (Contact / Switch) and the type of the equipment.
Other badges like door badges are working as expected for me
