### ISSUE TITLE
Add text wrapping in the things view 

### ISSUE THREAD

**Issue by felixschndr** [openhab/openhab-webui#1803]
## The problem
The text in the configuration part of a thing view isn't wrapped:
![image](https://user-images.githubusercontent.com/45742226/226322338-32ed5ab4-529e-467f-9cbd-d404347adafe.png) and thus overflows the textbox

## Expected behavior

Wrap the text up to a new line, add a scroll bar or add a `...` to the end (preferably the first).

I was able to achieve this by manually editing the `css` of the page:
![image](https://user-images.githubusercontent.com/45742226/226323632-347c1305-1043-4aa6-8423-4287ad966270.png)

Added `overflow: auto` or `overflow: scroll` to the element with the class `item-immer` (`/html/body/div/div[4]/div[2]/div[3]/div/div[1]/div[2]/div/div[6]/div/div/div/div/div/ul/li/div/div`)
![image](https://user-images.githubusercontent.com/45742226/226324014-25d2af38-359a-4e9d-b4e8-1ab9855a39ff.png)

## Steps to reproduce

1. Add the following thing
```
Bridge amazonechocontrol:account:Amazon_System_Konto "Amazon_System_Konto"@"System" [discoverSmartHome=2, pollingIntervalSmartHomeAlexa=15, pollingIntervalSmartSkills=120] {
    Thing smartHomeDevice      Amazon_Wohnzimmer_Herzlampe1   "Amazon_Wohnzimmer_Herzlampe"@"Wohnzimmer" [id="SKILL_eyJza2lsbZUHBjbdwqhHPIHbjEuYXNrLnNraWxsLmQxOWZiNjFiLTVkYzMtNGZlYS1iNGMzLTYyNmE2ZTkzNTA1erreihasxyx<yxdibGl2ZSJ9_OD_WE_HWUO-8912-_wUBAIrwerwesd-_lAAAAAAAAA"]
}
```
2. See the thing in the MainUI

## Your environment

Browser: Google Chrome Version 111.0.5563.65 (Offizieller Build) (64-Bit)

  startLevel: 100
```yaml
runtimeInfo:
  version: 3.4.2
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.18
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-11.0.18+10
  osName: Linux
  osVersion: 5.15.0-67-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 118327704
  totalMemory: 292552704
  startLevel: 100
```
