### ISSUE TITLE
oh-repeater requests new data in the context of css visibility

### ISSUE THREAD

**Issue by NRquadrat** [openhab/openhab-webui#1804]
## The problem

An oh-repeater always requests data via the REST as soon as the parent element of the repeater is changed with css attributes.
This costs runtime and processing power.

![grafik](https://user-images.githubusercontent.com/79790877/226610620-c18b1320-e86d-4ccc-911e-4c4d967670d2.png)

## Expected behavior
In my opinion, the repeater should retrieve data and then they are ready. When the parent is changed, the repeater should not retrieve data again.

## Steps to reproduce

```yaml

uid: test_repeater
tags: []
props:
  parameterGroups: []
timestamp: Mar 21, 2023, 1:38:12 PM
component: f7-block
config:
  stylesheet: >
    .disableOverObjVar{
      display: none;

    }
slots:
  default:
    - component: oh-button
      config:
        action: variable
        actionVariable: objVar
        actionVariableValue:
          visibility: "=vars.objVar.visibility == true ? false : true"
        text: Toggle Room Section objVar SECTION2 <-> undefined
    - component: Label
      config:
        text: '="vars.objVar.visibility: " + vars.objVar.visibility'
    - component: f7-block
      config:
        class:
          - '=vars.objVar.visibility == true ? "" : "disableOverObjVar"'
      slots:
        default:
          - component: f7-row
            config:
              class:
                - justify-content-flex-start
            slots:
              default:
                - component: oh-repeater
                  config:
                    fetchMetadata: semantics
                    filter: (loop.floors.metadata) && (loop.floors.metadata.semantics.value).includes("Floor")
                    for: floors
                    fragment: false
                    itemTags: ","
                    sourceType: itemsWithTags
                  slots:
                    default:
                      - component: f7-col
                        config:
                          style:
                            border-style: dashed
                            width: 100%
                        slots:
                          default:
                            - component: Label
                              config:
                                style:
                                  background-color: gray
                                text: '="1. Geschoss: " + loop.floors.name'
                      - component: oh-repeater
                        config:
                          fetchMetadata: semantics
                          filter: (loop.rooms.metadata) && ((loop.rooms.metadata.semantics.value).includes("Room")  || (loop.rooms.metadata.semantics.value).includes("Corridor"))
                          for: rooms
                          fragment: true
                          groupItem: =loop.floors.name
                          sourceType: itemsInGroup
                        slots:
                          default:
                            - component: f7-col
                              config:
                                style:
                                  border-style: dashed
                                  width: 100%
                              slots:
                                default:
                                  - component: Label
                                    config:
                                      style:
                                        background-color: lightgray
                                      text: '="2. Raum: " + loop.rooms.name'
                                  - component: f7-card
                                    config:
                                      title: ="Card of " + loop.rooms.name
                                      content: Content


```

## Your environment

RPI 4 , openhabian

## Browser network traffic

![grafik](https://user-images.githubusercontent.com/79790877/226610738-0ae6d783-ad09-46d1-824f-dbe9af6ed30c.png)
