### ISSUE TITLE
Better Item Picker Search UX

### ISSUE THREAD

**Issue by niwla23** [openhab/openhab-webui#1855]
## The problem

The "Add from Model" Item picker currently only searches in labels, not in item names. I am more familar with the actualy item names as these are what I work with everywhere else (Item files, Rule files, UI rules, UI YAML, ...). The other part of the problem is that when searching it still shows the collapsed folders instead of a plain item list

## Your suggestion
Search in item names, as well as labels (maybe even group names?). Once a user starts searching remove the folder view and just show a plain item list or show the path like this: "Weather > Temperature > Sensor Front". Maybe also show the item name  in brackets behind the label or in the secondary label.

![image](https://user-images.githubusercontent.com/46248939/233776379-18e45b1b-07bc-4db0-bfee-ff59b5362381.png)
Quick mock up of what I mean

To be clear, I am not suggesting to remove the folder view completly, but I think once you start searching it does not make sense any more and in my experience only gets in the way.

## Your environment

```yaml
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.15
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-11.0.15+10
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 72095792
  totalMemory: 379584512
  startLevel: 100
bindings:
  - chromecast
  - exec
  - modbus
  - mqtt
  - openweathermap
  - pushover
  - wled
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 4
    hardwareConcurrency: 8
    language: de
    languages:
      - de
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/112.0.0.0 Safari/537.36
timestamp: 2023-04-22T09:43:50.501Z

```
