### ISSUE TITLE
[Main UI] Slider widget causes unsolicited handleCommand() calls to bindings when channel value is PercentType(BigDecimal)

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#1862]
There is a bug in the Main UI page script as follows..

1. Main UI is displaying a slider value for a PercentType channel, and..
2. OH core sends an SSE update of the channel value comprising float PercentType(BigDecimal) value (not an integer), then..
3. Main UI makes a rounding error between the slider's supposed integer position, and the float value of the channel value, so..
4. Main UI wrongly sends a POST to OH core with the new (wrongly rounded) integer value, with the result that..
5. OH core therefore is forced to (wrongly) call handlecommand() on the binding..

The issue was first reported here:  https://github.com/openhab/openhab-core/issues/3571

**Comment by lolodomo** [comment]
@openhab/webui-maintainers : maybe something easy to fix? 
This issue looks relatively critical.

**Comment by florian-h05** [comment]
I am currently working on the evcc binding, but I can have a look at this.

**Comment by andrewfg** [comment]
@florian-h05 the posts in the thread starting [here](https://github.com/openhab/openhab-core/issues/3571#issuecomment-1523794004) will probably give you a better idea what is happening..

**Comment by florian-h05** [comment]
Have you considered adjusting the `step` property of the slider widget to something smaller? E.g. `0.1`?

**Comment by andrewfg** [comment]
I am not reporting a bug in a widget; it is a bug in Main UI
![image](https://github.com/openhab/openhab-webui/assets/893994/ecabd9e6-aef2-431d-9113-71e26ff875af)

**Comment by florian-h05** [comment]
MainUI is internally using the same components that you could use in widgets. Your Item is a dimmer right, and I guess it is using `oh-slider` as a control. 
The slider widget is rounding to a given number of decimals (default 0 decimals when `step` is 1), you can influence that behaviour by setting the `Default Standalone Widget` metadata and setting a step size like `0.25`, but I see your problem.

if my guess with `oh-slider` is correct, I can modify the slider so that it does not trigger commands when a state update is received but only when the user actually interacts with it.

**Comment by florian-h05** [comment]
@andrewfg Was a bit more complicated than expected, but here is the fix: #1894.

You can follow https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui/CONTRIBUTING.md#npm-scripts to set up a MainUI dev environment, then check out my PR and start up the dev server. Note that it is not finished yet.
When I am finished, I can also provide an artifact for 4.0.

**Comment by florian-h05** [comment]
@andrewfg I'm finished, you can download a 4.0 artifact here: https://we.tl/t-TxVppmjfqW

**Comment by mstormi** [comment]
I have a problem with current OH4 (S3515) that may or may not be related:
When I set a value like 2.3 via slider, the item is correctly set and remains correct.
However the slider position graphically resets to the next-lowest integer (2 in this case).

Example UI config:
```
                          - component: oh-slider-item
                            config:
                              item: Strombedarf_Spuelmaschine_Normal_Voreinstellung
                              label: true
                              max: 3
                              min: 0.1
                              scale: true
                              step: 0.01
                              title: Standardprogramm
                              unit: kWh
```
