### ISSUE TITLE
[MainUI] oh-slider does not send a command when mouse released outside slider bar

### ISSUE THREAD

**Issue by Ramon00** [openhab/openhab-webui#1866]
Issue: oh-slider does not send a command when mouse released outside slider bar

If I click on the slider it will send the command, if i actually slide it, then it doesnt always send a command when realeasing, especially when i drag it to the end point with the mouse cursor outside the actual scale (which i tend to do to make sure its at max or min). Changing “releaseOnly” to false does not really help.

See for slightly more detail: 
[https://community.openhab.org/t/oh-slider-does-not-update-when-dragging-it-outside-the-scale/146383?u=domofl](url)
Code:
```
                      - component: oh-slider
                        config:
                          item: =props.item + 'ColorRed'
                          releaseOnly: true
                          scale: true
                          min: 0
                          max: 255
```

Issue present on 3.4.2 and has been reproduced on 4.0M2.

Thank you.
