### ISSUE TITLE
Add a link to the language reference docs on the script editor page

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1915]
## The problem

New users to MainUI, particularly those who neglect to read the docs end up with the dreaded "blank screen" when they first try to create a Script Action or Script Condition. 

Even for proficient users of MainUI and OH, it would be an improvement to the work flow to have a link to the reference docs right there instead of needing to manually open a new tab and navigate through the openhab.docs to find the reference.

## Your suggestion

We can ease that and improve the workflow of even experienced users if we add a link to the reference docs for what ever language was selected for that script somewhere on the screen (perhaps at the bottom). If possible, configure it to open in another tab instead of the current tab so a user can open it without leaving their script editing screen.

I realize this might require a minor change to openhab-core so this information is part of the API.

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0
  buildString: "Build #3485"
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-17.0.7+7
  osName: Linux
  osVersion: 5.15.0-73-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 510549800
  totalMemory: 1098907648
  startLevel: 70
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
timestamp: 2023-06-05T14:02:48.177Z
```

## Additional information

https://community.openhab.org/t/confused-on-what-kind-of-rules-rules-engine-i-should-be-using/146999/13
@florian-h05
