### ISSUE TITLE
Vue key property does not refresh oh-repeater

### ISSUE THREAD

**Issue by JustinGeorgi** [openhab/openhab-webui#1918]
## The problem

As reported [in the forum](https://community.openhab.org/t/openhab-4-0-milestone-discussion/145133/381), after PR #1904 oh-repeaters no longer refresh properly in response to a change in the vue `key` property.

## Expected behavior

Repeater should refresh data and re-render when the vue `key` property changes.

## Steps to reproduce

Here's an example widget to test:
```
uid: demo_repeater_key
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Jun 7, 2023, 6:23:41 PM
component: f7-block
config: {}
slots:
  default:
    - component: oh-button
      config:
        action: variable
        actionVariable: keyReset
        actionVariableValue: =(vars.keyReset || 0) + 1
        text: ="Force reset " + (vars.keyReset || 0)
    - component: oh-button
      config:
        action: variable
        actionVariable: loopObject
        actionVariableValue:
          - name: Foo
            other: Apple
          - name: Bar
            other: Banana
        text: ="Foo Bar"
    - component: oh-button
      config:
        action: variable
        actionVariable: loopObject
        actionVariableValue:
          - name: Foo
            other: Apple
          - name: Bar
            other: Banana
          - name: Baz
            other: Cucumber
        text: ="Foo Bar Baz"
    - component: f7-block
      config: {}
      slots:
        default:
          - component: oh-repeater
            config:
              key: =Math.random() + (vars.keyReset || 0).toString()
              for: repeatObj
              sourceType: array
              in: =vars.loopObject
            slots:
              default:
                - component: oh-label-card
                  config:
                    label: =loop.repeatObj.name
    - component: oh-button
      config:
        clearVariable:
          - loopObject
          - keyReset
        text: ="Reset Variables"
```

Initial repeater will render no label cards because the source array is empty.
1) Click on `Foo Bar` to populate the source array.  Repeater does not render the new array.
2) Click on `Force Reset` and reset counter will increment but repeater will still not render the array.
3) Repeat with `Foo Bar Baz` for further testing.  Repeater will never render.

Move `key` property up one level to the `f7-block` then a different behavior is seen:
1) Repeater is rendered because of full widget redraw on change of yaml, so click `Reset Variables` to clear repeater.
2) Click on `Foo Bar` to populate the source array.  Repeater does not render the new array.
3) Click on `Force Reset` and reset counter will increment and block refresh will force repeater to refresh and re-render.
4) Repeat with `Foo Bar Baz` for further testing.  Repeater will re-render each time with a forced refresh.
