### ISSUE TITLE
[MainUI] Select transformations from list

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1944]
## The problem

Even when a user does everything through MainUI they have to remember and understand a text based syntax in order to select and apply a transformation to a Channel or a Profile. 

## Your suggestion

I know this is a huge job and may very well not be feasible without significant changes to core.

But now that we have a transformations API endpoint, it occurs to me we theoretically could use a selection dialog instead of needing to remember the syntax. 

Stuff to consider:

- Users should still be able to define a transformation inline
- Transformation chaining
- Transformation arguments (e.g. `JS(<scriptname>.js?arg=value)`)
- What happens when a transformation is removed?
- API needed to be implemented by developers of new transformations to handle any unique stuff about their transform and this selection dialog

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0
  buildString: "Build #3512"
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-17.0.7+7
  osName: Linux
  osVersion: 5.15.0-75-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 517044976
  totalMemory: 1174405120
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1.600000023841858
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
timestamp: 2023-06-28T14:39:21.041Z
```
