### ISSUE TITLE
Slider position graphically resets to the next-lowest integer

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-webui#1949]
I try to set a *fractional* Number item value like 2.3 via slider.
The step: option is honored and the item is correctly set.
However the slider position graphically resets to the next-lowest integer (2 in this case).
(just the graphics, the item state remains to what I've set it i.e. 2.3 here)

Example UI config:
```
                          - component: oh-slider-item
                            config:
                              item: Strombedarf_Spuelmaschine_Normal_Voreinstellung
                              label: true
                              max: 3
                              min: 0.1
                              scale: true
                              step: 0.01
                              title: Standardprogramm
                              unit: kWh
```

I'm on Snapshot S3515.

(eventually)
Related: #1503
