### ISSUE TITLE
SoundVolume property category shown as "undefined" in main UI

### ISSUE THREAD

**Issue by bkpsu** [openhab/openhab-webui#1976]
When viewing the Properties page in Main UI, the SoundVolume property group is labeled "undefined". This is a new issue noticed post OH3.4 -> OH4 upgrade.

![image](https://github.com/openhab/openhab-webui/assets/1578043/edd2c858-053a-4ebb-affc-56020e1b31c8)

Property page should be labeled "Sound Volume" per model

Click on Properties page and look at SoundVolume property page.

1. 

## Your environment

```yaml

runtimeInfo:
  version: 4.0.0
  buildString: "Build #3545"
locale: en-US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.7
  javaVendor: Private Build
  osName: Linux
  osVersion: 6.1.11-meson64
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 60074320
  totalMemory: 458227712
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/114.0.0.0 Safari/537.36
timestamp: 2023-07-21T18:01:32.050Z


## Browser console

<!--
Open the developer tools in your browser, go to the Console tab and paste errors and other messages that might be relevant to this issue.
You may also paste a screenshot if you prefer.
-->

```txt

```
