### ISSUE TITLE
Reintroduce inline script support for ECMAScript

### ISSUE THREAD

**Issue by ulfwin** [openhab/openhab-webui#1981]
## The problem
Inline script support for channel transformation profiles seems to exist for python and DSL, but is not there for ECMAScript since it presents a list of existing scripts rather than a text field (see below screenshot)

I believe earlier milestones had the custom text field also for ECMAScript.

![image](https://github.com/openhab/openhab-webui/assets/9116407/b27bcbeb-c322-49d0-b0ce-1f88a10c0e7d)

## Your suggestion

The list of scripts is also nice, so perhaps the list and an additional text field as well?

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0.M4
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.7
  javaVendor: Raspbian
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 46981712
  totalMemory: 479059968
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101
    Firefox/115.0
timestamp: 2023-07-22T17:51:17.492Z
```
