### ISSUE TITLE
[MainUI] Dynamic number of markers on a Map

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1990]
## The problem

There are some use cases where one wants to show a dynamic number of points on a map where you don't know at page configuration time how many points there will be. 

For example, in addition to showing just the current location but a history of that Item over a certain time period, or maybe a bunch of members of a Group which might change periodically.

This is related to Issue #1286 only more broad in scope.

## Your suggestion

Ultimately I'm thinking about something like an oh-repreater-card except for the markers on the Map page. Access to historic data would be cool but not necessary for all use cases so I don't want to limit this to just using that. Members of a Group, Items with a given tag, Items with "Location" in the name, etc. would all be usable ways to achieve what I'm after. 

Probably the most straight forward would be to pass a Group to a marker and it will generate one marker for each member of that Group. But I don't want to limit other potential approaches. 

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3562"
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 5.15.0-78-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 333165432
  totalMemory: 1149239296
  startLevel: 70
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
timestamp: 2023-07-26T17:14:09.243Z
```

## Additional information

I'm trying to approximate https://community.openhab.org/t/gpstracker-google-map/91646 using the built in mapping capabilities.
