### ISSUE TITLE
OH4.0.1: "Equipment" is missing in Semantic Class

### ISSUE THREAD

**Issue by EngiNearEngiFar** [openhab/openhab-webui#2003]
## The problem
In OH4.0.1 the "Equipment" as default Semantic Class is completely missing.
When adding a new Equipment in the Model view the default Semantic Class is "Apartment" which is a "location", which is wrong. 

## Expected behavior
Equipment Semantic Class should exist, like it is in OH 3.4.4. See printscreen on the right, compared to OH4.0.1 on the left. 
![image](https://github.com/openhab/openhab-webui/assets/83063002/27134768-bb13-4ef5-b97c-f5321717f49e)

## Steps to reproduce

1. Open Semantic Model and "Add Equipment". There is no "Equipment" as Semantic Class shown. 

## Your environment

```
runtimeInfo:
  version: 4.0.1
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.8
  javaVendor: Private Build
  osName: Linux
  osVersion: 6.1.11-meson64
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 239029432
  totalMemory: 717225984
  startLevel: 70
```

## Additional information

https://community.openhab.org/t/oh4-semantic-model-create-equipment-from-thing-adds-equipment-tag/148299/2?u=tuny
