### ISSUE TITLE
Trigger channels cant be assigned

### ISSUE THREAD

**Issue by PottiMc** [openhab/openhab-webui#2005]
When I try to assign trigger channel in rules the channel popup will not open. It is showing the animation but no popup for selction is opening.
Tested on up to date Edge and Firefox.

Existing trigger channels in rules from version 3 are working but if you want to edit the channel its not working too.

![grafik](https://github.com/openhab/openhab-distro/assets/39881308/ac33ff7d-f35c-4198-ba72-880f35520237)

Openhab Version is 4.0.1

**Comment by PottiMc** [comment]
I guess my issue is related or similar to #1996 

Anyway, I found out it is possible to still use triggers when manually writing the code. The rule is working fine then.

Example:
`triggers:
  - id: "1"
    configuration:
      channelUID: homematic:HmIP-FCI1:xxx:1#BUTTON
    type: core.ChannelEventTrigger`

**Comment by Linux2fast** [comment]
The issue persists in OH4.0.1 on a Raspberry Pi4 even when the rule is manually written. The trigger is not triggered or found.
On OH 3.4.5 isn't the problem.

**Comment by Linux2fast** [comment]
I get the following issue if the trigger ist set manuel in "Code" section.
![image](https://github.com/openhab/openhab-webui/assets/37037689/357248ad-94ad-4407-be63-707c68368246)
That's the Code 
![image](https://github.com/openhab/openhab-webui/assets/37037689/746de194-b8f5-4d8d-a4ae-a7300b67cf31)
Have another User this Problem or a Solution for this Problem?
Thanks

**Comment by chrisonline** [comment]
> I get the following issue if the trigger ist set manuel in "Code" section. ![image](https://user-images.githubusercontent.com/37037689/261075832-357248ad-94ad-4407-be63-707c68368246.jpeg) That's the Code ![image](https://user-images.githubusercontent.com/37037689/261075952-746de194-b8f5-4d8d-a4ae-a7300b67cf31.jpeg) Have another User this Problem or a Solution for this Problem? Thanks

You need to add the channelUID to the code manually (example of a hue device):
```
configuration: {}
triggers:
  - id: "1"
    configuration:
      thingUID: hue:device:ecb5fafffe179ad8:05b2b64a-44ee-4bbc-bd07-90130907e920
      channelUID: hue:device:ecb5fafffe179ad8:05b2b64a-44ee-4bbc-bd07-90130907e920:button-last-event
    type: core.ChannelEventTrigger
```

This line: "channelUID: hue:device:ecb5fafffe179ad8:05b2b64a-44ee-4bbc-bd07-90130907e920:button-last-event", but you need to change it to you your channelUID and event.
