### ISSUE TITLE
[blockly] contextual info block with quantity loses connection to Qty block

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-webui#2008]
## The problem

I am trying to use the Quantity selection of the contextual info block.

I can connect the contextual info block in a quantity or quantity match block. When I look at the code, the generated javascript looks good. However, the connection is lost when going back to the blockly view.

The following gif illustrates the problem.

![chrome_TE4xhshbBF](https://github.com/openhab/openhab-webui/assets/23501634/1d919b32-7937-4ded-947d-c41278d890eb)

## Expected behavior

Connection should be saved.

## Your environment

```yaml
runtimeInfo:
  version: 4.0.1
  buildString: Release Build
locale: nl-BE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.7
  javaVendor: Raspbian
  osName: Linux
  osVersion: 6.1.21-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 217701432
  totalMemory: 656318464
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-GB
    languages:
      - en-GB
      - en
      - nl
      - nl-BE
      - en-BE
      - en-US
      - nl-NL
      - fr
      - de
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/115.0.0.0 Safari/537.36
timestamp: 2023-08-07T14:28:10.443Z
```
