### ISSUE TITLE
Widget f7-Card is blurred after fade-in in Fixed Canvas Pages

### ISSUE THREAD

**Issue by neuling10** [openhab/openhab-webui#2017]
## The problem
Widgets with f7-card-content doesn't focus in fade-in mode and popups only blurred on fixed canvas pages
![image](https://github.com/openhab/openhab-webui/assets/124717762/c9bfa040-febc-446f-bd3b-9fa71e831572)
  

## Expected behavior
After clicking on the widget (fade-in), the content should appear clear and not blurry. Responsive layouts works perfectly. Fixed layouts doesn't work.

## Steps to reproduce
Tested UI Widget:
"Camera: Live feed with PTZ controls" from community marketplace

Tested Page:
Layout with Fixed Canvas Layout

## Your environment

```yaml
runtimeInfo:
  version: 3.4.5
  buildString: Release Build
locale: de-AT
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.18
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 219814304
  totalMemory: 705691648
  startLevel: 100
bindings:
 ...
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: simple
    homeBackground: default
    expandableCardAnimation: disabled
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
timestamp: 2023-08-11T15:59:03.544Z
```

## Browser console
![image](https://github.com/openhab/openhab-webui/assets/124717762/f9f1692d-8bc8-42a1-89f0-7cbe40b3c789)

```txt

```
