### ISSUE TITLE
Display error of group items since update to 4.0.1

### ISSUE THREAD

**Issue by Michi1983** [openhab/openhab-webui#2025]
## Which UI are you reporting an issue for?

- [X] Basic UI

## The problem

Since the update to OpenHAB 4.0.1, items that are defined as a group in the sitemap are no longer displayed correctly, the control elements are missing for all items except one and that is some times a different one.

![image](https://github.com/openhab/openhab-webui/assets/59232100/adbebb98-c89e-4af9-b79f-e59330cc6df9)

The bug does not occur with all controls that are included as a group, here with the shutters it fits.
![image](https://github.com/openhab/openhab-webui/assets/59232100/ef1096a9-3d3e-4015-8d2b-6231db2e8575)

## Expected behavior

It should be possible to adjust the temperature at each temperature display.

## Steps to reproduce

The problem occurs all the time.

Code snippet of the sitemap
```php
Frame label="Heizung"
    {
        Group item=gTemperatur_ist
        Switch item=gTemperatur_soll mappings=[16="OFF"]
        Group item=gTemperatur_soll
    }
```

Code snippet of the group
```csv
Group:Number:Temperature:AVG gTemperatur_soll "Wohnung Temperatur soll [%.1f °C]" <temperature> (gWohnung)

Group  gHeizung_Wohnzimmer "Wohnzimmer" (gWohnEsszimmer) {alexa="Endpoint.Thermostat"}
Number:Temperature Temperatur_soll_Wohnzimmer "Soll Temperatur Wohnzimmer [%.1f °C]" <heating> (gTemperatur_soll, gHeizungWohnzimmerGraph, gHeizung_Wohnzimmer) ["Setpoint", "Temperature"] {alexa="ThermostatController.targetSetpoint", channel="homematic:HmIP-BWTH:CCU:000C98A99DD55C:1#SET_POINT_TEMPERATURE"}

Group  gHeizung_Bad "Bad" {alexa="Endpoint.Thermostat"}
Number:Temperature Temperatur_soll_Bad "Soll Temperatur Bad [%.1f °C]" <heating> (gBad, gTemperatur_soll, gHeizungBadGraph, gHeizung_Bad) {alexa="ThermostatController.targetSetpoint", channel="homematic:HmIP-BWTH:CCU:000C98A99DD273:1#SET_POINT_TEMPERATURE"}

Group  gHeizung_Kinderzimmer "Kinderzimmer" {alexa="Endpoint.Thermostat"}
Number:Temperature Temperatur_soll_Kind "Soll Temperatur Kinderzimmer [%.1f °C]" <heating> (gKinderzimmer, gTemperatur_soll, gHeizungKindGraph, gHeizung_Kinderzimmer) {alexa="ThermostatController.targetSetpoint", channel="homematic:HmIP-BWTH:CCU:000C98A994B78C:1#SET_POINT_TEMPERATURE"}

Group  gHeizung_Kueche "Küche" {alexa="Endpoint.Thermostat"}
Number:Temperature Temperatur_soll_Kueche "Soll Temperatur Küche [%.1f °C]" <heating> (gKueche, gTemperatur_soll, gHeizungKuecheGraph, gHeizung_Kueche) {alexa="ThermostatController.targetSetpoint", channel="homematic:HmIP-BWTH:CCU:000C98A9A96B9F:1#SET_POINT_TEMPERATURE"}

Group  gHeizung_Schlafen "Schlafen" {alexa="Endpoint.Thermostat"}
Number:Temperature Temperatur_soll_Schlafen "Soll Temperatur Schlafzimmer [%.1f °C]" <heating> (gSchlafzimmer, gTemperatur_soll, gHeizungSchlafenGraph, gHeizung_Schlafen) {alexa="ThermostatController.targetSetpoint", channel="homematic:HmIP-BWTH:CCU:000C9A499B493A:1#SET_POINT_TEMPERATURE"}

Group  gHeizung_Buero "Büro" {alexa="Endpoint.Thermostat"}
Number:Temperature Temperatur_soll_Arbeit "Soll Temperatur Büro [%.1f °C]" <heating> (gBuero, gTemperatur_soll, gHeizungBueroGraph, gHeizung_Buero) {alexa="ThermostatController.targetSetpoint", channel="homematic:HmIP-BWTH:CCU:000C9A499B4944:1#SET_POINT_TEMPERATURE"}
```
## Your environment

```yaml
runtimeInfo:
  version: 4.0.1
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 174390656
  totalMemory: 455081984
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 3277
    height: 1728
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203
timestamp: 2023-08-17T16:47:17.975Z
```
