### ISSUE TITLE
Main UI rule triggers when click edit rule if trigger is set to "when system has reached level 70"

### ISSUE THREAD

**Issue by marioschouten** [openhab/openhab-webui#2027]
## The problem
When I'm editing rules in the Main-UI normally when you click on  "Execute a given script" it opens the script so you can edit it. This behaviour is different when the rule has the trigger "when the system has reached level 70". In that case it runs the rule and you need to click several times to be able to open the scrip to edit, ~~when you save it, it runs the rule again~~
![image](https://github.com/openhab/openhab-webui/assets/49558628/cd695126-c6a1-4475-b482-eac0e29d1aed)

## Expected behavior
When editing ~~/saving~~ a rule it should not start the rule, only when saving or manually starting the rule.

## Steps to reproduce

1. Create a rule with trigger "when the system has reached level 70" in OH 4.0.2

## Your environment

```

runtimeInfo:
  version: 4.0.2
  buildString: Release Build
locale: en-TH
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.8
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-11-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 307486416
  totalMemory: 1507852288
  startLevel: 70
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
      - th-TH
      - th
      - nl-NL
      - nl
    onLine: true
    platform: Win32
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: disabled
    bars: light
    homeNavbar: simple
    homeBackground: standard
    expandableCardAnimation: disabled
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/116.0.0.0 Safari/537.36
timestamp: 2023-08-19T04:50:42.334Z

```

## Browser console

```txt

```
