### ISSUE TITLE
Minor navigation problems in add-on store

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-webui#2028]
## The problem

Whenever I reload the "Other Add-ons" page or when using the browser navigation buttons to go to the previous page and go back to it, I'm redirected to the "Binding" page.

## Expected behavior

Reload into the "Other Add-ons" page as expected.

## Steps to reproduce

1. Enter to the Main UI go to "Conguration / Other Add-ons".
2. Reload the page using the browser button.
3. You are in the "Configuration / Bindings" section instead. 

## Your environment

```yaml
runtimeInfo:
  version: 4.0.2
  buildString: Release Build
locale: es-ES
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 5.10.110-rockchip-rk3588
  osArchitecture: aarch64
  availableProcessors: 8
  freeMemory: 142442032
  totalMemory: 440401920
  startLevel: 70
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1440
    height: 900
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/16.2 Safari/605.1.15
timestamp: 2023-08-19T09:52:04.982Z
```
