### ISSUE TITLE
Initial setup wizard no longer works

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#2052]
## The problem

When doing a fresh setup of OH 4.1.0-SNAPSHOT, after entering the admin username/password, I see `An error occurred while getting authorization: TypeError: Cannot read properties of undefined (reading 'router')`:

![Screenshot from 2023-09-02 22-37-34](https://github.com/openhab/openhab-webui/assets/12213581/8615d947-3abc-4610-9b41-d1f18d55a122)

The setup can be completed after manually navigating to: http://localhost:8080/setup-wizard/

## Expected behavior

Normally after entering the admin username/password it shows:

![Screenshot from 2023-09-03 09-10-59](https://github.com/openhab/openhab-webui/assets/12213581/8d454294-0243-434b-bcb1-cbdad25659fb)

## Steps to reproduce

1. Create a brand new openHAB instance
2. Navigate to the UI in your browser
3. Enter the admin username/password

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3614"
locale: en-us
systemInfo:
  configFolder: /home/wouter/software/openhab/instance/conf
  userdataFolder: /home/wouter/software/openhab/instance/userdata
  logFolder: /home/wouter/software/openhab/instance/userdata/logs
  javaVersion: 17.0.8
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-17.0.8+7
  osName: Linux
  osVersion: 6.2.0-31-generic
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 142720096
  totalMemory: 285212672
  startLevel: 100
addons: []
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.100000023841858
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
      - nl
      - nl-NL
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/116.0.0.0 Safari/537.36
timestamp: 2023-09-03T07:12:46.038Z
```

## Browser console

```txt
app.f55bd6755f28d9b92b43.js:23 TypeError: Cannot read properties of undefined (reading 'router')
    at app.f55bd6755f28d9b92b43.js:23:249978
```
