### ISSUE TITLE
Main UI basic rules conditions: make it possible to compare two items

### ISSUE THREAD

**Issue by svenb1234** [openhab/openhab-webui#2056]
## The problem
It is not possible to compare two items as a condition without using a script.

![grafik](https://github.com/openhab/openhab-webui/assets/46424536/10ff0b24-6060-4031-a4c3-0521ef48abfc)

The UI just offers to enter a state to compare against.

Simple comparisons would e.g. compare two temperatures, i.e. if temperature a is greater or equal to temperature b.

## Your suggestion

Allow the user to pick a second item.

## Your environment

```yaml
runtimeInfo:
  version: 3.4.5
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.18
  javaVendor: Debian
  osName: Linux
  osVersion: 5.14.21-150500.55.19-default
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 359634864
  totalMemory: 490733568
  startLevel: 70
bindings:
  - astro
  - knx
  - sonos
  - viessmann
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101
    Firefox/116.0
timestamp: 2023-09-05T18:40:20.056Z

```
