### ISSUE TITLE
[Blockly] Variables do not work in Quantity block

### ISSUE THREAD

**Issue by Dash** [openhab/openhab-webui#2057]
Discussion on this issue where I was asked to raise this: https://community.openhab.org/t/uom-blockly-quantity-not-working-with-variable/149372

## The problem
When assigning using a variable in conjunction with the Quantity block:
![c73cc75e9d8478c9e1d81d19eb7fc7fc9d7928e0_2_690x181](https://github.com/openhab/openhab-webui/assets/129838/9291f12a-4e33-4a55-b834-d2ff023ed7f2)
The following code is generated:
![b10d225f95eab7b9a6c1e03d39ed2225de4ac482](https://github.com/openhab/openhab-webui/assets/129838/6eec71f3-cc17-4c30-b6eb-92803b69a12e)

## Expected behavior
Primarily I would expect this to work as adding a literal value to the Quantity function works just fine.  At the very least, if this isn't supported functionality then the Quantity function should disallow variables in the UI.

## Steps to reproduce

As above
1. Create a Blockly script
2. Create a variable
3. Assign a value to the variable (string is the most honest)
4. Use the variable as the first parameter for the Quantity block

## Your environment

```yaml
runtimeInfo:
  version: 4.0.2
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.8
  javaVendor: N/A
  osName: Linux
  osVersion: 5.14.21-150400.24.81-default
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 335846760
  totalMemory: 778043392
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-GB
    languages:
      - en-GB
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101
    Firefox/116.0
timestamp: 2023-09-06T18:24:49.125Z

```

## Browser console

```txt

```
