### ISSUE TITLE
No picture with fixed grid layout and activated scaling

### ISSUE THREAD

**Issue by hamphh73** [openhab/openhab-webui#2060]
## The problem

When opening a page with grid layout and activated scaling over the url http://\<openhab\>/page/\<page\> the page ist not displayed. After changing the size of the browser window the page appears.  The error occurs after switching from version 3.4.5 to 4.0.3.

## Expected behavior

The page appears without resizing the browser window.

## Steps to reproduce

1. Create a new layout page
2. Switch to a fixed grid layout
3. Add a widget
4. Activate scaling in the grid layout configuration

## Your environment

```yaml
runtimeInfo:
  version: 4.0.3
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-11-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 750893800
  totalMemory: 1140850688
  startLevel: 70
addons:
  - automation-jsscripting
  - binding-astro
  - binding-homematic
  - binding-http
  - binding-icalendar
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-pushbullet
  - binding-tr064
  - persistence-influxdb
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-jsonpath
  - transformation-map
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 6
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/116.0.0.0 Safari/537.36
timestamp: 2023-09-10T19:51:59.468Z
```

## Browser console

No errors in the browser console

## Browser network traffic

![image](https://github.com/openhab/openhab-webui/assets/10182545/92266262-ea3f-4334-9312-7582c510379b)
