### ISSUE TITLE
[Blockly] Support testing if the context exists at all

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#2081]
## The problem

There are two conditions under which the `event` Object is `undefined`:

- manually triggered
- run from another rule

There are cases where knowing how the rule is triggered may change the behavior of the rule. For example, in my rule templates I treat a manual trigger to mean just check the config and report problems if there are any.

## Your suggestion

Add an "exists" option to the "contextual info" block that is `true` when `event` exists and `false` when `event` is `undefined`.

<img width="259" alt="image" src="https://github.com/openhab/openhab-webui/assets/6385096/a38f83b1-7dc1-46bb-b59c-abb74c159c57">

Then a user can test to see if `event` exists without errors. 

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0.M1
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 5.15.0-83-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 837787224
  totalMemory: 1579155456
  uptime: 156570
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-astro
  - binding-chromecast
  - binding-http
  - binding-ipcamera
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-roku
  - binding-shelly
  - binding-vesync
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
  - voice-googletts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
timestamp: 2023-09-21T16:14:13.724Z

```

## Additional information

This could be used as part of a proposed work around for the slow first execution of rules by writing a rule that runs at startup and runs other rules to get past that delay at the first run. But in order to avoid errors during startup there needs to be a way detect if `event` exists. 

https://community.openhab.org/t/blockly-rules-after-upgrade-to-oh-4-0-1-very-slow-on-the-first-run/148503/79

But it's useful outside of that use case as well.
