### ISSUE TITLE
[openhab-4] Equipment not visible after adding in the semantic model

### ISSUE THREAD

**Issue by ThaDaVos** [openhab/openhab-webui#2102]
## The problem
After adding equipment, for example in my case I try to add the DSMR binding Electricity Meter to my Home location object in the my semantic model - it does not show up in the model - it does show if I click on the location and open it's card. This used to work in Openhab 3 but seems broken since Openhab 4.

A second thing I noticed - almost always after this issue occuring - the search on the Items page is broken too and I need a CTRL-Refresh to get it working again.

![Recording 2023-10-01 at 15 16 08](https://github.com/openhab/openhab-webui/assets/5251028/aabb62d7-8e26-4db0-af17-3bc4e378f716)

## Expected behavior
The equipment being added to the model, visible and all - also the search not breaking.

## Steps to reproduce

1. Go to semantic model
2. Make sure there are already some locations
3. Add `Equipment from Thing`

## Your environment
I saw it's not included in the yaml - but I am running it as a Docker Container with the `openhab/openhab:snapshot` image currently (issue is also on `latest` and `milestone` tags)

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3653"
locale: en-NL
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 6.2.0-33-generic
  osArchitecture: amd64
  availableProcessors: 6
  freeMemory: 112623376
  totalMemory: 580911104
  uptime: 3741
  startLevel: 100
addons:
  - automation-jsscripting
  - automation-jsscriptingnashorn
  - binding-avmfritz
  - binding-dsmr
  - binding-gpstracker
  - binding-lgwebos
  - binding-remoteopenhab
  - binding-rfxcom
  - binding-shelly
  - binding-sonos
  - persistence-influxdb
  - persistence-mapdb
  - transformation-bin2json
  - transformation-exec
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-rollershutterposition
  - transformation-scale
  - transformation-vat
  - transformation-xpath
  - transformation-xslt
  - voice-mimictts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: nl
    languages:
      - nl
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1707
    height: 1067
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101
    Firefox/119.0
timestamp: 2023-10-01T13:20:39.762Z

```

## Browser console
Since upgrading to milestone the error `this.item.groupType is undefined` is gone - but this was an error I saw inside the console

```txt
N/A
```

## Additional information
https://community.openhab.org/t/oh4-semantic-model-create-equipment-from-thing-adds-equipment-tag/148299/16
