### ISSUE TITLE
Javascript support of Widgets not up to par with Javascript Scripting Automation

### ISSUE THREAD

**Issue by ThaDaVos** [openhab/openhab-webui#2121]
## The problem
It seems that when working on the widgets, they do not support the `.numericState` and `.quantityState` options of the items (maybe many more new properties) - I thought they did as it could remedy the old ugly check `.displayState` and then check `.state` code - but `.numericState` always returns undefined

Checking the item returned from `items` gives only the `state` and `type` values (see second screenshot below

![afbeelding](https://github.com/openhab/openhab-webui/assets/5251028/da770663-96b5-4420-aaab-32a0d4c876fe)

![afbeelding](https://github.com/openhab/openhab-webui/assets/5251028/b07b2eb4-4f49-4736-bc83-85741bfab3a1)

## Expected behavior

Or full Javascript support - or at least access to these new properties to ease the creation of Widgets now we have UoM

## Steps to reproduce

1. Just try to acccess the `.numericState` inside the `Widgets Expression Tester` for a UoM used item

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3662"
locale: en-NL
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 6.2.0-33-generic
  osArchitecture: amd64
  availableProcessors: 6
  freeMemory: 419641488
  totalMemory: 832569344
  uptime: 258197
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-avmfritz
  - binding-dsmr
  - binding-gpstracker
  - binding-kostalinverter
  - binding-lgwebos
  - binding-remoteopenhab
  - binding-rfxcom
  - binding-shelly
  - binding-solaredge
  - binding-sonos
  - persistence-influxdb
  - persistence-mapdb
  - transformation-bin2json
  - transformation-exec
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-rollershutterposition
  - transformation-scale
  - transformation-vat
  - transformation-xpath
  - transformation-xslt
  - voice-mimictts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: nl
    languages:
      - nl
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101
    Firefox/119.0
timestamp: 2023-10-09T09:39:21.502Z

```

## Browser console

```txt
N/A
```
