### ISSUE TITLE
OH4.1.0M2: Developer Sidebar edit and unpin icon missing on pinned items

### ISSUE THREAD

**Issue by EngiNearEngiFar** [openhab/openhab-webui#2133]
## The problem
With the newest milestone build the unpin and edit icons are missing in the view. See item DS_TEST here:
![grafik](https://github.com/openhab/openhab-webui/assets/83063002/a8f47b7c-a785-40b7-988f-254c1c827c68)

## Expected behavior

Unpin and edit icon should be visible. Like it is for rules or things. See printscreen above. 

## Steps to reproduce

1. Open Developer Sidbar and pin an item. 

## Your environment

```
runtimeInfo:
  version: 4.1.0.M2
  buildString: Milestone Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.8.1
  javaVendor: Private Build
  osName: Linux
  osVersion: 6.1.11-meson64
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 305771136
  totalMemory: 1073741824
  uptime: 173671
  startLevel: 70
```

## Additional information
The problem was not there on the previous releases of OH4. See also here: 
https://community.openhab.org/t/oh-4-1-0m2-developer-sidebar-edit-pinned-items/150265
