### ISSUE TITLE
Add other item as source for dynamic icon state in sitemap

### ISSUE THREAD

**Issue by tylla** [openhab/openhab-webui#2147]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

Currently the dynamic icon feature in the sitemap is restricted to use the state of the item in question. While this is perfect for simple cases, and some can be solved with the visibility property, but there are lots of complex situations that cannot be satisfied.

## Your suggestion

I would suggest another parameter - e.g. icon_item or something like this - to be able to specify the origin of the state to be used for the icon.
So for example something like follows could be used:
```
Text item=custom_combined_rain_and_wind "Last rainfall and current wind [%s]" icon="windrose" icon_item=custom_wind_direction
```
where
```
custom_combined_rain_and_wind="Rain: 4 mm Wind: 13 km/h (270°)"    //generated via rules from other three items
custom_wind_direction=75    //created via rules from other item, normalized to the 0-99 range
```
This would display an entry with a variable text and an icon showing the current wind direction.
OTOH it would deliver a really flexible solution to be used in several other cases where compact interfaces need to be created.

## Your environment

```yaml
runtimeInfo:
  version: 4.0.0
  buildString: Release Build
locale: en-HU
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.6
  javaVendor: Debian
  osName: Linux
  osVersion: 5.10.0-22-amd64
  osArchitecture: amd64
  availableProcessors: 6
  freeMemory: 224257640
  totalMemory: 880803840
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en
    languages:
      - en
      - en-US
      - en-GB
      - hu
      - hu-HU
      - de-DE
      - de
      - fr-FR
      - fr
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
timestamp: 2023-10-21T23:09:08.983Z

```

## Additional information

I hope that I did not misplaced this feature request, and I did not slipped over an already existing one - I tried to search thoroughly.
If any questions arise I'm more than happy to elaborate further.
