### ISSUE TITLE
Widget functions and constants

### ISSUE THREAD

**Issue by JustinGeorgi** [openhab/openhab-webui#2148]
There has been an interesting discussion on the forums about [how best to reduce the repetition of long expressions and improve readability and maintainability of complex widgets yaml](https://community.openhab.org/t/substitutions-in-widgets/150303).

That discussion has led me to propose the addition of a new widget component: a component that just adds to the widget context.  Like the `oh-repeater` , this widget would not, itself, be rendered but would inject evaluated objects into the context available to its child components.

Initially, I see this component as giving the widget creator the capability of using both functions and constants in widget expressions.  Here are some usage examples:

I have a widget which uses multiple numbers that I want rounded to the nearest 0.25. For every location in the widget where I want one of these values I can write out the expression:
```
text: =Math.round(Number.parseFloat(@@'ThisNumberItem') * 4) / 4
```
But with a context component that provided functions, I could define this once:
```
- component: oh-context
  config:
    functions:
      near25: =(i) => Math.round(Number.parseFloat(@@i) * 4) / 4
  slots:
    default:
      - component: f7-card
        config:
          title: =func.near25('ThisNumberItem')
...
```

I think constants could have the potential to be even more useful. First, because there are many more common situations where they could be used and second because they can themselves be objects.

Many complex widgets are built around the idea that the items involved have a naming structure that is some base item + an additional identifier. These are often then set in the props of a widget and used something like this:
```
textColor: =(@@(props.item + props.mode) == 'HEAT')?('rgb(255,67,0)'):('rgb(37,37,255)')
```
Constants, evaluated only at widget mounting, would allow for these constructions to be much more readable:
```
- component: oh-context
  config:
    constants:
      iMode: =props.item + props.mode
  slots:
    default:
      - component: f7-card
        config:
          textColor: =(@@(const.iMode) == 'HEAT')?('rgb(255,67,0)'):('rgb(37,37,255)')
```

In the UI docs, there a brief example of how to use objects in the widget expressions to select among several options.  Although it is shorter and more clear than the nested ternary statements, it can still get long and awkward:
```
textColor: =({'heat':'orange','cool':'blue','auto':'green','off':'white'})[@@hvacModeItem] || 'red'
```
With the ability to define a constant object this cleans up very nicely:
```
- component: oh-context
  config:
    constants:
      backColor:
        heat: orange
        cool: blue
        auto: green
        off: white
  slots:
    default:
      - component: f7-card
        config:
          textColor: =const.backColor[@@hvacModeItem] || 'red'
```

Is this worth pursuing further?

Edit:
It is worth noting, as I point out in the thread linked above, that by "misusing" an `oh-repeater` this capability is already mostly available.  The addition of a dedicated component for it would just formalize this and allow for it to be optimized.
