### ISSUE TITLE
Syntax validation errors when command mappings contain special characters like [ and ]

### ISSUE THREAD

**Issue by happenpappen** [openhab/openhab-webui#2149]
## The problem

When editing a sitemap in openHAB 4.0.3 in the code view, i get the same error as described in this issue:

https://github.com/openhab/openhab-webui/issues/748

A screenshot showing this:

![grafik](https://github.com/openhab/openhab-webui/assets/1398876/542cf818-46ee-44ab-9f8c-bbe94fc1880a)

When adding " around the special characters, the errors are fixed until i edit the sitemap in the code view again.

## Expected behavior

The code view should keep the added " signs.

## Steps to reproduce

1. Create a new sitemap with this code:

sitemap page_7376626e53 label="New Sitemap" {
  Switch item=test mappings=[TEXT="[=]", SUBTITLE="[_]"]
}

2. Save and close it.
3. Re-open the sitemap and switch to the code view.

## Your environment

```yaml
runtimeInfo:
  version: 4.0.3
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.8.1
  javaVendor: Private Build
  osName: Linux
  osVersion: 5.15.0-86-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 321543632
  totalMemory: 1778384896
  startLevel: 100
addons:
  - automation-groovyscripting
  - automation-jsscripting
  - binding-airquality
  - binding-astro
  - binding-avmfritz
  - binding-deconz
  - binding-dwdpollenflug
  - binding-dwdunwetter
  - binding-ecovacs
  - binding-enigma2
  - binding-exec
  - binding-gpstracker
  - binding-homeconnect
  - binding-http
  - binding-icalendar
  - binding-kodi
  - binding-lgwebos
  - binding-mpd
  - binding-mqtt
  - binding-network
  - binding-ntp
  - binding-openweathermap
  - binding-playstation
  - binding-rfxcom
  - binding-shelly
  - binding-smartmeter
  - binding-snmp
  - binding-sonos
  - binding-systeminfo
  - binding-tankerkoenig
  - binding-tr064
  - binding-unifi
  - binding-zwave
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-mapdb
  - transformation-bin2json
  - transformation-exec
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-scale
  - transformation-xpath
  - transformation-xslt
  - ui-basic
  - ui-habot
  - ui-habpanel
  - voice-marytts
  - voice-picotts
  - voice-porcupineks
  - voice-voicerss
  - voice-voskstt
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0)
    Gecko/20100101 Firefox/118.0
timestamp: 2023-10-23T07:51:25.234Z
```

## Browser console

```txt

```
