### ISSUE TITLE
Humidity values in percentage on location card are rendered incorrectly for the badge

### ISSUE THREAD

**Issue by FSeidinger** [openhab/openhab-webui#2161]
## Humidity values in percentage on location card are rendered incorrectly for badge and details

Given is an item defined to hold a humidity value. Then the item is rendered correctly in different places:

![image](https://github.com/openhab/openhab-webui/assets/4890418/cd781a6b-522e-4c3c-b02d-7462825790ce)
![image](https://github.com/openhab/openhab-webui/assets/4890418/091d74fe-b8de-4ef7-8529-8d4880c35bff)
![image](https://github.com/openhab/openhab-webui/assets/4890418/338be5b6-3f98-403b-a815-935c10b5c675)

But is not rendered correctly for the badge in the location card:

![image](https://github.com/openhab/openhab-webui/assets/4890418/c4ddeaa1-912c-4b84-8b75-672a868a0961)
![image](https://github.com/openhab/openhab-webui/assets/4890418/471991e0-b343-4154-8663-33a9c5ebe824)

Here the value shows up as 1 %. Looks like it is wrongly scaled and tries to show 0.59 rounded up as 1 %.

But again rendered correctly in the details of the location card:

![image](https://github.com/openhab/openhab-webui/assets/4890418/f1c54f98-faa6-4ffd-bda4-0ea8b26fe69e)

## Expected behavior

The badge value should be rendered as 59 %.

## Steps to reproduce

Define an item like as a dimensionless number:

```
label: Wohnzimmer Luftfeuchtigkeit
type: Number:Dimensionless
category: humidity
groupNames:
  - Wohnzimmer_Klima
  - Zentralfunktionen_Persistenz_Stuetzpunkte_Haeufig
groupType: None
function: null
tags:
  - Measurement
  - Humidity
```

with a State description formatting it as a percentage value:

```
value: " "
config:
  pattern: "%d %%"
  readOnly: true
```

1. Open the openHAB main ui
2. Switch to the location card
3. Look at the badge of the humidity value
4. Click on the card
5. Look at the badge of the humidity value

## Your environment

```yaml
runtimeInfo:
  version: 4.0.3
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.8.1
  javaVendor: Private Build
  osName: Linux
  osVersion: 5.15.0-87-generic
  osArchitecture: amd64
  availableProcessors: 1
  freeMemory: 144854240
  totalMemory: 515899392
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-homematic
  - binding-icalendar
  - binding-knx
  - binding-lgwebos
  - binding-mqtt
  - binding-samsungtv
  - binding-unifi
  - binding-yamahareceiver
  - misc-openhabcloud
  - persistence-jdbc-postgresql
  - persistence-mapdb
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-scale
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 16
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
      - it-IT
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/119.0.0.0 Safari/537.36
timestamp: 2023-11-03T17:28:12.286Z
```

## Browser console

```txt

```

## Browser network traffic

![image](https://github.com/openhab/openhab-webui/assets/4890418/9b2ee472-3073-4326-aacf-594d546f150e)
![image](https://github.com/openhab/openhab-webui/assets/4890418/4f161489-f60f-4bc3-9897-64db2590da30)
