### ISSUE TITLE
MainUI not showing current item value

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-webui#2167]
## The problem

An item has a current value, but it is not shown on the item page in MainUI. It is shown in the item list, though.

<img width="900" alt="Bildschirmfoto 2023-11-12 um 11 05 33" src="https://github.com/openhab/openhab-webui/assets/5159123/69272cf4-2ddd-4d60-b694-ee2d6e412bc4">
<img width="1005" alt="Bildschirmfoto 2023-11-12 um 11 05 22" src="https://github.com/openhab/openhab-webui/assets/5159123/3e98718a-e57a-4dd9-b6b5-96db56a43f22">
<img width="832" alt="Bildschirmfoto 2023-11-12 um 11 04 49" src="https://github.com/openhab/openhab-webui/assets/5159123/6646fab5-4050-4283-86c9-5d8909e8cd52">

## Expected behavior

Current item value is also shown on the item page.
 
## Steps to reproduce

see above 

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3716"
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-17.0.9+9
  osName: Linux
  osVersion: 6.1.0-13-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 550067632
  totalMemory: 1023410176
  uptime: 73561
  startLevel: 100
 clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
    onLine: true
    platform: MacIntel
  screen:
    width: 1512
    height: 982
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/17.1 Safari/605.1.15
timestamp: 2023-11-12T10:10:26.970Z
```

## Browser network traffic

<img width="998" alt="Bildschirmfoto 2023-11-12 um 11 12 52" src="https://github.com/openhab/openhab-webui/assets/5159123/536795ef-eb3e-4f0b-8ef3-cd6bdaedbc38">

## Additional information

Same situation with chrome, so it doesn't seem to be a browser issue.
