### ISSUE TITLE
[Rule Templates]MainUI should generate an error dialog if required properties are left blank

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#2172]
## The problem

Rule templates can have required properties. When the user instantiates a rule based on a template but neglects to fill in all the required properties a blank rule is created.

## Expected behavior

An error dialog pops up similar to the one that pops up if you neglect to give the rule a name.

## Steps to reproduce

1. Install a rule template from the marketplace (this was discovered with [org.openhab.core.items.ItemLookupException](https://www.openhab.org/javadoc/latest/org/openhab/core/items/itemlookupexception)](https://community.openhab.org/t/delay-start-4-0-0-0-4-9-9-9/144884).
2. Instantiate a rule from the template only entering a name for the rule. Do not choose anything for the "Rules" property
3. Save the rule and observe that the rule is blank.

If on step 2 the "Rules" property is filled in then the rule will be created with the expected contents. 

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0.M3
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 5.15.0-88-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 361010864
  totalMemory: 1153433600
  uptime: 7968
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-astro
  - binding-chromecast
  - binding-http
  - binding-ipcamera
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-roku
  - binding-shelly
  - binding-vesync
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
  - voice-googletts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
timestamp: 2023-11-16T16:59:58.241Z
```

## Browser console

I do not see anything relevant in the Console.

## Browser network traffic

I don't see anything relevant there but will provide if given some direction on what to look for.

## Additional information

Nothing gets sent to openhab.log either.
