### ISSUE TITLE
UI rendering/scaling of logos for suggested add-ons

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-webui#2205]
## The problem

The UI looks like this:

![image](https://github.com/openhab/openhab-webui/assets/19519842/0e2522b0-5cef-448c-b216-d1d26fbb37a8)

## Expected behavior

Are the logos rendered this large intentionally? It looks a bit strange compared to the section below with smaller logos.

## Steps to reproduce

Go to the Add-on Store page.

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3760"
```

## Browser console

```txt

```

**Comment by lolodomo** [comment]
Look at #1668

**Comment by jlaur** [comment]
Should we close this issue then? Additional questions before creating a separate issue:
- Should the suggestions be ordered, for example alphabestically?
- Should already installed add-ons be suggested?

![image](https://github.com/openhab/openhab-webui/assets/19519842/8723527f-a04f-4608-af58-52475b7f79a9)

Cc @florian-h05, @mherwege

**Comment by mherwege** [comment]
There are actually 3 categories: Suggested, Featured and all others. Featured is hard coded in the UI. The size of the logo’s for suggested is the same as for the Featured category.
I think the whole representation of the suggestions could improve. @holgerfriedrich also pointed it out.
Maybe there should even be a separate tab for suggestions, tab to automatically show.
Another aspect is search in the store (criteria like country and connection are now available).
I am inclined to create a separate issue and group all add-on store UI feature request in that. Actually, @holgerfriedrich already kind of volunteered to create one. I can look into developing after 4.1.

**Comment by jlaur** [comment]
You might consider also checking/closing #2050 and #2170 if they would become redundant when creating new issue.

**Comment by florian-h05** [comment]
I have created #2216 as a proposal to adjust the logo size. You can see several previews in my second comment, just expand it.

> Maybe there should even be a separate tab for suggestions, tab to automatically show.
Another aspect is search in the store (criteria like country and connection are now available).
I am inclined to create a separate issue and group all add-on store UI feature request in that. Actually, @holgerfriedrich already kind of volunteered to create one. I can look into developing after 4.1.

Sound really good! Now that we have add-on data available even if the add-on is not installed, there are many more possibilities for filtering etc.

**Comment by jlaur** [comment]
@florian-h05 - is the PR that closed this issue related? Just checking - because this difference in size still looks kind of strange to me, like it's not intentional that suggested addons are this big?

![image](https://github.com/user-attachments/assets/88d2bc4f-ebc3-4a72-8d8e-598d512afa6c)

**Comment by florian-h05** [comment]
What is your device and OS?

**Comment by jlaur** [comment]
> What is your device and OS?

Sorry, this is Chrome version 130.0.6723.70 running in Windows 10.

**Comment by florian-h05** [comment]
Can you please tell me your snapshot version and the Main UI commit? Both can be found on the about page.

**Comment by jlaur** [comment]
> Can you please tell me your snapshot version and the Main UI commit? Both can be found on the about page.

openHAB 4.3 snapshot build 4356, i.e. from yesterday. I'll be back with Main UI commit in the evening.

**Comment by jlaur** [comment]
openHAB 4.3.0
Build 4357
Main UI Commit 36b578a4

**Comment by florian-h05** [comment]
I cannot reproduce this with the same UI version on Windows 11 with Chrome 130.0.6723.92.
Can you please share About -> Technical Information? (You need to be logged in)

**Comment by florian-h05** [comment]
I cannot reproduce as well on Windows 10 Chromium 130 with browserstack.

<details>

<summary>Technical Information</summary>

```
runtimeInfo:
  version: 4.3.0
  buildString: "Build #4336"
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 21.0.5
  javaVendor: Red Hat, Inc.
  javaVendorVersion: (Red_Hat-21.0.5.0.11-1)
  osName: Linux
  osVersion: 6.11.4-201.fc40.x86_64
  osArchitecture: amd64
  availableProcessors: 16
  freeMemory: 120169680
  totalMemory: 645922816
  uptime: 8365
  startLevel: 100
addons:
  - automation-jsscripting
  - misc-homekit
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2048
    height: 1536
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/130.0.0.0 Safari/537.36
timestamp: 2024-11-01T21:07:51.938Z
```

</details>

Have you tried to reload the app and clear cache?

**Comment by jlaur** [comment]
Sorry for giving you such incremental and lacking information. I guess I somehow assumed it was easy to reproduce. 😊 I have now tried to clear cache, which did not help. Did you mean reload browser, or which app do you refer to?

I have tried in Firefox now as well:

![image](https://github.com/user-attachments/assets/cef49a18-96ea-4fec-bd13-576fe4d8c0fc)

Resized:

![image](https://github.com/user-attachments/assets/2448e0d9-1227-4d39-a675-e1777cf17f7f)

Maybe it's related to resizing when window becomes quite large in size?

**Comment by ghys** [comment]
Since the "featured" add-ons cards are now in a horizontal swiper maybe we could give an upper limit to their size, the goal was to give enough space to be able to display most titles above unabridged (or "not too abridged").

Clearly the logos are getting too big when the screen size increases from what I see.
The "sweet spot" I found in the former 3.4 add-on store was 150px, which was also convenient because I could reuse this component for UI widgets add-ons which have screenshots instead of logos (and you want them bigger).

![image](https://github.com/user-attachments/assets/5d9190c4-d320-4158-a519-d5ec62a98200)

![image](https://github.com/user-attachments/assets/3478b63b-349c-40dd-b0d8-8a6eaaa11697)

**Comment by ghys** [comment]
Maybe we could introduce a newly-designed component for these "featured" add-ons, something like:

![](https://www.apple.com/newsroom/images/2023/11/apple-unveils-app-store-award-winners-the-best-apps-and-games-of-2023/article/Apple-Store-Awards-2023-iPhone-App-of-the-Year-AllTrails_inline.jpg.large.jpg)

**Comment by florian-h05** [comment]
> Since the "featured" add-ons cards are now in a horizontal swiper maybe we could give an upper limit to their size

They are only in the swiper on mobile.

> Clearly the logos are getting too big when the screen size increases from what I see.

The CSS for desktop logos hasn’t changed, this is what makes me wonder what’s going wrong in Jacob’s Main UI. It looks like the UI somehow renders the swiper component, which should not happen on desktop or on iPad.
@jlaur Can you please share the technical information from the about page when the issue happens?

**Comment by florian-h05** [comment]
#2859 improves sizing behavior and adds a safeguard for the case that the swiper is rendered on desktop and renders a single add-on, in that case now the add-on card size is limited in its width.

**Comment by jlaur** [comment]
> Can you please share the technical information from the about page when the issue happens?

```
runtimeInfo:
  version: 4.3.0
  buildString: "Build #4357"
locale: da-DK
systemInfo:
  configFolder: C:\PROGRA~1\openHAB\conf
  userdataFolder: C:\PROGRA~1\openHAB\userdata
  logFolder: C:\PROGRA~1\openHAB\userdata\logs
  javaVersion: 17.0.8
  javaVendor: Oracle Corporation
  osName: Windows 10
  osVersion: "10.0"
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 178284288
  totalMemory: 390070272
  uptime: 38053
  startLevel: 70
addons:
  - automation-jsscripting
  - binding-astro
  - binding-deconz
  - binding-freecurrency
  - binding-harmonyhub
  - binding-sonos
  - binding-tradfri
  - persistence-inmemory
  - persistence-rrd4j
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: da
    languages:
      - da
      - en-US
      - da-DK
      - en-DK
      - en
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 1600
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/130.0.0.0 Safari/537.36
timestamp: 2024-11-02T23:17:18.802Z
```
