### ISSUE TITLE
Sticky Developer Sidebar

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-webui#2206]
## The problem

The Developer Sidebar is shown initially and it keeps reappearing on page refresh.

## Expected behavior

Is it intentionally shown initially (i.e. after installation)?
Is it intentionally shown after being hidden when refreshing the page?

I would hope that it is possible to hide it so that it won't be shown again until requested using the (Shift+Alt+D) shortcut.

## Steps to reproduce

Hide the Developer Sidebar.
Refresh the page.

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3760"
locale: da-DK
systemInfo:
  configFolder: C:\PROGRA~1\OPENHA~1\conf
  userdataFolder: C:\PROGRA~1\OPENHA~1\userdata
  logFolder: C:\PROGRA~1\OPENHA~1\userdata\logs
  javaVersion: 17.0.8
  javaVendor: Oracle Corporation
  osName: Windows 10
  osVersion: "10.0"
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 120730968
  totalMemory: 394264576
  uptime: 844
  startLevel: 100
addons: []
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: da
    languages:
      - da
      - en-US
      - da-DK
      - en-DK
      - en
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 1600
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/120.0.0.0 Safari/537.36
timestamp: 2023-12-08T14:59:00.120Z
```

## Browser console

```txt

```
