### ISSUE TITLE
[MainUI] Rule template for wrong version is shown

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2228]
## The problem

Using openHAB 4 I can see the following rule template in the market place:
![grafik](https://github.com/openhab/openhab-webui/assets/22525368/a67f0f1a-4a46-4f31-98a9-4a8741b2bbdc)

## Expected behavior

It's not shown.

## Steps to reproduce

1. Open market place

## Your environment

```yaml
runtimeInfo:
  version: 4.0.4
  buildString: Release Build
locale: de-DE
```
