### ISSUE TITLE
oh-slider-item scale showing wrong value

### ISSUE THREAD

**Issue by osztrovszky** [openhab/openhab-webui#2235]
## oh-slider-item scale showing wrong value

oh-slider-item scale showing wrong value but it jumps to the correct one if I resize the window.
oh-slider-card works fine.

Scale is also wrong in Android client.

https://youtu.be/lUoCswyJfJw

## Expected behavior

scale showing correct value

## Steps to reproduce

main ui:
```
- component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: oh-list-card
                      config: {}
                      slots:
                        default:
                          - component: oh-slider-item
                            config:
                              item: itemwithvalue
                              max: 23
                              min: 16
                              step: 0.5
                              releaseOnly: true
                              scale: true
                              label: false
```

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: Release Build
locale: en-HU
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.9
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-11-amd64
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 244188392
  totalMemory: 429916160
  uptime: 69876
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-chromecast
  - binding-mikrotik
  - binding-mqtt
  - binding-shelly
  - binding-telegram
  - binding-unifi
  - persistence-rrd4j
  - transformation-jsonpath
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
      - hu
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
timestamp: 2023-12-26T19:18:16.984Z


```
