### ISSUE TITLE
charts: ability to refer to (persisted) items matching in time in expressions

### ISSUE THREAD

**Issue by ewaldc** [openhab/openhab-webui#2241]
## The problem
A simple addon (that I developed) publishes 2 channels mapped to items:
- PVPC_Rate_Now (Number:Energy)
- PVPC_Is_Rate_Cheap_Now (Switch ON/OFF proxy for boolean)

It's currently impossible to create a simple chart that displays PVPC_Rate_Now with color 'green' when PVPC_Is_Rate_Cheap_Now is true/ON and color 'red' otherwise: 
```
  series:
    - component: oh-time-series
      config:
        name: Rate
        gridIndex: 0
        xAxisIndex: 0
        yAxisIndex: 0
        type: bar
        item:  PVPC_Rate_Now
        color: '= items.PVPC_Is_Rate_Cheap_Now.state  === "ON" ? "Green" : "Red"'
        on: true
```
does not yield the desired result, since `PVPC_Is_Rate_Cheap_Now` refers to its current/last state rather than its matching state in time.
See [community topic](https://community.openhab.org/t/oh4-chart-change-color-of-item-in-series-based-on-value-of-another-persisted-item-matching-in-time/152405)

## Your suggestion
Extend expressions to be able to refer to a historical item with matching timestamp for use in charts e.g.
```
color: '=  items.PVPC_Is_Rate_Cheap_Now.matchingState()=== "ON" ? "Green" : "Red"'
```
where matchingState picks up the timestamp from the current series timestamp/slot.

## Your environment
Openhab 4.04 Linux ARM64

## Additional info
Happy to contribute a PR, but would appreciate some guideance on what would be an acceptable approach and where to start.
Unless of course there is another way to solve this problem.

**Comment by florian-h05** [comment]
Hi @ewaldc,

I am trying to understand how that `matchingState()` should be calculated as a chart displays a time range and in that time range your Item may have several different states. Which state is chosen then?

And second, I don't think this can be implemented through widget expressions, because I don't see a way of passing in data from the chart components into the widget expression evaluator (timestamp).

If this is implemented, I'd rather expect it to work through some ECharts options, maybe https://echarts.apache.org/en/option.html#series-line.colorBy?

**Comment by ewaldc** [comment]
Hello @florian-h05, 
I appreciate someone looking at this, I had already given up on it.
In my example, PVPC stands for the Spanish "voluntary small consumer price" which is an hourly rate for electric current.  So every hour of the day, I log the hourly rate for electricity (PVPC_Rate_Now) as it is published at 9PM. Then with some logic I calculate whether that hourly price is cheap (green), expensive (red) or average (orange) and store that in PVPC_Is_Rate_Cheap_Now and PVPC_Is_Rate_Expensive_Now.  So now I want a simple daily graph that lists the hourly price as bars, but colors those bars green, orange or red.   There is this great "color' feature for graph bars, but somehow it can only refer to the very latest value of the variable and not the corresponding one in time.  So "matchingState" would refer to the value of that variable at the same point in time as the main item/element of the chart series.
For example, I would like it to be as follows:
At 7AM, price is 8 cents which is cheap. So I want that bar reflecting the 8 cent but colored green
At 8AM, price is 16 cent, which is expensive, hence I want that bar colored red (and twice as high as the 7AM one)

Now it is as follows: suppose we are 9PM now, the price is 9 cents then (cheap), so "PVPC_Is_Rate_Cheap_Now" is "True". Accordingly when the chart is opened at that time, all bars in the current day (and next day) will be colored green as "PVPC_Is_Rate_Cheap_Now.state" reflects only the last/current value (value at time === NOW).  So the idea of the ".matchingState" qualifier is to refer to the value of "PVPC_Is_Rate_Cheap_Now" as taken from the exact same point in time as the series element itself.  

I know that the data when persisted is already there and the "color" logic is also already there.  The chart logic also knows the points in time, in this case hourly, as it fetches the PVPC_Is_Rate from the persisted data. 

At some point in time I was able to get it working (v3.x) but as I wanted to check it in as PR, 4.0 came out and had some different code and then 4.04 and 4.10 came with yet more changed code, and I was unable to catch up.

Now to your questions:
-  " in that time range your Item may have several different states. Which state is chosen then?"
 The value of PVPC_Is_Rate_Cheap_Now at the exact same time as the series item (in this case matching hour)
- "I don't see a way of passing in data from the chart components into the widget expression evaluator (timestamp)."
If I recall well, from how I coded it, it is no different than passing "items.PVPC_Is_Rate_Cheap_Now.state".

Something like:
for i = 0 to 23 (hours) -> get item at time i -> evaluate color for item at time i -> get value for PVPC_Is_Rate_Cheap_Now but at not at time === NOW but at time === i -> pass that value to color expression evaluator

Does that help ?

**Comment by florian-h05** [comment]
> At 7AM, price is 8 cents which is cheap. So I want that bar reflecting the 8 cent but colored green
At 8AM, price is 16 cent, which is expensive, hence I want that bar colored red (and twice as high as the 7AM one)

I assume these thresholds are the same for the whole day, correct?
In that case, you can simply add a piecewise visualmap:

```yaml
  visualMap:
    - component: oh-chart-visualmap
      config:
        show: true
        type: piecewise
        pieces:
          - gt: 150
            label: High Price
            color: "#ff0000"
          - lte: 150
            label: Low Price
            color: '#00ff00'
```

<img width="1011" height="1051" alt="Image" src="https://github.com/user-attachments/assets/5c25e4f0-6ca0-463b-a13c-2525d39d732a" />

You may also use expressions for the `gt`, `gte`, `lt`, `lte` thresholds, so you can "decide" every day what would be a high and a low price.

> "I don't see a way of passing in data from the chart components into the widget expression evaluator (timestamp)."
If I recall well, from how I coded it, it is no different than passing "items.PVPC_Is_Rate_Cheap_Now.state".

But that refers to the current state. If you want the matching persisted state of `PVPC_Is_Rate_Cheap_Now`, you need the timestamp from ECharts, and according to its documentation (https://echarts.apache.org/en/option.html#series-bar), color doesn't accept functions, so no callback functionality.
We could implement some kind of expression specific to charts that allows the color property of a series to provide an expression that is then evaluated for each entry in the `item` series and the result of the evaluation is set as color property of each data Item.
But that would be quite complex, so if the above visualmap works for you, that would be great.

> for i = 0 to 23 (hours) -> get item at time i -> evaluate color for item at time i -> get value for PVPC_Is_Rate_Cheap_Now but at not at time === NOW but at time === i -> pass that value to color expression evaluator

The `color` property would also accept an array, with an entry for each bar. However with your approach, again I see the problem that if expressions could access persistence, we still need to think of a way of passing to the expression what time range is currently selected.

**Comment by ewaldc** [comment]
Hallo @florian-h05,
Thanks for the suggestion.  Yes, for any given day I calculate these in the code of my PVPC binding.  It's a formula based on standard deviation/average from the lowest and highest values:
```
double PVPC_Is_Rate_Cheap_Now= avg - (0.5 * std);
double PVPC_Is_Rate_Expensive_Now= avg + (0.5 * std);
```
 but once calculated, they are a constants for the day.  But then somehow I would need to generate the chart code on a daily basis as these constants will change daily.  I guess that I could send YAML code to the REST API and update it daily using "ScheduledExecutorService" or similar.
On the other hand, I was quite surprised that OH graphs can't refer to historic data in formula's, hence my suggestion for a item extension called ".matchingState()" (versus ".state()" which refers to the actual/lastest value).  I guess that is why many (power) users switch to grafana.  
I do know that a custom widget would have been another alternative, but still, these are quite complex solutions for a rather simple use case.  Lately I was coding an extension for my weather station and I was hitting the same problem with things like months that have more/less rain than average etc.  (echarts seems to have _average()_ calculation now).  All these requires conditions that are able to leverage persisted data in formula's.  

I am happy to help with the coding efforts and post a PR, but wanted some guidance from the OH development team on:
1. does my use case (use of historal/persistent data in chart formula's) make sense ?
2. if so, are there alternative (but simple) ways to achieve this ?
3. how to best code it (and avoid doing wasted work). 

I noticed echarts has a "dimension/pieces" function now. Maybe with a persistent PVPC_PriceCategory (0= cheap, 1, average, 2, expensive) and something like:
```
config:
  label: Historical PVPC Analysis
  # Add a dataset to fetch both items simultaneously from persistence
  dataset:
    - source:
        - item: PVPC_Price
        - item: PVPC_PriceCategory 
components:
  - component: oh-chart-visualmap
    config:
      type: piecewise
      # Dimension 2 refers to the 3rd element: [time, price, category]
      dimension: 2 
      pieces:
        - value: 0
          label: Cheap
          color: "#91cc75"
        - value: 1
          label: Average
          color: "#fac858"
        - value: 2
          label: Expensive
          color: "#ee6666"
  - component: oh-time-series
    config:
      name: Electricity Price
      type: bar
      datasetIndex: 0
      encode:
        x: 0 # Time
        y: 1 # Price
```
