### ISSUE TITLE
4.1 Sitemap warnings: Syntax error in labelcolor rule condition '' for widget Text

### ISSUE THREAD

**Issue by Dash** [openhab/openhab-webui#2244]
## The problem

Since upgrading to 4.1, I've been receiving log spam for sitemaps (viewing and saving).  Example:

````
2023-12-29 15:14:38.665 [WARN ] [omponents.UIComponentSitemapProvider] - Syntax error in labelcolor rule condition '' for widget Text
2023-12-29 15:14:50.654 [WARN ] [omponents.UIComponentSitemapProvider] - Syntax error in valuecolor rule condition '' for widget Text
````

A message occurs for every instance of an unqualified/default colour being set in either the label or value colour field for a sitemap.  The warning is not displayed when an expression is used first.

## Expected behavior

A simple colour entry is valid and should not cause warnings to be logged.

## Steps to reproduce

1. Create a sitemap with an item's label or value colour simply as "red" (with or without quotes), save and review the log.
2. Load the sitemap through the UI or mobile app, review the log.

### Example sitemap with issue:

````
sitemap page_c6c037636f label="New Sitemap" {
    Text item=KitchenLights label="Lights are: [%s]" valuecolor=["red"]
}
````

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: N/A
  osName: Linux
  osVersion: 5.14.21-150500.55.39-default
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 232432104
  totalMemory: 1055916032
  uptime: 6063
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-exec
  - binding-gpstracker
  - binding-http
  - binding-icalendar
  - binding-mqtt
  - binding-network
  - binding-onkyo
  - binding-renault
  - binding-snmp
  - binding-systeminfo
  - binding-xmppclient
  - persistence-rrd4j
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: true
    webview: true
    standalone: true
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 12
    language: en-GB
    languages:
      - en-GB
      - en
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 2160
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
timestamp: 2023-12-29T16:52:06.319Z

```

Forum reference: https://community.openhab.org/t/openhab-4-1-release-discussion/152252/83?u=dash
