### ISSUE TITLE
[blockly] Length UoM comparisons fail to convert

### ISSUE THREAD

**Issue by Dash** [openhab/openhab-webui#2252]
## The problem

When using Blockly to compare a dimension of length with a Quantity and a different Unit of Measurement, strange things happen.  I'm not sure the extent of the problem, but my scenario is specifically: I have an item of type length, it currently stores a value of 251000 metres.

I have an if block, comparing the value with a check to see if the value is less than X miles, using the Quantity block and "mi" as the UoM.
![image](https://github.com/openhab/openhab-webui/assets/129838/ad736bca-e939-4f5b-9bcb-2255fc913b72)

When I set this to 25 miles, the condition evaluates as false, when I set it to 26, it evaluates to true.  Despite 251,000 metres being ~156 miles.  To further complicate things, when I try 100 mi, it evaluates to false. 🥴

## Expected behavior

I expect that when using the documented UoM in Quantities, that I can do comparisons that make any sort of sense.

## Steps to reproduce

1. Create an item of type Number:Length
2. Assign it a value (I used 251,000 metres, I haven't tried other values)
3. Create a blockly script and do a comparison against the state of the item, using a Quantity block and miles as the UoM
4. Watch the world burn

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: N/A
  osName: Linux
  osVersion: 5.14.21-150500.55.39-default
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 301118760
  totalMemory: 1236271104
  uptime: 285303
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-exec
  - binding-gpstracker
  - binding-http
  - binding-icalendar
  - binding-mqtt
  - binding-network
  - binding-onkyo
  - binding-renault
  - binding-snmp
  - binding-systeminfo
  - binding-xmppclient
  - persistence-rrd4j
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 2.25
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: en-GB
    languages:
      - en-GB
      - en
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1707
    height: 1067
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
timestamp: 2024-01-01T22:26:14.776Z

```
