### ISSUE TITLE
After update to OH4 item selector is not working anymore (Uncaught (in promise) parseerror)

### ISSUE THREAD

**Issue by boehla** [openhab/openhab-webui#2258]
## The problem

Recently updated from Openhab 3.3.0 to 4.1.0. Worked pretty straightforward.
But now I wanted to edit a Label on a Page, but the item selector popup is not working anymore:

![image](https://github.com/openhab/openhab-webui/assets/460994/e4239c20-4453-4c09-89bd-e756da6908f6)
When I click nothing happens. (also no additional error added in console)

Edit the page in textmode is working.

Is it because of the weird error in the console?
"Uncaught (in promise) parseerror" What does this error means??

Same thing for "Items to Analyze" popup.

In the log viewer I don't see any (related) error.

## Expected behavior

Item selector popup should open.

## Steps to reproduce

I could reproduce the problem with an empty page.

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: Release Build
locale: en-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: Private Build
  osName: Linux
  osVersion: 5.4.0-169-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 226458816
  totalMemory: 717225984
  uptime: 1384
  startLevel: 70
addons:
  - automation-jsscripting
  - automation-pidcontroller
  - binding-astro
  - binding-daikin
  - binding-deconz
  - binding-fronius
  - binding-goecharger
  - binding-http
  - binding-modbus
  - binding-mqtt
  - binding-network
  - binding-shelly
  - binding-snmp
  - persistence-rrd4j
  - transformation-jsonpath
  - transformation-map
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - de-AT
      - de
      - en-AT
      - it-IT
      - it
      - sv-SE
      - sv
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/120.0.0.0 Safari/537.36
timestamp: 2024-01-07T06:30:55.965Z

```
