### ISSUE TITLE
Add-on settings header displayed in settings page when there's no add-on

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-webui#2266]
## The problem

When there is no add-on installed the "Add-on settings" header is still displayed:

![image](https://github.com/openhab/openhab-webui/assets/2004147/96e526d8-9f36-409d-acd4-839750c27963)

## Expected behavior

Should not display section headers with no content.

## Your environment

```yaml
runtimeInfo:
  version: 4.2.0
  buildString: "Build #3832"
```

## Browser console

Irrelevant.

## Browser network traffic

Irrelevant.

## Additional information

N/A
