### ISSUE TITLE
Unable to pick non-semantic items in rules if they have metadata

### ISSUE THREAD

**Issue by Proton23** [openhab/openhab-webui#2268]
## The problem

I opened up a thread on the openhab forum which describes the [problem](https://community.openhab.org/t/in-rules-unable-to-pick-non-semantic-items-if-they-have-metadata/152834).
While creating a rule I was not able to pick non-semantic items with metadata as shown in my posting.

## Expected behavior

Every item should be pickable. 

## Your environment

```
runtimeInfo:
  version: 4.1.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 322376336
  totalMemory: 629145600
  uptime: 537665
  startLevel: 100
addons:
  - automation-jsscripting
  - automation-jsscriptingnashorn
  - binding-amazonechocontrol
  - binding-astro
  - binding-exec
  - binding-gardena
  - binding-homematic
  - binding-ipcamera
  - binding-modbus
  - binding-mqtt
  - binding-network
  - binding-openweathermap
  - binding-shelly
  - binding-tplinksmarthome
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-rrd4j
  - transformation-jsonpath
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 16
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/120.0.0.0 Safari/537.36
timestamp: 2024-01-14T01:25:10.484Z

```
