### ISSUE TITLE
[Blockly] Support blocks that create variables

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#2324]
## The problem

I'm working on a Block library and some of the blocks I want to create need to create a variable that the end user can see and use in their own blocks. Think of something like a `for loop` where the index variable needs to be accessible inside of the body of the loop. 

Through reading, experimentation, and trial and error I've found that if I include a `field_variable` it will generate the variable as desired. It even shows up under "Variables" in the blocks menus which is fantastic. 

```
        args0:
          - type: field_variable
            name: VAR_NAME
            variable: item
```

However, I cannot actually access this new variable's name in my generated code.

Looking at the code: https://github.com/openhab/openhab-webui/blob/e18a057ffdab4b2869980fdbb69f810113317bbe/bundles/org.openhab.ui/web/src/assets/definitions/blockly/libraries.js#L50 it seems the proper way to reference this field is using `{{field:VAR_NAME}}`. However, that appears to return the randomly generated `id` (e.g. `:Qdtlf+vg4rV7iO!.0yX`, not the `name` (e.g. `i`). 

## Your suggestion

I am not familiar enough with this code to understand what `block` looks like on the line:

    context.fields[placeholderName] = block.getFieldValue(placeholderName)

Clearly, the `fieldValue` is different for `field_variable` compared to a `field_dropdown` in how it stores the value. I don't have the knowledge nor skills to figure out the class definition of `block` to see what is possible or not on a live system. From looking at the reference for `Block` I think using `block.getField()` might return the variable name. It also might just return the field name (e.g. `VAR_NAME` from above).

Looking at the JSON from the Advanced Blockly Playground hints that there is a separate "variables" section.

```
{
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "controls_forEach",
        "id": "HJ5_3bM=emwf-c6noKH;",
        "x": 212,
        "y": 338,
        "fields": {
          "VAR": {
            "id": "1K,V(0,NN!f9h$3DZCzN"
          }
        }
      }
    ]
  },
  "variables": [
    {
      "name": "j",
      "id": "1K,V(0,NN!f9h$3DZCzN"
    }
  ]
}
```

So I think the [VariableMap](https://developers.google.com/blockly/reference/js/blockly.variablemap_class) is what needs to be used but I cannot find any reference that calls `generateCodeBlock(block)` so I can't tell if the `VariablesMap` is available to pass when that function is called. 

Assuming the `VariablesMap` is available I'd propose the following:

1. Add a new placeholder `{{variable:VARNAME}}`
2. add the following code to `processPlaceholder`, assuming the `VariableMap` is passed into `generateCodeForBlock` as `varMap` (which is the part I have yet figured out how it works).

```
        case 'variable':
          context.vars[placeholderName] = varMap.getVariableById(block.getFieldValue(placeholderName).name
          return code.replace(placeholder, context.vars[placeholderName])
```

Maybe it makes sense to call it a `fieldvar` instead of `variable` to make it clear that the scope is more narrow than just any old variable. 

But what I'm lost on is figuring out where generateCodeForBlock is called and whether the `VariableMap` is available to pass to it. I'll continue to look but it's hard to follow the code backwards given the way it's structured (not a complaint, I just don't have the basics down yet so don't know how to effectively search).

## Your environment

```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.9
  javaVendor: Debian
  osName: Linux
  osVersion: 5.15.0-92-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 460250768
  totalMemory: 1732247552
  uptime: 68263
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-astro
  - binding-chromecast
  - binding-http
  - binding-ipcamera
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-shelly
  - binding-vesync
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
  - voice-googletts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 1
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1503
    height: 1047
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
timestamp: 2024-02-07T17:44:10.641Z
```

## Additional information

I'm trying to have a block that generates code along the lines of 

```
var item;

var OHRT = (() => {
  const ohrt = require('openhab_rules_tools');
  ohrt.helpers.validateLibraries('4.1.0', '2.0.3');
  return ohrt;
})();

// {{fieldvar:VAR_NAME}} gets replaced with "item" and {{statements:FILTER}} uses "item"
OHRT.membersToMappedList('MyItem', ({{fieldvar:VAR_NAME}}) => { {{statements:FILTER}} }, ...
```
