### ISSUE TITLE
Charts and date

### ISSUE THREAD

**Issue by JensHauser** [openhab/openhab-webui#2351]
## The problem

When I zoom into this diagram quite deeply, the time format changes from 24h to 12h format in my installation. I think that shouldn´t be like that. Data is coming from MariaDB, if that is of any help.

Expected behaviour:
![d3224c12a195c5c3f9efb522f3e9a2c70bcd8d70_2_690x392](https://github.com/openhab/openhab-webui/assets/44340656/c5a9fcf4-d5e4-4f9a-9313-efc371b0bc6a)

Same diagram, zooming into shows a change to 12h format
![496bf91491f4854c71c3a176f55c3119b07da9e0_2_690x288](https://github.com/openhab/openhab-webui/assets/44340656/a9590e3f-6657-4388-9830-0a7fc24b605a)

The change occurs, if seconds are visible.

## Expected behavior
24h format on all zoom levels

## Steps to reproduce
https://community.openhab.org/t/charts-and-date-issue/153816/3

## Your environment
```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.10
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-18-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 203860376
  totalMemory: 994050048
  uptime: 134503
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-dwdunwetter
  - binding-km200
  - binding-knx
  - binding-modbus
  - binding-mqtt
  - binding-networkupstools
  - binding-ntp
  - binding-openweathermap
  - misc-openhabcloud
  - persistence-jdbc-mariadb
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101
    Firefox/122.0
timestamp: 2024-02-13T10:56:26.776Z
```

## Browser console
Didn´t work with developer tools in my browser so far. It´s Firefox 122.0.1/W10
