### ISSUE TITLE
Allow oh-repeater in oh-chart components: grid, xAxis, yAxis, series, oh-chart-tooltip, dataZoom, and others

### ISSUE THREAD

**Issue by proggprod** [openhab/openhab-webui#2361]
## The problem

I can't use oh-repeater to propagate components of oh-chart

## Expected behavior

The oh-chart components should accept oh-repeater in the slots.

I should be able to create a list of charts with the following code that looks like this:
![image](https://github.com/openhab/openhab-webui/assets/81530084/1ba6b290-92ae-4f7a-8b56-491194fcc629)

```
uid: motionHistory_repeatertest
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Feb 16, 2024, 12:45:25 PM
component: f7-card
config:
  noShadow: true
slots:
  default:
    - component: oh-chart
      config:
        period: 6H
      slots:
        grid:
          - component: oh-repeater
            config:
              for: grids
              sourceType: itemsInGroup
              groupItem: gAll_MotionLightSensor_Motion
            slots:
              default:
                - component: oh-chart-grid
                  config:
                    top: =50 + (loop.grids_idx * 20)
                    left: 120
                    right: 20
                    height: 20
        xAxis:
          - component: oh-repeater
            config:
              for: xAx
              sourceType: itemsInGroup
              groupItem: gAll_MotionLightSensor_Motion
            slots:
              default:
                - component: oh-time-axis
                  config:
                    gridIndex: =loop.xAx_idx
                    axisLabel:
                      show: false
                    axisTick:
                      show: false
        yAxis:
          - component: oh-repeater
            config:
              for: yAx
              sourceType: itemsInGroup
              groupItem: gAll_MotionLightSensor_Motion
            slots:
              default:
                - component: oh-value-axis
                  config:
                    gridIndex: =loop.yAx_idx
                    name: =loop.yAx.label
                    nameGap: -20
                    position: left
                    offset: 10
                    nameTextStyle:
                      align: right
        series:
          - component: oh-repeater
            config:
              for: series
              sourceType: itemsInGroup
              groupItem: gAll_MotionLightSensor_Motion
            slots:
              default:
                - component: oh-time-series
                  config:
                    gridIndex: =loop.grids_idx
                    xAxisIndex: =loop.xAx_idx
                    yAxisIndex: =loop.yAx_idx
                    type: line
                  slots:
                    markArea:
                      - component: oh-mark-area
                        config:
                          item: =loop.series.name
```

## Additional information

Mentioned here 
https://community.openhab.org/t/oh-repeater-not-working-for-oh-time-series-in-oh-chart/123392/3
https://community.openhab.org/t/colored-graph-support-for-switch-contact-and-text-items/141024
https://community.openhab.org/t/oh-chart-multiple-switch-items-timeline-widget/153947
