### ISSUE TITLE
[mainui] Non-existing url generated in browser address bar

### ISSUE THREAD

**Issue by seime** [openhab/openhab-webui#2394]
## The problem

When navigating in MainUI, a non-existant URL is generated by the UI. When doing browser reload, the URL is not found and an error page is shown:

<img width="804" alt="CleanShot 2024-02-23 at 08 07 24@2x" src="https://github.com/openhab/openhab-webui/assets/1565156/caa65678-fa87-4fed-8d68-77f14cb50cb7">

## Expected behavior

The browser address field is populated only with URLs that exists.

## Steps to reproduce

1. Open `Settings` -> `Things`and choose any `Thing` with at least one channel that is linked to an existing `Item`
2. Click on `Channels` tab, choose any channel and click on the linked item: 
![CleanShot 2024-02-23 at 08 10 39@2x](https://github.com/openhab/openhab-webui/assets/1565156/71f6bcbe-47ca-49bc-9b91-b0b8c582ffd2)
You are taken to a page like 
<img width="718" alt="CleanShot 2024-02-23 at 08 12 58@2x" src="https://github.com/openhab/openhab-webui/assets/1565156/399c20fb-679e-48e0-bdf7-e3d68b54ea3c">

3. In the browser, reload the page -> *Page not found*

## Your environment

```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: en-NO
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
timestamp: 2024-02-23T07:15:46.836Z

```

## Browser console

No messages
