### ISSUE TITLE
[main ui] not possible to select semantic class "none" on creation of point

### ISSUE THREAD

**Issue by svenb1234** [openhab/openhab-webui#2429]
## The problem

If one creates a point from the model tree, it is not possible to select "none" as semantic class. If one edits the point after that, it is possible.

No "none" in the list for sematic class:
![grafik](https://github.com/openhab/openhab-webui/assets/46424536/e97ada4c-cee2-4756-9d75-d4d0b1ab5d76)

"None" is available as semantic class type in the edit dialogue:
![grafik](https://github.com/openhab/openhab-webui/assets/46424536/2d5d971d-92bd-4f9e-95f2-f5b1b9c843e3)

## Expected behavior
Always show "none" in the list of semantic classes.

## Steps to reproduce
1. Create a point and open the list for semantic class
2. Save the point with any available class
3. Edit the point and open the semantic class list

## Your environment
```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.9
  javaVendor: Debian
  osName: Linux
  osVersion: 5.14.21-150500.55.49-default
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 254359112
  totalMemory: 616562688
  uptime: 433127
  startLevel: 70
addons:
  - automation-jsscripting
  - binding-astro
  - binding-knx
  - binding-sonos
  - persistence-rrd4j
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101
    Firefox/123.0
timestamp: 2024-02-28T20:51:22.547Z
```
