### ISSUE TITLE
"An error occurred while creating the items: Bad Request"

### ISSUE THREAD

**Issue by winnall** [openhab/openhab-webui#2444]
## The problem
I'm trying to set up a new OH4 instance from scratch. Whilst trying to add items to the semantic model, I keep on getting the following error message in a pop-up: "An error occurred while creating the items: Bad Request". This has the potential to win the "Most Unhelpful Message of the Year" award :-)

<img width="395" alt="Screenshot 2024-03-03 at 22 44 40" src="https://github.com/openhab/openhab-webui/assets/5444565/690f2a31-fbfb-4d3a-8292-da5a5461a289">

## Expected behavior

I would expect some helpful text enabling the user to start correcting the error. Purely by chance, I discovered that such a text is actually generated in the log file:

`2024-03-03 22:02:37.453 [WARN ] [rest.core.internal.item.ItemResource] - Received HTTP PUT request with an invalid item name '2nd_Floor_Zone'.
`

Why not output it as well in the pop-up?

## Steps to reproduce

The problem seems to be that OH4 doesn't like item names that begin with a digit. In this case I was importing things automatically discovered by the Hue bridge. Hue doesn't mind devices whose names start with a digit: OH4 is happy to import them but complains when you try to make items out of them.

## Your environment

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: Release Build
locale: en-CH
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.9
  javaVendor: Debian
  osName: Linux
  osVersion: 6.6.16-linuxkit
  osArchitecture: aarch64
  availableProcessors: 10
  freeMemory: 111029080
  totalMemory: 269484032
  uptime: 17254
  startLevel: 100
addons:
  - binding-hue
  - binding-nanoleaf
  - misc-homekit
  - misc-metrics
  - persistence-influxdb
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-GB
    languages:
      - en-GB
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
timestamp: 2024-03-03T22:03:24.731Z
```

## Browser console

```txt
???
```

## Additional information
This is a content and design issue, not a technical one.
