### ISSUE TITLE
Right padding on the main UI add-on store buttons

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-webui#2456]
## The problem

Seems like the buttons have lost their right padding on narrow screens in the add-on store:

![image](https://github.com/openhab/openhab-webui/assets/2004147/d3845979-de3b-44bc-b03a-0dfce69ac763)

## Expected behavior

Buttons with the right padding, like on wider screens:

## Steps to reproduce

![image](https://github.com/openhab/openhab-webui/assets/2004147/656c9b49-1476-4638-8826-6904a0ed92cc)

## Your environment

```yaml
runtimeInfo:
  version: 4.2.0
  buildString: "Build #3972"
locale: en-US
systemInfo:
  configFolder: /root/oh4/conf
  userdataFolder: /root/oh4/userdata
  logFolder: /root/oh4/userdata/logs
  javaVersion: 17.0.6
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu17.40+19-CA
  osName: Linux
  osVersion: 5.10.103-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 43826512
  totalMemory: 233177088
  uptime: 15251
  startLevel: 100
addons: []
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: true
    webview: true
    standalone: true
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
      - fr
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/110.0.0.0 Safari/537.36
timestamp: 2024-03-05T20:11:58.648Z

```

## Browser console

```txt

```

**Comment by florian-h05** [comment]
Can you please help me to reproduce that issue? I can neither reproduce it on my real phone nor with the browsers dev tool device simulator.

**Comment by ghys** [comment]
I have identified the problem, it seems to be this piece of CSS:
```css
.button {
    padding-left: 5px;
    padding-right: 0
}
```
Apparently it's been added to [`components/pagedesigner/sitemap/attribute-details.vue`](https://github.com/openhab/openhab-webui/pull/2193/files#diff-5b43a20d22809cd115c17f8be11b37f20e9718ac7e7b91db09564d468426bf27) in #2193:
https://github.com/openhab/openhab-webui/pull/2193/files#diff-9c486fe8694b36e1157920d405a6693f85c0d7bd12162a36780e4feeb970e05c

```html
<style lang="stylus">
.button
  padding-left 5px
  padding-right 0px
.input
  width inherit
</style>
```

When you don't add the "scoped" attribute to the style node in Vue 2, and redefine these global classes, they effectively have a global impact.
I don't trust the "scoped" attribute too much so when designing components I made sure I added some parent class to scope these kinds of change to this particular component.

cc @mherwege
