### ISSUE TITLE
Copy rule -> edit cron not working

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2460]
## The problem
When I copy a rule that contains a cron trigger and try to update the cron, it resets to "Every day 08:00".

The original rule:

````yaml
configuration: {}
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 0 6 ? * * *
    type: timer.GenericCronTrigger
[...]
````

## Steps to reproduce

![grafik](https://github.com/openhab/openhab-webui/assets/22525368/70d40797-7fc1-4f1f-822a-3ba950291138)

Looks good after copy:
![grafik](https://github.com/openhab/openhab-webui/assets/22525368/725e34d1-6efd-466d-8cef-86f2481645f0)

But when I click on the cron:
![grafik](https://github.com/openhab/openhab-webui/assets/22525368/c9a87c33-c739-4282-8c88-b4497f75335d)

## Your environment

```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: de-DE
```
