### ISSUE TITLE
Redundant "Changes have not been saved" dialog

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2462]
## The problem

When I want to delete a rule that I just changed, I get asked if I want to delete this rule (which is fine) and after that I get asked if I want to save unsaved changes. This seems redundant, because I just deleted the rule.

## Steps to reproduce

1. Edit a rule
2. Don't save it
3. Delete it

## Your environment

```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: de-DE
```
