### ISSUE TITLE
Decline addon suggestions

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2464]
## The problem

The addon store always suggests me the IPP binding. I don't need it, because a different binding already integrates my printer.

## Your suggestion

Add a new button "Ignore" next to the "Install" button to ignore this addon suggestion.

## Your environment

```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: de-DE
```
