### ISSUE TITLE
Changing Thing UID reverts to default

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#2469]
## The problem

When creating a new Thing and I change the randomly generated Thing UID, upon clicking on another field the UID I entered reverts to the randomly generated default. However, when actually saving the Thing it uses the UID I typed in.

## Expected behavior

The field retains the changed UID.

## Steps to reproduce

1. Create a new Thing
2. Edit the UID field
3. Click somewhere else on the form. Notice the UID reverted to the randomly generated one.
4. Save the Thing and notice that the UID used is actually the one you typed in.

## Your environment

```yaml
runtimeInfo:
  version: 4.2.0.M1
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.10
  javaVendor: Debian
  osName: Linux
  osVersion: 5.15.0-97-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 567651704
  totalMemory: 1205862400
  uptime: 4453
  startLevel: 100
addons:
  - automation-jsscripting
  - automation-jsscriptingnashorn
  - binding-amazonechocontrol
  - binding-astro
  - binding-chromecast
  - binding-http
  - binding-ipcamera
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-shelly
  - binding-vesync
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
  - voice-googletts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 1
    hardwareConcurrency: 2
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1439
    height: 1044
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: simple
    homeBackground: standard
    expandableCardAnimation: default
    blocklyRenderer: zelos
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
timestamp: 2024-03-12T16:01:12.687Z
```

## Browser console

Nothing of note

## Browser network traffic

No errors shown.

## Additional information

May be related to #2468
