### ISSUE TITLE
Unable to create a persistence configuration for all items

### ISSUE THREAD

**Issue by obones** [openhab/openhab-webui#2516]
## The problem

When adding a persistence configuration, we have a dialog that allows selecting to which group or item this configuration will apply:

![image](https://github.com/openhab/openhab-webui/assets/1314739/d26369d6-a059-443c-a2c0-770d3dda90c1)

Considering that adding a configuration for any item disables the default strategy, I was trying to create a configuration for every other item.

The code allows typing '*' as indicated in the documentation, but that UI does not allow to select "all items", short of checking all items individually and then excluding items added in the future.

## Expected behavior

There should be a way to say "all items" in this UI, maybe as a third option beneath the "select items" one.

## Steps to reproduce

1. Go to Settings
2. Click on your persistence layer
3. Click on "Persistence configuration" at the top
4. Add a configuraiton

## Your environment

```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: en-FR
systemInfo:
  javaVersion: 17.0.10
  javaVendor: N/A
  osName: Linux
  osArchitecture: amd64
addons:
  - automation-jsscripting
  - binding-astro
  - binding-http
  - binding-mqtt
  - binding-serial
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - ui-basic
  - ui-habot
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: fr
    languages:
      - fr
      - fr-FR
      - en
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: disabled
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101
    Firefox/124.0
timestamp: 2024-03-31T09:32:51.337Z
```

## Browser console

No details needed

## Browser network traffic

No details needed

## Additional information

None that I can think of.
