### ISSUE TITLE
Add a "Select all" button to inbox/things/rules

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2544]
## The problem

It can be cumbersome to approve multiple new Things in the inbox, because you have to click on "Select" and check every single new Thing.

## Your suggestion

Add a new button "Select all" to lists that already have a "Select" options, e.g. Things, Thing Inbox, Rules, Items, etc.:

![grafik](https://github.com/openhab/openhab-webui/assets/22525368/cc85e0dd-90d1-48ce-bd23-fc5859fc92f5)

## Your environment

```yaml
runtimeInfo:
  version: 4.1.2
  buildString: Release Build
```

## Additional information

This is similar to #901, but more general.
