### ISSUE TITLE
Tag of Rule cannot be deleted

### ISSUE THREAD

**Issue by Boldfor** [openhab/openhab-webui#2546]
## The problem

After having created a rule and included two tags, only the second tag can be deleted by clicking on the "x". The first tag, however, cannot be deleted anymore. When clicking on the "x", nothing happens.
![image](https://github.com/openhab/openhab-webui/assets/37384006/cbf4e651-4b66-4b4a-bd95-34563ae86061)

## Expected behavior

When being in "Edit"-mode of a rule, the first tag can be deleted by clicking on the "x" next to the tag.

## Steps to reproduce

So far I have not been able to reproduce this on another rule. However, I could provide logs of the unsuccessful attempt to remove the first tag if someone lets me know the log level.

## Your environment

```
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.9
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-rpi8-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 228846736
  totalMemory: 1065353216
  uptime: 509222
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-gardena
  - binding-homematic
  - binding-irobot
  - binding-mqtt
  - binding-systeminfo
  - binding-yamahamusiccast
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - transformation-xpath
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
timestamp: 2024-04-21T17:46:38.969Z
```

```yaml

```

## Browser console

```txt

```
