### ISSUE TITLE
Blockly: When loading a list with things, the list keeps changing randomly in the Blockly UI while adding more things

### ISSUE THREAD

**Issue by Boldfor** [openhab/openhab-webui#2552]
## The problem
When creating a list in blockly (in my case: with 30+ items), as I am adding things to the list, preceeding elements keep changing (see video).

This behavior is so prevailing, that it is impossible for me to define a list of all my things, as elements of the list constantly keep changing, and fixing it changes other entries throughout the list.

https://github.com/openhab/openhab-webui/assets/37384006/a56c2223-9e0f-4829-bec9-79a0afac684d

## Expected behavior
The list can be defined without items shifting that have been defined before.

## Steps to reproduce
Re-build the "create list"-blockly-code as seen in the video, and try adding a large (>10 items) number of things.

## Your environment
```
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.9
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-rpi8-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 372064752
  totalMemory: 1065353216
  uptime: 86531
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-gardena
  - binding-homematic
  - binding-irobot
  - binding-mqtt
  - binding-systeminfo
  - binding-yamahamusiccast
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - transformation-xpath
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
timestamp: 2024-04-29T15:01:27.150Z
```

## Browser console

```txt

```
