### ISSUE TITLE
Sitemap editor has a lot of unused space

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2574]
## The problem

Today I pulled the latest snapshot Docker image. The Sitemap editor wastes a lot of space:

![grafik](https://github.com/openhab/openhab-webui/assets/22525368/068e188b-ff6d-4214-b23e-79c80799b1e4)

I tried to reload without cache, but that didn't help.

## Steps to reproduce

1. Open Sitemap editor

## Your environment

```yaml
runtimeInfo:
  version: 4.2.0
  buildString: "Build #4075"
```

Firefox 125
