### ISSUE TITLE
[MainUI] rules list unresponsive when large number of Rules

### ISSUE THREAD

**Issue by jpg0** [openhab/openhab-webui#2593]
## The problem

I have a large number of rules (currently 697) and the rules list in the main UI is becoming unusable. It fails entirely on phones, and repeatedly hangs when scrolling on a (fast) laptop. The items list (which has more elements in it) is fine.

## Expected behavior

Rules list behaves the same way as items list.

## Steps to reproduce

1. Create a large number of rules
2. Try to view the list on a phone, or load on a laptop and scroll very quickly through the list

## Your environment

```yaml
runtimeInfo:
  version: 4.1.2
  buildString: Release Build
locale: en-AU
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.11
  javaVendor: Debian
  osName: Linux
  osVersion: 4.9.277-122
  osArchitecture: aarch64
  availableProcessors: 6
  freeMemory: 299810928
  totalMemory: 975175680
  uptime: 599275
  startLevel: 70
addons:
  - binding-astro
  - binding-fronius
  - binding-hpprinter
  - binding-icalendar
  - binding-melcloud
  - binding-mqtt
  - binding-openuv
  - binding-sonos
  - binding-surepetcare
  - binding-telegram
  - persistence-influxdb
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2.200000047683716
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 10
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1512
    height: 982
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
timestamp: 2024-05-29T03:20:56.017Z

```

## Browser console

```txt

```
