### ISSUE TITLE
oh-input calendarParams not working

### ISSUE THREAD

**Issue by SimonB27P** [openhab/openhab-webui#2604]
## The problem

Using the oh-input component with type: set to datepicker, calendarParams config properties are ignored by the component.

It has been suggested that the component is overwriting the f7 parameter options.

## Expected behaviour

calendarParams (or calendar-params) should enable you to specify a number of additional parameters for the datepicker widget such as dateFormat, closeOnSelect, locale, minDate etc as set out in the Framework7 documentation.  All of these parameters, if set, are ignored by the component.

## Steps to reproduce

Sample widget
```yaml
uid: datePicker
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Jun 7, 2024, 4:18:43 PM
component: f7-block
config: {}
slots:
  default:
    - component: oh-input
      config:
        type: date
        item: TestDate
        outline: false
        sendButton: true
        calendarParams:
          locale: en-GB
          dateFormat: d mmmm yyyy
          closeOnSelect: false
          monthSelector: false
```

The above code should change the date format and enable closeOnSelect but it does not

## Your environment

runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: Raspbian
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 133738184
  totalMemory: 419606528
  uptime: 1463327
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-enocean
  - binding-homematic
  - binding-hue
  - binding-samsungtv
  - binding-squeezebox
  - binding-zwave
  - misc-hueemulation
  - misc-openhabcloud
  - persistence-rrd4j
  - transformation-map
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 0.8955223880597015
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1429
    height: 1143
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101
    Firefox/125.0
timestamp: 2024-06-07T19:30:13.585Z

**Comment by florian-h05** [comment]
I have just checked the oh-input code, and indeed it is not possible to overwrite calendarParams defaults of oh-input, but your code example also has a minor problem:

`date` is a HTML5 input type that cannot be configured by setting calendarParams, these only apply for type `datepicker`:

```yaml
uid: datePicker
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Jun 27, 2024, 4:58:29 PM
component: f7-block
config: {}
slots:
  default:
    - component: oh-input
      config:
        type: datepicker
        item: TestDate
        outline: false
        sendButton: true
        calendarParams:
          locale: en-GB
          dateFormat: d mmmm yyyy
          closeOnSelect: false
          monthSelector: false
```

#2634 allows to overwrite the calendarParams defaults when using datepicker as input type, so your example should work.
