### ISSUE TITLE
sitemaps with 'AND' in visibilty can not be saved after editing in code tab

### ISSUE THREAD

**Issue by nolantern** [openhab/openhab-webui#2605]
## The problem
When I create a sitemap with the mainUI and use the `AND` operator in the visibility attribute, I can not save the sitemap after I edited it in the code tab. The "Sitemap updated" toast does not appear. If I reload the page, the version before my edits shows up.

## Expected behavior
I can save sitemaps that contain `AND` operators and have been edited in the code view of the mainUI.

## Steps to reproduce

1. Create a new sitemap
2. Add a Text widget
3. Add a visibility attribute with an `AND` operator
4. Go to the Code tab
5. Change anything using the Code tab (for example the name of a widget)
6. Try to save the sitemap

## Your environment

```yaml
runtimeInfo:
  version: 4.1.2
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu17.50+19-CA
  osName: Linux
  osVersion: 5.15.0-1053-raspi
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 509455240
  totalMemory: 801112064
  uptime: 1381719
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-modbus
  - binding-mqtt
  - binding-network
  - binding-openweathermap
  - binding-shelly
  - binding-tibber
  - binding-tradfri
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101
    Firefox/126.0
timestamp: 2024-06-11T18:36:14.579Z

```

## Browser console

Replaced my openhab address with `openhab.example.com`.
```txt
TypeError: e.config[o].forEach is not a function
    validateWidgets https://openhab.example.com/js/16.app.ac598e3ce6e035bd1153.js:1
    validateWidgets https://openhab.example.com/js/16.app.ac598e3ce6e035bd1153.js:1
    validateWidgets https://openhab.example.com/js/16.app.ac598e3ce6e035bd1153.js:1
    save https://openhab.example.com/js/16.app.ac598e3ce6e035bd1153.js:1
    click https://openhab.example.com/js/16.app.ac598e3ce6e035bd1153.js:1
    Ue https://openhab.example.com/js/app.ac598e3ce6e035bd1153.js:7
    n https://openhab.example.com/js/app.ac598e3ce6e035bd1153.js:7
    Ue https://openhab.example.com/js/app.ac598e3ce6e035bd1153.js:7
    $emit https://openhab.example.com/js/app.ac598e3ce6e035bd1153.js:7
    a https://openhab.example.com/js/app.ac598e3ce6e035bd1153.js:7
    a https://openhab.example.com/js/app.ac598e3ce6e035bd1153.js:7
    dispatchEvent https://openhab.example.com/js/app.ac598e3ce6e035bd1153.js:7
    onClick https://openhab.example.com/js/app.ac598e3ce6e035bd1153.js:7
app.ac598e3ce6e035bd1153.js:7:11689

```
