### ISSUE TITLE
[BasicUI] No timepicker in Firefox

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2645]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

There's no timepicker in Firefox as there's in Chrome:

Chrome:
![grafik](https://github.com/openhab/openhab-webui/assets/22525368/555a7590-aa95-4381-ab2e-1a1a39eaf78d)

Firefox:
![grafik](https://github.com/openhab/openhab-webui/assets/22525368/085b98e4-3a73-4fbf-961c-20651b217587)

I'm using this sitemap definition:
````
Input inputHint="time" item=MyDateTimeItem
````

## Expected behavior

It should be similiar in both browsers.

## Your environment

```yaml
runtimeInfo:
  version: 4.1.3
  buildString: Release Build
locale: de-DE
```

## Browser console

no output in the console.
