### ISSUE TITLE
Issues with the 4.2 Basic UI settings menu (cogwheel) and Edge

### ISSUE THREAD

**Issue by quensen** [openhab/openhab-webui#2654]
## The problem
a) **The Basic UI settings page does not open when I click on it using MS Edge.**
I can see the new cogwheel (4.2.0) and it works in Chrome, but in Edge it only works on the page that is shown if you didn’t specify the sitemap (`http://<host>:8080/basicui/app?sitemap`). On all sitemaps the settings are not considered (always light mode, always 3 columns)
The settings menu is not shown when you click the cogwheel on those pages (nothing happens).

b) **The back button (arrow) is overlayed by the cogwheel.**
![image](https://github.com/openhab/openhab-webui/assets/24944195/4e595e6c-6338-4bab-823e-16a10f48bb51)
Therefore, back button does not work any more.

## Expected behavior
a) The Basic UI settings can be opened by clicking on the cogwheel button on all pages that show it (at least on the root page).
b) The back button (arrow) is not overlayed by the cogwheel and it goes back one page.

## Steps to reproduce
1. Open MS Edge
2. Open a sitemap `http://<host>:8080/basicui/app?sitemap=default`
3. Click on the cogwheel button (nothing happens)
4. Click on a link that leads to a sub-page (youre on that page afterwards)
5. Click on the back button (arrow) [that is overlayed by the cogwheel] (nothing happens)

## Your environment
openHAB 4.2.0 Release Build on Raspberry Pi openhabian
MS Edge Version 126.0.2592.87 (Offizielles Build) (64-Bit) on Windows 11

```yaml
runtimeInfo:
  version: 4.2.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.11
  javaVendor: Debian
  osName: Linux
  osVersion: 6.6.31+rpt-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 224180480
  totalMemory: 801112064
  uptime: 2694
  startLevel: 100
addons:
  - automation-jrubyscripting
  - automation-jsscripting
  - binding-astro
  - binding-exec
  - binding-fsinternetradio
  - binding-http
  - binding-knx
  - binding-lgwebos
  - binding-miio
  - binding-mqtt
  - binding-network
  - binding-tr064
  - misc-openhabcloud
  - persistence-rrd4j
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-xslt
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 20
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
timestamp: 2024-07-08T13:05:08.376Z
```
