### ISSUE TITLE
oh-icon doesn't send command when using iconify icon

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2664]
This works and sends a command to the given item:

```
                    - component: oh-icon
                      config:
                        icon: light
                        action: toggle
                        actionCommand: ON
                        actionCommandAlt: OFF
                        actionItem: Item1
                        style:
                          height: 2.5rem
                          opacity: "=@'Item1' === 'ON' ? '100%' : '30%'"
```

This doesn't work, it doesn't send a command to the item when clicked:

```
                    - component: oh-icon
                      config:
                        icon: iconify:weui:tv-outlined
                        action: toggle
                        actionCommand: ON
                        actionCommandAlt: OFF
                        actionItem: Item1
                        style:
                          height: 2.5rem
                          opacity: "=@'Item1' === 'ON' ? '100%' : '30%'"
```

The only thing different is the icon. The first one is using oh icon, the other one uses iconify.

Also the iconify shows up tiny in size. I had to apply other tweaks to make it sized the same as the classic icon.
