### ISSUE TITLE
Sitemap editor: Code tab is broken

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2674]
## The problem

![grafik](https://github.com/user-attachments/assets/310c0674-761c-43ed-9a79-64636b8bbd6b)

As you can see the editable code block and the rendered json are overlapping, making the code block unusable.

## Expected behavior

Both things don't overlap.

## Steps to reproduce

1. Have a sitemap with many entries (more than one page height)
2. Open the code tab.

## Your environment

```yaml
runtimeInfo:
  version: 4.2.0
  buildString: Release Build
```

This worked on 4.1.0.
