### ISSUE TITLE
[MainUI] Allow color settings for own svg icons

### ISSUE THREAD

**Issue by sKinyo** [openhab/openhab-webui#2679]
## The problem

Because I don't like the internal and most of the external icons I have created my own svg icons.
I can integrate them with the components svg and use in widgets and can set a color.
This shows the icon but can't directly use them in oh-list-item, oh-label-item, oh-icon, oh-botton, oh-link, and all others.

The BasicUI allows colors for own icons but this is missing in the MainUI

## Your suggestion
Internal/own svg icons should have the same feature set as external icons.
Allow to set a css color.

This should be possible:
```
- component: oh-icon
  config:
    icon: oh:my_own_icon
    color: "#BDB76B"
- component: oh-list-item
  config:
    icon: oh:my_own_icon
    iconColor: "#BDB76B"
```

## Your environment

```yaml
runtimeInfo:
  version: 4.2.0
  buildString: Release Build
```
