### ISSUE TITLE
Checkboxes of Semantic Model not shown correctly on iPhone in portrait mode

### ISSUE THREAD

**Issue by Boldfor** [openhab/openhab-webui#2718]
## The problem
When opening the semantic model with the screen resolution of an iPhone 13 in portrait mode, the checkboxes on the bottom are not shown correctly (partially overlapping / not enough vertical space), see red marking. In landscape mode, the checkboxes are shown / can be used correctly.
![image](https://github.com/user-attachments/assets/66ffacc3-9f18-462f-abef-45b003b7c586)

## Expected behavior
The checkboxes can be used as intended also in portrait mode.

## Steps to reproduce
1. Load Main UI on an iPhone 13 latest iOS / 17.6.1) on safari 
2. Go to "Semantic Model"

Notes: The same bug appears when using the iOS App.

## Your environment
```

runtimeInfo:
  version: 4.2.1
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.12
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-rpi8-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 95130904
  totalMemory: 456130560
  uptime: 181716
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-gardena
  - binding-goecharger
  - binding-homematic
  - binding-irobot
  - binding-mqtt
  - binding-systeminfo
  - binding-yamahamusiccast
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - transformation-xpath
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: true
    android: false
    androidChrome: false
    desktop: false
    iphone: true
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: ios
    osVersion: 17.6.1
    webView: true
    webview: true
    standalone: true
    pixelRatio: 3
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
    onLine: true
    platform: iPhone
  screen:
    width: 390
    height: 844
    colorDepth: 24
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: true
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X)
    AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148
    Safari/604.1
timestamp: 2024-08-15T21:08:19.796Z

```

## Browser console

```txt

```
