### ISSUE TITLE
[Developer Sidebar] Running rule in Uninitialized state appears to work but doesn't

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#2748]
## The problem

When there is something wrong with a rule it falls into an Uninitialized status. Attempting to run such a rule from the rule's page throws up a toast saying "Rule cannot be run if uninitialized".

However, if the rule is run from the developer sidebar the "Runing rule" toast pops up and the rule appears to run. However there is no error anywhere in the UI. Eventually I say an error message in openhab.log.

## Expected behavior

Click the run button from the developer sidebar behaves the same as pushing the play button from the rule's page. 

## Steps to reproduce

```yaml
configuration: {}
triggers:
  - id: "1"
    configuration:
      itemName: TestSwitch
    type: core.ItemStateChangeTrigger
conditions:
  - inputs: {}
    id: "3"
    configuration:
      type: application/javascript
      script: console.info('Test rule condition');
    type: script.ScriptCondition
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript
      script: console.info('Test Rule action');
    type: script.ScriptAction
  - inputs: {}
    id: "3"
    configuration:
      type: application/broken
      script: console.info('Broken Test Rule action');
    type: script.ScriptAction
```
This rule is an error because action 3 has an invalid mime type.

1. Deploy a broken rule
2. click the play button on the rule page and see the "can't run" message
3. search for, pin, and click the play button from the developer sidebar and see the "Running rule" message

## Your environment

```yaml
runtimeInfo:
  version: 4.3.0.M1
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.12
  javaVendor: Debian
  osName: Linux
  osVersion: 6.8.0-41-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 122698512
  totalMemory: 494927872
  uptime: 164
  startLevel: 70
addons:
  - automation-jsscripting
  - automation-jsscriptingnashorn
  - binding-amazonechocontrol
  - binding-astro
  - binding-chromecast
  - binding-http
  - binding-ipcamera
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-shelly
  - binding-vesync
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-basicprofiles
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
timestamp: 2024-09-11T20:50:56.541Z

```

## Browser console

```txt

```
