### ISSUE TITLE
Improve HANLDER_INITIALIZING_ERROR so it's more understandable

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#2749]
## The problem

When there is a fatal error in a rule it becomes UNINITIALIZED and shows a HANLDER_INITIALIZING_ERROR. The name of this error and the details are not generally understandable or actionable by the average user. For example, if the rule has a Script for a language that doesn't have the add-on installed appears as:

![image](https://github.com/user-attachments/assets/35552cc1-7d9e-46a7-bc2a-9b6a631da6be)

## Your suggestion

I've several suggestions:

1. Gray out the play button for rules that cannot be run becuase they are not in the Idle state.
2. Improve the error message to something more understandable and actionable for the end user (in this case something like "Cannot find installed automation add-on that supports "broken" scripts". If it can be even more specific that would be even better (e.g. "This rule requires the jRuby add-on to be installed").
3. Add some sort of indication to the rule page to show what component is generating the error (i.e. which trigger, action or condition the error is comming from).

## Your environment

```yaml
runtimeInfo:
  version: 4.3.0.M1
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.12
  javaVendor: Debian
  osName: Linux
  osVersion: 6.8.0-41-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 148337520
  totalMemory: 494927872
  uptime: 932
  startLevel: 70
addons:
  - automation-jsscripting
  - automation-jsscriptingnashorn
  - binding-amazonechocontrol
  - binding-astro
  - binding-chromecast
  - binding-http
  - binding-ipcamera
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-shelly
  - binding-vesync
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-basicprofiles
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1600
    height: 900
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/128.0.0.0 Safari/537.36
timestamp: 2024-09-11T21:03:39.099Z
```
