### ISSUE TITLE
Incoming Value Transformation of a copied channel cannot be changed to a new value inside copy process

### ISSUE THREAD

**Issue by matmai** [openhab/openhab-webui#2770]
## The problem

If a channel of a thing of type generic MQTT Thing is copied via the main UI to a new channel the values are correctly copied. But if the already prefilled Incoming Value Transformation is altered to a new value and the channel is saved the Incoming Value Transformation stays the same (as copied from the previous channel).

## Expected behavior

It is expected that the copied values could be adjusted and saved to the newly created channel.

## Steps to reproduce

1.  Create a thing of type generic MQTT Thing and a channel with an Incoming Value Transformation
2. Copy this channel via Copy Channel functionality
3. Alter the prefilled value of Incoming Value Transformation
4. Save the channel
5. Check if the adjustments of the Incoming Value Transformation are saved

## Your environment

```yaml
runtimeInfo:
  version: 4.2.1
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.12
  javaVendor: Raspbian
  osName: Linux
```

## Browser console

Nothing that looks like an error, just "Thing updated according to SSE, reloading"

## Browser network traffic

There are no failed requests

## Additional information

As a workaround the channel has to be edited and saved again. Then the new values for Incoming Value Transformation are saved as expected.
