### ISSUE TITLE
Double scrollbars on /settings/items/

### ISSUE THREAD

**Issue by sonic74** [openhab/openhab-webui#2788]
## The problem

Double scrollbars on `/settings/items/` that interfere with mousewheel scrolling:

![image](https://github.com/user-attachments/assets/b42e2cf0-c3b9-46a7-aea8-010c2d08e763)

## Expected behavior

When I remove the `-x` in
```
.block-narrow {
    overflow-x: hidden !important;
    z-index: auto;
}
```
that might come from
https://github.com/openhab/openhab-webui/blob/e2c3c53d29d6f717f947712d8a759ecae54b07c9/bundles/org.openhab.ui/web/src/css/app.styl#L190
it works as expected again, like some versions ago.

## Steps to reproduce

Browse to http://openhab:8080/settings/items/ and scroll to the bottom.

## Your environment

```yaml
runtimeInfo:
  version: 4.2.2
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.12
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-23-amd64
  osArchitecture: i386
  availableProcessors: 8
  freeMemory: 54319296
  totalMemory: 292552704
  uptime: 589418
  startLevel: 100
addons:
  - binding-amazonechocontrol
  - binding-shelly
  - binding-tplinksmarthome
  - persistence-rrd4j
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 2.5
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 32
    language: en-GB
    languages:
      - en-GB
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/129.0.0.0 Safari/537.36
timestamp: 2024-10-06T19:40:23.276Z
```

Also happens in Firefox 91
