### ISSUE TITLE
When minimum font size is set in browser, Items list is truncated in admin UI

### ISSUE THREAD

**Issue by MelanieT** [openhab/openhab-webui#2841]
## The problem
The admin section of the main UI displays lists of things, items, and so on.  The Items list appears to precalculate the height of all items in pixels, however, it does not take into account that the minimum font size setting in the browser can vary the height of items.

Items lists are truncated:
![image](https://github.com/user-attachments/assets/09575c01-a450-4fef-ad93-1020560bedce)

## Expected behavior
Items list should be complete:
![image](https://github.com/user-attachments/assets/a9abd9cc-9041-495b-aea2-03f1c2272fef)

## Steps to reproduce

1. Install Openhab, open admin UI and create some items.
2.  Set the "Mninimum Font Size" in the browser to a large font:
![image](https://github.com/user-attachments/assets/16d16ef5-e2b2-41f4-99d6-a71c11120a1f)

Observe the list of items is now truncated.

## Your environment
Mac OSX tested with both Firefox and Chrome. Openhab running on Raspberry Pi 5, install via packages.

```yaml
runtimeInfo:
  version: 4.2.2
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu17.54+21-CA
  osName: Linux
  osVersion: 6.6.51+rpt-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 115538792
  totalMemory: 251658240
  uptime: 82605
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-mqtt
  - persistence-inmemory
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-bin2json
  - transformation-exec
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-scale
  - transformation-xpath
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-GB
    languages:
      - en-GB
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0)
    Gecko/20100101 Firefox/119.0
timestamp: 2024-10-27T17:25:29.192Z

```

## Browser console

There are no relevant error messages.

I have identified the culprit:
![image](https://github.com/user-attachments/assets/c9fc1441-bc28-471e-94f6-3c7062df7004)

Note the element stye applied: "height: 425.39px;"

Toggling this:
![image](https://github.com/user-attachments/assets/f48ecd9e-a270-494f-bd43-3876ef3ed15e)

Shows the item list as designed when the checkbox is off, and truncated when the checkbox is on (the limit is in effect)
```txt

```

## Browser network traffic

No requests fail

## Additional information

I could not observe any related issues on the Things list.
