### ISSUE TITLE
Item states not tracked at context variable and constant evaluation

### ISSUE THREAD

**Issue by JustinGeorgi** [openhab/openhab-webui#2842]
oh-context variables and constant expressions are evaluated before the component is mounted. If the UI is newly opened (or recently reset) any item states are not available via the store when those expression are calculated for the very first time.

Replicate the issue

Here's a basic widget:
```yaml
uid: demo-context-error
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Oct 27, 2024, 11:04:06 AM
component: oh-context
config:
  constants:
    testItemConst: =`testNumber state is ${items.testNumber.state}`
  variables:
    testItemVar: =`testNumber state is ${items.testNumber.state}`
slots:
  default:
    - component: f7-card
      config:
        title: =`testNumber state is ${items.testNumber.state}`
        content: =const.testItemConst
        footer: =vars.testItemVar
```
All three text outputs should be the same:
![image](https://github.com/user-attachments/assets/48b000ae-3ddb-45ac-a4b5-72aaf9277008)

However, after a [ctrl + shft + f5] the result is different:
![image](https://github.com/user-attachments/assets/36a9da88-12bf-43a2-bfff-2239341cb62c)

At this point, however, the item is now in the store because of the title expression so any further interaction (refresh the widget, leave the page and come back, etc.) will result in the proper calculations.

Even if you do activities first, for example open some other widgets or pages in the UI, the first time this widget is opened the item states are not properly available.

...except! Here's a second widget:
```yaml
uid: demo-context-error-2
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Oct 27, 2024, 11:16:00 AM
component: f7-card
config:
  title: Add testNumber to store
  content: =items.testNumber.numericState
```
Opening this widget after a refresh, but before the first you open the first widget means that the first widget will be properly displayed the first time it opens. The testNumber item is now being tracked as a result of the second widgets expression being called prior to the first widget's use.

I assume there is a very simple solution to this, but after poking around for a few minutes, I admit, I don't see it.

**Comment by florian-h05** [comment]
The problem seems to be that the Item state is not already tracked, and the oh-context constant/var init does not wait for the states. 
BTW, I don‘t think that is super easy to fix.

**Comment by sasbibic** [comment]
Any progress on this?

**Comment by JustinGeorgi** [comment]
A new report in the forums:

https://community.openhab.org/t/item-state-available-for-oh-repeater-config-only-after-additional-refresh/161992

shows, I believe, that this error is actually not just restricted to the oh-context. It also exists in the repeater (and possibly beyond?), it's just that normal function of the repeater masks the issue. The difference with the oh-context is that the constants are (because they are constant) never recalculated even if the item state they were initially calculated with changes. Therefore this error shows up readily in the context. The repeater, on the other hand, if it doesn't encounter an actual error, will recalculate the offending expression as soon as the item state is collected, (which I guess represents a change event that triggers the recalculation).

Even if this doesn't make the general error easier to find, it might suggest a workaround for the context, where a single recalculation of the constant expressions is permitted when the item states finally catch up.

**Comment by jsjames** [comment]
@florian-h05 - i'm running into this one in my own setup. It seems like you have looked at this before - any pointers on how to fix?

**Comment by jsjames** [comment]
Actually - i realize my issue as I thought the variables in oh-context should be reactive to changes in the underlying elements. Does anyone understand the reasoning here to NOT make them reactive?

**Comment by JustinGeorgi** [comment]
The variables still appear to be reactive in my system (Build #5121).

This is part of my original test widget when creating the context and still seems to work as it did:

```yaml
uid: oh-context-demo
tags: []
props: {}
timestamp: Apr 13, 2024, 11:14:38 AM
component: oh-context
config:
  constants:
    fruitColor:
      apple: red
      banana: =(dayjs().hour() < 6)?'green':((dayjs().hour() < 14)?'yellow':'black')
      blueberry: blue
      orange: orange
    fruitList:
      - apple
      - banana
      - orange
      - blueberry
  functions:
    a2o: =(str) => (str || 'no fruit').replaceAll('a','o')
    nextFruit: >
      =(fr) =>
        (fr)
        ? (['apple','banana','orange','blueberry'])[(['blueberry','apple','banana','orange']).indexOf(fr)]
        : ('apple')
  variables:
    currentFruit: apple
slots:
  default:
    - component: f7-card
      config:
        content: =`Global fruit is ${fn.a2o(vars.currentFruit)}`
        textColor: =const.fruitColor[vars.currentFruit] || 'deeppurple'
        title: Fn, Const, and Scoped Variables
      slots:
        default:
          - component: oh-context
            config:
              functions:
                a2o: =(str) => (str || 'no fruit').replaceAll('a','0')
              variables:
                currentFruit: orange
            slots:
              default:
                - component: f7-row
                  config:
                    style:
                      justify-content: space-around
                  slots:
                    default:
                      - component: oh-button
                        config:
                          action: variable
                          actionVariable: currentFruit
                          actionVariableValue: =fn.nextFruit(vars.currentFruit)
                          text: =`Local fruit is ${fn.a2o(vars.currentFruit)}`
                      - component: oh-button
                        config:
                          clearVariable: currentFruit
                          text: =`Clear local fruit`
                - component: f7-row
                  config:
                    style:
                      justify-content: center
                  slots:
                    default:
                      - component: Label
                        config:
                          text: Input local fruit
                      - component: oh-input
                        config:
                          outline: true
                          placeholder: Please select a fruit
                          style:
                            color: var(--f7-text-color)
                            margin-left: 18px
                          type: text
                          variable: currentFruit
    - component: oh-input-card
      config:
        placeholder: Please select a fruit
        title: Input global fruit
        type: text
        variable: currentFruit
    - component: oh-context
      config:
        constants:
          fruitColor:
            apple: green
            banana: black
            blueberry: pink
            orange: orange
      slots:
        default:
          - component: f7-card
            config:
              content: =`Global fruit is ${fn.a2o(vars.currentFruit)}`
              textColor: =const.fruitColor[vars.currentFruit] || 'deeppurple'
              title: Fn, Const, and Scoped Variables
            slots:
              default:
                - component: f7-row
                  config:
                    style:
                      justify-content: space-around
                  slots:
                    default:
                      - component: f7-row
                        config:
                          style:
                            justify-content: space-around
                        slots:
                          default:
                            - component: oh-button
                              config:
                                action: variable
                                actionVariable: currentFruit
                                actionVariableValue: =fn.nextFruit(vars.currentFruit)
                                text: =`Global fruit is ${fn.a2o(vars.currentFruit)}`
                            - component: oh-button
                              config:
                                clearVariable: currentFruit
                                text: =`Clear global fruit`
```
Or am I misunderstanding what you are seeing?

**Comment by jsjames** [comment]
I have the following where the binding provides a bunch of one-hot channels to determine state. Depending on these values, I want to set a variable to make thing simpler in the rest of the code.

```
    - component: oh-context
      config:
        variables:
          state: =(@@'alarmPanelStatusReady' == 'ON')?'READY':(@@'alarmPanelStatusAway' ==
            'ON')?'AWAY':(@@'alarmPanelStatusAlarm' == 'ON')?'ALARM':'NOT READY'
```

Based on this line in the doc `Variables are evaluated once before the widget is displayed the first time .` and in looking a the code, i see it is the case that state will not be reactive.

I believe this is the root of the issue for this thread as well - if on startup the value for these variables is not know, they will never be changed since they are not reactive. I was wondering if this was intentional in the design and if it would make sense to change that behavior?

**Comment by JustinGeorgi** [comment]
Ah, OK, I see what you mean. Yes the initial variable value in the context is not reactive. This is intended to only be a default value for the variable. After that default value is set, widget variables will only change in response to variable actions from components. That keeps the context variables consistent with the original widget variable implementation.

Context functions are fully reactive so if you need to set a fully reactive value in the context, use the function object. I personally prefer to use actual functions in "getter" format:
```yaml
functions:
  getState: = () => (@@'alarmPanelStatusReady' == 'ON')?'READY':(@@'alarmPanelStatusAway' ==
            'ON')?'AWAY':(@@'alarmPanelStatusAlarm' == 'ON')?'ALARM':'NOT READY'
```
However, there's currently no actual type checking on the context objects so you could just define your variable in the function object and then call it as `fn.state` instead of `vars.state`.
