### ISSUE TITLE
'displayState' equivalent for 'oh-stepper-card'

### ISSUE THREAD

**Issue by ErikDB87** [openhab/openhab-webui#2875]
## The problem

Currently this yaml code:
```
- component: oh-grid-col
  config: {}
  slots:
    default:
      - component: oh-stepper-card
        config:
          fontSize: 34px
          fontWeight: bold
          item: haard_eetkamer_temperatuurgestuurd_uit
          step: 0.5
          noBorder: false
          outline: false
          stylesheet: |
            .card-header { justify-content: center }
          title: Temperatuurdrempel om haard uit te zetten
```

Generates this:
![image](https://github.com/user-attachments/assets/22e021df-6e59-4edd-baba-e4ca303f96d7)

But in Dutch, a decimal comma should be used... Also, `° C` is missing, and would be nice to have.

## Your suggestion

Provide something to the effect of `displayState`.

## Your environment

Not important.

## Additional information

Not applicable.
