### ISSUE TITLE
Saving thing channel configuration results in Thing reinitialisation

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-webui#2882]
## The problem

If a Thing channel has configuration, when the config is saved, it does a PUT to save the complete thing rather than just updating the channel config. The channel config is updated as part of this, but now the thing is reinitialised rather than just updating the channel configuration.

It also seems that the PUT request to save the Thing is sent even when no configuration update to the channel is made - ie go to the Channel Details for a channel with config, then clock Done and we get the same PUT request that causes the thing to reinitialise. In this case (ie with no actual config change) when moving away from the Thing page, we don't get the error that the thing has changed.

One issue with this is because the thing is reinitialised, this can make it difficult to manage battery devices in zigbee since they need to be woken up when the channel config is updated. If the thing gets reinitialised, then firstly this configuration may not be transferred to the device, or if the binding does try and transfer it, the device may have gone to sleep since the user has no real way to know when this is happening as it's delayed from the point at which they save the UI data.

## Expected behavior

The config for the channel should be updated separately, and at the time the user clicks Save/Done, and should only be updated if the channel configuration is changed. The thing shouldn't reinitialise.

## Steps to reproduce

1. Edit a thing
2. Select a channel that has configuration
3. Select Channel Details
4. Change channel configuration
5. Click Done - at this point the thing will be reinitialised as there is a PUT to save the thing configuration. It should instead just save the channel config.

## Your environment

```yaml
runtimeInfo:
  version: 4.3.0
  buildString: "Build #4363"
locale: en-NZ
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu17.54+21-CA
  osName: Linux
  osVersion: 6.1.0-25-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 164329368
  totalMemory: 1269825536
  uptime: 229982
  startLevel: 70
addons:
  - automation-jsscripting
  - binding-astro
  - binding-boschshc
  - binding-ipcamera
  - binding-modbus
  - binding-speedtest
  - binding-surepetcare
  - binding-systeminfo
  - binding-wled
  - misc-openhabcloud
  - persistence-jdbc-h2
  - transformation-basicprofiles
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
timestamp: 2024-11-20T00:42:23.862Z

```

## Browser console

```txt

```
