### ISSUE TITLE
Support link on a page that directly opens user specified tab on a tabbed page.

### ISSUE THREAD

**Issue by div-co** [openhab/openhab-webui#2901]
Support Navigate to Specific Tabs in OpenHAB UI. This feature would enable users to create more intuitive and user-friendly navigation within their OpenHAB UI. For example, a user could create a link on a page that directly opens the fourth tab on a tabbed page, improving the overall user experience.

<img width="1401" alt="image" src="https://github.com/user-attachments/assets/63657895-5882-4f87-8afa-a8793d6a19de">

## Your suggestion

Support parameter to Navigate to Specific Tabs in OpenHAB UI.

E.g. `tabIndex: 3` or `actionPageParams: tab=3`

Sample page containing links to other tabbed page

<img width="478" alt="image" src="https://github.com/user-attachments/assets/5e7b9de9-2b29-411a-a38c-a3f15ce07546">

In the above example the link "BATH" cannot directly opens the fourth tab but opens the first element, which is `tab 0`.

```
- component: oh-label-item
     config:
       action: navigate
       actionPage: page:rooms_tabbed
       title: баня #BATH
```

Target page: rooms_tabbed

<img width="1401" alt="image" src="https://github.com/user-attachments/assets/63657895-5882-4f87-8afa-a8793d6a19de">

## Your environment

```yaml
UI appearance (theming, color scheme etc.)
Web Audio Sink support
Setting up the UI Command Item
More Help
You can find many more details and help at these resources:
About
About

openHAB 4.2.3
Release Build

Configuration folder
/openhab/conf
User data folder
/openhab/userdata
Logs folder
/openhab/userdata/logs
Operating system
Linux/4.4.302+ (amd64)
Java Runtime
Debian
17.0.13 (undefined)
2 available processors - 257/812MB available memory
Appearance (for this device only)
Theme
Auto
logo_android
logo_ios
desktopcomputer
Dark mode
Auto
Light
Dark
Navigation bars style
Miscellaneous
Simple navigation bar on home page
Standard home page background color
Disable card expansion animations
Disable page transition animations
Enable Web Audio sink support
Reload
Standard Library
Personal Widgets
Standard Library (List)
Personal Widgets
runtimeInfo:
  version: 4.2.3
  buildString: Release Build
locale: en-BG
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.13
  javaVendor: Debian
  osName: Linux
  osVersion: 4.4.302+
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 269132472
  totalMemory: 851443712
  uptime: 455060
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-http
  - binding-mail
  - binding-network
  - binding-ntp
  - binding-onkyo
  - binding-shelly
  - binding-zwave
  - persistence-jdbc-mariadb
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2.200000047683716
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 10
    language: en-GB
    languages:
      - en-GB
      - en
      - en-US
      - bg
    onLine: true
    platform: MacIntel
  screen:
    width: 1728
    height: 1117
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
timestamp: 2024-12-06T18:21:19.758Z
```
