### ISSUE TITLE
Log level dropdown menu doesn't get built

### ISSUE THREAD

**Issue by ErikDB87** [openhab/openhab-webui#2927]
## The problem

When trying to filter the logs in the UI, while tailing, the dropdown menu doesn't get built:
![image](https://github.com/user-attachments/assets/0bca3980-efb2-4217-b0d4-20a8ccec1c95)

## Expected behavior

I would expect the dropdown menu to be built.

## Steps to reproduce

1. 

## Your environment

```yaml
runtimeInfo:
  version: 4.3.0
  buildString: Release Build
locale: nl-BE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu17.54+21-CA
  osName: Linux
  osVersion: 6.8.0-50-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 101106368
  totalMemory: 890241024
  uptime: 87816
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-buienradar
  - binding-chromecast
  - binding-enocean
  - binding-gpstracker
  - binding-hpprinter
  - binding-http
  - binding-icloud
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-openweathermap
  - binding-semsportal
  - binding-sonos
  - binding-tado
  - binding-upnpcontrol
  - misc-openhabcloud
  - persistence-rrd4j
  - transformation-jsonpath
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: nl-BE
    languages:
      - nl-BE
      - nl-NL
      - nl
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/131.0.0.0 Safari/537.36
timestamp: 2024-12-16T20:08:31.158Z
```

## Browser console

```txt
[USO] Button detection aborting due to timeout.
4contentInit.4c8b2279.js:2 Uncaught Error: Attempting to use a disconnected port object
    at contentInit.4c8b2279.js:2:1836
```

![image](https://github.com/user-attachments/assets/98177d48-64c1-4cf3-82eb-601ffceb7dd7)

## Browser network traffic

No problem, as far as I can see.

## Additional information

See https://community.openhab.org/t/openhab-4-3-release-discussion/160888/31.
