### ISSUE TITLE
[Main UI] screen.viewAreaWidth not updating / working

### ISSUE THREAD

**Issue by MatzeMuc86** [openhab/openhab-webui#2929]
## The problem
Using screen.viewAreaWidth within custom widgets. With Opdateing from OH 4.2.2 to OH 4.3.0 on Docker the functions causes issues in custom widgets. For better understanding, I generated a specific test widget and test page.

Until OH 4.2.2screen.viewAreaWidth reacted live on changes of screen width (e.g. when re-sizing browser windows). This stoped now as one can see in the GIF. Neither reloading page (URL + ENTER) nor F5 work. Only clicking the link in OH menu reloads current values once.

![explorer_UIVKL3bS8v](https://github.com/user-attachments/assets/60182b08-3137-496d-ba8b-0689ccc36835)

Test Widget
```yaml
uid: Cell_Test
tags: []
props:
  parameters:
    - description: HEX or rgba
      label: Backgroundcolor
      name: bgcolor
      required: false
      type: TEXT
    - description: Page which will be opened as popup
      label: Page ID
      name: page
      required: false
timestamp: Dec 18, 2024, 11:42:39 AM
component: f7-card
config:
  title: = (screen.viewAreaWidth) + " Title"
slots:
  content:
    - component: Label
      config:
        text: = (screen.viewAreaWidth) + " Label"
```

Test Page
```yaml
config:
  label: test1234
  sidebar: true
blocks:
  - component: oh-block
    config: {}
    slots:
      default:
        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: widget:Cell_Test
                      config: {}
masonry: []
grid: []
canvas: []
```
