### ISSUE TITLE
Interactive SVG Backgrounds / Dialog is not appearing when grid is visible

### ISSUE THREAD

**Issue by Oetz1987** [openhab/openhab-webui#2944]
## The problem
If an Layoutpage with an fixed Canvas is in design mode, the dialog for an interactive background element will not be shown on click while the grid is visible.

all details can be found here:
See also: https://community.openhab.org/t/interactive-svg-backgrounds-dialog-is-not-appearing/160981

## Expected behavior
If I click on an element with activated SVG the dialog should be shown.

## Steps to reproduce

1.  Grid is not visible --> it works
2.  Grid is visible --> it isn't working
3.  Grid is not visible --> it works

## Your environment

```yaml
runtimeInfo:
  version: 4.3.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.13
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.15.0-127-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 61993824
  totalMemory: 344981504
  uptime: 93989
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-homeconnect
  - binding-hpprinter
  - binding-icalendar
  - binding-ipcamera
  - binding-knx
  - binding-luxtronikheatpump
  - binding-mail
  - binding-miio
  - binding-mqtt
  - binding-openweathermap
  - binding-shelly
  - binding-systeminfo
  - misc-openhabcloud
  - persistence-rrd4j
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - en-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: geras
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/131.0.0.0 Safari/537.36
timestamp: 2024-12-23T14:47:43.111Z
```

## Browser console

When the effect is taken place, there is no message in the console when I'm clicking on the element.
```txt

```
