### ISSUE TITLE
[Log Viewer] Make the width of columns resizeable

### ISSUE THREAD

**Issue by nelsonaponte** [openhab/openhab-webui#2960]
## The problem
In many cases, the standard width of columns is too long for most records in that column, leaving little space for data in other columns.

![image](https://github.com/user-attachments/assets/bafb3e63-8be9-40f3-96c3-1ed4b23124ce)

## Your suggestion

The width of each column should be easily and dynamically manageable with the cursor so users can modify it as it better suits them.
When the column is not long enough for the data contained in one of its cells, the data from that cell should be wrapped in the cell.

![image](https://github.com/user-attachments/assets/355190dd-d0a7-482d-b9cf-38c690bb26ff)

When the height of a cell increases or decreases, the size of the whole row should increase or decrease accordingly.

## Your environment

```yaml
runtimeInfo:
  version: 4.3.0
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.13
  javaVendor: Red Hat, Inc.
  javaVendorVersion: (Red_Hat-17.0.13.0.11-1)
  osName: Linux
  osVersion: 5.4.60-v8.1.el8
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 309470264
  totalMemory: 730857472
  uptime: 489198
  startLevel: 100
clientInfo:
  device:
    desktop: true
    edge: false
    ie: false
    firefox: false
    macos: true
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1470
    height: 956
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15
timestamp: 2025-01-01T09:16:29.042Z

```
