### ISSUE TITLE
[Log Viewer] The logs from exceptions errors are converted to a single line

### ISSUE THREAD

**Issue by nelsonaponte** [openhab/openhab-webui#2961]
## The problem
Logs from exception errors (such as stack traces) are being converted from multiple lines to a single line.

Reading such messages in a single line is inconvenient and may force users to unnecessarily copy the text and paste it on a different tool to analyze the problem.

## Your suggestion

Logs with internal formatting to split the text into multiple lines should not be modified to fit in a single line.

## Your environment

```yaml
runtimeInfo:
  version: 4.3.0
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.13
  javaVendor: Red Hat, Inc.
  javaVendorVersion: (Red_Hat-17.0.13.0.11-1)
  osName: Linux
  osVersion: 5.4.60-v8.1.el8
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 309470264
  totalMemory: 730857472
  uptime: 489198
  startLevel: 100
addons:
  - binding-astro
  - binding-hue
  - binding-irobot
  - binding-netatmo
  - binding-openweathermap
  - binding-roku
  - binding-sonos
  - binding-systeminfo
  - binding-telegram
  - binding-tplinksmarthome
  - binding-unifi
  - binding-upnpcontrol
  - misc-openhabcloud
  - persistence-jdbc-mysql
  - transformation-map
  - ui-habot
  - voice-marytts
clientInfo:
  device:
    desktop: true
    edge: false
    ie: false
    firefox: false
    macos: true
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1470
    height: 956
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15
timestamp: 2025-01-01T09:16:29.042Z

```
