### ISSUE TITLE
Non-string widget props with defaults are converted to strings when stored in JSONDB

### ISSUE THREAD

**Issue by Nadahar** [openhab/openhab-webui#2990]
## The problem
I don't know if this problem is actually in MainUI or in Core, but I'm posting here first. The problem probably doesn't just apply to widgets, but that's where I've observed it.

When you define a prop for a widget that is a boolean or a number and which has a default, the type isn't respected when the widget is stored, and everything seems to be converted to strings - which causes widgets to misbehave once retrieved from storage.

Example definition:
```yaml
    - default: false
      description: Whether to show the LCD
      label: Show LCD
      name: showLCD
      required: false
      type: BOOLEAN
```

After storing and reopening the widget, this has "magically" been transformed to
```yaml
    - default: "false"
      description: Whether to show the LCD
      label: Show LCD
      name: showLCD
      required: false
      type: BOOLEAN
```

When using this in an expression like `=props.showLCD?`, the default will in effect be "true" because it's not an empty string. Before the widget is stored (and the quotes added), the evaluation works correctly. To make it behave correctly after retrieval, one must instead do something like `props.showLCD&&props.showLCD!='false'?`. The issue is the same with numbers, where various bugs appear after retrieving the widget from storage.

By peeking in the JSONDB, I can see that the default values have already been converted to string before being stored, so it looks like the problem is somewhere "on the way to storage" - not during retrieval:
```json
          {
            "default": "false",
            "description": "Whether to show the LCD",
            "label": "Show LCD",
            "name": "showLCD",
            "required": false,
            "type": "BOOLEAN"
          },
```
As can be seen, `required` is stored correctly and doesn't suffer from this issue.

It seems to me that the `type` should be taken into account when the `default` is converted, and I'm starting to realize that this problem probably is in Core.
