### ISSUE TITLE
oh-image-card changes image size when action is defined

### ISSUE THREAD

**Issue by dujal** [openhab/openhab-webui#3002]
## Action defined in oh-image-card changes image size 

When I added an action to oh-image-card in fixed grid layout the image has been scaled to smaler size (maybe added more padding). The same image card seems to be rendered correctly in another page under oh-masonry.

![image](https://github.com/user-attachments/assets/51da556d-83b3-4bf9-ae27-4e1c34aeaef7)

## Expected behavior

I expect the image in image card looks the same whenever action for card is defined or not. 

## Steps to reproduce

Following test layout page with two image cards could reproduce the problem.

```yaml
config:
  layoutType: fixed
  fixedType: grid
  label: test image card
blocks: []
masonry: []
grid:
  - component: oh-grid-item
    config:
      x: 0
      y: 0
      h: 2
      w: 2
    slots:
      default:
        - component: oh-image-card
          config:
            url: 'https://www.pngall.com/wp-content/uploads/8/Sample.png'
            actionModal: widget:ozo_svozy_list
            action: popup
  - component: oh-grid-item
    config:
      x: 2
      y: 0
      h: 2
      w: 2
    slots:
      default:
        - component: oh-image-card
          config:
            url: 'https://www.pngall.com/wp-content/uploads/8/Sample.png'
```

1. 

## Your environment

Reproduced on Chrome, Edge and Firefox in Windows 11 as well as openHAB android app and fully kiosk browser on android.

System info:
```yaml
runtimeInfo:
  version: 4.3.1
  buildString: Release Build
locale: cs-CZ
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.13
  javaVendor: Debian
  osName: Linux
  osVersion: 6.6.62+rpt-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 505353264
  totalMemory: 1415577600
  uptime: 806866
  startLevel: 100
```

## Browser console

```txt

```
