### ISSUE TITLE
OH 4.3.3 change to oh-image-card has global effect

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-webui#3091]
After upgrading from OH 4.3.2 to 4.3.3, my main UI page with my custom widgets is messed up.
There are too large margins everywhere.
Looks like this commit for a small change to oh-image-card is responsible:
https://github.com/openhab/openhab-webui/commit/8b80f8ebe7cf2d7f54c7356fcbdbc2fa83681a31

Line 32: This makes changes to the global stylesheet, not to the oh-image-card, maybe that was unintended:
`
.card
  .list
    margin 0 !important
`
I am trying now to workaround this, but I think this is probably a bug.

## Steps to reproduce

1. 

## Your environment

```yaml
runtimeInfo:
  version: 4.3.3
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /home/mythtv/openHAB/conf
  userdataFolder: /home/mythtv/openHAB/userdata
  logFolder: /home/mythtv/openHAB/userdata/logs
  javaVersion: 17.0.14
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-17.0.14+7
  osName: Linux
  osVersion: 6.6.62-gentoo-x86_64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 369112840
  totalMemory: 679477248
  uptime: 3857
  startLevel: 70
addons:
  - automation-jsscripting
  - automation-jsscriptingnashorn
  - binding-avmfritz
  - binding-chromecast
  - binding-denonmarantz
  - binding-enigma2
  - binding-exec
  - binding-homeconnect
  - binding-homematic
  - binding-http
  - binding-ipcamera
  - binding-lgwebos
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-pushover
  - binding-tr064
  - binding-unifi
  - misc-openhabcloud
  - persistence-jdbc-mysql
  - transformation-jsonpath
  - transformation-regex
  - transformation-xpath
  - ui-basic
  - ui-habpanel
  - voice-googletts
  - voice-voicerss
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
      - fr
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
timestamp: 2025-03-07T17:44:53.845Z
```

## Browser console

```txt

```

## Additional information

I will probably downgrade tomorrow to be able to provide comparison screenshots, although I do not think that will be of much relevance.
