### ISSUE TITLE
[Blockly] New Block for enabling and disabling rules

### ISSUE THREAD

**Issue by jeschmidt** [openhab/openhab-webui#3096]
## The problem

Currently it's not possible to change the enabled-status of a rule within blockly.

## Your suggestion

Introduce a new block "set enabled/disabled [rule]"
It may also be useful to have "get enabled-status [rule]" (i.e., so you can write code that's semantically equivalent to "if rule X is enabled, then ABC, else DEF")

## Your environment

```yaml
runtimeInfo:
  version: 5.0.0.M1
  buildString: Milestone Build
locale: en-CA
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 21.0.6
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-31-amd64
  osArchitecture: amd64
  availableProcessors: 6
  freeMemory: 119667808
  totalMemory: 230686720
  uptime: 510119
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-harmonyhub
  - binding-http
  - binding-mqtt
  - persistence-inmemory
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-jsonpath
  - transformation-map
  - ui-basic
```

## Additional information

This thread has a helpful reference to an alternative method for accomplishing this, but it's a big chunk of inline scripting: https://community.openhab.org/t/how-to-disable-a-rule-from-a-blockly-script/144548/4
