### ISSUE TITLE
Multiple selection bug in persistence configuration

### ISSUE THREAD

**Issue by WoutCode** [openhab/openhab-webui#3104]
## The problem

In persistence configurations, multiple (de)selection only performs one of the selection changes.
Subsequent changes have to be done one by one.

The below error is spotted in the browser console as soon as a second operation is performed:
`Uncaught TypeError: i.selectEl is undefined`

## Expected behavior

All selections and deselections are reflected in the list.

## Steps to reproduce

1. Create or edit a persistence configuration, regardless of the persistence backend used.
2. Click any of the item or group selection fields.

![Image](https://github.com/user-attachments/assets/ac671589-29d3-4ac0-a872-cf3d4b317780)

3. Select multiple items or groups from the list.
4. Click "Close".
5. Note how only one of the selected items was added to the list.
6. Repeat from step 2 to add more items. Note how only one item can be added at a time.

The behavior pertains to any changes in the selection. 
When adding a tick and removing another one, again, only the first operation will have worked.

## Your environment

```yaml
runtimeInfo:
  version: 4.3.3
  buildString: Release Build
locale: en-BE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.14
  javaVendor: Alpine
  osName: Linux
  osVersion: 6.11.11-1-MANJARO
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 572711672
  totalMemory: 960495616
  uptime: 2405
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-dsmr
  - binding-loxone
  - binding-modbus
  - binding-openweathermap
  - binding-solaredge
  - binding-unifi
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101
    Firefox/136.0
timestamp: 2025-03-13T16:32:50.565Z
```

## Browser console

The below error is logged in the browser console as soon as a second operation is performed:

```txt
Uncaught TypeError: i.selectEl is undefined
```

## Browser network traffic
N/A

## Additional information
N/A
