### ISSUE TITLE
Better validation for token names

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#3161]
## The problem

openHAB user tokens may only contain alphanumeric chars. When creating a new token this requirement isn't mentioned here:

![Image](https://github.com/user-attachments/assets/ad5906fe-c0e3-4f90-8a10-43577268b3c6)

When the user clicks the create button, an error is shown on the next page.

## Your suggestion

Keep that validation, but make it impossible to enter non-alphanumeric chars, so no page reload is required to get this feedback.

## Your environment

```yaml
runtimeInfo:
  version: 4.3.4
  buildString: Release Build
locale: de-DE
```
