### ISSUE TITLE
Blockly-block "contextual info --> event available" cannot be attached to "notification"-block

### ISSUE THREAD

**Issue by Boldfor** [openhab/openhab-webui#3186]
## The problem

When trying to add the block "contextual info" to the block "notification", I can select any value in the dropdown ("rule ID", "event type", ...), but *not* the selection "event available" (the block then unlinks).
![Image](https://github.com/user-attachments/assets/dee75d74-bf5a-4f92-9489-e80874fc827f)

At first, I thought that this is not possible because "contextual info --> event available" is a boolean variable (but needs to be a string). But then I noticed that I can add it perfectly well to the block "log info", which just dumps strings as well (and has no problem dumping the "contextual info --> event available"-block.

*Update:* The same appears to be true for the "get context attribute"-block: Can be attached to the "log"-block, but not to the "notification"-block.
![Image](https://github.com/user-attachments/assets/da6eeb34-7557-4a97-a29b-61809e386ef5)

## Expected behavior
Being able to attach the block "contextual info --> event available" to the block "notification".

## Steps to reproduce
1. Create new Rule in OH
2. Create new Blockly script
3. Add a "notification"-block
4. Try to add the block "contextual info --> event available" to this block

## Your environment
```yaml
runtimeInfo:
  version: 4.3.3
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.14
  javaVendor: Debian
  osName: Linux
  osVersion: 6.12.20+rpt-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 107753864
  totalMemory: 571473920
  uptime: 800941
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-androidtv
  - binding-astro
  - binding-gardena
  - binding-goecharger
  - binding-homematic
  - binding-irobot
  - binding-mqtt
  - binding-systeminfo
  - binding-tibber
  - binding-yamahamusiccast
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - transformation-xpath
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0
timestamp: 2025-05-07T22:35:15.585Z
```

## Additional information
Not sure if I'm missing something. Of course the "contextual info --> event available" is probably a boolean value, and dumping it via the notification-block is not the most common thing to do. However, for consistency-reason it's probably best to make this link-able to the "logging"-block *and* the notification-block, or to none of the two.
