### ISSUE TITLE
oh-colorpicker does not update the sliders

### ISSUE THREAD

**Issue by constambeys** [openhab/openhab-webui#3208]
oh-colorpicker hue/saturation/brightness sliders do not work !
Probably after  commit https://github.com/openhab/openhab-webui/commit/1e4e69e0189ffcc67648f60366278ca3100fdc09

@florian-h05 

## Expected behavior

Sliders always are at 0,0,0

![Image](https://github.com/user-attachments/assets/c98d7b39-c95e-455e-819a-f4fed6a8d5c9)

## Your environment

```

        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: oh-colorpicker-card
                      config:
                        item: Backlight_LED_Color
                        sliderLabel: true
                        sliderValue: true

```

## Browser console

```
oh-colorpicker: Updating value to 308,0.76,0.3

```
