### ISSUE TITLE
Show the full semantic hierarchy on Item's page

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#3217]
## The problem

The representation of the semantic model and an Item's position within it is different in the Model view and the individual Item's view. In the model view there is a nice tree structure with icons presents a lot of information about the semantic model in an intuitive way that doesn't take up much space. On the Item's page there are three or four fields showing the semantic information as text and the semantic significance of the parent Groups is not shown.

## Your suggestion

Present a little snippet of the tree structure as it's presented Model view. All the pertinent semantic information is shown in the tree with the icons and small print showing the tags. For example, one of my lights would look something like this:

```
Wuithering Heights (House)
  |_Ground Floor (Groundfloor)
    |_Family Room (FamilyRoom)
      |_Family Room Lights (Lightbulb)
        |_Family Room Counch Lamps (Switch/Light)
```
The "Family Room Lights" Item may or may not show up in the "Direct Parent Groups" list. It probably should appear there even if the information is redundant.

Not only will more information be shown about the Item's position in the semantic model in about the same amount of space, the consistency with how the semantic model is presented throughout MainUI reduces complexity and the amount of mental translation required on end users to understand their own config.

## Your environment

```yaml
runtimeInfo:
  version: 5.0.0.M2
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 21.0.7
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-21.0.7+6
  osName: Linux
  osVersion: 6.8.0-60-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 172026720
  totalMemory: 1336934400
  uptime: 414561
  startLevel: 70
addons:
  - automation-jsscripting
  - automation-pidcontroller
  - binding-amazonechocontrol
  - binding-astro
  - binding-chromecast
  - binding-exec
  - binding-http
  - binding-ipcamera
  - binding-mail
  - binding-mqtt
  - binding-nest
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-shelly
  - binding-vesync
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-basicprofiles
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
  - voice-pipertts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2560
    height: 1600
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101
    Firefox/138.0
timestamp: 2025-06-06T13:50:39.564Z
```

## Additional information

Related to #3211
