### ISSUE TITLE
Default standalone item should respect unit conversion in min/max/step.

### ISSUE THREAD

**Issue by quantheory** [openhab/openhab-webui#3218]
## The problem

The default standalone representation of an item tries to use the min/max/step from an item's state description (e.g. as defined [here](https://github.com/openhab/openhab-webui/blob/c12c18cddef28dde536589e37b13a978e7379cb5/bundles/org.openhab.ui/web/src/components/widgets/standard/default-standalone-item.js#L111-L119)).

However, an item can use different units from a channel it is linked to, meaning that the min/max/step appropriate for the channel is wildly off for the item. In the example I encountered below (screenshot from the semantic model page), we have an MQTT channel that allows access to the temperature setpoint for a heat pump, which provides values in Celsius. That channel has a max/min/step associated with it in Celsius. The linked item uses units of Fahrenheit, and an appropriate conversion is automatically applied, giving a reasonable value of 75 degrees F. However, the little stepper widget that is automatically generated uses the max in Celsius, forcing it to the max value of 31.5.

![Image](https://github.com/user-attachments/assets/4930f5cc-bb7f-42fa-b61f-598ad85763af)

This can be fixed by manually adding State Description metadata to the item (as mentioned in the comments of `default-standalone-item.js`, linked at the top), but this is a little annoying, and also as a new user it took me a while to figure out how to solve this, since the phrase "State Description" is pretty vague and it was not immediately obvious that this is where the min/max/step for the default widget would be set.

## Your suggestion

I don't know too much about openhab internals (besides spending half an hour searching for random keywords just now), so it's unclear to me how much this should be seen as purely a UI issue, versus an issue with the way StateDescription information for an item is derived from a linked channel (or even an issue with how MQTT specifically is behaving, though I don't think it's addon-specific). But I think the right behavior here is either:

a) Ignore the linked channel's min/max/step if a unit conversion is being done. (I think ignoring this information is better than copying over values that are almost certainly unhelpful.)

or

b) Perform a unit conversion on the min/max/step so that it is appropriate for the Item's units.

I don't know if the fix should be done on the UI side, or somewhere in `openhab-core` (or the MQTT addon). I'm reporting it here because in practice the "symptom" is only visible in the configuration of these default UI elements.

## Your environment

```yaml
runtimeInfo:
  version: 4.3.5
  buildString: Release Build
locale: en-US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.15
  javaVendor: Debian
  osName: Linux
  osVersion: 6.12.25+rpt-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 34028848
  totalMemory: 219152384
  uptime: 52093
  startLevel: 100
addons:
  - binding-astro
  - binding-mqtt
  - binding-zigbee
  - persistence-inmemory
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-jsonpath
  - transformation-map
  - ui-basic
timestamp: 2025-06-06T20:58:02.092Z
```
