### ISSUE TITLE
Search in developer bar doesn't show rules triggered

### ISSUE THREAD

**Issue by ErikDB87** [openhab/openhab-webui#3222]
## The problem

As discussed in the "community" (https://community.openhab.org/t/search-in-developer-bar-doesnt-show-rules-triggered/164442):
My search for `gWindowsOpen` only finds the item itself. But there's a rule which has a trigger that revolves around the item. Wouldn't it make sense to have those pop up as well?

Because I want to do some reorganization, and in my future setup, `gWindowsOpen` would not be a logical trigger for this rule anymore. If I had not searched manually, that would have led to problems.

![Image](https://github.com/user-attachments/assets/19dd5432-88f8-4262-b9c2-6d3fe7db9ea5)

## Expected behavior

I expect the rule to be among the search results.

## Steps to reproduce

1. Choose an item which is involved in a rule trigger.
2. Search for that item in the developer bar.

## Your environment

```yaml
runtimeInfo:
  version: 4.3.5
  buildString: Release Build
locale: nl-BE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 21.0.7
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 6.8.0-60-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 89225952
  totalMemory: 479199232
  uptime: 6071
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-buienradar
  - binding-chromecast
  - binding-enocean
  - binding-gpstracker
  - binding-hpprinter
  - binding-http
  - binding-icloud
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-semsportal
  - binding-sonos
  - binding-tradfri
  - binding-upnpcontrol
  - misc-openhabcloud
  - persistence-rrd4j
  - transformation-jsonpath
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: nl-BE
    languages:
      - nl-BE
      - nl-NL
      - nl
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/137.0.0.0 Safari/537.36
timestamp: 2025-06-10T08:01:16.474Z
```

## Browser console

![Image](https://github.com/user-attachments/assets/08d3c9fd-b083-4de5-a884-afe867460cdc)

## Browser network traffic

(this doesn't seem relevant)

## Additional information

(not the case)

**Comment by jimtng** [comment]
It seems that this already works. I can find it in my developer sidebar (OH5). @rkoshak are you able to try this on your system?

**Comment by rkoshak** [comment]
It's hard for me to test becuase most of my rules that use Items as triggers end up referring to those elsewhere,  but I think I've been able to reproduce it.

I created a new Group:Switch Item called "TestGroupItem". I created a rule that has a member of changed for this Item. The rule has nothing else in it.

```yaml
label: Test Group Item
type: Group
icon: ""
groupNames: []
tags: []
groupType: Switch
function:
  name: EQUALITY
```
```yaml
configuration: {}
triggers:
  - id: "1"
    configuration:
      groupName: TestGroupItem
    type: core.GroupStateChangeTrigger
conditions: []
actions: []
```

This rule does not show up when I search for "TestGroupItem".

<img width="264" height="295" alt="Image" src="https://github.com/user-attachments/assets/ec00932d-4ea5-4cb2-85e3-daf1fb870b7a" />

The rule only shows up when I search for Test, which makes sense as "test" is in the rules ID and label.

And just in case I used "search for all usages of this Item" on the Item's page and only the Group Item showed up.
