### ISSUE TITLE
Developer sidbar: Save "sessions"

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#3224]
## The problem

Sometimes I might be working on multiple projects at the same time and need to switch between them. Each needs a different set of Items, Things, and Rules pinned to the sidebar. 

However: 
- refreshing the web page gets rid of all the pinned entities
- closing and reopening the developer sidebar gets rid of all the pinned entities
- if something goes wrong, the page needs to be refreshed, losing all the pinned entities.

## Your suggestion

Have the ability to save a group of pinned entities and recall it. It doesn't necessarily need to be saved to the server as I know that could become a really big deal with a new registry and API endpoint and all that mess. Though this would be really nice if the saved pinned entities could be shared across browsers. 

I'd be happy if it could be saved locally in a cookie or something like that and only saved to the local browser until cookies/cache is cleared. 

## Your environment

```yaml
runtimeInfo:
  version: 5.0.0.M2
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 21.0.7
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-21.0.7+6
  osName: Linux
  osVersion: 6.8.0-60-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 371509344
  totalMemory: 990904320
  uptime: 234882
  startLevel: 70
addons:
  - automation-jsscripting
  - automation-pidcontroller
  - binding-amazonechocontrol
  - binding-astro
  - binding-chromecast
  - binding-exec
  - binding-http
  - binding-ipcamera
  - binding-mail
  - binding-mqtt
  - binding-nest
  - binding-network
  - binding-networkupstools
  - binding-openweathermap
  - binding-shelly
  - binding-vesync
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-basicprofiles
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
  - voice-pipertts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2560
    height: 1600
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101
    Firefox/138.0
timestamp: 2025-06-10T16:18:51.012Z
```
