### ISSUE TITLE
Interactive SVG-backgrounds / Does not work when loaded as part of Tabbed pages

### ISSUE THREAD

**Issue by dimka-dk** [openhab/openhab-webui#3231]
## The problem

If Tabbed pages are used to display different pages and one of those pages is Interactive SVG-backgrounds page - Interactive items gets clicked but no evens passed to the bus. Therefore no reaction happening.

Confirmed by @stefan-hoehn here https://community.openhab.org/t/interactive-svg-backgrounds-in-tabbed-page/163024/2

## Expected behavior

Interactive SVG-backgrounds should work from under Tabbed Pages.

## Steps to reproduce

Create Interactive SVG-background Page as per https://www.openhab.org/docs/ui/layout-pages-fixed.html#interactive-svg-backgrounds . 
Create main Tabbed page and add Interactive SVG-background Page as a new tab 
Compare UI reactions on UI clicks directly in Interactive SVG-background Page and loaded via Tabs

1. 

## Your environment

```
runtimeInfo:
  version: 4.3.5
  buildString: Release Build
locale: en-DK
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.6-ea
  javaVendor: Red Hat, Inc.
  javaVendorVersion: (Red_Hat-17.0.6.0.9-0.3.ea.el8)
  osName: Linux
  osVersion: 4.18.0-553.6.1.el8.x86_64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 1121256528
  totalMemory: 3145728000
  uptime: 4050311
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-energidataservice
  - binding-evohome
  - binding-exec
  - binding-fineoffsetweatherstation
  - binding-gardena
  - binding-goecharger
  - binding-heos
  - binding-http
  - binding-hue
  - binding-icalendar
  - binding-ihc
  - binding-ipcamera
  - binding-mail
  - binding-meater
  - binding-mielecloud
  - binding-modbus
  - binding-mqtt
  - binding-mybmw
  - binding-ntp
  - binding-shelly
  - binding-snmp
  - binding-urtsi
  - binding-wifiled
  - binding-zwave
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-mapdb
  - persistence-rrd4j
  - transformation-exec
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-rollershutterposition
  - transformation-scale
  - transformation-vat
  - transformation-xpath
  - transformation-xslt
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-GB
    languages:
      - en-GB
      - en-US
      - en
      - ru
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/134.0.0.0 Safari/537.36
timestamp: 2025-06-18T08:28:44.636Z

```

## Browser console

```txt

```
