### ISSUE TITLE
Custom semantic tag shown as non-semantic tag when provisioned from a file

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-webui#3244]
## The problem

Given this tag definition in $OH_CONF/tags/tags.yaml:
```yaml
version: 1
tags:
  Property_App:
    label: App2
    description: Software program
    synonyms:
      - Application
```

And this item definition:
```java
String LGTV_Application "Application" ["Control", "App2"]
```

It is correctly shown here:

![Image](https://github.com/user-attachments/assets/746cf54f-d9be-4575-bcb2-42a23dd6cf44)

But when viewing the details:

![Image](https://github.com/user-attachments/assets/8f8aab74-cd4f-42bf-88a4-16c99f597f79)

It is shown as a non-semantic tag:

![Image](https://github.com/user-attachments/assets/b51d0cd4-4d1a-4298-98f6-65ca396aa4b9)

## Expected behavior

I would assume the tag should be shown as a semantic tag in the same way as "built-in" semantic tags.

## Steps to reproduce

Create the two mentioned files.

## Your environment

```yaml
runtimeInfo:
  version: 5.0.0
  buildString: "Build #4701"
locale: en-DK
systemInfo:
  javaVersion: 21.0.5
  javaVendor: Oracle Corporation
timestamp: 2025-06-24T21:23:44.368Z
```

## Browser console

```txt

```
