### ISSUE TITLE
Picking a Point Item to use for a badge will no longer render it in the Semantic Equipment

### ISSUE THREAD

**Issue by ghostface** [openhab/openhab-webui#3246]
As suggested here https://github.com/openhab/openhab-core/issues/4777#issuecomment-3006058152 I am creating a new issue here:

> > It will be used for the badge value as you said but it will no longer show up in the Sensor Equipment.
> 
> In the Overview tabs or in the Model view? Depending on where that could point to a bug.
> 
> Just to be clear in case what I said is confusing, the humidity Item should be a direct member of both the Equipment and the Location.
> 
> > Thanks to everyone who contributed. Should I close the issue as "Close not planned" then?
> 
> Probably yes, though another issue might need to be opened for the disappearing Item issue.

I was referring to the Locations Tab -> Location Card

When I open the card I have an Equipment called "Sensor Decke", this is our starting point, notice there is abs. and rel. Luftfeuchtigkeit present.

![Image](https://github.com/user-attachments/assets/4337c909-23db-4168-bb87-e89566323ee1)

As soon I make officeCHMultisensor_RelLuftfeuchtigkeit a direct member of the location gOfficeCH, it will fix the badge but it will no longer show up in the locations card expanded Equipment of "Sensor Decke" (missing OfficeCH rel. Luftfeuchtigkeit)

![Image](https://github.com/user-attachments/assets/25fc2e26-c3d2-4f07-a402-dbc5654922c0)

Items: 

```
Number:Dimensionless    officeCHMultisensor_RelLuftfeuchtigkeit     "OfficeCH rel. Luftfeuchtigkeit  [%.1f %]"        <humidity>     (gOfficeCHSensorDecke,gOfficeCH)          ["Measurement","Humidity"]      { channel="knx:device:bridge:generic:officeCHMultisensorRf", unit="%" , stateDescription=""[ pattern="%.2f %unit%" ] }

Number:Density          officeCHMultisensor_AbsLuftfeuchtigkeit     "OfficeCH abs. Luftfeuchtigkeit  [%.1f g/m³]"     <humidity>       (gOfficeCHSensorDecke)         ["Measurement","Humidity"]      { unit="g/m³",stateDescription=""[ pattern="%.2f %unit%" ] }
```

Semantic Model Groups:

```
Group   gOfficeCH       "Office Christoph"            <office>            (gKG)        ["Office"]
            Group gOfficeLichtAlles          "Licht Alles"        <light> (gOfficeCH)     ["WallSwitch"]
            Group gOfficeCHLichtTisch  "Licht Tisch"        <light> (gOfficeCH)      ["Lightbulb"]
            Group gOfficeCHLichtFenster  "Licht Fenster"        <light> (gOfficeCH)      ["Lightbulb"]
            Group gOfficeCHLichtSpot  "Licht Spot"        <light> (gOfficeCH)      ["Lightbulb"]
            Group gOfficeCHFenster  "Fenster"        <window> (gOfficeCH)      ["Window"]
            Group gOfficeCHSteckdose  "Steckdose"        <poweroutlet> (gOfficeCH)        ["PowerOutlet"]
            Group gOfficeCHSensorSchalter         "Sensor Schalter"       <heating>   (gOfficeCH)             ["Sensor"]
            Group gOfficeCHSensorDecke         "Sensor Decke"       <heating>   (gOfficeCH)             ["Sensor"]

```

```yaml
runtimeInfo:
  version: 4.3.2
  buildString: Release Build
locale: en-AT
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.13
  javaVendor: Debian
  osName: Linux
  osVersion: 5.4.65-1-ARCH
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 32836176
  totalMemory: 367001600
  uptime: 5165386
  startLevel: 70
addons:
  - automation-jsscripting
  - binding-androiddebugbridge
  - binding-androidtv
  - binding-astro
  - binding-chromecast
  - binding-denonmarantz
  - binding-homeconnect
  - binding-hue
  - binding-ipcamera
  - binding-ipp
  - binding-knx
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-playstation
  - binding-spotify
  - binding-squeezebox
  - binding-telegram
  - binding-upnpcontrol
  - binding-weathercompany
  - binding-zwave
  - misc-openhabcloud
  - persistence-rrd4j
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
  - ui-habot
  - ui-habpanel
  - voice-voicerss
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.2
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2133
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0
timestamp: 2025-06-27T08:51:53.877Z

```

Your Environment

    Openhab 4.3.5
    Archlinux
    Raspberrypi 4
