### ISSUE TITLE
[MainUI] See and edit Item metadata on the Item page

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#397]
More discussion of this exists at https://community.openhab.org/t/openhab-3-0-my-getting-started-and-notes/106467.

I'm aware that the metadata is stored in a separate JSONDB store and the REST API for it is separate. And I do recognize the WebUI does the best it can with the REST API as it is. But it would be a huge improvement if we could have a list of metadata namespaces to choose from instead of just a text field. Even better would be a list of those name spaces that actually are on that Item. Even better would be to just see all the custom metadata applied to that Item. 

Even a modest system might have lots of metadata and as it is now one must remember the namespace exactly in order to see it.

Flipping things around, it would be quite useful to have a way to find all the Items that have a given custom metadata namespace applied. I think the REST API easily supports that.

This is a usability feature request.

**Comment by ghys** [comment]
Here's how I'd suggest we tackle this issue without changing the API:

We introduce a new concept: "metadata editors". The idea is that it might be useful to have pages in the UI dedicated to configure a particular metadata namespace, like the built-in ones (alexa, homekit, etc.) but those would be user-defined.

So we consider them to be a UI concept, like pages or widgets, which gives us the excuse to use a new type of UI components to store them. For instance `system:metadataeditor` or something like that. They will be therefore managed with `/rest/ui/components/system:metadataeditor` and stored in `userdata/jsondb/uicomponents_system_metadataeditor.json`

A new management menu option would be added to the developer tools, with a list and YAML editor, very much like the existing Widgets.

The "props" of the root UI component would be used to configure the parameters and groups that will be presented to the user as a config sheet when configuring the metadata for an item. This allows to configure the metadata in a both standardized and user-friendly way than simply editing them in YAML. They are very similar to the existing concept of metadata providers in openHAB, which have config descriptions (see for instance http://localhost:8080/rest/config-descriptions?scheme=metadata), but cannot be defined easily by the user.

And we could actually make a [MetadataConfigDescriptionProvider](https://next.openhab.org/javadoc/latest/org/openhab/core/config/core/metadata/metadataconfigdescriptionprovider) providing metadata config descriptions from the `system:metadataeditor` components like we have a [SitemapProvider](https://next.openhab.org/javadoc/latest/org/openhab/core/model/sitemap/sitemapprovider) providing sitemaps from the `system:sitemap` components.

The UID of the root UI component would be the metadata namespace, and a "label" config option would be the display name.

Example:
```yaml
uid: mymetadata
props:
  parameterGroups: []
  parameters:
   - name: value
     label: Main Value
     description: The main value
     type: TEXT
   - name: param1
     label: Parameter 1
     description: What the parameter is for
     type: BOOLEAN
   - name: param2
     label: Parameter 2
     description: Another parameter
     type: TEXT
     limitToOptions: true
     options:
      - value: option1
        label: Option 1
      - value: option2
        label: Option 2
component: MetadataEditor     # useless but actually required
config:
  label: My Metadata
```

In the item details page and the model page, the UI will retrieve these additional metadata editors and add additional buttons to edit the related namespaces.

![image](https://user-images.githubusercontent.com/2004147/97285638-c069cf00-1842-11eb-838f-03b20222b31b.png)

It will present the parameters defined in "props" in the first Config tab if any, in a config sheet. The example above would look like this:

![image](https://user-images.githubusercontent.com/2004147/97286911-3f133c00-1844-11eb-8111-dca80c122f58.png)

If there is a "value" parameter (of type TEXT) it go to the main value of the metadata, the rest will go to the config map.
If there are no parameters only the Code tab will be shown.

Wdyt?

**Comment by cherub-i** [comment]
Hello, are there any plans to address this topic in one of the coming releases?
I use three custom rules which use their own metadata and the UI fails to support me properly here. I understand, that OH is moving towards focusing more on an UI approach for setting up the system (and OH3 is doing a great job at this!), so not being able to see (let alone change) custom meta data really is a limitation for me.

**Comment by pacive** [comment]
Regarding this topic: I noticed that when getting item data from the `/rest/items` it supplies a predefined list of metadata namespaces. If specifying the query string as `?metadata=%20` (i.e. a space character) all metadata is returned for the items. Not sure if this is intentional or not, but it seems it could help with displaying custom metadata in addition to the predefined ones.

**Comment by ssalonen** [comment]
Use case I encounter with this limitation: 

Some of the more advanced rules in community forums now utilize item metadata to be more generic. I have also followed this practice in my own rules.

The fact that I am forced to use raw REST API makes this quite clunky. Without API calls it is not possible to know whether the item has the custom metadata associated, let alone view/change the value.

My parameters are very simple and a simple text box would suffice.

Example attached as images below.

![image](https://user-images.githubusercontent.com/315866/147206415-4a484288-42c9-44fa-9ca3-a0755aaa15ab.jpeg)

![image](https://user-images.githubusercontent.com/315866/147206430-c2faa8bf-3023-4ebd-85b6-446ca86f0323.jpeg)

**Comment by ThaDaVos** [comment]
Any progress on this? Loving the new Marketplace template rules - but not being able to see and edit the metadata easily isn't really that helpful

**Comment by lordjaxom** [comment]
+1

**Comment by stefan-hoehn** [comment]
#1623 Allows editing existing namespace now

However providing a UI editor for custom namespaces can be pretty tricky because I would have to support a lot of flexibility in terms of configuration hierarchy. 

While I was implementing the blockly blocks for metadata (coming as soon as #1597 is merged), I noticed how flexible it is. Here are some samples you can do with the yaml editor but i would image it becomes pretty complicated with a UI

````
value: ON
config:
  default:
    setpoints: 2
    setpoint1:
      time: 22:00
      degrees: 19
    setpoint2:
      time: 08:00
      degrees: 21.5

````

````
value: ON
config:
  currentDelayIndex: "0"
  nextAlert: 2023-01-17 20:50:01
  alarmActive: OFF
````

````
value: Stefan
config:
  oone:
    two: "456"
  close: 22:00
  open: 03:03
  ooone: "123"
  one:
    two:
      three: "756"

````

Note that I use all of these kind of configurations in my rules...
