### ISSUE TITLE
[Main UI] Icons not showing item state

### ISSUE THREAD

**Issue by kuifje123** [openhab/openhab-webui#403]
Using OH3 build 1966.

When defining an (openhab provided) icon to a toggle item component, I do not see the status of the item reflected in the icon. In the example below, the icon shown is always the lightbulb-on, independent on the status of the item.
Are dynamic icons implemented already?

```
component: oh-list-card
config:
  simpleList: false
  mediaList: true
  visible: =items.g1.state == 'ON'
slots:
  default:
    - component: oh-toggle-item
      config:
        title: Overloop
        icon: oh:lightbulb
        item: LightHall1
        color: green
```
