### ISSUE TITLE
[MainUI] Possibility to clear multiple variables at once

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-webui#407]
It would be nice to clear multiple variables at once (e.g. on a button click)
'clearVariable' currently only works with one parameter.

**Comment by ghys** [comment]
This rang a bell so I had to check and apparently we were on the same page 🙂 

https://github.com/openhab/openhab-webui/blob/838d79eac2254f028b26adc57c08899dbc40bc9d/bundles/org.openhab.ui/web/src/components/widgets/system/oh-button.vue#L18-L23
(same for oh-link)

Looks like if you provide an array it should clear all the variables in it! Let me know if it works for you.
Should have been documented in the parameter description though. I'll probably review all of those at some point and will add the info.

**Comment by rgrollfitz** [comment]
@ghys Works flawlessly :) - Thank you!

So we´re already on the topic of arrays (and before I open another issue)... wouldn´t it be nice to also have the option to use arrays on 'actions'?! (at least for the combination 'action: command' and 'action: variable' it should work (as there are separate 'actionVariable' and 'actionCommand'))?!

**Usecase:**
I´m currently working on a dynamic button list (which getting its values from a string item) for the very niche usecase of a phonebook for sending out sms to contacts.

Currently, I have to use another button to execute the 'action: variable' with it´s commands to (re)load 
![phonebook](https://user-images.githubusercontent.com/71724877/96350846-04790900-10b8-11eb-892b-50610a646955.gif)

```
          - component: oh-button
            config:
              text: (Re)load contacts
              action: variable
              actionVariable: contact
              actionVariableValue: =items.contactSMS.state
          - component: f7-row
            slots:
              default:
                - component: oh-button
                  config:
                    text: '=(vars.contact.split(";")[0] === undefined) ? "" : vars.contact.split(";")[0].split(",number:")[0].split(["name:"])'
                    tooltip: '=(items.contactSMS.state != "") ? (vars.contact.split(";")[1]).split([",number:"]).pop() : ""'
                    visible: =vars.contact.split(";")[0] != undefined
                    action: variable
                    actionVariable: viewContact
                    actionVariableValue: contact
```

And last but not least - is there anything like a 'onLoad' function when loading a widget? I´m sure more questions will come, so be aware. :-P
