### ISSUE TITLE
[MainUI] Combine 'command' & 'variable'-action on components

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-webui#409]
Wouldn´t it be nice to have the option to use multiple actions (most important 'variable' and 'command' from my perspective) on all action-able components?! There are already separate 'actionVariable' and 'actionCommand' available.

**Usecase:**
I´m currently working on a dynamic button list (which getting its values from a string item) for the very niche usecase of a phonebook for sending out sms to contacts.

Currently, I have to use another button to execute the 'action: variable' with it´s commands to (re)load 
![phonebook](https://user-images.githubusercontent.com/71724877/96350846-04790900-10b8-11eb-892b-50610a646955.gif)

```
          - component: oh-button
            config:
              text: (Re)load contacts
              action: variable
              actionVariable: contact
              actionVariableValue: =items.contactSMS.state
          - component: f7-row
            slots:
              default:
                - component: oh-button
                  config:
                    text: '=(vars.contact.split(";")[0] === undefined) ? "" : vars.contact.split(";")[0].split(",number:")[0].split(["name:"])'
                    tooltip: '=(items.contactSMS.state != "") ? (vars.contact.split(";")[1]).split([",number:"]).pop() : ""'
                    visible: =vars.contact.split(";")[0] != undefined
                    action: variable
                    actionVariable: viewContact
                    actionVariableValue: contact
```

Regarding this widget, it would be also interesting, if theres anything like a 'onLoad' function when loading a widget? I´m sure more questions will come, so be aware. :-P
