### ISSUE TITLE
[MainUI] oh-swiper / f7-swiper doesn`t work inside sheet and popups

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-webui#436]
If you open up a swiper-element (oh-swiper as well as the f7- one) in a sheet or a popup, it won´t function as expected anymore (no automatic snapping) - also all set params (e.g. 'slidesPerView: 3') will be ignored.

It works flawlessly if used on a separate page.

**Comment by ghys** [comment]
Swiper or slider? Swiper I assume? I have barely used it.

**Comment by rgrollfitz** [comment]
Yeah, swiper - sry for the confusion.

I didn´t used it much also - but tried to recreate another UI-element from the internet and came across it.
![slider_page](https://user-images.githubusercontent.com/71724877/97078657-de8ac180-15ed-11eb-92ee-e769d15dac9b.PNG)

![slider_popup](https://user-images.githubusercontent.com/71724877/97078661-e34f7580-15ed-11eb-81b2-c1ab18d6463f.PNG)

**Comment by ghys** [comment]
Can you post a source example?

**Comment by rgrollfitz** [comment]
Of course! Simplified it a bit for demonstration.
```
- component: oh-swiper
      config:
        params:
          slidesPerView: 3
      slots:
        default:
          - component: oh-label-card
            config:
              title: "card #1"
          - component: oh-label-card
            config:
              title: "card #2"
          - component: oh-label-card
            config:
              title: "card #3"              
          - component: oh-label-card
            config:
              title: "card #4"
          - component: oh-label-card
            config:
              title: "card #5"
          - component: oh-label-card
            config:
              title: "card #6"                       
```

Same with 'f7-swiper' and its corrosponding 'f7-swiper-slide' components - as soon as you resize the page its get displayed corrected. Presumably due to the calculation of the width of the parent element?!

**Comment by ghys** [comment]
I suppose, maybe there's a way to initialize it later, after the popup has rendered its proper size, with some trick, but this needs investigation.

**Comment by rgrollfitz** [comment]
For anybody who is searching for this - You can reinitialize the swiperby setting a observer with the following parameters in the component-config:

```
- component: oh-swiper
  config:
     params:
       observer: true
       observeParents: true
       observeSlideChildren: true
```
