### ISSUE TITLE
[MainUI] Custom Widget: F7 icon not shown on oh-button

### ISSUE THREAD

**Issue by tarag** [openhab/openhab-webui#513]
I created a custom widget with a segmented control with 3 buttons, I can't get the icons to show in the oh-button neither following the indicated syntax nor using a slot with an f7-icon component inside.

Using either a `f7-button` directly works as expected.

```yaml
                - component: f7-segmented
                  config:
                    raised: true
                  slots:
                    default:
                      - component: oh-button
                        config:
                          icon: f7:wind
                      - component: f7-button
                        config:
                          icon-f7: wind
                      - component: oh-button
                        slots:
                          default:
                            - component: f7-icon
                              config:
                                f7: wind
```

It appears that the html generated is not consistent between oh-button and the native f7-button components:

```html
<div class="segmented segmented-raised">
    <a href="#" class="button"><i class="icon f7:wind"></i></a>
    <a href="#" class="button"><i class="icon f7-icons">wind</i></a>
    <a href="#" class="button"></a>
</div>
```

Only the middle one works.

**Comment by ghys** [comment]
This is a description mistake - the oh-button is just a f7-button able to execute an action, but apart from that, all its properties are forwarded to the underlying f7-button.
So this would work:
```yaml
component: oh-button
config:
  icon-f7: wind
```
