### ISSUE TITLE
Layout rendering difference between Widget Editor Preview and actual page: columns spacing.

### ISSUE THREAD

**Issue by tarag** [openhab/openhab-webui#514]
I have a layout issue when the custom widget is rendered in the actual page, whereas in the preview of the widget editor it looks ok.
When in runtime, there is no spacing between f7-col components.

Widget Editor:
<img width="945" alt="Screenshot 2020-11-12 at 15 46 07" src="https://user-images.githubusercontent.com/11686092/98954794-777e6f80-24fe-11eb-8676-cf627d8bc7ca.png">

Runtime page:
<img width="947" alt="Screenshot 2020-11-12 at 15 46 19" src="https://user-images.githubusercontent.com/11686092/98954804-79e0c980-24fe-11eb-9f44-824f34d71d15.png">

The configuration of the widget is:
```yaml
uid: widget_5348731943
tags: []
props:
  parameters:
    - description: Title of the cell
      label: Title
      name: title
      required: false
      type: TEXT
    - description: Footer of the cell
      label: Footer
      name: footer
      required: false
      type: TEXT
    - context: This is the context
      description: The name prefix of widget items
      label: Prefix
      name: prefix
      required: false
      type: TEXT
  parameterGroups: []
timestamp: Nov 12, 2020, 2:54:56 PM
component: f7-card
config:
  title: =props.title
  footer: =props.footer
slots:
  content:
    - component: f7-row
      config:
        class:
          - vasmargin
      slots:
        default:
          - component: f7-col
            config:
              class:
                - text-align-center
            slots:
              default:
                - component: f7-gauge
                  config:
                    value: 0.5
                    value-text: =items[props.prefix + 'TH_SET'].state
                    type: semicircle
                    border-color: "=items[props.prefix + 'TH_SW'].state == 'ON' ? '#e64a19' :  '#e6baad'"
                    labelText: "='Actual: ' + items[props.prefix + 'TH_TEMP'].displayState"
                  slots:
                    default:
                      - component: oh-toggle
                        config:
                          color: green
                          value: 0.5
                          value-text: =items[props.prefix + 'TH_SET'].state
                          type: semicircle
                          labelText: "='Actual: ' + items[props.prefix + 'TH_TEMP'"
                - component: oh-toggle
                  config:
                    style:
                      position: absolute
                      left: 50%
                      transform: translateX(60px)
                    item: =props.prefix + 'TH_SW'
    - component: f7-row
      config:
        class:
          - margin
      slots:
        default:
          - component: f7-col
            config:
              width: 100
              large: 50
            slots:
              default:
                - component: f7-segmented
                  config:
                    class: -margin
                    raised: true
                  slots:
                    default:
                      - component: oh-button
                        config:
                          text: "-"
                          action: command
                          actionItem: =props.prefix + 'TH_SET'
                          actionCommand: = +items[props.prefix + 'TH_SET'].state - 0.5
                      - component: oh-button
                        config:
                          text: 18
                          action: command
                          actionItem: =props.prefix + 'TH_SET'
                          actionCommand: 18
                      - component: oh-button
                        config:
                          text: 20
                          action: command
                          actionItem: =props.prefix + 'TH_SET'
                          actionCommand: 20
                      - component: oh-button
                        config:
                          text: 22
                          action: command
                          actionItem: =props.prefix + 'TH_SET'
                          actionCommand: 22
                      - component: oh-button
                        config:
                          text: +
                          action: command
                          actionItem: =props.prefix + 'TH_SET'
                          actionCommand: = +items[props.prefix + 'TH_SET'].state + 0.5
          - component: f7-col
            config:
              width: 100
              large: 50
            slots:
              default:
                - component: f7-segmented
                  config:
                    raised: true
                  slots:
                    default:
                      - component: oh-button
                        config:
                          icon-f7: wind
                          iconSize: 15px
                          action: command
                          actionItem: =props.prefix + 'SPLIT_FS'
                          actionCommand: 33
                          active: =items[props.prefix + 'SPLIT_FS'].state == 33
                      - component: oh-button
                        config:
                          icon-f7: wind
                          iconSize: 18px
                          action: command
                          actionItem: =props.prefix + 'SPLIT_FS'
                          actionCommand: 67
                          active: =items[props.prefix + 'SPLIT_FS'].state == 67
                      - component: oh-button
                        config:
                          icon-f7: wind
                          iconSize: 21px
                          action: command
                          actionItem: =props.prefix + 'SPLIT_FS'
                          actionCommand: 100
                          active: =items[props.prefix + 'SPLIT_FS'].state == 100
                      - component: oh-button
                        config:
                          text: Auto
                          action: command
                          actionItem: =props.prefix + 'SPLIT_FA'
                          actionCommand: ON
                          active: =items[props.prefix + 'SPLIT_FA'].state == 'ON'
    - component: f7-row
      config:
        class:
          - margin
      slots:
        default:
          - component: f7-col
            config:
              width: 100
              large: 50
            slots:
              default:
                - component: f7-segmented
                  config:
                    raised: true
                  slots:
                    default:
                      - component: oh-button
                        config:
                          text: Cool ❄️
                          action: command
                          actionItem: =props.prefix + 'SPLIT_MO'
                          actionCommand: Cool
                          active: =items[props.prefix + 'SPLIT_MO'].state == 'Cool'
                      - component: oh-button
                        config:
                          text: Auto 🔄
                          action: command
                          actionItem: =props.prefix + 'SPLIT_MO'
                          actionCommand: Auto
                          active: =items[props.prefix + 'SPLIT_MO'].state == 'Auto'
                      - component: oh-button
                        config:
                          text: Heat ☀️
                          action: command
                          actionItem: =props.prefix + 'SPLIT_MO'
                          actionCommand: Heat
                          active: =items[props.prefix + 'SPLIT_MO'].state == 'Heat'
          - component: f7-col
            config:
              width: 100
              large: 50
            slots:
              default:
                - component: f7-segmented
                  config:
                    raised: true
                  slots:
                    default:
                      - component: oh-button
                        config:
                          text: Eco 🌳
                          action: command
                          actionItem: =props.prefix + 'TH_MO'
                          actionCommand: Standby
                          active: =items[props.prefix + 'TH_MO'].state == 'Standby'
                      - component: oh-button
                        config:
                          text: Comfort
                          action: command
                          actionItem: =props.prefix + 'TH_MO'
                          actionCommand: Comfort
                          active: =items[props.prefix + 'TH_MO'].state == 'Comfort'
```
