### ISSUE TITLE
Allow negative values in Gauge widget configuration

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-webui#519]
I would like to use the Gauge widget to show temperatures. On the widget configuration page it is not possible to enter a negative minimum value. In the YAML editor it is possible but it seems to be ignored.

**Comment by ghys** [comment]
Works here... Please provide a reproductible test case.

```yaml
component: oh-grid-row
config: {}
slots:
  default:
    - component: oh-grid-col
      config: {}
      slots:
        default:
          - component: oh-slider-card
            config:
              step: 0.1
              scale: true
              min: -10
              max: 10
              scaleSteps: 10
              scaleSubSteps: 10
              label: true
              item: TestNumber
              unit: " °C"
    - component: oh-grid-col
      config: {}
      slots:
        default:
          - component: oh-gauge-card
            config:
              min: -10
              max: 10
              type: semicircle
              item: TestNumber
```

![image](https://user-images.githubusercontent.com/2004147/99248169-540e3a00-2808-11eb-9757-f9cea912e1e6.png)
![image](https://user-images.githubusercontent.com/2004147/99248213-64261980-2808-11eb-8d16-a7247d766daf.png)
