### ISSUE TITLE
[MainUI] Import/Export for rules as yaml

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#529]
## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: "Build #2008"
locale: en_US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.8
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.41+23-CA
  osName: Linux
  osVersion: 5.4.0-54-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 157852528
  totalMemory: 300941312
bindings:
  - astro
  - exec
  - network
  - openweathermap
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 2
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
timestamp: 2020-11-17T20:32:51.530Z
```

## The problem

I'm porting a bunch of rules that I have made available in my repo to JavaScript JSONDB rules. I'm exporting the YAML to my repo (copy and paste). Users will need to create a new rule in MainUI, click on the code tab and paste the YAML in there.

## Your suggestion

It would be a little nicer to have an import/export function for rules. The existing YAML format is more than fine. But it would be a whole lot easier on both ends to be able to import/export the YAML as a file. This could provide a little bit of convenience until such time that we have a marketplace where we can distribute these sorts of things.

## Additional information

This is a very low priority request. There are not many who will be using a feature like this I think in the short run. Depending on how long it takes to build a marketplace it might become more important over time though.
