### ISSUE TITLE
[MainUI] Thing creation and editing pages are broken until logging out and back in

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#541]
## The problem

When creating or editing a Thing the UI does not render the forms for most of the options. Clicking "Show advanced" shows nothing or only one or two labels (not forms). The code tab is blank and uneditable.

![Peek 2020-11-19 12-20](https://user-images.githubusercontent.com/6385096/99713907-202e5100-2a62-11eb-973f-23e216af80ae.gif)

Logging out of the session and logging back in seems to fix the problem. 

This occurred after an update from build 2009 to 2010

## Expected behavior

If the login session times out or somehow otherwise becomes no longer valid the UI should detect this and inform the user somehow rather than allow the user to continue with half broken UI pages. It was not at all clear that my session was the root of the problem.

## Steps to reproduce

1. Go to Things
2. Select any Thing that has advanced options
3. Open that Thing's page and click on "Show advanced"
4. Click on "code"

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: "Build #2019"
locale: en_US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.8
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.41+23-CA
  osName: Linux
  osVersion: 5.4.0-54-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 149439536
  totalMemory: 287309824
bindings:
  - astro
  - mail
  - mqtt
  - network
  - openweathermap
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 2
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
timestamp: 2020-11-19T19:33:58.450Z

```

## Browser console

Nothing seems relevant but I can try again if there is something I need to look for.
```txt

```

## Additional information

I'm running the docker version of OH.
