### ISSUE TITLE
Deleting values when configuring grid for chart renders differently from initial setting

### ISSUE THREAD

**Issue by jpharvey** [openhab/openhab-webui#553]
## The problem
Changing a value when configuring the grid of a chart such as left or right affects the chart as expected. Then removing the value by pressing the x changes the way the chart is drawn to the same as 0 being entered instead of the initial default value.
The yaml in this case contains left: null etc. which causes the chart to be draw differently than if the value is missing.

## Expected behavior
THe chara

## Steps to reproduce

1. 

## Your environment

```yaml
component: oh-chart-grid
config:
  show: true
  width: 1400px
  height: 400px
  left: 480px
  right: null
slots: null

```

## Browser console

```txt

```

## Additional information
This is the second case of something similar i have reported. Would it be better for the x to remove the complete yaml entry instead of setting it to null and all rendering having to cope with null as well as no value?
