### ISSUE TITLE
[main UI] Create Points from a Thing leads to 400 Bad Request

### ISSUE THREAD

**Issue by jeffstagedoor** [openhab/openhab-webui#583]
## The problem

In Model editing, when I create Points from a Thing (without existing Items) I get back an *"An error occured while creating the items: Bad Request."*

Looking at the browsers network-tab I see a request with an *empty first object in the json-array* of the payload, which might be related:
![image](https://user-images.githubusercontent.com/15057361/100678956-bc176100-336e-11eb-9014-a4b335533053.png)

## Expected behavior
Adding the points/items without errors

## Steps to reproduce

1.  In Model-Editing "Create Points from Thing"
![image](https://user-images.githubusercontent.com/15057361/100679102-0698dd80-336f-11eb-9f27-2dcb42f3a416.png)
2.  Select thing and 1 or more channels, click "Add to model"
![image](https://user-images.githubusercontent.com/15057361/100679164-2e884100-336f-11eb-830f-571fe7fc3fce.png)
3. See the Popup-Error "An error occured while creating the items: Bad Request."

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0.M3
  buildString: Milestone Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.72-v7+
  osArchitecture: arm
bindings:
  - astro
  - homematic
  - mqtt
  - velux
clientInfo:
  device:
    windows: true
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/86.0.4240.198 Safari/537.36
timestamp: 2020-11-30T23:54:05.703Z
```
I'm running Vivaldi Browser.

## Browser network traffic

![image](https://user-images.githubusercontent.com/15057361/100679708-5d52e700-3370-11eb-961b-3706c5d21f12.png)
