### ISSUE TITLE
[MainUI] Map view page editing: map centered on Berlin

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#588]
## The problem

When editing a map view page and using the run mode, the displayed map is sometimes centered on Berlin. It does not happen the first time you enable the run mode but always the next times.

## Expected behavior

Centering on the item position.

## Steps to reproduce

Here is an example of map view page:
```
config:
  label: Test map view
  sidebar: true
markers:
  - component: oh-map-marker
    config:
      item: OWMLocation
      label: Source
    slots:
      default: []
```

1. Open the page view editing

![image](https://user-images.githubusercontent.com/10186704/100868784-64771380-349c-11eb-9941-a3b17188a9cd.png)

2. enable run mode with the switch at bottom right the => works well, the map is centered on the item position
3; disable run mode with the switch at bottom right
4. enable run mode with the switch at bottom right the => the map is wrongly centered on Berlin
5; disable run mode with the switch at bottom right
6. enable run mode with the switch at bottom right the => the map is wrongly centered on Berlin
...

If I do F5 to refresh the page, we restart at step 2 again.

## Your environment

Not depending on environment.

## Browser console

Nothing special in the the browser console.

## Browser network traffic

I see network traffic the first time (when it works) but not the next times (when it failed and centered on Berlin).
