### ISSUE TITLE
Dynamic assigning actionAnalyzerItems: in component: oh-label-card not working

### ISSUE THREAD

**Issue by JAMESBOWLER** [openhab/openhab-webui#598]
## The problem

When trying to use props in actionAnalyzerItems: it opens new blank Analyzer page.
```yaml
          - component: oh-label-card
            config:
              action: analyzer
              trendItem: =(props.item + '_CurrentTemperature')
              item: =(props.item + '_CurrentTemperature')
              actionAnalyzerItems:
                -  =(props.item + '_CurrentHumidity')
                -  =(props.item + '_CurrentTemperature')
```
Trend item and item state show correctly
## Expected behavior

This works and is displayed correctly when pressed.
```yaml
            - component: oh-label-card
            config:
              action: analyzer
              trendItem: =(props.item + '_CurrentTemperature')
              item: =(props.item + '_CurrentTemperature')
              actionAnalyzerItems:
                - LoungeRoomAircon_CurrentHumidity
                - LoungeRoomAircon_CurrentTemperature
```
## Steps to reproduce

1. Create custom widget and set prop then click on widget.
```yaml
uid: widget_dcf61f01d1
tags: []
props:
  parameters:
    - description: A text prop
      label: Prop 1
      name: prop1
      required: false
      type: TEXT
    - context: item
      description: An item to control
      label: Item
      name: item
      required: false
      type: TEXT
  parameterGroups: []
timestamp: Dec 7, 2020, 11:06:26 AM
component: oh-label-card
config:
  title: '=(props.item) ? "State of " + props.item : "Set props to test!"'
  footer: =props.prop1
  content: =items[props.item].displayState || items[props.item].state
  action: analyzer
  trendItem: =props.item
  item: =props.item
  actionAnalyzerItems:
    - =props.item
```
If you use the correct name of the item it works e.g.
```yaml
  actionAnalyzerItems:
    - LoungeRoomAircon_CurrentHumidity
```

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0.M4
  buildString: Milestone Build
locale: en_AU
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.72-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 62744776
  totalMemory: 201326592
bindings:
  - astro
  - chromecast
  - irtrans
  - mqtt
  - panasonictv
  - sensibo
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
timestamp: 2020-12-07T09:51:38.003Z
```

## Browser console

```txt
No error shown in logs
```

**Comment by ghys** [comment]
Try something like
`actionAnalyzerItems: =[props.item + '_CurrentHumidity', props.item + '_CurrentTemperature']`

**Comment by JAMESBOWLER** [comment]
Awesome that works I guess its not a bug but a lack of understanding on my part of how it works.

Thankyou 

This is a working example 
```yaml
uid: widget_dcf61f01d1
tags: []
props:
  parameters:
    - description: A text prop
      label: Prop 1
      name: prop1
      required: false
      type: TEXT
    - context: item
      description: An item to control
      label: Item
      name: item
      required: false
      type: TEXT
  parameterGroups: []
component: oh-label-card
config:
  title: '=(props.item) ? "State of " + props.item : "Set props to test!"'
  footer: =props.prop1
  content: =items[props.item].displayState || items[props.item].state
  action: analyzer
  trendItem: =props.item
  item: =props.item
  actionAnalyzerItems: =[props.item]

```
