### ISSUE TITLE
No Blocky button appears while opening script editor from rule defintion. 

### ISSUE THREAD

**Issue by cinadr** [openhab/openhab-webui#610]
## The problem

In Openhab 3 M3-M5-#2050 there is no Blockly button appears while adding script action and editing it during a new rule definition. Blocky only appears while defining new independent script in script editor directly.

![No blockly](https://user-images.githubusercontent.com/16361576/101627369-90574380-3a1e-11eb-84fc-bbe4c6910749.gif)

## Expected behavior

Blockly button shuold appear while editing script inside rule editor. 

## Steps to reproduce

1. Click Administation menu Rules item
2. Click blue cross right bottom to add new rule
3. Click Add Action
4. Select Execute a given script
5. Click Edit script. Blockly blue button should be on the middle of the editor.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: "Build #2050"
locale: hu_HU
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.8
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.41+23-CA
  osName: Linux
  osVersion: 3.10.0-1062.9.1.el7.x86_64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 144716856
  totalMemory: 3924819968
bindings:
  - ambientweather1400ip
  - astro
  - chromecast
  - darksky
  - evohome
  - mqtt
  - ntp
  - remoteopenhab
  - samsungtv
  - unifi
  - zoneminder
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.0020242929458618
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: hu
    languages:
      - hu
      - hu-HU
      - en-US
      - en
    onLine: true
    platform: Linux aarch64
  screen:
    width: 1676
    height: 1047
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-09T12:03:49.419Z
```

## Browser console

```txt
Nothing relevant displayed.
```

## Browser network traffic

![image](https://user-images.githubusercontent.com/16361576/101628052-884bd380-3a1f-11eb-93f4-47cf45520756.png)
