### ISSUE TITLE
No all values showed in graph

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab-webui#611]
## The problem

All values aren't showed in the graph. It seem always the last 1-2 hours are missing.

The last value on the graph below is 58 lux, at 11:10:

![bild](https://user-images.githubusercontent.com/2837262/101623574-f04aeb80-3a18-11eb-9b1d-cf21e12de026.png)

At the same time I had the following values in my persistence database (pasting from mysql):
| 2020-12-09 11:00:32 |  40.00 |
| 2020-12-09 11:10:32 |  58.00 |
| 2020-12-09 11:20:32 |  23.00 |
| 2020-12-09 11:30:32 |  82.00 |
| 2020-12-09 11:40:32 | 106.00 |
| 2020-12-09 11:50:32 |  43.00 |
| 2020-12-09 12:00:32 |  30.00 |
| 2020-12-09 12:10:32 |  66.00 |

## Expected behavior
The graph should show all values.

## Steps to reproduce

1. Go to an Item in the UI
2. Click on Analyze

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0.M5
  buildString: Milestone Build
locale: sv_SE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+100-CA
  osName: Linux
  osVersion: 5.9.11-rockchip64
  osArchitecture: aarch64
  availableProcessors: 6
  freeMemory: 67019920
  totalMemory: 442499072
bindings:
  - exec
  - mail
  - networkupstools
  - pushover
  - robonect
  - sonos
  - systeminfo
  - tellstick
  - tibber
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: sv-SE
    languages:
      - sv-SE
      - sv
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101
    Firefox/83.0
timestamp: 2020-12-09T12:32:19.503Z


```

## Additional information

Using jdbc-mysql persistence.

Also see discussion at https://community.openhab.org/t/small-graph-glitches-in-oh3/109734
