### ISSUE TITLE
[Main-UI] Group[:itemtype[:function]] does not accept all itemtypes

### ISSUE THREAD

**Issue by Rosi2143** [openhab/openhab-webui#616]
## The problem
If I add my group definition in "Developer Tools/Add Items from Textual Definition" it does not accept itemtype
* String
* Location
* Color
* Image
* Player

it does accept
* Number
* Contact
* DateTime
* Dimmer
* Switch
* RollerShutter

![Unbenannt](https://user-images.githubusercontent.com/6383737/101833138-d1437b00-3b38-11eb-9cf4-cc74baebb7f8.JPG)

## Expected behavior
all [defined types](https://next.openhab.org/docs/configuration/items.html#type) should be accepted.

## Your environment
```yaml
runtimeInfo:
  version: 3.0.0
  buildString: "Build #2061"
locale: en_DE
systemInfo:
  configFolder: /home/micha/Downloads/openHAB3/conf
  userdataFolder: /home/micha/Downloads/openHAB3/userdata
  logFolder: /home/micha/Downloads/openHAB3/userdata/logs
  javaVersion: 11.0.9.1
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.4.0-56-generic
  osArchitecture: amd64
  availableProcessors: 3
  freeMemory: 37202176
  totalMemory: 132120576
bindings:
  - astro
  - coronastats
  - homematic
  - hue
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 3
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 950
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
timestamp: 2020-12-10T21:41:59.988Z
```

## Browser console
none

## Browser network traffic
none

## Additional information
none
