### ISSUE TITLE
Don't save thing when coming back from the Code tab if it hasn't changed

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-webui#618]
## The problem
In thing detail page, if I just look to Code tab and then switch back to Thing or Channels tab, the Thing gets destroyed and re-initialized.

## Expected behavior
Thing get destroyed/initialized only if its Code definition is changed and saved from Code tab

## Steps to reproduce
1. from MainUI open a Thing detail
2. go to Code tab
3. do not change any code, nor click Save
4. click on Channels tab
Looking at the log it's clear that the thing is first destroyed then re-created: initialize() is called on thing handler

## Your environment
I am on 3.0.0-SNAPSHOT
```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Unknown Build No.
locale: it_IT
systemInfo:
  configFolder: ----
  userdataFolder: ----
  javaVersion: 11.0.8
  javaVendor: Oracle Corporation
  javaVendorVersion: "18.9"
  osName: Windows 10
  osVersion: "10.0"
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 108136160
  totalMemory: 161480704
bindings:
  - astro
  - openwebnet
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 4
    language: it
    languages:
      - it
      - en-GB
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-10T23:32:29.715Z

```
