### ISSUE TITLE
Visual glitch in Items list

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab-webui#619]
## The problem

In the bottom of the Items list, the last Items continues below the end of the white background panel.

![bild](https://user-images.githubusercontent.com/2837262/101876052-1513a000-3b8c-11eb-89ef-cea6b6a5e98c.png)

## Steps to reproduce

1. Open the UI in Firefox
2. Go to Settings -> Items
3. Scroll to the bottom

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0.M5
  buildString: Milestone Build
locale: sv_SE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+100-CA
  osName: Linux
  osVersion: 5.9.11-rockchip64
  osArchitecture: aarch64
  availableProcessors: 6
  freeMemory: 152783784
  totalMemory: 442499072
bindings:
  - exec
  - mail
  - networkupstools
  - pushover
  - robonect
  - sonos
  - systeminfo
  - tellstick
  - tibber
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: sv-SE
    languages:
      - sv-SE
      - sv
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101
    Firefox/83.0
timestamp: 2020-12-11T07:38:39.371Z

```

## Additional information

Can't seem to reproduce the problem on Chrome or Edge, so I guess it's Firefox specific.
