### ISSUE TITLE
Widgets' External URL action not working

### ISSUE THREAD

**Issue by hubsif** [openhab/openhab-webui#630]
## The problem

When defining an "External URL"-Action e.g. for a Label click, the url does not open.

## Expected behavior

URL gets opened

## Steps to reproduce

1. add a label with External URL action and url, sample:
```yaml
- component: oh-label-card
  config:
    action: url
    actionPage: page:overview
    actionUrl: https://www.openhab.org
    label: somelabel
```

2. open the page and click the label. Console shows `opening URL: https://www.openhab.org` but nothing happens

## Your environment

OH3 MainUI, master branch of this repository at 9f0e43b
Also tested with openHAB 3.0.0.M4.

## Browser console

see above

## Additional information

Not sure how this is supposed to work, [code part](https://github.com/openhab/openhab-webui/blob/016e3b091d7677c3ac21d50cf4d7b1848f0b1e4c/bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js#L219) seems to only assign url to local constant on action:
```js
        case 'url':
          const actionUrl = actionConfig[prefix + 'actionUrl']
          console.log('opening URL: ' + actionUrl)
          break
```

perhaps it's not fully implemented yet?
