### ISSUE TITLE
Average temperature in location semantic card does not skip NULL temperatures.

### ISSUE THREAD

**Issue by fxpde** [openhab/openhab-webui#650]
## The problem

When there are multiple temperature values used to aggregate the average, NULL values are also taken into account as 0. Is it possible to just skip these? For some sensors from MQTT, I don't have persistence and restoreOnStartup setup yet, and thus I get invalid values displayed until I receive the first update.

I have not tested it for other semantics, but would expect that it's the same, e.g., for humidity. Here, I would also propose to skip NULL values.

## Expected behavior

All temperature measurements that are set to NULL should not be used to aggregate the average temperature for the room.

## Steps to reproduce

Create two temperature measurement points in a room.
Set the first one to some value and leave the second one at NULL.
Then check out the location semantic card header and see that the temperature is displayed as (temperature1 + temperature2) / 2

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: "Build #2083"
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.4.59+
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 43450472
  totalMemory: 191889408
bindings:
  - knx
  - mqtt
  - sonos
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: de-de
    languages:
      - de-de
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
timestamp: 2020-12-17T10:09:30.372Z
```

## Browser console

```txt

```
