### ISSUE TITLE
Show both lock states in location semantic card

### ISSUE THREAD

**Issue by fxpde** [openhab/openhab-webui#651]
## The problem

In issue #556, semantics cards are introduced.
The location semantic card shows only the unlocked icon. When it's locked, there is no icon displayed.
But from the description in the issue #556, it's suggested that both states should be displayed. I think this would be helpful as well.

## Your suggestion

Both lock states should be displayed

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: "Build #2083"
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.4.59+
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 43450472
  totalMemory: 191889408
bindings:
  - knx
  - mqtt
  - sonos
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: de-de
    languages:
      - de-de
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
timestamp: 2020-12-17T10:09:30.372Z

```
