### ISSUE TITLE
Rule editor: remove keyboard shortcuts when a module is open

### ISSUE THREAD

**Issue by jeffstagedoor** [openhab/openhab-webui#663]
## The problem

When I edit a script of a rule via "Edit Module"
![image](https://user-images.githubusercontent.com/15057361/102557483-95299080-40cb-11eb-8308-46d517556402.png)
and then save that script via Ctrl+S (with the script editor stil open) I get the nofication-msg "Rule updated" and indeed, it does get put to the api - **but without the fresh edits of the script**.

Opening the script editor from the list-item (not the icon) opens the big editor directly *and* there the edited script gets sent to the api.

## Expected behavior
The fresh edits should be updated/saved when pressing Ctrl+S - *or* Ctrl+S could be disabled.

## Steps to reproduce

https://user-images.githubusercontent.com/15057361/102557941-a1621d80-40cc-11eb-8a9e-aca73718a3a0.mp4

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0.RC1
  buildString: Milestone Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.72-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 86931728
  totalMemory: 194969600

clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 3072
    height: 1728
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/86.0.4240.198 Safari/537.36
timestamp: 2020-12-18T00:02:27.536Z
```

Browser: Vivaldi (latest)

## Browser console

```txt
no errors
```

## Additional information

appologies if there's an issue open already for that, I couldn't find a matching one.
