### ISSUE TITLE
Expand semantic model on search

### ISSUE THREAD

**Issue by felixpause** [openhab/openhab-webui#665]
## The problem

When you have the semantic model tree, e.g., to select an item in blockly or for a rule, you have to expand the tree structure to find your item. To speed up the process, you can search. But when searching, you still need to expand each branch by itself. 
![Bildschirmfoto 2020-12-18 um 22 00 57](https://user-images.githubusercontent.com/14113610/102661191-a54d7880-417c-11eb-8c35-e52dd6206971.png)
![Bildschirmfoto 2020-12-18 um 22 01 10](https://user-images.githubusercontent.com/14113610/102661197-a8486900-417c-11eb-9d8d-65ec4a8c0739.png)
![Bildschirmfoto 2020-12-18 um 22 01 21](https://user-images.githubusercontent.com/14113610/102661201-aaaac300-417c-11eb-8d50-aa68cacc98fa.png)

## Your suggestion

It would be better if the branches are expanded automatically when searching. Now if this would show too many items, it should at least automatically expand branches that have only one child to display.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: "Build #2089"
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.4.59+
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 52784168
  totalMemory: 159383552
bindings:
  - knx
  - mqtt
  - sonos
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: de-de
    languages:
      - de-de
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
timestamp: 2020-12-18T20:59:54.943Z


```
