### ISSUE TITLE
[MainUI] [OH3 Final] Things can not be searched in "Add a new Thing" dialog

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#683]
## The problem
in the "Add a new Thing" dialog, after a Scan the found items are not filtered when I type in the "Search" bar:

![image](https://user-images.githubusercontent.com/1475672/102908340-9a922c80-4477-11eb-9ae9-7de1b82cbf87.png)

## Expected behavior
Things should be filtered, only Things containing "Heizung" should be shown.

## Steps to reproduce

1. Install openHAB Remote binding
2. Add Bridge
3. Go to Things -> "+"
4. Click "Scan"
5. Type in something in the Search bar
6. No filtering happens

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 150403912
  totalMemory: 194838528
bindings: []
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
      - es
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 2160
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-22T14:18:38.597Z

```

## Browser console

Nothing unusual to see.

## Browser network traffic

Nothing unusual to see.

## Additional information

---
