### ISSUE TITLE
[MainUI] [OH3 Final] Item search does not work for unicode characters, e.g. äöüß

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#684]
## The problem

Searching in the Items tab doesn't work for some commonly used (in some languages at least) special characters like äöüß.

Works:
![image](https://user-images.githubusercontent.com/1475672/102935966-7b12f800-44a7-11eb-93a5-f70ea4a94dd0.png)

Doesn't work:
![image](https://user-images.githubusercontent.com/1475672/102935988-8534f680-44a7-11eb-9ca7-09b253133a53.png)

## Expected behavior

It is possible to use special characters for labels and so the search should also respect that.

## Steps to reproduce

1. See above.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 150403912
  totalMemory: 194838528
bindings: []
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
      - es
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 2160
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-22T14:18:38.597Z

```

## Browser console

Nothing unusual to see.

## Browser network traffic

Nothing unusual to see.

## Additional information

---
