### ISSUE TITLE
Allow selecting non-managed items to create managed links

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#685]
## The problem

I have a fresh OH3 installation with a minimal configuration with the following things:
1) Hue Bridge
2) Hue Light

I also have items defined in an .items file:
```
// Hue (WW)
Group	e_EG_Buero_Hue_Decke		"Büro Decke"			(g_EG_Buero)					["Lightbulb"]
Dimmer	EG_Buero_Hue_Decke			"Büro Decke"			(e_EG_Buero_Hue_Decke)			["Control"]
Switch	EG_Buero_Hue_Decke_sw 		"Büro Decke"			(e_EG_Buero_Hue_Decke)			["Switch"]					// Workaround Schalter (Helligkeitswiederherstellung)
```

The room (g_EG_Buero) is defined in another .items file and shown just fine in the semantic model:
![image](https://user-images.githubusercontent.com/1475672/102938208-2625b080-44ac-11eb-9410-7346604fe2a2.png)

Going to the Thing (Hue Light) > Channel "Brightness" > "Add Link to Item" > "Item to Link" shows an empty dialog:
![image](https://user-images.githubusercontent.com/1475672/102937466-7f8ce000-44aa-11eb-9061-73c4ced0d6e3.png)

Going to the Item in the semantic model > Add Link shows the Hue Thing and it can be linked without problem:
![image](https://user-images.githubusercontent.com/1475672/102937608-dabed280-44aa-11eb-9c94-c3c9618c4d18.png)

After that it is also shown in the Channels tab:
![image](https://user-images.githubusercontent.com/1475672/102937830-502aa300-44ab-11eb-8664-f5a96c92e8b0.png)

The linked item also works just fine, no errors / warnings in the log so I think my definition is correct.

## Expected behavior

Items should be listed in the dialog. It should be possible to add them from the Things > Channels page.

## Steps to reproduce

1. See above.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 76538096
  totalMemory: 194838528
bindings:
  - hue
  - remoteopenhab
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
      - es
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 2160
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-22T22:17:37.910Z

```

## Browser console

Nothing unusual to see.

## Browser network traffic

Nothing unusual to see.

## Additional information

---
