### ISSUE TITLE
make "hasLocation" editable for items  

### ISSUE THREAD

**Issue by LightIsLife** [openhab/openhab-webui#688]
## The problem
Items added textually do not display "hasLocation" feature. Items that are added through "add point" feature in the model, do have "hasLocation" feature. However, even when added this way, 'hasLocation" is not editable in edit mode.
 
Screenshot of add "point" displays "hasLocation" feature: 
<img width="749" alt="Screen Shot 2020-12-23 at 10 04 00 AM" src="https://user-images.githubusercontent.com/24855935/102980021-2ef7a000-4507-11eb-9437-a8cba1549219.png">

Edit screen of item above, note the absence of "hasLocation" feature:
<img width="754" alt="Screen Shot 2020-12-23 at 10 10 38 AM" src="https://user-images.githubusercontent.com/24855935/102980164-6cf4c400-4507-11eb-942d-0042d59d2c74.png">

## Your suggestion

Make "hasLocation" feature available for editing 

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_IT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Debian
  osName: Linux
  osVersion: 4.19.0-13-amd64
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 51188936
  totalMemory: 230686720
bindings:
  - astro
  - dmx
  - hpprinter
  - http
  - hue
  - icloud
  - networkupstools
  - ntp
  - shelly
  - squeezebox
  - tplinksmarthome
  - tradfri
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 5
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1440
    height: 900
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36
timestamp: 2020-12-23T09:02:33.994Z
```
