### ISSUE TITLE
Cron resets to 08:00 when updating in adminstration/Rules dialog

### ISSUE THREAD

**Issue by bvdg-github** [openhab/openhab-webui#696]
## The problem

When updating an existing cron definition for a rule the dialog defaults back to 08:00 (Cron: 0 0 8 * * ? *  )

## Expected behavior

I would expect the dialog to show the original cron values for update

## Steps to reproduce

1. From the Openhab web interface/Settings/Rules create a rule with a cron timer. In this example I created a cron for every 5 seconds     
![image](https://user-images.githubusercontent.com/76540835/103046254-a05e3f80-4555-11eb-80d9-297f6b4b9224.png)

2. Double click the timer entry to edit
3. The resulting screen show not the original cron setting but a default 08:00 definition
![image](https://user-images.githubusercontent.com/76540835/103046350-e4514480-4555-11eb-82e6-403131258996.png)
4. What I would have expected is this: 
![image](https://user-images.githubusercontent.com/76540835/103046714-38105d80-4557-11eb-90be-f35d7cc6a185.png)

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  configFolder: /opt/openhab3/conf
  userdataFolder: /opt/openhab3/userdata
  logFolder: /opt/openhab3/userdata/logs
  javaVersion: 11.0.8
  javaVendor: N/A
  osName: Linux
  osVersion: 5.9.10-arch1-1
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 63889704
  totalMemory: 305135616
bindings:
  - myq
  - nest
  - unifi
  - wemo
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
timestamp: 2020-12-24T00:35:52.086Z
```

## Browser console

```txt

```

## Additional information

https://community.openhab.org/t/cron-resets-to-08-00-when-updating-in-adminstration-rules-dialog/111080
