### ISSUE TITLE
Implicit user role for unauthenticated requests required

### ISSUE THREAD

**Issue by Legion2** [openhab/openhab-webui#699]
## The problem

When turning off "Implicit user role for unauthenticated requests" in the advanced settings of API Security, Item states are not updated anymore.

## Expected behavior

The Main UI should work when authentication is required by the HTTP API.

## Steps to reproduce

1. Disable "Implicit user role for unauthenticated requests" in the API Security settings
2. Open Main UI in new tab
3. Open browser console and see 'GET .../rest/events/states 401 (Unauthorized)'

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 21437584
  totalMemory: 132120576
bindings:
  - mqtt
  - tr064
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-25T16:50:34.982Z

```

## Browser console

```txt
:8080/rest/events/states:1 GET http://<...>:8080/rest/events/states net::ERR_ABORTED 401 (Unauthorized)
app.js:27 SSE error
r.onerror @ app.js:27
error (async)
_h @ app.js:27
connectStateTracker @ app.js:27
startTrackingStates @ app.js:32
(anonymous) @ app.js:14
u.dispatch @ app.js:20
dispatch @ app.js:14
onPageAfterIn @ app.js:27
qe @ app.js:7
n @ app.js:7
qe @ app.js:7
e.$emit @ app.js:7
(anonymous) @ app.js:7
t.a @ app.js:7
dispatchEvent @ app.js:20
onPageAfterIn @ app.js:20
(anonymous) @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
value @ app.js:9
D.forward @ app.js:9
g @ app.js:9
e @ app.js:20
(anonymous) @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
updated @ app.js:20
qe @ app.js:7
tn @ app.js:7
(anonymous) @ app.js:7
pn @ app.js:7
(anonymous) @ app.js:7
Qe @ app.js:7
Promise.then (async)
Ye @ app.js:7
at @ app.js:7
(anonymous) @ app.js:7
fn.update @ app.js:7
pe.notify @ app.js:7
set @ app.js:7
mn.set @ app.js:7
(anonymous) @ app.js:27
Promise.then (async)
created @ app.js:27
qe @ app.js:7
tn @ app.js:7
e._init @ app.js:7
o @ app.js:7
(anonymous) @ app.js:7
init @ app.js:7
(anonymous) @ app.js:7
d @ app.js:7
(anonymous) @ app.js:7
e._update @ app.js:7
a @ app.js:7
fn.get @ app.js:7
fn @ app.js:7
(anonymous) @ app.js:7
On.$mount @ app.js:7
On.$mount @ app.js:7
e._init @ app.js:7
On @ app.js:7
(anonymous) @ app.js:32
i @ app.js:1
(anonymous) @ app.js:27
i @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
Show 7 more frames
app.js:27 =!= Event source connection broken...
```

## Browser network traffic

![image](https://user-images.githubusercontent.com/12752323/103139288-da0c8300-46da-11eb-9074-7debbb676427.png)
