### ISSUE TITLE
[MainUI] Alarm badge not shown for points part of equipment

### ISSUE THREAD

**Issue by hannibal85** [openhab/openhab-webui#708]
## Alarm badge not shown for points part of equipment

According to #556 alarm badges should work like this:

**Point_Alarm** _hasLocation_ **(the location)**
**_If no matching item found:_**
**Point_Alarm** _isPointOf_ **(any equipment)** _hasLocation_ **(the location)**

But in OH3.0 alarm badge is just shown, when **Point_Alarm** _hasLocation_ **(the location)**.
Second option with **Point_Alarm** _isPointOf_ **(any equipment)** _hasLocation_ **(the location)** does not work.

See: https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui/web/src/components/cards/glance/location/status-badge.vue

Line 156
```
case 'alarms':
    return findPoints(this.element.properties, 'Point_Alarm', true)
```

Compared to e.g. the code for lightbulb badge (which is working as expected) the second part seems to be missing

Line 63
```
case 'lights':
  direct = findPoints(this.element.properties, 'Point_Control', true, 'Property_Light')
  if (direct.length) return direct
  return findPoints(allEquipmentPoints(this.element.equipment), 'Point_Control', true, 'Property_Light')
```

## Expected behavior

**Point_Alarm** _isPointOf_ **(any equipment)** _hasLocation_ **(the location)** should lead to expected number of active alarms shown on location cards

## Steps to reproduce

1. Create items (via .items file or UI)

```
// Points attached to Equipment
Group g1     "Group Location 1"                  ["Room"]
Group e1     "Group Equipment 1 for L1"  (g1)    ["Siren"]
Switch s1    "Switch 1 for E1"           (e1)    ["Alarm", "Temperature"]
Switch s2    "Switch 2 for E1"           (e1)    ["Alarm", "Temperature"]

// Points straight under Location
Group g2     "Group Location 2"                  ["Room"]
Switch s3    "Switch 3 for L2"           (g2)    ["Alarm", "Temperature"]
Switch s4    "Switch 4 for L2"           (g2)    ["Alarm", "Temperature"]
```
2. Set all 4 switches to ON
3. Go to `Location` tab and check of the badge is shown in both cases

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 3.10.105
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 681346656
  totalMemory: 834666496
bindings:
  - ...
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1280
    height: 1024
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
timestamp: 2020-12-27T11:01:39.476Z
```
Additional hint: OH3.0 hosted with Docker on Synology NAS

## Browser console

```txt
Uncaught (in promise) DOMException: The operation is insecure. app.js:27
```

## Additional information

See also https://community.openhab.org/t/oh3-representation-of-semantic-model-in-mainui/111020
