### ISSUE TITLE
Channel links with a broken link fail to render

### ISSUE THREAD

**Issue by simonihmig** [openhab/openhab-webui#709]
## The problem

When migrating from OH 2.5.x to 3.0 I ended up having items refer to non-existing things (uploaded .items file in UI, referring to `onewire` things with an old unique ID). When editing such an item in the UI, this is what you get:

<img width="1792" alt="Bildschirmfoto 2020-12-27 um 12 44 09" src="https://user-images.githubusercontent.com/1325249/103170480-dac12880-4844-11eb-817a-99634c4e93b3.png">

As you can see in the network tab, the REST API rightfully responds with a 404 for the old thing that does not exist anymore. But the UI does not handle this case gracefully, showing not any channel link.

## Expected behavior

The UI should display
* the broken channel link, with a way to remove that
* the two healthy links (see successful requests below the 404)

## Steps to reproduce

As described above, uploading an .items file with a broken channel definition should reproduce this error.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 4.19.118-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 84200216
  totalMemory: 259522560
bindings:
  - amazonechocontrol
  - astro
  - denonmarantz
  - harmonyhub
  - hue
  - knx
  - onewire
  - openweathermap
  - squeezebox
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-27T12:08:07.890Z

```

## Browser network traffic

See above.
