### ISSUE TITLE
[MainUI] Broken href in navigation

### ISSUE THREAD

**Issue by simonihmig** [openhab/openhab-webui#710]
## The problem

The `<a href="/...">` links refer to non-existing URLs. They point to "real" path-based URLs (like with a server-rendered app or when using the `history.pushState` API), but the SPA's routing obviously uses hashbang URLs.

## Expected behavior

Right-clicking on any navigation link and opening in new tab, I would expect to see the page I clicked on, instead I get a 404 error:

![image](https://user-images.githubusercontent.com/1325249/103170732-e7df1700-4846-11eb-951d-3741fc07c042.png)

*Ideally* the app should use path-based URLs for its routing IMHO, but that means the server needs to understand that it has to serve the SPA for those URLs. If that is not feasible (short-term), the SPA should render the hashbang URLs it expects in all `href` it renders.

## Steps to reproduce

1. Right-click on any navigation link and open in new tab

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 4.19.118-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 82453752
  totalMemory: 259522560
bindings:
  - amazonechocontrol
  - astro
  - denonmarantz
  - harmonyhub
  - hue
  - knx
  - onewire
  - openweathermap
  - squeezebox
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-27T12:25:28.218Z

```
