### ISSUE TITLE
Items Unavailbe 

### ISSUE THREAD

**Issue by jsiemon** [openhab/openhab-webui#712]
## Steps to reproduce

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.19.98-Unraid
  osArchitecture: amd64
  availableProcessors: 24
  freeMemory: 298780536
  totalMemory: 763363328
bindings:
  - astro
  - darksky
  - denonmarantz
  - exec
  - gpstracker
  - http
  - icloud
  - ipcamera
  - kodi
  - konnected
  - network
  - ntp
  - opensprinkler
  - panasonictv
  - remoteopenhab
  - shelly
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: false
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
timestamp: 2020-12-27T17:09:48.407Z

```

## Browser console

```txt

```
