### ISSUE TITLE
Items Not Available to Link From Thing Channels

### ISSUE THREAD

**Issue by jsiemon** [openhab/openhab-webui#713]
## Problem
I am using Docker containers and all Items and Rules are Text files.  I have almost 400 items.  I have successfully migrated my OH2.5.9 to OH3.0.0-release.  The items and Rules appear in the OH3 UI.  However when I attempt to link an existing Item to a Thing Channel, any Thing Channel, only 10 Items appear as available to Link as shown in the screenshot, and it is always the same 10 Items.  If I select an Item then in most cases, but not all cases, the Link Item Button is available an I can link to Thing Channel this way.  
![image](https://user-images.githubusercontent.com/6732269/103175856-32f32d00-483b-11eb-9fa1-31de0f616090.png)

## Expected behavior
I am using Docker containers and all Items and Rules are Text files.  I have almost 400 items.  I have successfully migrated my OH2.5.9 to OH3.0.0-release.  The items and Rules appear in the OH3 UI.  However when I attempt to link an existing Item to a Thing Channel, any Thing Channel, only 10 Items appear as available to Link as shown in the screenshot, and it is always the same 10 Items.  If I select an Item then in most cases, but not all cases, the Link Item Button is available an I can link to Thing Channel this way.  
![image](https://user-images.githubusercontent.com/6732269/103175856-32f32d00-483b-11eb-9fa1-31de0f616090.png)

## Steps to reproduce

1. I updated a 2.5.9 Docker to 3.0.0.  Update went smoothly, no errors or issues during update process.  All Items defined using 2.5.9 as Text files then I attempted  to Link the  Items to an appropriate Thing Channel.  Doesn't matter which Item or Things or Channel, same behavior.  Only same Items displayed and available to Link.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.19.98-Unraid
  osArchitecture: amd64
  availableProcessors: 24
  freeMemory: 298780536
  totalMemory: 763363328
bindings:
  - astro
  - darksky
  - denonmarantz
  - exec
  - gpstracker
  - http
  - icloud
  - ipcamera
  - kodi
  - konnected
  - network
  - ntp
  - opensprinkler
  - panasonictv
  - remoteopenhab
  - shelly
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: false
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
timestamp: 2020-12-27T17:09:48.407Z

```

## Browser console

```txt

```

## Additional information
I have been successful for the most part in working around this issue by selecting each Item and then Linking each individual Item to the Thing Channel, instead of selecting the Thing Channel and Linking the Item to the Channel in this way.  In some cases the Item that I needed to Link had no Link Button associated with it so I had to use the UI to create a new Item as a work around.  In no case did I import(copy/paste) Items or Rules into the UI from Text files.  All Items and Rules remain exclusively in the Text files, except those few Item without Link Buttons for which I had to create new Items using the UI.
