### ISSUE TITLE
[main ui] Alphabetize semantic classes and properties in pop-over

### ISSUE THREAD

**Issue by SRGDamia1** [openhab/openhab-webui#714]
## The problem

In the (awesome) new ui, the semantic classes and semantic properties are not alphabetized in the pop-over from the "create equipment from thing" and "add items from thing" screens.  This makes it harder to quickly find and select the correct one.

![image](https://user-images.githubusercontent.com/5374350/103176962-07c10b80-4844-11eb-93b9-81cc0124ba40.png)

## Your suggestion

Alphabetize (0-9,A-z) the list of item for the selection

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7+
  osArchitecture: arm
clientInfo:
  device:
    desktop: true
    firefox: true
    windows: true
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101
    Firefox/84.0
```
