### ISSUE TITLE
Unable to Unlink a Single Item from Thing - Must unlink all channel items to remove only 1  Link

### ISSUE THREAD

**Issue by jsiemon** [openhab/openhab-webui#715]
## The problem
For Items created using Text Files, once they are linked to Thing using the UI they cannot be removed.  Missing Unlink button.  For Items created using the UI both "Unlink" and "Unlink and Remove" buttons are available.  

![image](https://user-images.githubusercontent.com/6732269/103178890-ee748b00-4854-11eb-83de-3e52f3533878.png)

## Expected behavior
I understand that Items created in Text files cannot be removed by the UI(same behavior as OH2), but they should be able to be Unlinked from a channel without having to remove All Items from from All Channels for a Thing.  Behavior similar to what is available in OH2.

## Steps to reproduce

1. Manually Link a Text file defined Item to a Channel in a Thing.
2. Done/Save
3. Try to Unlink the Link Item due to a mistake.
4. No Unlink Button Available for the single Item
5.Only option is Unlink All Items for the Thing to remove the Single Link

![image](https://user-images.githubusercontent.com/6732269/103179073-5ecfdc00-4856-11eb-9189-f4b1ffba4e77.png)

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.19.98-Unraid
  osArchitecture: amd64
  availableProcessors: 24
  freeMemory: 264195632
  totalMemory: 763363328
bindings:
  - astro
  - darksky
  - denonmarantz
  - exec
  - gpstracker
  - http
  - icloud
  - ipcamera
  - kodi
  - konnected
  - network
  - ntp
  - opensprinkler
  - panasonictv
  - remoteopenhab
  - shelly
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: false
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
timestamp: 2020-12-27T20:09:33.198Z


```

## Browser console

```txt

```
