### ISSUE TITLE
Google Assistant metadata missing optional thermostat items

### ISSUE THREAD

**Issue by Jzooor** [openhab/openhab-webui#720]
## The problem

When adding metadata to some items for Google Assistant thermostat integration, the UI is missing the optional thermostatTemperatureSetpointHigh and thermostatTemperatureSetpointLow assistant class items mentioned in the docs.

[Google Assistant | Thermostats](https://www.openhab.org/docs/ecosystem/google-assistant/#thermostats)

## Expected behavior

List of metadata to add to the item should include  
thermostatTemperatureSetpointHigh and thermostatTemperatureSetpointLow.

## Steps to reproduce

1. Select Add Metadata when editing an item.
2. Choose Google Assistant
3. Select Google Assistant Class
4. See referenced options are missing.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 4.19.66-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 69464328
  totalMemory: 235208704
```

## Browser console

n/a

## Browser network traffic

n/a

## Additional information

n/a
