### ISSUE TITLE
[MainUI] Code view for Item (and its link, if relevant)

### ISSUE THREAD

**Issue by digitlength** [openhab/openhab-webui#728]
## The problem
(Not really a problem - this is a feature request - but I'll keep the template title)

We have a friendly `Code` tab for Things, from which YAML code can be edited, copied and shared on the Community forum.

This `Code` tab does not exist for Items (except for its metadata) and its links (if relevant).

I realise the API Explorer exists, but that's quite a 'scary' looking thing for a beginner, with its colour coding and location within the Developer Tools. Additionally, if the API Explorer is used one needs to enter the Items and Links separately - coming from OH2 where Items and Links where defined in a single line in a text file this adds to the 'unfriendliness', so to speak.

Is it possible, for an Item, to have a `Code` tab which includes all information required to recreate the Item and its Link, for easy and friendly editing and sharing? That would also improve consistency between Items and Things.

I have seen #397, but I think that just pertains to the Item metadata. This issue is essentially about _all_ the Item parameters, as they used to be (still can be, I guess!) defined in Items files.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+55-CA
  osName: Linux
  osVersion: 5.4.0-58-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 29474216
  totalMemory: 96468992
bindings:
  - http
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
```
