### ISSUE TITLE
Switch OFF Command stuck

### ISSUE THREAD

**Issue by BremerButjer** [openhab/openhab-webui#731]
## The problem

A switch bulb item was created.
If it is switched via MS Edge or Chrome Browser, only the ON command is sent, not the OFF command.
If the item is switched via SAFARI (iPhone), it works without any problems.

## Expected behavior

The function should work the same with all browsers.

1.

**Comment by roquestrongo** [comment]
I can confirm this behavior on my Openhab 3 installation (Ubuntu 18.04.5 LTS, Java 11.0.9.1 Zulu)

I upgraded from openhab 2.5 to Openhab 3. 

I got the following MQTT Channel:

```
    UID: mqtt:topic:wzog_lcu
    label: ogwz_lcu
    thingTypeUID: mqtt:topic
    configuration:
      availabilityTopic: wzog_lcu/status
      payloadAvailable: online
    bridgeUID: mqtt:broker:afc2aaab5a
    location: Wohnzimmer
    channels:
      - id: ogwz_lcu_cct_group_1_state
        channelTypeUID: mqtt:switch
        label: CCT Group 1 - STATE
        description: ""
        configuration:
          postCommand: false
          qos: 1
          formatBeforePublish: '{"state":"%s"}'
          commandTopic: wzog_lcu/light/cct_group_1/command
          stateTopic: wzog_lcu/light/cct_group_1/state
          transformationPattern: JSONPATH:$.state
          off: OFF
          on: ON
```

If i switch the corresponding switch item inside "Basic UI > Settings > Items" on my Windows PC (Chrome) i get the following Karaf output:

```
    13:45:45.401 [INFO ] [openhab.event.ItemCommandEvent       ] - Item 'ogwz_lcu_CCT_Group_1_STATE' received command ON
    13:45:45.402 [INFO ] [openhab.event.ItemStatePredictedEvent] - Item 'ogwz_lcu_CCT_Group_1_STATE' predicted to become ON

```
I only see a log output when switching on, if i switch off there is no output in Karaf , neither an error reported, and accordingly i also don´t see a message published on the mqtt topic.

Now if i open BasicUI in Chrome on my Android phone, and switch the corresponding switch item inside "Basic UI > Settings > Items" , both on and off command are visible in Karaf and also messages are published to the mqtt topic.

I doubt there might be an issue due the behavior sholud be the same independent the OS that is used?

Regards

Roque
