### ISSUE TITLE
Add Rule Condition: Ephemeris.NotAHoliday not displayed in ephemeris group

### ISSUE THREAD

**Issue by soenkekueper** [openhab/openhab-webui#740]
## The problem
When configuring the ephemeris.NoHolidayCondition which is added in https://github.com/openhab/openhab-core/issues/2035 this won't be displayed within the "Ephemeris" Category, but within ephemeris when choosing the "show all".

<img width="485" alt="AddCondition" src="https://user-images.githubusercontent.com/24605357/103442386-fe75db80-4c55-11eb-8097-913803b08f5a.PNG">
<img width="475" alt="ephemeris_conditin" src="https://user-images.githubusercontent.com/24605357/103442392-046bbc80-4c56-11eb-928c-93f8366d58ac.PNG">
<img width="478" alt="all_condition" src="https://user-images.githubusercontent.com/24605357/103442394-0766ad00-4c56-11eb-90fd-6b4a23756370.PNG">

## Your suggestion
Add the "Not a holiday" in ephemeris category when adding a condition.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 67231320
  totalMemory: 194904064
bindings:
  - astro
  - avmfritz
  - denonmarantz
  - heos
  - network
  - tradfri
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2021-01-01T16:24:15.489Z
```
