### ISSUE TITLE
[MainUI] Switch Item linked to two Thing Channels becomes read-only

### ISSUE THREAD

**Issue by digitlength** [openhab/openhab-webui#742]
## The problem
When a Switch Item is linked to more than one Switch Channel, the Item becomes read only in the UI - there's no toggle to switch the Item ON and OFF.

Below, a Switch Item linked to a single Switch Channel:

<img src="https://user-images.githubusercontent.com/62958838/103453986-28bbad80-4cd7-11eb-96f9-67d645cbfaef.png" width="50%">

The `Power` Switch Channel is configured as below:
```
Type switch : power "Power" [ 
	stateTopic="stat/swTestSwitch/POWER", 
	commandTopic="cmnd/swTestSwitch/POWER",
	on="ON",
	off="OFF"          
]
```

Below is the same Switch Item, now linked to a second Switch Channel. Note that the toggle has disappeared:

<img src="https://user-images.githubusercontent.com/62958838/103454070-18580280-4cd8-11eb-968e-b59136e68400.png" width="50%">

The `State` Switch Channel is configured as below (i.e. read-only):

```
Type switch : state "State" [
	stateTopic="tele/swTestSwitch/STATE",
	transformationPattern="JSONPATH:$.POWER",
	on="ON",
	off="OFF"
]
```
## Expected behavior

I would expect the toggle to remain available with any number of linked Channels, as it is (or used to be) in OH2 BasicUI/Sitemaps.

This is a Tasmota device sending a periodic status update which includes the state of the power switch. This can be used to lazily update the state of the Switch Item when persistence is not used.

## Steps to reproduce

See above.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+55-CA
  osName: Linux
  osVersion: 5.4.0-58-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 97163112
  totalMemory: 233832448
bindings:
  - http
  - mqtt
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 2
    language: en-GB
    languages:
      - en-GB
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
```

## Browser console

n/a

## Browser network traffic

n/a

## Additional information

n/a

**Comment by digitlength** [comment]
I have now realised that I can override the default widget presentation by adding

```
... widget="oh-toggle-card", listWidget="oh-toggle-item" ... 
```

into the metadata of my Items configuration file.

So is switching the widget type to 'label' rather than keeping it at 'toggle' when more than one Channel is attached expected behaviour?

**Comment by ghys** [comment]
Interesting, I believe the default widget representation for Switches will use a label instead of a toggle if the state description's `readOnly` is set to true. So it might be the two links both trying to set this from the channel type and your "state" link, which supposedly has `readOnly: true`, ends up being the winner.

Can you go to Developer Tools > API Explorer > items > GET /items/{itemname} > Try it out (button on the right) > put your item name > Execute
Then check whether you have `readOnly: true` in `stateDescription`.

**Comment by ghys** [comment]
You can override this manually on the item with `stateDescription=" " [ readOnly=false ]` on the item (or with the UI).

**Comment by digitlength** [comment]
You are right - `readOnly` is set to `true`

```yaml
{
  "link": "http://localhost:8080/rest/items/TestSwitch",
  "state": "ON",
  "stateDescription": {
    "pattern": "%s",
    "readOnly": true,
    "options": []
  },
  "editable": false,
  "type": "Switch",
  "name": "TestSwitch",
  "tags": [],
  "groupNames": []
}
```

With only the Channel which can both read and write:

```yaml
{
  "link": "http://localhost:8080/rest/items/TestSwitch",
  "state": "ON",
  "stateDescription": {
    "pattern": "%s",
    "readOnly": false,
    "options": []
  },
  "editable": false,
  "type": "Switch",
  "name": "TestSwitch",
  "tags": [],
  "groupNames": []
}
```

With only the Channel that can read:

```yaml
{
  "link": "http://localhost:8080/rest/items/TestSwitch",
  "state": "ON",
  "stateDescription": {
    "pattern": "%s",
    "readOnly": true,
    "options": []
  },
  "editable": false,
  "type": "Switch",
  "name": "TestSwitch",
  "tags": [],
  "groupNames": []
}
```

So it looks like the Channel with `readOnly: true` ends up being the winner, as you stated.

Is that expected?
