### ISSUE TITLE
Please add switch items for displaying open window badges

### ISSUE THREAD

**Issue by sim0nx** [openhab/openhab-webui#747]
## The problem
I want to have open/closed windows modeled in the main UI as described in #556 though my items are bound to being of *switch* type by the binding, and not contact which is expected here.

## Expected behavior
Look for state *OPEN* but also for *ON*.

## Steps to reproduce
Use a switch item as *reed contact* of a window.

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_LU
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.4.72-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 61822048
  totalMemory: 279969792
bindings:
  - astro
  - comfoair
  - hue
  - km200
  - knx
  - ntp
  - nuki
  - openweathermap
  - satel
  - velux
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 24
    language: en-US
    languages:
      - en-US
      - en
      - de
      - fr
      - lb
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3072
    height: 1728
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2021-01-02T21:53:51.474Z

```

## Browser console

```txt

```
