### ISSUE TITLE
Status badges are not shown on cards when item value is 0

### ISSUE THREAD

**Issue by krocans** [openhab/openhab-webui#750]
## The problem

Status badges for example Temperature are not shown on location cards when item value is 0 (e.g. 0 °C)

![Capture1](https://user-images.githubusercontent.com/42302779/103479790-bd5a0480-4dd8-11eb-941c-7347d60a853f.PNG)

```
{
  "members": [
    {
      "state": "0.0 °C",
      "type": "Number:Temperature",
      "name": "Test_temp",
      "label": "Test temperature",
      "category": "temperature",
      "tags": [
        "Measurement",
        "Temperature"
      ],
      "groupNames": [
        "Test"
      ]
    }
  ],
  "state": "NULL",
  "editable": true,
  "type": "Group",
  "name": "Test",
  "label": "Test",
  "category": "",
  "tags": [
    "Location"
  ],
  "groupNames": []
}
```
 Badge is shown when value is any positive or negative number.
![Capture2](https://user-images.githubusercontent.com/42302779/103479907-8506f600-4dd9-11eb-9eaf-7cad7bde0d3f.PNG)

```
{
  "state": "-1.0 °C",
  "editable": true,
  "type": "Number:Temperature",
  "name": "Test_temp",
  "label": "Test temperature",
  "category": "temperature",
  "tags": [
    "Measurement",
    "Temperature"
  ],
  "groupNames": [
    "Test"
  ]
}
```
## Expected behavior

Zero values should be shown as badges. Only NULL or unexistent should be hidden.

## Steps to reproduce

1. Create ["Measurement", "Temperature"] in any location group and set its value to 0.
2. Observe that badge is not shown on location card.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_LV
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Red Hat, Inc.
  javaVendorVersion: "18.9"
  osName: Linux
  osVersion: 4.18.0-240.el8.x86_64
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 50627136
  totalMemory: 270532608
bindings:
  - astro
  - exec
  - gpstracker
  - http
  - mail
  - miio
  - mqtt
  - network
  - networkupstools
  - ntp
  - openweathermap
  - samsungtv
  - systeminfo
  - yamahareceiver
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
      - lv
      - ru
      - de
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66
timestamp: 2021-01-03T13:19:30.531Z

```

## Browser console

n/a

## Browser network traffic

n/a

## Additional information

n/a
