### ISSUE TITLE
Settings point/Item link does not save profiles when adding and all profiles are not shown when editing.

### ISSUE THREAD

**Issue by robmachab** [openhab/openhab-webui#751]
## The problem

When linking channels to points/items from the model setup screen if you select the change timestamp profile this is not saved.

Example measurement timestamp point

![image](https://user-images.githubusercontent.com/48614861/103481047-25581d00-4dd0-11eb-8204-d67b4699c36c.png)

add link to zwave switch channel

![image](https://user-images.githubusercontent.com/48614861/103481110-82ec6980-4dd0-11eb-9170-c971277bc585.png)

select profile

![image](https://user-images.githubusercontent.com/48614861/103481135-b3340800-4dd0-11eb-96b8-9dab15a1fc15.png)

But when going into item link to edit no profile is selected only profiles that are available are these

![image](https://user-images.githubusercontent.com/48614861/103481156-eaa2b480-4dd0-11eb-9abd-335f6b072bd9.png)

To make screenshots:
* On Windows: use Win+Shift+S
* On macOS: use Cmd+Shift+4

To make animated GIFs we recommend:
* On Windows: ShareX - https://getsharex.com/
* On macOS: Giphy Capture - https://giphy.com/apps/giphycapture
* On GNU/Linux: Peek - https://github.com/phw/peek
-->

## Expected behavior

Profile set should be saved.]=
All profiles should be available from edit item.

## Steps to reproduce

1. Create Point in semantic model
2. Link point to channel
3. Set profile to change 
4. Save

Profile should be saved against the link.

1. Select an Item with links
2. Edit link
3. Should be able to select from all available profiles

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 113037264
  totalMemory: 203423744
bindings:
  - remoteopenhab
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-GB
    languages:
      - en-GB
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1620
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2021-01-03T18:49:49.477Z

```

## Browser console

![image](https://user-images.githubusercontent.com/48614861/103486426-c0afb900-4df5-11eb-8088-7d4dd85bb820.png)

```none

```
