### ISSUE TITLE
Scrollbars in UI not working

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab-webui#755]
## The problem

Some scrollbars in the UI does not work as intented. I can't drag them to move up or down and also the clickable arrows at the end of the scrollbars are not clickable.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: sv_SE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+100-CA
  osName: Linux
  osVersion: 5.9.14-rockchip64
  osArchitecture: aarch64
  availableProcessors: 6
  freeMemory: 8017528
  totalMemory: 749731840
bindings:
  - exec
  - mail
  - networkupstools
  - pushover
  - robonect
  - sonos
  - systeminfo
  - tellstick
  - tibber
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: sv-SE
    languages:
      - sv-SE
      - sv
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101
    Firefox/84.0
timestamp: 2021-01-04T13:18:54.967Z

```

## Additional information

I've experienced this since I upgraded from 2.5 to 3.0 around milestone 3, just haven't got around to reporting it. It affects Firefox which is my primary browser, but I get the same behaviour in Chrome.

This affects the scrollbars which have letters on them, like in the list of Items and the list of Rules (so for example the Items list is no problem). Clicking the letter works, but not using the "rest" of the scroll bar.
