### ISSUE TITLE
Values not visible in Sitemap for channelless items

### ISSUE THREAD

**Issue by fredericdepuydt** [openhab/openhab-webui#757]
## Which UI are you reporting an issue for?

- [X] Basic UI (Both in browser and the Android app)
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

Values from items with no channels/things linked to them won't show correctly in sitemaps on Basic UI or the Android app, although the values are set, they can be changed and can be viewed when using a drop down selection (Android app).

In the screenshots underneath the 'Badkamer' setpoint value is set at 21, but isn't shown as it doesn't have an channel linked to it.

![2021-01-04 18h36m56s - Screenshot 001](https://user-images.githubusercontent.com/9569314/103564622-2451e900-4ebf-11eb-8851-34c8bf57b684.png)

![2021-01-04 18h37m53s - Screenshot 001](https://user-images.githubusercontent.com/9569314/103564667-36cc2280-4ebf-11eb-92bf-efdc3378cadc.png)

![2021-01-04 18h38m08s - Screenshot 001](https://user-images.githubusercontent.com/9569314/103564676-3a5fa980-4ebf-11eb-8a82-50b28053841d.png)

![2021-01-04 18h38m36s - Screenshot 001](https://user-images.githubusercontent.com/9569314/103564683-3cc20380-4ebf-11eb-8886-84faa00606a3.png)

And this is the sitemap code:
```
    Frame label="Leefruimte" {
        Switch item=Thermostat_State_Leefruimte label="Enable"
        Setpoint item=Thermostat_Setpoint_Leefruimte label="Setpoint"
    }

    Frame label="Bureau" {
        Switch item=Thermostat_State_Bureau label="Enable"        
        Setpoint item=Thermostat_Setpoint_Bureau label="Setpoint"
    }

    Frame label="Badkamer" {
        Switch item=Thermostat_State_Bathroom label="Enable"
        Setpoint item=Thermostat_Setpoint_Badkamer label="Setpoint"
    }
```

## Expected behavior

The expected behavior is for these values to be visible.

## Steps to reproduce

1. Create an item (can be a string)
2. Refer to the item in a sitemap
3. Take a look at the sitemap in either a browser or using the Android app

## Your environment(s)
Dockerized Openhab 3.0.0 M2
Dockerized Openhab 3.0.0 M5
Dockerized Openhab 3.0.0

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_BE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.51-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 34720000
  totalMemory: 133681152
bindings:
  - icalendar
  - mqtt
  - network
  - openweathermap
  - satel
  - velbus
  - zway
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101
    Firefox/84.0
timestamp: 2021-01-04T17:50:23.730Z
```
