### ISSUE TITLE
[MainUI] Slider widget scales incorrectly rendered and missing numbers

### ISSUE THREAD

**Issue by digitlength** [openhab/openhab-webui#758]
## The problem

The slider widget is missing `18` on the scale, which means the 'ball' is not in the correct position either...

![image](https://user-images.githubusercontent.com/62958838/103587276-caf9b200-4ede-11eb-94bd-2ce0dde0940d.png)

## Expected behavior

I would expect to see the numbers 15, 16, 17, 18, 19, 20 and 21 equispaced, with the 'ball' of the slider perfectly atop one of the integers.

## Steps to reproduce

1. Create a number Item as follows:
![image](https://user-images.githubusercontent.com/62958838/103587019-3c853080-4ede-11eb-85ca-5b1fdc3de241.png)

2. Define a _Default Standalone Widget_ and add metadata as follows, and Save:

```yaml
value: oh-slider-card
config:
  scale: true
  step: 1
  min: 15
  max: 21
```
3. Slider widget ends up looking like this, with `18` missing from the scale, and the 'ball' of the slider not sitting atop exact integers.

![image](https://user-images.githubusercontent.com/62958838/103587216-aa315c80-4ede-11eb-9326-9c3b72b4670e.png)

4. This is also true for the list slider widget. Have not tried the cell slider widget.

This configuration:

![image](https://user-images.githubusercontent.com/62958838/103587687-b0740880-4edf-11eb-9368-7ad66e5fe97f.png)

Results in:

![image](https://user-images.githubusercontent.com/62958838/103587727-ca155000-4edf-11eb-9961-f112620870a5.png)

when clicking on the _Test Location_ from the _Locations_ tab.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+55-CA
  osName: Linux
  osVersion: 5.4.0-58-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 52029816
  totalMemory: 136314880
bindings:
  - http
  - mqtt
  - network
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 2
    language: en-GB
    languages:
      - en-GB
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

```
