### ISSUE TITLE
Things in the Things view not getting loaded

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-webui#762]
## The problem

The Things view does not properly load and is stuck with loading.
![Screenshot 2021-01-06 012739](https://user-images.githubusercontent.com/7902693/103714272-8c3b2900-4fbe-11eb-89f1-18214354c9f1.png)

## Expected behavior

Things should be shown

## Steps to reproduce

Occurs from time to time, I'm not able to reproduce it. As soon as it occurs once, it's permanently and reproducible by just opening the Things view. Running

```
systemctl stop openhab
openhab-cli clean-cache
systemctl start openhab
```

solves it temporarily, but issue occurs again after some time (usually hours or days, but sometimes also minutes).

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 18819736
  totalMemory: 142606336
bindings:
  - amazonechocontrol
  - bluetooth
  - exec
  - flicbutton
  - heos
  - homematic
  - milight
  - pfinkprofiles
  - rfxcom
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2021-01-06T00:31:25.934Z
```

## Browser console

[raspberrypi-1609892118016.log](https://github.com/openhab/openhab-webui/files/5773291/raspberrypi-1609892118016.log)

_Summary:_

two errors

```
Unchecked runtime.lastError: The message port closed before a response was received.
```

and

```
Uncaught (in promise) TypeError: Cannot read property 'localeCompare' of undefined
    at app.js:27
    at Array.sort (<anonymous>)
    at app.js:27
```
## Browser network traffic

[raspberrypi.zip](https://github.com/openhab/openhab-webui/files/5773273/raspberrypi.zip)

_Summary:_

All HTTP responses OK, , REST response by /things seems to be fine

## Additional information

I'm happy to assist resolving the issue within the code, but currently I don't really know where to start. If you may could me some initial hints @ghys, I'm maybe able to find the bug on my own and do a PR :)
