### ISSUE TITLE
[OH3.1 #2118]: Image element ignored/not being displayed

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-webui#763]
## The problem
When using image elements in basicUI which have been created via the sitemap generator in mainUI, these image elements won't be displayed.

## Expected behavior
Image elements should to be displayed in basicUI.

## Steps to reproduce
1. Create the following sitemap:
```
sitemap test label="Test" {
    Image url="https://www.openhab.org/openhab-logo-square.png"
}
```
2. Go to the page: http://_localIPaddress_:8080/basicui/app?sitemap=uicomponents_test
3. My current result:
![image](https://user-images.githubusercontent.com/22266373/103766167-a6a4ef00-501e-11eb-9bd8-e28993d2dce6.png)

## Your environment
```
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2118"
locale: de_AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 61027672
  totalMemory: 208728064
bindings:
  - amazonechocontrol
  - daikin
  - denonmarantz
  - exec
  - harmonyhub
  - http
  - ipcamera
  - mqtt
  - netatmo
  - network
  - ntp
  - systeminfo
  - unifi
  - wled
  - worxlandroid
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-US
      - en-AU
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2021-01-06T11:56:48.078Z
```
## Browser console
![image](https://user-images.githubusercontent.com/22266373/103766260-d18f4300-501e-11eb-9b62-90b378adc17d.png)

## Browser network traffic
![image](https://user-images.githubusercontent.com/22266373/103766309-e66bd680-501e-11eb-91fe-4a3e9c3d3cbd.png)

## Additional information
This problem only occurs in sitemaps being generated via mainUI; .sitemap files don't show this behaviour.
There is NO error message in the logfiles.
