### ISSUE TITLE
[3.1.0-SNAPSHOT - Build #2127] Entered text in search box not visible when using DARK mode in Windows 10

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-webui#780]
## The problem
When using the MainUI in dark mode, in various search boxes the entered text is not visible.
Example: When I enter "netatmo" in the box, the filter works fine - but I can't see my entered text:
![image](https://user-images.githubusercontent.com/22266373/104091722-832caf00-527f-11eb-9f1f-4db1a1081e4c.png)

When I mark the entered text it becomes visible:
![image](https://user-images.githubusercontent.com/22266373/104091726-8cb61700-527f-11eb-943a-0742dd6f8d06.png)

Manipulating the CSS temporarily adding "! important" makes the text visible:
![image](https://user-images.githubusercontent.com/22266373/104091742-a7888b80-527f-11eb-9857-5ef8c3f395cd.png)

## Expected behavior
The entered text in search/filter boxes should be always visible, no matter what theme I'm using

## Steps to reproduce
1. Switch windows to dark mode
2. Use a filter box (e.g. in the item list)

## Your environment
```
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2127"
locale: de_AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.83-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 69775648
  totalMemory: 194838528
bindings:
  - amazonechocontrol
  - coronastats
  - daikin
  - denonmarantz
  - enigma2
  - exec
  - harmonyhub
  - http
  - ipcamera
  - mqtt
  - netatmo
  - network
  - ntp
  - systeminfo
  - unifi
  - wled
  - worxlandroid
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-US
      - en-AU
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-09T12:38:51.377Z
```

## Browser console
![image](https://user-images.githubusercontent.com/22266373/104091823-457c5600-5280-11eb-8e48-96319c9e4fc8.png)

## Browser network traffic
![image](https://user-images.githubusercontent.com/22266373/104091847-65ac1500-5280-11eb-90e7-2fbd72ed11c6.png)

## Additional information
I'm NOT having this issue in Microsoft Edge on the same machine or on Chrome (iOS).
