### ISSUE TITLE
[UIComponentsSitemapProvider] Missing chart labels

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-webui#781]
## The problem
When using a chart in a sitemap (no matter if created in the UI or .sitemap file), the title won't be displayed anymore:
UI:
![image](https://user-images.githubusercontent.com/22266373/104099928-42dc2980-529d-11eb-9bb0-12416db92d7d.png)

Code: 
```
    Group label="Corona Statistik AT" {
        Text item=CoronaStatisticsAT_NewCases label="Neue Fälle"
        Text item=CoronaStatisticsAT_NewDeaths label="Neue Tote"
        Text item=CoronaStatisticsAT_Updated label="Daten vom [%1$td.%1$tm.%1$tY, %1$tH:%1$tm]"
        Chart icon="chart" item=CoronaStatisticsAT_NewCases refresh=60000 service="rrd4j" period="W" label="Neue Fälle"
    }
```

Result: Chart is being displayed, but without given title:
![image](https://user-images.githubusercontent.com/22266373/104100873-8a62b580-529d-11eb-995d-8da74f66123b.png)

## Expected behavior
When label= is being used, the label should be displayed as well

## Steps to reproduce
1. Create a chart with a lable
2. Check page in basicUI

## Your environment
```
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2127"
locale: de_AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.83-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 84129568
  totalMemory: 194772992
bindings:
  - amazonechocontrol
  - coronastats
  - daikin
  - denonmarantz
  - enigma2
  - exec
  - harmonyhub
  - http
  - ipcamera
  - mqtt
  - netatmo
  - network
  - ntp
  - systeminfo
  - unifi
  - wled
  - worxlandroid
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-US
      - en-AU
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-09T16:11:12.238Z
```

## Browser console
![image](https://user-images.githubusercontent.com/22266373/104102099-e9c0c580-529d-11eb-92f5-f79c365c23e9.png)

## Browser network traffic
![image](https://user-images.githubusercontent.com/22266373/104102421-06f59400-529e-11eb-8bc3-affcaa917b6c.png)
