### ISSUE TITLE
[nearley] Parse group w/ quantity base type & aggregation + parameters

### ISSUE THREAD

**Issue by hannibal85** [openhab/openhab-webui#784]
## The problem

During my migration of all the items from OH2.5 to OH3 with "Add Items from Textual Definition" feature of MainUI I came across 2 bugs when importing Group items:

1. Aggregation function "OR" / "One ON then ON else OFF"
   * Aggregation setting for `Group:Switch:OR(ON,OFF)` is not set for imported item
   * Same behaviour with AND Aggregation while it's working for SUM Aggregation

2. QuantityType as BaseType (UoM)
   * If Group has a QunatityType as Base Type it is not parsed correct
   * QuantityType is replaced with Number for imported group item
   * For a combiniation of QuantityType and Aggregation function there is a parsing error and it's not possible to import at all
   * Same syntax is working fine when used in `*.rules` file

## Expected behavior

Groups being imported w/o errors and same settings as in textual configuration

## Steps to reproduce

1. Aggregation function "OR" / "One ON then ON else OFF"
   * Go to "Items" > "Add Items from Textual Definition"
   * Paste following item definition: `Group:Switch:OR(ON,OFF) gTest  "Test Aggregation"`
   * Previews shows Item settings w/o errors 
![image](https://user-images.githubusercontent.com/16479725/104105595-893a8400-52af-11eb-8917-1c02adc66672.png)
   * Hit "Add"
   * Go to "Developer Tools" > "API Explorer"
   * Search for "GET /items/{itemname}" endpoint, enter itemname `gTest` and hit Execute 
![image](https://user-images.githubusercontent.com/16479725/104105757-a6238700-52b0-11eb-97ec-3b722fba69d9.png)
   * Check response body 
    ```
    {
      "members": [],
      "groupType": "Switch",
      "function": {
        "name": "EQUALITY"
      },
      "link": "http://192.168.178.201:18080/rest/items/gTest",
      "state": "NULL",
      "editable": true,
      "type": "Group",
      "name": "gTest",
      "label": "Test Aggregation",
      "tags": [],
      "groupNames": []
    }
    ```
    * Function name is "EQUALITY" where it should be "OR"

2. QuantityType as BaseType (UoM)
   * Go to "Items" > "Add Items from Textual Definition"
   * Paste following item definition: `Group:Number:Temperature gTest1  "Test Quantity"`
   * Previews shows Item settings w/o errors > Hit "Add"
   * Go to "Developer Tools" > "API Explorer"
   * Search for "GET /items/{itemname}" endpoint, enter itemname `gTest1` and hit Execute 
   * Check response body 
    ```
    {
      "members": [],
      "groupType": "Number",
      "function": {
        "name": "EQUALITY"
      },
      "link": "http://192.168.178.201:18080/rest/items/gTest1",
      "state": "NULL",
      "editable": true,
      "type": "Group",
      "name": "gTest1",
      "label": "Test Quantity",
      "tags": [],
      "groupNames": []
    }
    ```
    * groupType is "Number" where it should be "Number:Temperature"

3. Combination of QuantityType and Aggregation function
   * Go to "Items" > "Add Items from Textual Definition"
   * Paste following item definition: `Group:Number:Temperature:SUM gFileTest2  "Test Quantity with Aggregation"`
   * Parsing error occurs
    ```
    Error: Syntax error at line 1 col 25:
        Group:Number:Temperature:
                                ^
    Unexpected colon token: ":". Instead, I was expecting to see one of the following: ....
    ```

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 3.10.105
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 171169824
  totalMemory: 338690048
bindings:
 ...
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1280
    height: 1024
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
timestamp: 2021-01-09T19:00:49.757Z

```

## Browser console

```txt

```
