### ISSUE TITLE
openhab webui remains empty when using fqdn of host

### ISSUE THREAD

**Issue by 75ohm** [openhab/openhab-webui#786]
## The Problem
After a fresh install of the openhab debian packet 3.0.0 or 3.1.0~S2130 the webui remains clean when using the fully qualified domain name of the host running openhab.

The webroot only returns the following html code, which only renders a white page in several webbrowsers (firefox, chromium and even Microsoft Edge):
`<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui,viewport-fit=cover"><meta name="theme-color" content="#e64a19"><meta name="format-detection" content="telephone=no"><meta name="msapplication-tap-highlight" content="no"><title>openHAB</title><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><link rel="apple-touch-icon" href="res/icons/apple-touch-icon.png" crossorigin="use-credentials"><link rel="icon" href="res/icons/favicon.png" crossorigin="use-credentials"><link rel="manifest" href="/manifest.json" crossorigin="use-credentials"><link href="css/app.css" rel="stylesheet"></head><body><div id="app"></div><script src="js/app.js"></script></body></html>
`

If I only use the hostname (without the domain ending) or even the IP address everything is rendered as expected.

## Expected behavior
The same content should be shown in any webbrowser independent of the address used to address the openhab website.

## Steps to reproduce
Setup clean install of debian buster.
Install Java 11 (OpenJDK & recommended Zulu packages lead to the same behavior)
Install openhab debian package
Access openhab via the fully qualified domain name (e.g. host.openhab.org): site will not be rendedered correctly.
Access openhab via hostname (host) or IP address: site will be rendered as intended.

## Your environment
```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Debian
  osName: Linux
  osVersion: 4.19.0-13-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 127713352
  totalMemory: 283115520
    onLine: true
    platform: Linux x86_64
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
```
