### ISSUE TITLE
Item Analyzer on Main UI sets earliest timepoint to current time when using a non-standard time period with time as the coord system.

### ISSUE THREAD

**Issue by DarrylNoakes** [openhab/openhab-webui#808]
## The problem

Opening the Analyzer on the Main UI sets the earliest timepoint to the current time when using a non-standard time period (e.g. 3 hours).

## Expected behavior

When opening the Analyzer (in any way) with a non-standard time period, it should behave the same as with a standard time period.

## Steps to reproduce

1. Enter http://hostname:port/#!/analyzer/?items=youritem&chartType=&coordSystem=time&period=3h in the address bar of your browser, replacing `hostname`, `port`, and `youritem` with your server's hostname and port, and any item that you can analyze.

**OR**

1. Open the Main UI.
2. Enter "item label over 3 hours" into the chat bar on the overview page, replacing "item label" with the label of an item that can be analyzed.
3. Click "Open Analyzer" on the response if it did not open automatically.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 18133088
  totalMemory: 194772992
bindings:
  - astro
  - exec
  - http
  - modbus
  - mqtt
  - network
  - openweathermap
  - telegram
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-14T14:59:17.771Z
```

## Browser console

No errors were reported.

## Browser network traffic

![image](https://user-images.githubusercontent.com/67335139/104608818-59dd9b80-5650-11eb-84e4-63d7f22b26e7.png)

## Additional information

I don't have any additional information.
