### ISSUE TITLE
Front- and backend do not use a consistent locale format

### ISSUE THREAD

**Issue by philippwaller** [openhab/openhab-webui#824]
**Update**: The problem is caused by an incompatible locale format. 

--------

## The problem
In certain constellations, no link can be clicked/no page can be opened after pressing the back button:
![locale bug](https://user-images.githubusercontent.com/1090452/105193527-e13b7b00-5b38-11eb-95e9-64614a83d5b0.gif)

## Expected behavior

All links should be clickable after using the back button.

## Steps to reproduce

1. Open the page "http://localhost:8080/#!/settings/"
2. Click on "Regional Settings"
3. Click on "Settings" (Back button top left)
4. Try to click on "Regional Settings" again

## Your environment

Tested with Browser:
- Chrome Version 87.0.4280.141
- Firefox Version 84.0.1
- Safari Version 14.0.2 

Tested with OpenHAB Version:

- openHAB 3.0.0 Release Build
- openHAB 3.0.0 SNAPSHOT - Build #2154

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE_#Latn
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.19.121-linuxkit
  osArchitecture: amd64
  availableProcessors: 6
  freeMemory: 34185352
  totalMemory: 102760448
bindings: []
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 12
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-19T09:49:17.389Z
```

## Browser console

```txt
app.js:7 RangeError: Incorrect locale information provided
    at Date.toLocaleString (<anonymous>)
    at o.<anonymous> (app.js:27)
    at o.e._render (app.js:7)
    at o.a (app.js:7)
    at fn.get (app.js:7)
    at new fn (app.js:7)
    at app.js:7
    at o.On.$mount (app.js:7)
    at o.On.$mount (app.js:7)
    at init (app.js:7)
Ge @ app.js:7
We @ app.js:7
Ue @ app.js:7
e._render @ app.js:7
a @ app.js:7
fn.get @ app.js:7
fn @ app.js:7
(anonymous) @ app.js:7
On.$mount @ app.js:7
On.$mount @ app.js:7
init @ app.js:7
(anonymous) @ app.js:7
d @ app.js:7
(anonymous) @ app.js:7
S @ app.js:7
(anonymous) @ app.js:7
e._update @ app.js:7
a @ app.js:7
fn.get @ app.js:7
fn.run @ app.js:7
pn @ app.js:7
(anonymous) @ app.js:7
Qe @ app.js:7
Promise.then (async)
Ye @ app.js:7
at @ app.js:7
(anonymous) @ app.js:7
fn.update @ app.js:7
pe.notify @ app.js:7
set @ app.js:7
Ie @ app.js:7
(anonymous) @ app.js:7
t.a @ app.js:7
setState @ app.js:20
onPagePosition @ app.js:20
(anonymous) @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
value @ app.js:9
D @ app.js:9
(anonymous) @ app.js:9
(anonymous) @ app.js:9
r @ app.js:1
c @ app.js:1
```

## Additional information
The issue does not occur when I navigate to the settings via the menu bar. However, when I access the settings directly via a link/bookmark, the problem is reliably reproducible.
