### ISSUE TITLE
Wrong value of Slider for (e.g. MQTT) dimmer items

### ISSUE THREAD

**Issue by CSchlipp** [openhab/openhab-webui#832]
## The problem
Preface: This issue may not be specifically related to MQTT items, but that's where I've noticed it and what's probably the easiest way to reproduce..

I have several MQTT things with channels of type "dimmer", annotated with min, max, and step values, usually ranging from 0-254. These channels are linked to OH items of type Dimmer.

Main UI shows a slider for these dimmer items, but mixes up the display of raw min/max values and calculated dimmer percentages. The following Dimmer is e.g. set to 100%:
![image](https://user-images.githubusercontent.com/4139563/105385003-2633e000-5c13-11eb-908c-61c1c093158c.png)
(Channel: min=0, max=254, step=1; Item: state=100%)
- The slider in the UI is set to be between min and max of the channel
- The position of the slider is however the percentage value.
- Setting the slider to a value outside of 0-100 will not update the item state at all

This especially gets worse when the min-value is not equal to 0, then the slider dot may even appear outside of the slider bar:
![image](https://user-images.githubusercontent.com/4139563/105387544-f33f1b80-5c15-11eb-99e2-5b00ce338555.png)
(Channel: min=137, max=370, step=1 ; Item: state=11%)

## Expected behavior
The [MQTT documentation](https://www.openhab.org/addons/bindings/mqtt.generic/) states in Section “Channel Type “dimmer””, that:
Defining a channel of type dimmer with min/max/step definition leads to an automatic calculation of a percentage value, that should be linked to to an item of type Rollershutter or Dimmer. 

Dimmer items are defined to be in the range of 0-100.

Therefore:
For all dimmer items, the UI should by default (=without having to change the state representation every time) display a slider ranging from 0 to 100, with the dot representing the current percentage value.

## Steps to reproduce

1. Create a MQTT Thing with a channel of type dimmer, e.g.:
```yaml
Thing topic ledpanel "LED Panel"
{
  Type dimmer : brightness  "brightness"  [ stateTopic = "<anyStateTopic>", commandTopic = "<anyCommandTopic>", min = 0, max = 254, step = 1 ]
  Type dimmer : colortemp  "colortemp"  [ stateTopic = "<anotherStateTopic>", commandTopic = "<anotherCommandTopic>", min = 153, max = 370, step = 1 ]
}
```
2. Map this dimmer channel to a dimmer item, e.g.
```yaml
Dimmer  LedPanel_Dimmer  "Dimmer"  ["Control", "Light"]  {channel="mqtt:topic:server_retain:ledpanel:brightness"}
Dimmer  LedPanel_ColorTemp  "Colortemp"  ["Control", "ColorTemperature"] {channel="mqtt:topic:server_retain:ledpanel:colortemp"}
```

3.  Update the channel state, e.g. via Developer Tools to a percentage value, e.g. 100 for the first example, or 11 for the second one.
4. Observe the wrong slider position
5. Update the item state with the slider, e.g. to the very right
6. Observe that there is no change to the item state (in the logs)

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 5.4.0-48-generic
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 49627896
  totalMemory: 132120576
bindings:
  (...)
  - mqtt
  (...)
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 12
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-21T17:31:57.670Z

```

## Browser console
e.g. for the second example with the colortemp channel, when setting the slider to a value of 333:
![image](https://user-images.githubusercontent.com/4139563/105389910-baed0c80-5c18-11eb-8b45-1d4d58c8d6b9.png)

## Browser network traffic
e.g. for the second example with the colortemp channel, when setting the slider to a value of 333:
![image](https://user-images.githubusercontent.com/4139563/105392820-ed4c3900-5c1b-11eb-8a82-cee0ce6f6f73.png)

## Additional information
* If the channel and item would have been of type number, the current behavior would most likely be correct.
* I know that you can currently work around this, by setting the state representation for every item manually to min=0, max=100, but this should already be the default for all items of type dimmer, as other values cannot be represented in such an item anyways.
* This topic is being discussed in the forums: https://community.openhab.org/t/slider-scaling-on-oh3/110727
