### ISSUE TITLE
[MainUI] Be able to navigate to the Item/Channel from the Link Page

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#846]
## The problem

Sometimes there are situations where one wants to start at a Thing, go to the Channels and navigate to the Link and then want to go to the Item. Other times one may want to start at the Item, navigate to the Link and then go to the Thing. 

But currently there is no way to get to the Thing or the Item itself from the Link page.

## Your suggestion

Make the Channel and Item clickable to navigate to the Thing and Items pages.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 5.4.0-62-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 105442640
  totalMemory: 370147328
bindings:
  - astro
  - chromecast
  - mail
  - mqtt
  - network
  - networkupstools
  - openweathermap
  - remoteopenhab
  - shelly
  - zigbee
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 2
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
timestamp: 2021-01-26T18:08:00.652Z

```
