### ISSUE TITLE
Notification for being offline

### ISSUE THREAD

**Issue by stritti** [openhab/openhab-webui#848]
## Problem

White page if device is offline.

I installed the MainUI as PWA on Homescreen which could replace the iOS App in future for me.
Now I noticed, that if this app is started outside my Wi-fi area where my Raspi is not reachable the app shows a white page.

## Your suggestion

Maybe this could be improved and there is a error message, that openHab server is not reachable.

## Your environment

```yaml

runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.83-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 65365112
  totalMemory: 246493184
bindings:
  - amazonechocontrol
  - astro
  - exec
  - innogysmarthome
  - mqtt
  - openweathermap
  - systeminfo
clientInfo:
  device:
    ios: true
    android: false
    androidChrome: false
    desktop: false
    iphone: true
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: ios
    osVersion: "14.3"
    webView: true
    webview: true
    standalone: true
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: de-de
    languages:
      - de-de
    onLine: true
    platform: iPhone
  screen:
    width: 375
    height: 812
    colorDepth: 32
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: true
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: standard
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X)
    AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148
    Safari/604.1

```
