### ISSUE TITLE
Copy button behind time of system bar on iOS

### ISSUE THREAD

**Issue by stritti** [openhab/openhab-webui#849]
## The problem

Opening the technical information of the app within the app installed as PWA on Homescreen (headless browser), the top bar with Copy and Close is behind the System Bar with the time and wi-fi information and not reachable by touch.

![image](https://user-images.githubusercontent.com/184547/105912156-558b8800-602b-11eb-8ff6-8ad12293eb46.jpeg)

Within normal browser (Safari) it is working as expected.

## Expected behavior

The buttons should be below the system line and reachable in headless browser mode too.

## Steps to reproduce

1. Open MainUI
2. Use Share/Add to Homescreen
3. Open Technical Information details

## Your environment

```yaml

runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.83-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 65365112
  totalMemory: 246493184
bindings:
  - amazonechocontrol
  - astro
  - exec
  - innogysmarthome
  - mqtt
  - openweathermap
  - systeminfo
clientInfo:
  device:
    ios: true
    android: false
    androidChrome: false
    desktop: false
    iphone: true
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: ios
    osVersion: "14.3"
    webView: true
    webview: true
    standalone: true
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: de-de
    languages:
      - de-de
    onLine: true
    platform: iPhone
  screen:
    width: 375
    height: 812
    colorDepth: 32
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: true
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: standard
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X)
    AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148
    Safari/604.1

```

## Browser console

```txt

```
