### ISSUE TITLE
[MainUI] Allow the modification of Group Membership from the Model page

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#856]
## The problem
In addition to tags, Group membership is one of the key attributes for defining the model. However, while tags and even Item metadata can be modified from the Model page, to change Group membership one needs to navigate to the Item or Group in order to, for example, move a piece of equipment to another location. This significantly increases the number of clicks.

What would be best would be to be able to do a drag and drop on the hierarchy tree. But even just showing and allowing the modification of the Group membership on the right hand panel showing the selected Item's information would be a big improvement.

## Your suggestion

![image](https://user-images.githubusercontent.com/6385096/106157432-eeabc300-613f-11eb-8a51-4a0f7a55ba88.png)

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2166"
locale: en_US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 5.4.0-64-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 255273680
  totalMemory: 412090368
bindings:
  - astro
  - chromecast
  - mail
  - mqtt
  - network
  - networkupstools
  - openweathermap
  - remoteopenhab
  - roku
  - shelly
  - zigbee
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 2
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
timestamp: 2021-01-28T15:08:50.573Z
```
