### ISSUE TITLE
Sitemap editor does not apply minValue=0 to Slider in code

### ISSUE THREAD

**Issue by loewexy** [openhab/openhab-webui#862]
## The problem

I added a slider to a Sitemap via main UI and filled in minValue=0, maxValue=100 and step=1. If I now switch to the code view minValue is not transfered. Also if I edit the code and switch back to the editor the missing min value from the code is now also missing in the editor.

This happens only if minValue=0 other values I tested work completely as expected.

## Expected behavior

It should also apply minValue in code view.

## Steps to reproduce

1. Add new sitemap
2. Add slider with arbitrary item and minValue=0, maxValue=100 and step=1
3. Go to code view and see that the minValue is missing.
4. Edit maxValue to e.g. 99
5. Switch back to editor and see that the minValue is now also missing.

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+55-CA
  osName: Linux
  osVersion: 4.15.0-132-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 143126984
  totalMemory: 377487360
bindings:
  - mqtt
  - tradfri
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
timestamp: 2021-01-29T14:47:07.185Z

```

## Browser console

```txt
Leerer String an getElementById() übergeben. app.js:1:3783
```

In English something like: `Empty string passed to getElementById(). app.js:2:3783`

## Browser network traffic

There is only one request to retrieve all Items with succeeds with 200 OK.
