### ISSUE TITLE
Provide access to item label in expressions (e.g. to be used as title in widgets)

### ISSUE THREAD

**Issue by c--r** [openhab/openhab-webui#869]
When configuring an list item, it would be good to be able to access label of the item which is configured for that widget. Some expression like '=item.label' (referring to the config>item: attribute) would be good, so that changes to the item label in the item definition would be reflected in the UI automatically. 
Without that feature, you have to hard-code the title of a list item, although this is already set as item label and could be taken from there automatically and dynamically. This would reduce errors and increase convenience. This would restore functionality which was available in OH2: use the default item label or overwrite it in the sitemap.

This is where it should appear as additional option:
![image](https://user-images.githubusercontent.com/9051600/106392658-255d3400-63f3-11eb-9de7-9c108bee9680.png)

Rather than providing something like ='items.MyItem123.label' I would prefer to have '=item.label' (or have both options), because then users don't have to type in the item name twice when configuring the widget.

**Comment by krocans** [comment]
Probably it's bug not enhancement.

If items are being accessed in loop through group (oh-repeater; for: i, sourceType: itemsInGroup...) then most of item data is accessible via loop variable. Like loop.i.label or even loop.i.groupNames works.

If items are accessed from items repository iems.<itemname> then only "state" and "displayState" are available.
Currently that' s a big limitation for using "forged" item names in widgets like for example "=items["Prefix_" + props.variable].label"

**Comment by fastlorenzo** [comment]
Glad to see I'm not the only one having this issue 😁

I'm trying to get the label of the parent group of the items in the loop.

This works:
```yaml
 - component: oh-repeater
    config:
      for: item
      sourceType: itemsWithTags
      itemTags:
        - Battery
      fetchMetadata: semantics,widgetOrder,w
    slots:
      default:
        - component: oh-list-item
          config:
            title: =loop.item.groupNames[0]
            icon: oh:battery
            badge: =items[loop.item.name].displayState
            badgeColor: =(items[loop.item.name].state > 50)?"green":"red"
```

Renders:
![image](https://user-images.githubusercontent.com/768639/119231323-9cdcdd80-bb20-11eb-8b4a-e56e38882cc4.png)

This doesn't work:
```yaml
 - component: oh-repeater
    config:
      for: item
      sourceType: itemsWithTags
      itemTags:
        - Battery
      fetchMetadata: semantics,widgetOrder,w
    slots:
      default:
        - component: oh-list-item
          config:
            title: =items[loop.item.groupNames[0]].label
            icon: oh:battery
            badge: =items[loop.item.name].displayState
            badgeColor: =(items[loop.item.name].state > 50)?"green":"red"
```

Renders:
![image](https://user-images.githubusercontent.com/768639/119231360-cd247c00-bb20-11eb-8564-7a96c9612abc.png)

Pretty annoying bug I would say.
