### ISSUE TITLE
Wrong URL for Log Viewer when multihomed OH3

### ISSUE THREAD

**Issue by TheNightmanX** [openhab/openhab-webui#872]
## The problem
Wrong URL for Log Viewer, when you start Log Viewer from the 'Andere Apps' sidebar in the OH3 main webui and have a multihomed OH3

Wrong URL example: http://192.168.1.123192.168.50.28:9001/

## Expected behavior

Expected URL example: http://192.168.1.123:9001/

## Steps to reproduce

**Prerequisite:**
Have multihomed OH3 with e.g. following network settings:
![Screenshot 2021-02-02 080743](https://user-images.githubusercontent.com/77199169/106564665-d4058f80-652d-11eb-9610-61b47d27b044.png)

1. Navigate to the 'Overview' page.
2. Click on the 'Andere Apps' icon in the right upper corner. ![Screenshot 2021-02-02 081018](https://user-images.githubusercontent.com/77199169/106565011-5e4df380-652e-11eb-8bcd-6748e6aaecf8.png)
3. Click on the picture of 'openHAB Log Viewer'
4. Another browser tab will open with the wrong URL

## Your environment

```yaml
runtimeInfo:
  version: 3.0.1
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 4.19.0-13-686-pae
  osArchitecture: i386
  availableProcessors: 2
  freeMemory: 24886112
  totalMemory: 110100480
bindings:
  - pushover
  - shelly
  - sonos
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 2820
    height: 1156
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.56
timestamp: 2021-02-02T07:16:06.086Z

```

**Comment by TheNightmanX** [comment]
even the same bug with current 3.1.0.M1

```
runtimeInfo:
  version: 3.1.0.M1
  buildString: Milestone Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 4.19.0-13-686-pae
  osArchitecture: i386
  availableProcessors: 2
  freeMemory: 19118216
  totalMemory: 115343360
bindings:
  - pushover
  - shelly
  - sonos
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 2820
    height: 1156
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.56
timestamp: 2021-02-02T12:48:18.261Z

```
