### ISSUE TITLE
When Change item of type color in Rules-UI - add "choose color"-functionality

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-webui#882]
## The problem

When I create a rule and change an action for an item of type color, the "pick a color" - section is missing. 
If I add the action, it looks like this:
![image](https://user-images.githubusercontent.com/43743230/107095741-a492a380-6809-11eb-938a-cdb3388fc209.png)
But when I change the action, it looks like this: 
![image](https://user-images.githubusercontent.com/43743230/107095706-917fd380-6809-11eb-828f-719a0af63a96.png)

I am missing that last line "pick a color" in the change-action popup. 
## Your suggestion

Either add this little section to the change-action popup or replace the "edit module" to a "change action" Popup with the same layout/functionality as "add action". 

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+55-CA
  osName: Linux
  osVersion: 5.4.44-1-pve
  osArchitecture: amd64
  availableProcessors: 1
  freeMemory: 103091992
  totalMemory: 246415360
bindings:
  - astro
  - http
  - lifx
  - logreader
  - mqtt
  - network
  - openweathermap
  - shelly
  - telegram
  - velux
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
      - fr
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 2160
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/88.0.4324.146 Safari/537.36
timestamp: 2021-02-05T22:29:21.109Z

```
