### ISSUE TITLE
Aggregate using diff_first or diff_last will leave a gap at first entry

### ISSUE THREAD

**Issue by crnjan** [openhab/openhab-webui#912]
## The problem

Having a HP that logs usage time - incrementally, number of hours. Used this values to display number of hours HP was producing heat for either DHW or underfloor heating:

```
   ...
    - component: oh-aggregate-series
      config:
        name: DHW
        gridIndex: 0
        xAxisIndex: 0
        yAxisIndex: 0
        type: bar
        item: gBasement_BoilerRoom_HP_DHW_InOperation_HP
        dimension1: date
        aggregationFunction: diff_first
        service: influxdb
  ...
```

result:

<img width="893" alt="Screenshot 2021-02-16 at 21 16 37" src="https://user-images.githubusercontent.com/3818211/108119978-dbd24180-70a0-11eb-9991-2bf5ef3c7e36.png">

All good, just first bar is missing. Looking at the code, this is expected.

## Your suggestion

We could extend the period and fetch one item "before" first period and use that one for reference to calculate first diff - but might be problematic to define what time interval to use to fetch that item?

I used a bit different approach and introduced a new aggregator `diff` that just takes first and last value from within the group itself.

```
    case 'diff':
      aggregate = arr[1][arr[1].length - 1] - arr[1][0]
```

result:

<img width="872" alt="Screenshot 2021-02-16 at 21 23 08" src="https://user-images.githubusercontent.com/3818211/108120577-c873a600-70a1-11eb-9799-2543a8d5233a.png">

I look forward to any feedback or comments - and if `diff` aggregator makes sense to others as well, I can prepare a PR ...
