### ISSUE TITLE
oh-stepper with variable always starts at 0

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-webui#924]
## The problem

If I create a oh-stepper component without a linked item and just a variable to store its state, the min values gets ignored on load / reload and it always starts at 0.

If I use the toggles then, to set the stepper +1 it sets the value to the min value +1 as expected (but ignoring the set min-value itself)

![oh-stepper](https://user-images.githubusercontent.com/71724877/108857732-ad49ee80-75eb-11eb-8c53-1cb729a73bce.gif)

## Expected behavior
Starting at the set min value on load/reload if a variable name is given.

## Steps to reproduce

Creating a oh-stepper component with a button as a trigger to reset the stepper.
```
- component: oh-stepper
   config:
     variable: addQuantity
     min: 1
     max: 10
     value: 1
     step: 1
- component: oh-button
   config:
      clearVariable:
         - addQuantity
```

## Your environment
openHAB 3.1.0
Build #2190
