### ISSUE TITLE
Bindings do not show up in dialogue for addings Things

### ISSUE THREAD

**Issue by aurelio1** [openhab/openhab-webui#926]
## The problem
When doing Things -> New the Main UI does not show the binding, although it has been properly loaded and is active, according to the OpenHAB console.

## Expected behavior
This happened both in the Eclipse environment and in an operational environment by adding the binding to the addons folder.

## Steps to reproduce

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_CH
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 4.19.66-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 34081032
  totalMemory: 245112832
bindings:
  - airq
  - gpstracker
  - homematic
  - hue
  - mail
  - miele
  - network
  - solaredge
  - synologysurveillancestation
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - en-US
      - en
      - es-AR
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
timestamp: 2021-02-24T19:13:26.205Z

```

## Browser console

```txt

```

## Additional information

It is not allowed to upload the .jar, but I can send it upon request.
The problem does not appear only with my Siro binding (in the works), but also with others, see [https://community.openhab.org/t/binding-in-development-not-appearing-in-main-ui/117779](https://community.openhab.org/t/binding-in-development-not-appearing-in-main-ui/117779)
