### ISSUE TITLE
Opening popover/popup/sheet doesn't work from oh-list-item (listButton)

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-webui#927]
## The problem

Triggering a popover / popup / sheet from `oh-list-item` with `listButton: true` doesn't work

![openingSheet](https://user-images.githubusercontent.com/71724877/109090119-c4373080-7712-11eb-9eff-f5c6bbe3a2dc.gif)

## Expected behavior
I would expect the behavior similar to the one from the `oh-button` seen in the above *.gif

## Steps to reproduce
Create a widget with the following content and try to open the popover.
```
- component: f7-list
  slots:
    default:
        - component: oh-list-item
          config:
            listButton: true
            popoverOpen: .deleteItems
            
- component: f7-popover
  config:
    class: deleteItems
  slots:
    default:
        - component: Label
          config:
            text: Some sheet content
```

## Your environment
openHAB 3.1.0 (Build #2190) on RPi4b

**Comment by ghys** [comment]
It seems to work with a standard `f7-list-button`:
```yaml
component: f7-card
config:
slots:
  default:
    - component: oh-button
      config:
        text: Open popover
        listButton: true
        popoverOpen: .deleteItems
    - component: f7-list
      slots:
        default:
            - component: f7-list-button
              config:
                title: Test
                listButton: true
                popoverOpen: .deleteItems
    - component: f7-popover
      config:
        class: deleteItems
      slots:
        default:
            - component: Label
              config:
                text: Some sheet content
```
