### ISSUE TITLE
[habot] Habot does not find semantically tagged items

### ISSUE THREAD

**Issue by chiefymuc** [openhab/openhab-webui#931]
## Which UI are you reporting an issue for?

- [ ] Basic UI
- [ ] HABPanel
- [X] HABot
- [ ] CometVisu

## The problem

HABot does not find the intended items even though semantic tagging was implemented correctly.

Issue described with screenshots on the Forums:
https://community.openhab.org/t/habot-walkthrough-2-n-semantic-tagging-item-resolving/55651/90?u=spaceglider

## Your suggestion

Improve HABot handling of the semantic tagging

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M1
  buildString: Milestone Build
locale: en_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.83-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 5641808
  totalMemory: 324403200
bindings:
  - astro
  - chromecast
  - dwdpollenflug
  - dwdunwetter
  - gpstracker
  - hpprinter
  - http
  - ipcamera
  - kodi
  - lametrictime
  - luftdateninfo
  - max
  - miio
  - mqtt
  - network
  - ntp
  - onkyo
  - openweathermap
  - sony
  - spotify
  - squeezebox
  - systeminfo
  - tradfri
  - wled
  - yeelight
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101
    Firefox/86.0
timestamp: 2021-02-28T10:13:41.420Z

```
