### ISSUE TITLE
Make OH3 WebUi Audiosink for WebAudio

### ISSUE THREAD

**Issue by bf8392** [openhab/openhab-webui#936]
## The problem

Habpanel can Play Audio, but the new OH3 UI not...My current workaround is to frame the OH3 UI in Habpanel, but that's a rather "ugly" solution...native Audio support of the normal OH3 UI would be cool, as I can use the new UI in the habpanelviewer App from vbier and I love the Design of the new OH3 UI :-). Together with the functions of habpanelviewer, the new UI is absolutely genius!
https://github.com/vbier/habpanelviewer

## Your suggestion

Add WebAudio support to OH3 WebUi

## Your environment

```
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_AT
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.83-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 186720888
  totalMemory: 481714176
bindings:
  - amazonechocontrol
  - astro
  - chromecast
  - gardena
  - harmonyhub
  - ipcamera
  - jablotron
  - kodi
  - mail
  - ntp
  - openweathermap
  - orvibo
  - samsungtv
  - smartthings
  - telegram
  - unifi
  - unifiedremote
  - upnpcontrol
  - zwave
clientInfo:
  device:
    ios: false
    android: true
    androidChrome: true
    desktop: false
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: android
    osVersion: "10"
    webView: false
    webview: false
    standalone: false
    pixelRatio: 2.625
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Linux armv8l
  screen:
    width: 412
    height: 892
    colorDepth: 24
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Linux; Android 10; ONEPLUS A6013) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/88.0.4324.181 Mobile Safari/537.36
timestamp: 2021-03-05T19:15:57.472Z
```
