### ISSUE TITLE
NULL error when switching to the same tab in settings

### ISSUE THREAD

**Issue by hoefnageltom** [openhab/openhab-webui#940]
## The problem
Currently, the ```fromYaml()``` method is called everytime one pressed the ``design`` button in the toolbar. But the ```pageYaml``` is only created after the toYaml has been loaded before. This produces the exception to be called since ```pageYaml``` is not initialized yet.

![null-reference-error-webui](https://user-images.githubusercontent.com/19148688/110325882-3283c900-8018-11eb-829b-f2e2ae307e38.gif)

## Expected behavior
No error should occur here

## Steps to reproduce

1. Go to the main UI as admin
2. Settings -> Pages -> Layout -> Overview
3. Try to reload the design tab by pressing it
4. See the TypeError

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M2
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: ***/opehab/conf
  userdataFolder:***/opehab/userdata
  logFolder: ***/opehab/userdata/logs
  javaVersion: 11.0.10
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.4.0-65-generic
  osArchitecture: amd64
  availableProcessors: 12
  freeMemory: 95440528
  totalMemory: 375390208
bindings:
  - pioneeravr
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 12
    language: nl
    languages:
      - nl
      - en-US
      - nl-NL
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/88.0.4324.182 Safari/537.36
timestamp: 2021-03-08T13:18:08.684Z
```

## Browser console

No error

## Additional information

I think checking the pageYaml before entering the ```fromYaml()``` function will fix this bug
