### ISSUE TITLE
[MainUI - Sitemap Pagedesigner] Wrong type "number" for list separator in Designer

### ISSUE THREAD

**Issue by DarkC35** [openhab/openhab-webui#949]
## The problem

Sitemap pagedesigner widget uses wrong type `number` for control `Separator`.  Therefore a correct separator for a list widget (like `,`) cannot be set via the designer. It is possible to set the separator via code (see screenshot below) but the set separator will not be displayed in the designer (and a following change+save of the separator with a string/text in the designer results in an unset of the seperator in the sitemap code... i guess because of validation?).
![grafik](https://user-images.githubusercontent.com/38973046/110632915-773e6a00-81a8-11eb-95d3-cc5dcccb5f56.png)

## Expected behavior

Control `separator` should have type `text` so it is possible to set the separator with the designer too.

## Steps to reproduce

1. make a sitemap (Settings -> Pages -> Create Sitemap)
2. add a list widget
3. try to set separator `,` in designer
4. save the sitemap (no error occures and separator is still visible in designer)
![grafik](https://user-images.githubusercontent.com/38973046/110632645-27f83980-81a8-11eb-8bc3-3b52cc9dd3f0.png)
5. switch to tab `Code`
6. no separator prop was added in sitemap code
![grafik](https://user-images.githubusercontent.com/38973046/110632718-3fcfbd80-81a8-11eb-9ae7-32c070c87491.png)
7. switch back to tab `Design`
8. separator `,` disappeared
![grafik](https://user-images.githubusercontent.com/38973046/110632768-49f1bc00-81a8-11eb-8cfa-80954afa493f.png)

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2211"
locale: de-AT
systemInfo:
  configFolder: c:\openhab\conf
  userdataFolder: c:\openhab\userdata
  logFolder: c:\openhab\userdata\logs
  javaVersion: 11.0.6
  javaVendor: Oracle Corporation
  javaVendorVersion: "18.9"
  osName: Windows 10
clientInfo:
  device:
    firefox: true
    os: windows
```

## Additional information

The problem seems to be in this line:

https://github.com/openhab/openhab-webui/blob/eb7596c42ddb9d73fd4f6e2dcd506fd38299474b/bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue#L30

ListRenderer in BasicUI uses `getSeparator()` to split the string

https://github.com/openhab/openhab-webui/blob/eb7596c42ddb9d73fd4f6e2dcd506fd38299474b/bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ListRenderer.java#L64

and according to `openhab-core` separator is of type `string`:

https://github.com/openhab/openhab-core/blob/4a79e9bfe7dca9f6abd1e40d3eb398a9aa2c8988/bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext#L104

I'm willing to submit a PR that fixes the wrong type in the `widget-details.vue` file.
