### ISSUE TITLE
[MainUI] Group:Number:COUNT("string") is not possible in MainUI

### ISSUE THREAD

**Issue by WhiteSockedDancer** [openhab/openhab-webui#956]
## The problem

It seems that i can't add a group with a "COUNT" aggregate function in MainUI.

Following the description (https://www.openhab.org/docs/configuration/items.html#groups) works if used in a .items file (and the use of "Group:Number:COUNT" instead of "Group:String:COUNT")

Is there any metadata i would have to add to the group-item or is this function just not (yet?) implemented into the MainUI?

## Your environment

```
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2244"
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.17-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 55390976
  totalMemory: 198656000
bindings:
  - denonmarantz
  - http
  - hue
  - miio
  - mqtt
  - network
  - systeminfo
  - tr064
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101
    Firefox/86.0
timestamp: 2021-03-14T19:47:55.929Z
```
