### ISSUE TITLE
[MainUI] List of Item types for Group Members Base Type is incomplete

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#957]
## The problem

Theoretically one should be able to create a Group with a Members Base Type of any openHAB Item type (except Group of course). However, the list to choose from in MainUI is incomplete.

![image](https://user-images.githubusercontent.com/6385096/111183339-68bfcc00-8575-11eb-9d34-8d5de2fa3462.png)

Missing are:

- Color
- Image (which may not make sense)
- Location
- Player
- String

## Expected behavior

All Item types are possible and should be listed. Furthermore, aggregation functions are possible with many of these and those should be allowed as well which might make this a little more complicated to support. But even with out the aggregation functions, creating a Group:Color is still useful to send a command to a number of bulbs at once which is currently not possible in the UI.

## Steps to reproduce

1. 

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2246"
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.4.0-66-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 457216464
  totalMemory: 1015021568
bindings:
  - astro
  - chromecast
  - evohome
  - ipcamera
  - mail
  - mqtt
  - network
  - networkupstools
  - openweathermap
  - remoteopenhab
  - roku
  - shelly
  - zigbee
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 2
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/89.0.4389.72 Safari/537.36
timestamp: 2021-03-15T16:05:18.628Z

```

## Browser console

```txt

```
