### ISSUE TITLE
Wrong width of oh-slider component in oh-cell

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-webui#967]
## The problem

The slider component (and maybe other components?!) sets its width depending on the number of visible cell components in the row they resides in (asuming that each of the components will take up the same amount of the page-width - which would work in the row / column layout). 

So if e.g. 2 cells are in one row the slider will take up 50% of the avilable width of that page (even if only parts of it are filled with cells because of their fixed width) - Everything works as expected in the row/column layout.

![oh-cell_slider](https://user-images.githubusercontent.com/71724877/111983369-59f38f00-8b0a-11eb-8007-7412427c0322.gif)
The upper row consits of 2 cells; the lower row uses the row / column layout (and works fine)

## Expected behavior
The used components inside the oh-cell should only use the available width of that cell.

## Your environment
OH 3.1.0 build 2269 on RPi 4

**Comment by ghys** [comment]
Can you add a YAML example?
If you put the slider in the `header` slot my guess would be that the width is the expanded card width (`--f7-card-expandable-tablet-width: 300px` on large screens). It's true that it doesn't seem to be possible to set the styles to override that CSS variable, maybe you can do it in the parent `oh-grid-cells`.

Another workaround for now if the card/cell isn't expandable is to use the `background` slot instead:

```yaml
component: oh-cell
config:
  style:
    background-color: blue
    width: 100%
slots:
  background:
    - component: oh-slider
      config:
        class:
          - card-prevent-open
        style:
          margin: 2rem
          width: calc(100% - 4rem)
          background-color: blue
```

But you're right ultimately it should be possible to modify the cell's CSS attributes & classes from their config.

**Comment by rgrollfitz** [comment]
Of course!

The behaviour was discussed here: https://community.openhab.org/t/oh-slider-not-correctly-shown/119438/
All components are inside the `content` slot of a `f7-card`, which - after thinking about it - seems to be part of the problem, as it doesn't make a lot of sense putting a `f7-card` component inside of a `oh-cell` component. 

I've tried to change the f7-card to oh-cell but didn't thought about changing to a header or background slot then.

Using the background slot fixed the problem - even if the card is messed up a bit due to the excessive styling, which should be an easy fix. :-)

The original YAML from the thread:
```
uid: Cell_Light_Card_1
tags: []
props:
  parameters:
    - description: Small title on top of the card
      label: Title
      name: title
      required: false
      type: TEXT
    - description: Header big sized
      label: Header
      name: header
      required: false
      type: TEXT
    - description: Icon on top of the card (only f7 icons (without f7:))
      label: Icon
      name: icon
      required: false
      type: TEXT
    - label: Background Color
      name: bgcolor
      required: false
      type: TEXT
    - context: item
      description: Item to control on/off
      label: Item
      name: item_schalter
      required: false
      type: TEXT
    - context: item
      description: Item to control brightness
      label: Item
      name: item_brightness
      required: false
      type: TEXT
  parameterGroups: []
timestamp: Mar 10, 2021, 8:00:57 PM
component: f7-card
config:
  style:
    noShadow: false
    padding: 0px
    border-radius: var(--f7-card-expandable-border-radius)
    box-shadow: 5px 5px 10px 1px rgba(0,0,0,0.1)
    background-color: "=props.bgcolor ? props.bgcolor : ''"
    height: 120px
    margin-left: 5px
    margin-right: 5px
slots:
  content:
    - component: f7-block
      config:
        style:
          position: absolute
          top: -5px
          left: 16px
          flex-direction: row
          display: flex
      slots:
        default:
          - component: f7-icon
            config:
              f7: =props.icon
              size: 18
              style:
                margin-right: 10px
              visible: "=props.icon ? true : false"
          - component: Label
            config:
              text: "=props.title ? props.title : ''"
              style:
                font-size: 12px
                margin-top: 0px
    - component: f7-block
      config:
        style:
          position: absolute
          bottom: -15px
          left: 16px
          flex-direction: row
      slots:
        default:
          - component: Label
            config:
              text: "=props.header ? props.header : 'Set Props'"
              style:
                font-size: 17px
                font-weight: 600
                margin-left: 0px
                margin-top: 0px
    - component: oh-slider
      config:
        item: =props.item_brightness
        min: 0
        max: 100
        style:
          position: absolute
          bottom: -75px
          left: 20px
          width: calc(100% - 40px)
          --f7-range-bar-size: 8px
          --f7-range-bar-border-radius: 8px
          --f7-range-knob-size: 20px
          --f7-range-knob-box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3)
    - component: oh-toggle
      config:
        item: =props.item_schalter
        style:
          position: absolute
          top: 15px
          right: 20px
```
