### ISSUE TITLE
OpenHab 3 -> Semantic Model: Items shoul appear in every group they are members of

### ISSUE THREAD

**Issue by NCC1701M** [openhab/openhab-webui#969]
## The problem
I have the following model:
```
Shutters
├── FirstFloor
│   ├── Bedroom
│   ├── Livingroom
│   └── Kitchen
└── ControlGroups
    └── DownOnSunset
        ├── Bedroom
        └── Livingroom
```
`FirstFloor`, `ControlGroups` and `DownOnSunset` are groups. As you can see, the shutters `Bedroom` and `Livingroom` are in the groups `FirstFloor` and `DownOnSunset` but in the model the only are display in one of those groups. In which group can change when you modify one of those groups (e.g. by adding a new member).

## Expected behavior
Every item should be displayed in every group they are a member of. Even if this means that the item is more than once in this list.

## Steps to reproduce
1. Create a group
2. Add a item to the group
3. Create a different group
4. Add the same item to the new group

You will see, that the item is only display in one group. But how can you tell, that it is also in the second group? Only by selecting the group in the list, click on the Item on the right side of the screen and take a look at `Direct Group Members`

## Your environment

```yaml
runtimeInfo:
  version: 3.0.1
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.17-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 10072952
  totalMemory: 139206656
bindings:
  - astro
  - homematic
  - hue
  - network
  - openweathermap
  - telegram
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 12
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/89.0.4389.90 Safari/537.36
timestamp: 2021-03-22T18:06:06.323Z

```
