### ISSUE TITLE
styles/background changes don't appear in 'run-mode'

### ISSUE THREAD

**Issue by Ursusprimus** [openhab/openhab-webui#971]
## Steps to reproduce

1. 

## Your environment

```
config:
  label: simple_test_page
  sidebar: true
  style:
    background: linear-gradient(to top left,rgb(21,25,36) 0%, rgb(57,63,77) 100%)
blocks:
  - component: oh-block
```

## Browser console

```txt

```
