### ISSUE TITLE
styles/background changes don't appear in 'run-mode'

### ISSUE THREAD

**Issue by Ursusprimus** [openhab/openhab-webui#972]
## The problem

When adding code for background information at the page level, it doesn't appear in 'Design' or 'Run Mode'. I need to exit first and open the page in live view.
Detailed information at: https://community.openhab.org/t/oh3-pages-background-color/115454/12   post 11

## Expected behavior

when going to design or run-mode, the background color should've changed.

## Steps to reproduce

start new page, go to code, enter background-style, go to run-mode

1. 

## Your environment

win 10 PC, Chrome-Browser;   Openhab on RasPi4 with 'hassle-free installation'

```
config:
  label: simple_test_page
  sidebar: true
  style:
    background: linear-gradient(to top left,rgb(21,25,36) 0%, rgb(57,63,77) 100%)
blocks:
  - component: oh-block

```

## Browser console

```txt

```
