### ISSUE TITLE
Can't add selection elements to oh-input type 'select'

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-webui#982]
## The problem

Currently it's not possible to add selection elements to the `oh-/f7-input` component with type `select`. Due to the f7-documentation, the elements should be placed inside the `default` slot of the component to be visible inside of the selection element.

I've tried it with `oh-input-item` and `oh-link` inside the default slot - both variants did not work.

```
uid: input_select
component: f7-card
config:
  title: "'select' Input"
slots:
  default:
    - component: oh-input
      config:
        type: select
      slots:
        default:
          - component: oh-input-item
            config:
              title: oh-input-option
          - component: oh-link
            config:
              text: oh-link-option
```
![oh-input_select](https://user-images.githubusercontent.com/71724877/112838715-a5bfae80-909d-11eb-95e1-c2660d97a518.gif)

## Expected behavior
Elements in the default slot should appear inside the dropdown-selection. After clicking on one of the options, the selected value should be populated to the parent elements variable.

## Your environment
openHAB build 2289 on RPi4

**Comment by hubsif** [comment]
According to the [Framework7 docs](https://v5.framework7.io/vue/inputs.html) `f7-input` requires to wrap the select values as plain `<option>` HTML tags, or for them to be inserted as component using the default slot.

There is currently no component available rendering plain `<option>` tags. Adding such a component would be required to make this possible and then some adjustments in oh-input for it to be rendered and evaluated correctly.

**Comment by davidtowers** [comment]
No solution found?

**Comment by florian-h05** [comment]
This will be possible with #2633 and this code:

```yaml
uid: input_select
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Jun 27, 2024, 1:14:31 PM
component: f7-card
config:
  title: oh-input select with options
slots:
  default:
    - component: oh-input
      config:
        type: select
        style:
          margin-left: 15px
      slots:
        default:
          - component: option
            config:
              value: foo
            slots:
              default:
                - component: Content
                  config:
                    text: foo
          - component: option
            config:
              value: bar
            slots:
              default:
                - component: Content
                  config:
                    text: bar
```
