### ISSUE TITLE
UI enhancements for Item list in admin area

### ISSUE THREAD

**Issue by stefandnm** [openhab/openhab-webui#987]
## The problem

I'm also affected from #925, so I started using the Items admin view for some of the tasks. I have a lot of items to manage, and I would really like to see some more features for sorting and filtering the list. 

## Your suggestion

Here are my use cases and suggestions:

Use Case 1: I heavily use non-semantic tags to structure my items. It would be helpful to reduce the list to those items with one or more tags (both semantic and non-semantic).
Use Case 2: I heavily use functional groups. It would be helpful to restrict the list to items within a certain group (recursively)
- Allow for filtering based on tags and group memberships
  - Items list should be filtered based on one or more tags: Have a filter to specify the tags you are interested in
  - Items list should be filtered based on recursive group membership: Hava a filter to specify the groups you are interested in

Use Case 3: I have a naming scheme for the item names. It would be helpful to also order the items list based on the name of an item.
- Allow sorting the list based on Name or Label

## Your environment

```yaml
runtimeInfo:
  version: 3.0.1
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 4.19.0-14-amd64
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 32065384
  totalMemory: 268435456
bindings:
  - astro
  - dwdunwetter
  - harmonyhub
  - knx
  - openweathermap
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 3072
    height: 1728
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63
timestamp: 2021-04-02T08:11:07.204Z

```
