### ISSUE TITLE
OH3 MainUI "forgets" rules coming from .rules files when editing .items files related to these rules

### ISSUE THREAD

**Issue by sirupflex** [openhab/openhab-webui#989]
## The problem
I'm running OH V3.0.1 docker image on QNAP NAS, being in the process of migrating from 2.5.6 to OH3. I have all things, items, rules, sitemaps, etc. in text files.

When I edit an .items text file, it sometimes happens that OH3 "forgets" about all the rules in a rule file related to these items.

**Specific example:**
I have Miele devices (dishwasher, washingmachine, dryer), for which I have one .items file that define the Groups to have them defined as equipment, plus all the items. I also have one .rules file that has 12 different rules triggering in the context of the Miele devices / items.
There are a total of 53 rules listed in the MainUI, all coming from 12 different .rules text files.

When I now edit the Miele.items file (might be a minor change to change a letter in a label string), I see afterwards in the MainUI list that there are only 41 rules listed, and the 12 rules of the Miele.rules file are missing. As far as I can tell, the rules are then also not firing, i.e. OH3 "forgot" about them.

This does not happen every time I edit an .items file but in about 1 out of 3 times. It happens with all .items / .rules files, not only for the Miele ones. For example, if I change something in the .items file for the heat pump, then OH3 forgets about the rules related to heat pump items.

To bring the rules back, I have to edit the .rules file (e.g. add a comment line) which triggers the reload of the rules and I see all 53 rules in the MainUI again.

This is quite a hassle because each time I do a modification in a .items file, I have to check the rules numbers in the MainUI and often then do the "dummy edit" of the .rules file to bring the rules back. And if I forget about it, the rules don't trigger and I end up with missing or inconsitent data.

## Expected behavior

When I edit an .items file, I expect all rules to still be visible and active in the MainUI without any further actions or checks on my side.

## Steps to reproduce
I assume:
1. Have an .items file with a device defined as equipment and items related to this equipment
2. Have a .rules file with some rules that trigger based on these items
3. Check the MainUI for the rules (all rules should be visible in the list)
4. Edit the .items file
5. Check again the MainUI for the rules to see that some rules are now missing. You might have to edit / save the .items file a few times until you'll see that the related rules disappeared (does not happen each time you modify an .items file; only around one out of 3 times, I would say)

## Your environment
OpenHAB 3.0.1 Release Build, official docker image on QNAP NAS TS-673 with 16GB RAM. Using InfluxDB V2.0.4 as persistence service.

```
runtimeInfo:
  version: 3.0.1
  buildString: Release Build
locale: de_CH
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 4.2.8
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 277190496
  totalMemory: 524288000
bindings:
  - astro
  - daikin
  - gardena
  - http
  - icalendar
  - mail
  - miele
  - mielecloud
  - modbus
  - worxlandroid
```
