### ISSUE TITLE
Default values for widget property parameters

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-webui#990]
## The problem
If s.o. implements property parameters in a custom widget, it's needed that these parameters gets set by the user of that widget to give it a value. The other way would be, that the widget-creator have to implement expressions which intercept these empty property params and exchange them with something useful at every point where that parameter is used in the code.

A very basic example for this would be:

```
uid: example
props:
  parameters:
    - name: backgroundColor
      label: Background color
      type: TEXT
component: f7-card
config:
  title: This is a title
  content: ...and some content
  style:
    background: "=!props.backgroundColor ? 'green' : props.backgroundColor"
```

## Your suggestion
It would be nice to have the option to set optional default values for widget property parameters, which would be applied if no value is set by the user. These default values could be visible as a placeholder inside the widget configuration:

```
uid: example
props:
  parameters:
    - name: backgroundColor
      label: Background color
      type: TEXT
      default: green
component: f7-card
config:
  title: This is a title
  content: ...and some content
  style:
    background: =props.backgroundColor
```

![default_value](https://user-images.githubusercontent.com/71724877/113691725-0a49c180-96cd-11eb-9960-7af1a832abbf.png)
