### ISSUE TITLE
Sort Things in Add Things to Semantic Model View by Appearance Count in Model

### ISSUE THREAD

**Issue by Hypfer** [openhab/openhab-webui#995]
## The problem

As a long-time user of home-assistant, I've recently discovered the new OpenHab and decided to give it another try.
Unfortunately, I didn't get very far.

Adding the existing Setup of over 200 devices to a newly created Semantic Model turned out to be rather painful with one of the reasons for that being that I've completely lost track of which Thing I've added and which Thing I didn't add yet even with just a few Things being configured at all.

I refer to this list view
![image](https://user-images.githubusercontent.com/974410/114144079-3bb4ce00-9915-11eb-9876-1c8811fb3462.png)

## Your suggestion

The Idea I came up with to solve this would be to add another column to that view which shows the Count of times that specific thing already appears in the Semantic Model and then sort ascending by it.

This would result in unmapped things always appearing at the top and the software keeping track of what you already did instead of you having to resort to take notes while you're doing it.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M3
  buildString: Milestone Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 4.19.0-14-amd64
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 250759448
  totalMemory: 381681664
bindings:
  - deconz
  - mqtt
  - squeezebox
  - yamahareceiver
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 1600
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101
    Firefox/87.0
timestamp: 2021-04-09T07:26:06.801Z

```
