### ISSUE TITLE
Arrow-Key Tree Navigation for the Semantic Model View

### ISSUE THREAD

**Issue by Hypfer** [openhab/openhab-webui#996]
## The problem

Having to click and reposition the mouse multiple times to traverse the tree that is the Semantic Model is hard/annoying.

![image](https://user-images.githubusercontent.com/974410/114145372-9b5fa900-9916-11eb-926b-76e238f7918e.png)

In this selected state, I've expected that the right arrow key would expand it.
Unfortunately, neither of the arrow keys does anything

## Your suggestion

I'd propose handling arrow key input events there so that it behaves like most tree views do, since that would make working with it a lot easier.

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0.M3
  buildString: Milestone Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 4.19.0-14-amd64
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 250759448
  totalMemory: 381681664
bindings:
  - deconz
  - mqtt
  - squeezebox
  - yamahareceiver
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 1600
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101
    Firefox/87.0
timestamp: 2021-04-09T07:26:06.801Z

```
