### ISSUE TITLE
Unwanted dialog when creating a new rule

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-webui#998]
## The problem

When creating a new rule screen the "Changes have not been saved - Do you want to leave this page without saving?" dialog is shown, although it shouldn't be.
The rule is created nonetheless.

## Expected behavior

Allow to create a rule without unwarranted interference.

## Steps to reproduce

1. Go to the Schedule or Rule page
2. Click on the '+' button
3. Configure the rule
4. Save the rule - an unwanted dialog box is shown

## Environment 

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2319"
locale: en-US
```

## Additional information

cc @hubsif
